### ISSUE TITLE
[Steamworks.NET] SteamAPI_Init() failed.

### ISSUE THREAD

**Issue by Scumble373** [rlabrecque/Steamworks.NET#103]
Hi there,

Recently I've been greenlit on steam, and have been trying to integrate steamworks.net with Unity. I've done all the importing steps and everything seems to be fine, except I get this error when running the game.

[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information. UnityEngine.Debug:LogError(Object, Object) SteamManager:Awake() (at Assets/Scripts/Steamwork.NET/SteamManager.cs:97)

I have my steam_appid.txt and steam_api.dll in the same place where the "Assembly-CSharp" is, steam is running, my steam_appid is correct, etc

Anyone have any idea why this is happening or things to try? There is a shocking lack of information about this error. Thanks

**Comment by Tagette** [comment]
If you run unity as Administrator does it work? (Right Click, then "Run as Administrator")
I am currently having this issue with my Windows 8 computer. All other computers load steam fine.

**Comment by Tagette** [comment]
If you run unity as Administrator does it work? (Right Click, then "Run as Administrator")
I am currently having an issue with my Windows 8 computer where it won't load steam. All my other computers load steam fine.

**Comment by Magris** [comment]
I have same issue
other appid(480 or published) is working but not mine T.T(492610)
What can i do??

Unity 5.3.6 OSX 10.11

**Comment by rlabrecque** [comment]
If you're still having issues could you repost in #83?
