### ISSUE TITLE
undefined symbol: SteamInternal_Init

### ISSUE THREAD

**Issue by hadesfury** [rlabrecque/Steamworks.NET#104]
When launching the game under linux we've got this error concerning libCSteamworks.so 
It happens in 32 and 64 bit mode

It does not work with the last changelist but work with commit 81214e2636781619899ec34b3c836497b74a83bc

Regard

**Comment by TechCor** [comment]
I'm also having this issue. This bug cripples Steamworks.NET for Linux.

**Comment by hadesfury** [comment]
Don't you have any clue on this one?

2016-07-07 13:15 GMT+02:00 TechCor <notifications@github.com>:

**Comment by rlabrecque** [comment]
Hey guys, sorry this one took so long!

This is fixed with 90852e3bab8beade1f3b0b95a79e3dd6e0af2ba8
