### ISSUE TITLE
Get user currency

### ISSUE THREAD

**Issue by sqadrifork** [rlabrecque/Steamworks.NET#105]
Hello everyone,

I am having a bit of a trouble. As per the steam documentation we need a few things before our server sends in a request to steam for an in-app purchase. One of the things is currency and according to steam we can get it from GetUserInfo. But I am unable to find any appropriate function to get the currency in your rapper. I have got the other things as:

```
CSteamID userSteamID = SteamUser.GetSteamID();
string userLanguage  = SteamApps.GetCurrentGameLanguage();
string userCountry = SteamUtils.GetIPCountry();
```

but i cant get the currency. I am sure i am missing something here can someone please help me in the rite direction?

Thanks,
Qadri

**Comment by rlabrecque** [comment]
Hey @sqadrifork, I think those APIs are only provided through the WebAPI?

**Comment by sqadrifork** [comment]
Yes they are, sorry about that.
