### ISSUE TITLE
SteamManager class not defined as public

### ISSUE THREAD

**Issue by PaoloMonkey** [rlabrecque/Steamworks.NET#109]
I have to access SteamManager from a UnityScript code, but it seems that I cannot access the static SteamManager.Initialized if the class is not declared public

With the code provided, I get this error
BCE0005: Unknown identifier: 'SteamManager'.

this is solved by setting the class public

(I've also moved the SteamManager.cs in a Standard Asset subfolder, to make the code visible to the UnityScript code, but this is just a compilation issue)

**Comment by rlabrecque** [comment]
Thanks for the report! Fixed in:
https://github.com/rlabrecque/SteamManager/commit/71685313d9c7106cedd2dfa1fb62d46272080fcd
