### ISSUE TITLE
Leaderboard is fetching incomplete results

### ISSUE THREAD

**Issue by gsylvain2** [rlabrecque/Steamworks.NET#110]
Hi! We're about to launch our game on Steam and we noticed that LeaderboardScoresDownloaded_t seems to return incomplete result.

Example:
I call LeaderboardScoresDownloaded_t once: I get 3 entries.
I call LeaderboardScoresDownloaded_t again: I get 5 entries.
I call LeaderboardScoresDownloaded_t again: I get 7 entries.

And those 3 calls were made on the same SteamLeaderboard_t with the same parameters each time. It where something I'm missing out? I know that the call is async so I populate my leaderboard display only when I receive the callback.

Thank you!

UPDATE:
@rlabrecque 
We are releasing our game and I had to find a patch for this issue. Our leaderboard UI contains 10 slots. So I call the steam leaderboard data a first time. If I receive 0 entries, I consider that the leaderboard is empty/new. No more call­. 

On the other hand, let's imagine that I received 3 entries. This is less than 10 so I call the steam leaderboard data once again. Now I get let's say, 5 entries. Since the number of entries received is different than the previous call, I assume that I am dealing with the bug so I call the leaderboard again! I do this until the entry count is the same 2 calls in a row OR that I got 10 results to populate my UI properly. Note: I wait 0.25 sec between each call.

This is weird, this is a patch but it's working very well actually.

**Comment by unityguy12** [comment]
Hello @gsylvain2 

how did you manage to call and get the leaderboard data?
I cant find the code to call the leaderboard data.

Also i keep getting this error in my console
**[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.**

Can you please help me out.
I want to get the leaderboard data. dont know what method to call in order to get data.
Thanks a lot.

**Comment by gsylvain2** [comment]
Hi @unityguy12

If the Steam API init failed, you obviously cannot get any leaderboard data. You must fix that asap. Is it crashing in editor mode or only when running the game executable (.exe)?

You have a valid steam dev app? https://partner.steamgames.com/home 

Your Steam client must be open and logged using your login/pass registered on your steam dev account.

Make sure that you have a text file named steam_appid.txt at the root of your application with your steam app id inside.

Just as a sanity check, make sure that your steam dlls are properly setup. Mines are located in Assets/Plugins/x86 and Assets/Plugins/x64. Verify that each files (CSteamworks, libCSteamworks, libsteam_api and steam_api) are targeting the matching platform. Dlls in the x86 folder must target ONLY the x86 platform (in my case...) Once it is done, restart unity.

Do you still have issues initializing Steam API after verifying everything?

**Comment by rlabrecque** [comment]
Pretty sure this was a Valve bug that they fixed, let me know if they haven't!
