### ISSUE TITLE
ExecutionEngineException: SIGILL after achievement is unlocked

### ISSUE THREAD

**Issue by hexwar** [rlabrecque/Steamworks.NET#113]
The game ran without any issues before an achievement was unlocked. It then crashed at the point the achievement unlocked, then since then it will not run and gives a "ExecutionEngineException: SIGILL" error in the output_log.txt. See relevant snippets below:

Platform assembly: F:\C-Games\Steam\steamapps\common\1775\1775_Data\Managed\UnityScript.Lang.dll (this message is harmless)
"
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_InitSafe ()
  at Steamworks.SteamAPI.Init () [0x00000] in <filename unknown>:0 
  at SteamManager.Awake () [0x00000] in <filename unknown>:0 

(Filename:  Line: -1)
# 

Initialize engine version: 5.4.0f3 (a6d8d714de6f)
GfxDevice: creating device client; threaded=0
d3d11: no D3D11 installed
GfxDevice: creating device client; threaded=0
Direct3D:
    Version:  Direct3D 9.0c [ati2dvag.dll 6.14.10.6999]
    Renderer: ATI Radeon HD 3450 
    Vendor:   ATI
    VRAM:     512 MB (via registry)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=0 NULL=0 RESZ=1 SlowINTZ=1 ATOC=0
# 

This was using Steamworks.NET 8.0.0 and SDK version 1.35

**Comment by nihilocrat** [comment]
I also have a player who sent me an error that's similar, and it also seems to be happening when the game wants to set an achievement. This is the first time I've ever seen this error.

Initialize engine version: 5.2.4f1 (98095704e6fe)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 10.1]
    Renderer: ATI FirePro V3700 (FireGL) (ID=0x95cc)
    Vendor:   ATI
    VRAM:     253 MB


ExecutionEngineException: SIGILL
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_InitSafe ()

  at Steamworks.SteamAPI.Init () [0x00000] in <filename unknown>:0 

  at SteamManager.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
SteamManager:get_Instance()
SteamManager:get_Initialized()
AchievementTracker:SetAchievement(String)
AchievementTracker:OnTechChosen()
GameSettings:Init()
GameSettings:Awake()

**Comment by rlabrecque** [comment]
Closing this as we don't use SteamAPI_InitSafe() anymore, so hopefully what ever this was is loonng gone.
