### ISSUE TITLE
[Steamworks.NET] SteamAPI_Init() failed. Leaderboard and Achievement

### ISSUE THREAD

**Issue by unityguy12** [rlabrecque/Steamworks.NET#114]
When i change the steam app id from 480 to my id.
 i keep getting this error in my console
**[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.**
How to solve this ?

Also i want to get the leaderboard data and set achievements.
I don't know what method to call in order to do these things.
Couldn't find much in the documentation.

Please help.
Thanks :-)

**Comment by ridoutb** [comment]
Make sure you are logged into Steam using the same ID that your app is associated with.

**Comment by rlabrecque** [comment]
If you're still having issues could you repost in #83?

Just trying to consolidate stuff.
