### ISSUE TITLE
DON'T BUILD FROM SOURCE! Download the binary

### ISSUE THREAD

**Issue by Linchy** [rlabrecque/Steamworks.NET#117]
Just wasted five hours with this so am putting it here to help others. I downloaded from source and built it with my C# engine solution (not using Unity), and when I went to create a lobby the API just failed and said I had corrupt memory. 

I decided to try with the binaries from:

https://github.com/rlabrecque/Steamworks.NET/releases

and it worked! I can only guess there is a mismatch between the C code and the c# wrapper source as of the moment. Please like if this helped!

**Comment by elamaunt** [comment]
I had the same problem half an year ago. To solve the problem you should build sources with Windows compilation directive (or another for your platform). If you build Steamworks.Net project in debug (or release) mode it will not work correctly and can become in memory corrupting. Also see x86 or x64 version in you startup project.

**Comment by Linchy** [comment]
Ah good point that may have been it.

**Comment by rlabrecque** [comment]
Another potential issue is the version of CSteamworks.dll and steam_api.dll that you are using along side the compile Steamworks.NET.dll. All 3 dlls need to match both the platform and target the same version of the API.
