### ISSUE TITLE
Where I can found windows x64 version for Non-Unity project?

### ISSUE THREAD

**Issue by rutony** [rlabrecque/Steamworks.NET#119]
I tried to build, but it just closes with no message.
The release archive x86 only there.

**Comment by rutony** [comment]
I had to give up the x64 version.

**Comment by rlabrecque** [comment]
I only included a prebuilt x86 dll as XNA did not supported x64 and 99% of Non-Unity projects using Steamworks.NET are XNA based on Windows.

The biggest thing to watch out for is making sure you have the correct dll, either a Windows or OSX/Linux version and in x64, and then making sure you have the correct CSteamworks.dll AND steam_api.dll from the same version of Steamworks.NET that you're building for. (Taking those dlls from a prebuilt release and using them with the latest version of Steamworks.NET WONT work.)
