### ISSUE TITLE
How I can disable in-game overlay?

### ISSUE THREAD

**Issue by rutony** [rlabrecque/Steamworks.NET#120]
I use the component in the program. It has a little window with rendering. But this is not a game, I do not need that to be displayed in this window Steam achievements and posts. It is necessary to achieve that would be displayed near the clock, as default without a game window.

**Comment by rlabrecque** [comment]
You have to ask Valve on the Steamworks discussion board to disable it for you. By default it's automatically injected into all applications that render with D3D/OpenGL.
