### ISSUE TITLE
InitSafe() aborts with SIGILL

### ISSUE THREAD

**Issue by noio** [rlabrecque/Steamworks.NET#121]
A lot of our users are having the game crash with the following error:

```
ExecutionEngineException: SIGILL
at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_InitSafe ()
at Steamworks.SteamAPI.Init () [0x00000] in <filename unknown>:0 
at SteamManager.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
SteamManager:get_Instance()
SteamManager:get_Initialized()
<WaitForSteam>c__IteratorA3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
SteamWrapper:Init()
Managers:Init(Manager)
Managers:InitAll()
Managers:Awake()
```

I have found similar reports:
- https://steamcommunity.com/app/251570/discussions/1/626329821117472985/
- https://knucklecracker.com/forums/index.php?topic=20592.0
- http://steamcommunity.com/discussions/forum/1/371918937262070086/
- http://steamcommunity.com/app/348670/discussions/0/371918937278953902/
- and ours: http://steamcommunity.com/app/496300/discussions/0/360672304898613464/

Do you think there is a generic cause to these? And do you have any idea as for how to fix them?

If this is definitely not an issue with Steamworks.NET, please close this GitHub issue, in that case apologies for going through this channel with a question ;).

_EDIT_: Apologies! Just found the topic on the SteamworksDevelopment discussion board around this topic. Guess it doesn't show up on Google because it's walled off without login. For those with access:
- http://steamcommunity.com/groups/steamworks/discussions/0/364039531223325638/

**Comment by rlabrecque** [comment]
Hey noio, do you have any specific helpful users that could help us track this down? I never could reproduce it on many different computers.

Basically the first step is to try Valves steam_api.cs from the Steamworks SDK. It will likely require some 20-40 minutes worth of time disabling Steamworks.NET and integrating Valves steam_api.cs. If there's any chance that you could do that and then put up a beta branch for those users to try out it would be awesome!

**Comment by noio** [comment]
Ok! It's worth a shot.

Where do I find steam_api.cs ? I couldn't find it in the latest SDK download (1.37), maybe I'm looking wrong?

**Comment by rlabrecque** [comment]
Oh sorry, I wrote that really late, it's actually `steam_api_interop.cs` in the SDK.

Make sure you're using the latest steam_api.dll from that SDK version as well.

**Comment by noio** [comment]
Just as an update. I have a few users who consistently run into the issue, how could they help?

One is running a Pentium D, another one a Pentium 4.

**Comment by WazWaz** [comment]
The user I have with this problem is running Windows XP, if that helps.

**Comment by rlabrecque** [comment]
Were you ever able to look into this more yet @noio ?

**Comment by noio** [comment]
Not yet! I opted for a workaround, I uploaded a build without Steam integration to a beta branch for the 3-4 users with this problem.

I guess it's a group that will get even smaller over time, as it seems to be hardware bound.

**Comment by IQpierce** [comment]
Is this issue considered resolved? Or is it still outstanding?

**Comment by rlabrecque** [comment]
It comes up less and less, I'm pretty sure it's actually on Valve's side, but I've never been able to reproduce it. It seems to be a hardware spec issue, It only ever really happens to people running with really old <=Pentium 4 era hardware.

I'm keeping it open for now though until we can get some kind of confirmation that it's fixed.
