### ISSUE TITLE
SteamGameServer.InitGameServer doesn't work on Linux

### ISSUE THREAD

**Issue by mpah** [rlabrecque/Steamworks.NET#122]
I'm having the following issues here: 

**GameServer.Init** - works on Linux, doesnt work on Windows, connecting results in k_EBeginAuthSessionResultGameMismatch

**SteamGameServer.InitGameServer** - doesnt work on Linux, works on Windows, connecting results in k_EBeginAuthSessionResultOK

Any way to get SteamGameServer.InitGameServer to work on Linux so that I don't get a GameMismatch? GameServer.Init doesnt provide a parameter for the app id (my dedicated server has a different app id)

**Comment by rlabrecque** [comment]
With that last part specifically, I think you're supposed to set the appid with a steam_appid.txt in that case.

**Comment by mpah** [comment]
I have steam_appid.txt set, but its not enough.
It seems the only way to get a SessionResultOk instead of a GameMismatch is to provide the appid of the client inside InitGameServer. See: http://steamcommunity.com/groups/steamworks/discussions/0/523897653319127545/

**Comment by rlabrecque** [comment]
Awesome so did you get it resolved with those instructions?
