### ISSUE TITLE
CSteamID explicit cast operator to ulong, meant to be implicit?

### ISSUE THREAD

**Issue by Geminior** [rlabrecque/Steamworks.NET#123]
Is it by design that the cast operator is explicit?

I would personally make it implicit since its use case is such that it is only used to provide or receive a ulong argument/result.

**Comment by rlabrecque** [comment]
Yes, it's supposed to be explicit. It initially was not, and it ended up getting very confusing with all of the ulong types getting thrown around in the SteamAPI. Those cases where you get a ulong version of a CSteamID should be rare enough, I think the biggest offender is some of the older Callbacks.
