### ISSUE TITLE
IDisposable on CallResult and Callback

### ISSUE THREAD

**Issue by Geminior** [rlabrecque/Steamworks.NET#124]
I would like to suggest that IDisposable be implemented on CallResult and Callback so they can be disposed explicitly rather than wait for GC.

**Comment by rlabrecque** [comment]
That's a good idea, how would you like your code to look when using this? Would you just call Dispose() manually in OnDisable() or do you have a plan to use them with `using` statements?

**Comment by Geminior** [comment]
The former, e.g. when disabling components or other cases where you want to control life time explicitly.
I doubt there is a use case for the using statement given the asynchronous nature of these callback registrations.
But implementing IDisposable would cater to both.

**Comment by NKnusperer** [comment]
This would be very nice, currently have my own wrapper to do so which basically looks like this:
```
public interface DisposableSteamworksType : IDisposable { }

public class DisposableSteamworksCallback<T> : DisposableSteamworksType
{
	public DisposableSteamworksCallback(Callback<T> callback) { [...] }
	public void Dispose() => callback.Unregister();
}

public class DisposableSteamworksCallResult<T> : DisposableSteamworksType
{
	public DisposableSteamworksCallResult(CallResult<T> callResult) { [...] }
	public void Dispose() => callResult.Cancel();
}
```

**Comment by rlabrecque** [comment]
Let me know how that works out for you!
