### ISSUE TITLE
Method for excluding Steam on certain platforms?

### ISSUE THREAD

**Issue by noio** [rlabrecque/Steamworks.NET#125]
Sometimes it is necessary to exclude the Steam libraries completely when building for a certain platform. Simply not _Initializing_ is not enough on—for example—Universal Windows Platform. That compiles with .NET Core, in which much of the Steam lib's code is not allowed.

Right now I'm **1)** deleting the Steamworks.NET folder **2)** exporting projects for UWP **3)** adding the folder back in. But this is manual work that also requires a reimport on each step.

I wish that Unity had a method for managing which code (which folders) get included per platform or per "build configuration", but—in lieu of that—Steamworks.NET could do what Google Play Games Services does, as requested in this issue: https://github.com/playgameservices/play-games-plugin-for-unity/issues/276

They added a `NO_GPGS` symbol that excludes compilation of every single file in the library. Could that be an approach that is used in Steamworks.NET too? I'm about to try adding it locally to all the code in Steamworks.NET (i.e. `NO_STEAM`) but that will break when updating the code in the future of course.

**Comment by rlabrecque** [comment]
Thanks for the report, I think I fixed two different ways.

A: Building for UWP should just work now with ea4d348c42b8b1ba3eaed9848b05f16538df5e7b
B: All of the files are wrapped with "#if !DISABLESTEAMWORKS" in c303806e73cc1696775ea36ff8268a59afd6392d, so defining that via Unity's custom defines will prevent all Steamworks.NET code ending up in your builds.

Let me know how these work out for you!

**Comment by noio** [comment]
This is brilliant, going to check it out asap! 

So does that mean that the whole library is now compatible with **.NET Core** even _without_ excluding it through DISABLESTEAMWORKS ? (Why would you want to compile for UWP _with_ Steam support?)

**Comment by rlabrecque** [comment]
When you use something like DISABLESTEAMWORKS then you have to make sure to wrap all usages of Steamworks.NET in #if statements as well.

See also: #126
