### ISSUE TITLE
Unity 5.1.3 callback crash

### ISSUE THREAD

**Issue by s-m-k** [rlabrecque/Steamworks.NET#127]
I try to implement leaderboards. Everything seems to work in the editor (Windows, 64-bit), the leaderboard data is downloaded, scores are uploaded etc., but the editor crashes when I quit the game. It's even worse in 32-bit build, as it just crashes right when the menu (with leaderboards) is loaded (the 64-bit one behaves like the editor).

I think that something weird happens when I create CallResult<T> object. Is it fairly known problem or am I possibly doing something stupid?

**Comment by s-m-k** [comment]
Bump.

**Comment by rlabrecque** [comment]
Hey sorry, I was out of town when you first posted that, I looked at it but then forgot about it!

I had noticed a leaderboard related crash happening in a script that I had too, I'll look into it this week!

**Comment by s-m-k** [comment]
Great! So far I ended up implementing my own backend for leaderboards.

Also, that means I can't probably really implement anything else that uses callbacks, like Steamworks integration etc., so having that feature work would be really helpful. So, thanks in advance :)

**Comment by rlabrecque** [comment]
I was able to reproduce it twice but I can't anymore :(

I'll keep trying but it's a weird one!

**Comment by s-m-k** [comment]
Any update on this issue?

**Comment by s-m-k** [comment]
I managed to port my project to Unity 5.5.1. I wonder if the issue will still be there.

**Comment by rlabrecque** [comment]
Not yet, I've been out of town, let me know if it's stioll happening or if you can help me repro it easier!

**Comment by s-m-k** [comment]
Unfortunately, it still doesn't work in Unity 5.5.1. In the editor, it works (i.e. downloads all data and stuff) until I stop the game, then the editor crashes.

Executing the following code a single time is enough to crash and works every time (i.e. when I stop the game).

```
onSteamLeaderboardFind = CallResult<LeaderboardFindResult_t>.Create();
SteamAPICall_t call = SteamUserStats.FindOrCreateLeaderboard(levelName, ELeaderboardSortMethod.k_ELeaderboardSortMethodAscending, ELeaderboardDisplayType.k_ELeaderboardDisplayTypeTimeMilliSeconds);
onSteamLeaderboardFind.Set(call, OnLeaderboardFind);
```

I probably won't use the steam leaderboards since I ended up rolling my own solution which works now, but I'm yet to try Steamworks functionality.

I'm using the current .unitypackage version available on the site.

**Comment by s-m-k** [comment]
Weird, I've found that it might be actually a FMOD problem. For some reason I'd never checked the Unity dump logs before, but...

```
fmodstudio.dll caused an Access Violation (0xc0000005)
  in module fmodstudio.dll at 0033:d95abdf0.
```

I'll let you know more when I find out what's actually wrong. It's really a weird issue, maybe even unrelated to Steamworks.NET. I'll try using a different version of FMOD and see if that helps.

Ah, the wonders of unmanaged code.

**Comment by rlabrecque** [comment]
Hmm, try updating Steamworks.NET as well by grabbing the latest master here. https://github.com/rlabrecque/Steamworks.NET/archive/master.zip

Close Unity, unzip that and then copy and overwrite the Plugins/ and Editor/ folders in your Assets/ folder.

**Comment by s-m-k** [comment]
So far I've updated the fmod integration to the latest version (and the 2.0 one, which was unavailable for 5.1.3). There's some progress. No crash in editor nor in 64-bit build, still crashes in 32-bit builds though (and as soon as you try to download the scores).

I'll try now with the freshest Steamworks.NET version you suggested.

**Comment by s-m-k** [comment]
Tried Steamworks.NET from master.zip. The difference is that I get the nicknames for some reason (with the .unitypackage one I didn't). Again, works OK for x86_64, crashes for x86.

It's like the FMOD system instance pointer is somehow freed and the next update causes access violation. Not sure why that happens.

I narrowed the crash-causing line down to this (again, now it happens only in x86 version):
```CallResult<LeaderboardFindResult_t>.Create();```

Without it, the API call is fine. Trying to understand why it does funny things with FMOD memory.

**Comment by rlabrecque** [comment]
Is that `CallResult<LeaderboardFindResult_t>.Create();` line being assigned to a member variable that outlasts everything or a function local variable that gets cleaned up when the scope returns?

**Comment by s-m-k** [comment]
It's assigned to a private property of an object (not temp variable). It should actually be

```onSteamLeaderboardFind = CallResult<LeaderboardFindResult_t>.Create();```

Like in my previous example.

**Comment by s-m-k** [comment]
Now I think I narrowed it down something weird. In `CallbackDispatcher.cs`, `OnRunCallResult` method, when I simply access `hSteamAPICall` argument, it crashes. Tested with nothing but `UnityEngine.Debug.LogError(hSteamAPICall);` in the function body (empty function doesn't crash).

In the real code, the crash seemed to happen on the line `if (hAPICall == m_hAPICall) {`.

Also, `SteamAPICall_t hAPICall = (SteamAPICall_t)hSteamAPICall;` works fine for some reason.

I changed the `ulong` to `uint` and that way it didn't crash when I accessed the variable.

Are my findings helpful so far?

**Comment by s-m-k** [comment]
BTW is there a possibility to just have sync functions as a failsafe variant, i.e. all callback stuff would be done in an unmanaged library and it would just return nice and simple data?

**Comment by s-m-k** [comment]
I tried to make a fresh project with the basic functionality (FMOD, leaderboards, some functions in the game) and did a 32-bit build. It worked. I have no idea what might be wrong with my game. I don't really do anything unsafe (besides FMOD and Steamworks.NET). I still think it _might_ be Steamworks.NET problem (though not really sure now), since you were able to reproduce the bug 2 times, and it all seems to be just a lottery that I won.

Now (with new FMOD and Unity) the 64-bit version seems to work flawlessly, the 32-bit build still crashes right away.

Any ideas how to work around it besides writing my own specialized wrapper in C++?

**Comment by rlabrecque** [comment]
Oh hey, I think this was fixed recently!

**Comment by ZehCastro** [comment]
Sorry for the necromancy, I just got a crash that sounds a lot like what he describes.
It's the first time it happens, so I'm still going to try to pinpoint it further. For the time being, here is
the log file:
[FModSteamworksCrash-clean.log](https://github.com/rlabrecque/Steamworks.NET/files/2666123/FModSteamworksCrash-clean.log)

**Comment by ZehCastro** [comment]
What I don't get is this kind of stack trace:
```
NullReferenceException: Object reference not set to an instance of an object
  at Steamworks.CallResult`1[T].OnRunCallResult (System.IntPtr thisptr, System.IntPtr pvParam, System.Boolean bFailed, System.UInt64 hSteamAPICall_) [0x00009] in C:\devel\mvsc\musashi-vs-cthulhu\Assets\Plugins\Steamworks.NET\CallbackDispatcher.cs:314 
  at (wrapper managed-to-native) FMOD.Studio.System.FMOD_Studio_System_GetBus(intptr,byte[],intptr&)
  at FMOD.Studio.System.getBus (System.String path, FMOD.Studio.Bus& bus) [0x0001b] in C:\devel\mvsc\musashi-vs-cthulhu\Assets\Plugins\FMOD\Wrapper\fmod_studio.cs:393 
  at FMODUnity.RuntimeManager.GetBus (System.String path) [0x0000c] in C:\devel\mvsc\musashi-vs-cthulhu\Assets\Plugins\FMOD\RuntimeManager.cs:962 
  at FMODUnity.RuntimeManager.MuteAllEvents (System.Boolean muted) [0x00006] in C:\devel\mvsc\musashi-vs-cthulhu\Assets\Plugins\FMOD\RuntimeManager.cs:986 
  at FMODUnity.RuntimeManager.Update () [0x001e8] in C:\devel\mvsc\musashi-vs-cthulhu\Assets\Plugins\FMOD\RuntimeManager.cs:366 
 
(Filename: Assets/Plugins/Steamworks.NET/CallbackDispatcher.cs Line: 314)
```

Why would `FMOD_Studio_System_GetBus` ever call `Steamworks.CallResult1[T].OnRunCallResult`?

```
public RESULT getBus(string path, out Bus bus)
{
	using (StringHelper.ThreadSafeEncoding encoder = StringHelper.GetFreeHelper())
	{
		return FMOD_Studio_System_GetBus(this.handle, encoder.byteFromStringUTF8(path), out bus.handle);
	}
}

[DllImport(STUDIO_VERSION.dll)]
private static extern RESULT FMOD_Studio_System_GetBus(IntPtr studiosystem, byte[] path, out IntPtr bus);
```
