### ISSUE TITLE
SteamUGCQueryCompleted_t Call result not working outside of editor?

### ISSUE THREAD

**Issue by meadows1989** [rlabrecque/Steamworks.NET#128]
Everything is working as intended inside of editor, getting callresult no problems. When I create a build though, nothing is returning from my query request (UGC).   Same issue when piped to steam and run through their system.

**Comment by rlabrecque** [comment]
Sorry for the late reply!

Which version of Steamworks/.NET are you running? Could you try again with the latest master?
