### ISSUE TITLE
ISteamController_TriggerRepeatedHapticPulse unavailable

### ISSUE THREAD

**Issue by carrotstien** [rlabrecque/Steamworks.NET#129]
Hi, I see this in your code, but I don't see anyway of calling it. Furthermore, it looks like that code gets auto generated, and the latest generation doesn't contain that call. 

Is that call no longer available, or is there another way to get to it?

**Comment by rlabrecque** [comment]
Hey @carrotstien,

Are you running the latest version of Steamworks.NET from github? The packaged releases are a couple updates behind the latest Steamworks SDK.

https://github.com/rlabrecque/Steamworks.NET/blob/d617ccdb85db1ca72af8c020e55196d7e03a53bf/Plugins/Steamworks.NET/autogen/isteamcontroller.cs#L155
