### ISSUE TITLE
Test (unity) app does not shut down properly.

### ISSUE THREAD

**Issue by JocelynSachs** [rlabrecque/Steamworks.NET#13]
If you run the test app, and then close it, Steam thinks it's still running and won't close.

**Comment by omgnoseat** [comment]
I am still having this issue unfortunately. Even manually calling SteamApi.Shutdown() at any time in the game's lifecycle does not do anything :( 
I'm using the latest build and latest example, and the example also has this problem.

**Comment by derosa** [comment]
Hi, I'm having the same issue too. I'm using Unity 5.0.0 b19 with the latest Steamworks.NET stable version (5.0.0).

It happens when running the game both from Unity and from Steam. In fact when running from Unity, you can clearly see that even after stopping the game and calling SteamApi.Shutdown(), the game is shown as "currently playing" on my Steam profile.

**Comment by rlabrecque** [comment]
So with @derosa's help there's been some improvements.

His issue ended up being Unity starting adb.exe for Android Development. Steam tracks all subprocesses (I.E. if there's a launcher) and if something that has been launched from Unity remains open afterwards it will still detect you as In-Game. (Visual Studio, MonoDevelop are common culprits as well!)

With commit 3e4580294b423517315cbde9135cb275d03e9235 Steamworks.NET now checks to ensure that SteamAPI.Init() has not been called more than once per session. The big thing that this should hopefully help with is checking SteamManager.Initialized after SteamAPI.Shutdown() has been called (say in an OnDestroy that gets called after SteamManager goes away).

And just a reminder that Steam will always show you as In-Game when the editor is open after you play in the editor once.

Do any of these help you @omgnoseat?

**Comment by sloankelly** [comment]
I'm having this issue too, I'm afraid. Even after closing down Unity/Visual Studio, the client still says I'm playing the game. This also affects the build too; playing the game through the Steam client and then quitting does not reset what game I'm playing.

**Comment by rlabrecque** [comment]
http://steamcommunity.com/groups/steamworks/discussions/0/611696927914497414/

There is this report of it happening due to the launcher, I haven't had a chance to investigate that yet, but it's another thing to look into.

**Comment by omgnoseat** [comment]
@rlabrecque commit 3e45802  seemed to do it for me, thanks! :+1:

**Comment by rlabrecque** [comment]
Not Steamworks.NET related but I found this pretty funny and relevent to this issue: http://steamcommunity.com/groups/steamworks/discussions/0/612823460253767971/

If you're still having this issue at this point please try running [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) to see if your project launches any subprocesses.

**Comment by WazWaz** [comment]
Is there a reason _intialized is not set to false in Shutdown()?

I'm accessing global stats from editor windows and if I don't call Init(), I get "Steamworks is not initialized.", but calling Init() gives "Tried to Initialize Steamworks twice in one session!". Currently I'm setting _initialized=false in Shutdown(), but I'm concerned that's defeating whatever commit 3e45802 was trying to fix.

**Comment by rlabrecque** [comment]
Hey @WazWaz, that commit is largely trying to fix calling SteamAPI_Init from OnDestroy/OnDisable/OnApplicationQuit, which could occur after SteamAPI_Shutdown has already been called. This results in no final Shutdown() being called, and hence this issue. (Well, atleast part of this issue.)

By setting _initialized to false ever you counteract this safeguard. This wasn't implemented with your use case in mind. so what you're doing (or even ripping out the _initialized stuff completely) would be completely fine.

**Comment by rlabrecque** [comment]
Looks like this experiment worked out, but I've since removed it and moved it into SteamManager.

Commit where it was removed: f02de041669bf0183356de3ab65b012c7426afa2
Additional reading: #59 
Commit where it was added to SteamManager: https://github.com/rlabrecque/SteamManager/commit/91d821a5d0a8095878c341fb05e5330a7ebac8b9

**Comment by cttpla** [comment]
This issue is still persistent.
I simply downloaded the latest package and installed it.
I'm doing nothing special, i simply call Application.Quit() on pressing ESC.

The triggered code is

public void OnDestroy() {
		if (s_instance != this) {
			return;
		}

		s_instance = null;

		if (!m_bInitialized) {
			return;
		}

		SteamAPI.Shutdown();
	}


But still Steam says the game is running.

**Comment by gsylvain2** [comment]
I have the exact same issue.

> This issue is still persistent.
> I simply downloaded the latest package and installed it.
> I'm doing nothing special, i simply call Application.Quit() on pressing ESC.
> 
> The triggered code is
> 
> public void OnDestroy() {
> if (s_instance != this) {
> return;
> }
> 
>     s_instance = null;
> 
>     if (!m_bInitialized) {
>         return;
>     }
> 
>     SteamAPI.Shutdown();
> }
> But still Steam says the game is running.

**Comment by rlabrecque** [comment]
Yeah, SteamAPI.Shutdown() won't stop your game from running in Steam. The only thing that will do that is having all the processes spawned by your game close. That is including the Unity editor, and any other applications that it launches.

**Comment by KidneyThief** [comment]
I'm having the same issue, but it has nothing to do with the Unity Launcher.
It's a Unity based game, however, I'm thinking the problem is Windows 10 related.

1.  I've tried every variation of calling SteamAPI.Shutdown() in OnApplicationQuit(), OnDestroy(), and tied to the callback event for a button press - nothing works.
2.  I've used Process Explorer, and can not find any other process related to my game (which makes sense - it's a simple game, and I don't create any), except the GameOverlayUI.exe from Steam, and I've verified that it shuts down when my application exits.
3.  The game shuts down just fine, on my other PC, which is still running Vista.  My current system exhibiting this issue is running Windows 10.  (Related?  idk, but not the first Windows 10 issue I've had)

I could use some additional suggestions...

**Comment by Gruguir** [comment]
So maybe it can help, i had the same issue (Windows 10), and that does the trick for me :

```
private void OnDestroy() {
		if (s_instance != this) {
			return;
		}

		s_instance = null;

		if (!m_bInitialized) {
			return;
		}

		SteamAPI.Shutdown();
	}

    private void OnApplicationCancelQuit() // (CUSTOM)
    {
        if (s_instance != this)
        {
            return;
        }

        s_instance = null;

        if (!m_bInitialized)
        {
            return;
        }

        SteamAPI.Shutdown();
    }

    private void OnApplicationQuit() // (CUSTOM)
    {
        if (s_instance != this)
        {
            return;
        }

        s_instance = null;

        if (!m_bInitialized)
        {
            return;
        }

        SteamAPI.Shutdown();
    }
```

**Comment by KidneyThief** [comment]
Hmm... for some reason, I'm now no longer to reproduce the issue - 
I'll add the new method anyways - your help is much appreciated! 

----- Original Message -----

**Comment by GLJeff** [comment]
Win10, PC 64 and 32 bit builds, version 7.0.0, this problem is occurring.
Attempts to shutdown steam will sometimes result in Unity closing on its own. Yet even with Unity, Visual Studio, and the application itself being shut down, steam still believes the app is running and won't shut off.

-Tried Grugier's fix above, which had no effect.

**Comment by fredsa** [comment]
I also continue to be plagued by the game still showing up as "Running" after it is killed:
- Windows 10, 32 bit builds
- Steamworks SDK 1.38a
- Steamworks.NET version 7.0.0, but with latest files from commit d617ccdb

If I remove all references to Steamworks.NET APIs from my scripts, my game no longer gets stuck showing that is "Running" according to Steam. All I need to do is add an empty game object to my scene and attach `SteamManager.cs` to experience the "Running" issue.

I verified with extra logging that `SteamAPI.Shutdown()` is being called from SteamManager's `OnDestroy()` method when the game shuts down.

My app launch options (https://partner.steamgames.com/apps/config/<app_id>) specify the _Executable_ and _Launch Type_: **Launch SteamVR App**.

**Comment by codingoat** [comment]
I encountered the issue in Windows 10 64bit too, my game is a SteamVR app as well.

**Comment by fredsa** [comment]
I found (using Unity 5.4.2f2-GVR13) that hitting play inside the Unity editor causes Unity to execute `adb forward tcp:7201 tcp:7201` (even when the current build platform is not "Android", but "Standalone" Windows). This adb command causes adb to start a persistent server process (which looks something like this: `adb -P 5037 fork-server server --reply-fd 652`). It's this persistent adb.exe process which can cause Steam to think your game is still running even after you quit the Unity editor.

I reported this unexpected execution of `adb forward...` when the build platform is "Standalone" as Unity case # 865265.

**Comment by gw1108** [comment]
I think fredsa is right. I also had adb.exe creating itself in my Unity project whenever I launched from the editor. Adding an OnApplicationQuit() { kill process adb.exe } and then closing the Unity editor stopped Steam from thinking I was still in the game.

**Comment by kazenotenshi** [comment]
Is this issue still open? I'm having the same problem in windows 10 and Unity 5.4.3 and I've tried already to use the code snippet above.

**Comment by gw1108** [comment]
If you don't have the adb.exe process visible in task manager then steam should show you as online (not in game) assuming you also closed Unity and any other process started by Unity like Visual Studio. Try to recreate your problem in a simpler Unity project that's almost empty.

**Comment by kazenotenshi** [comment]
@gw1108 I just created a small project in Unity that basically has one script which does the following:

`public class SteamInit : MonoBehaviour {

    public static SteamInit Instance;

    private bool m_bInitialized;
    public static bool Initialized
    {
        get
        {
            return Instance.m_bInitialized;
        }
    }

    void Awake()
    {
        Instance = this;

        m_bInitialized = SteamAPI.Init();
        if (!m_bInitialized)
        {
            Debug.LogError("[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.", this);

            return;
        }
    }

    // Use this for initialization
    void Start () {
	
	}
	
	// Update is called once per frame
	void Update () {
	
	}

    private void OnGUI()
    {
        GUI.Label(new Rect(1, 1, 20, 10), m_bInitialized ? "Steam is Ok!" : "Steam is not initialized");
    }

    private void OnDestroy()
    {
        if (!m_bInitialized)
        {
            return;
        }

        SteamAPI.Shutdown();
    }
}`

And the error still appears. I'm using Unity 5.4.3 Pro and Windows 10.
Here's the link for the project: https://drive.google.com/open?id=0ByDHc2dTpFoJYmE1SEZPQzBSOTA
Here's a screenshot of my steam after shutting down Unity: https://drive.google.com/file/d/0ByDHc2dTpFoJTVI4SW80QjA4QXc/view?usp=sharing

**Comment by fredsa** [comment]
For the `adb` subprocess issue here are a couple of tips:
- You can run `adb kill-server` to get rid of that adb process, although the next time you enter play mode, Unity will spawn a new adb process.
- As a workaround you can run `adb forward tcp:7201 tcp:7201` *before* starting Unity, which makes it so that Steam will no longer consider adb a subprocess (because it's not spawned from Unity editor).

**Comment by skyniteVRinsider** [comment]
Gruguir's code worked for me on a SteamVR project. At least for now...

**Comment by rlabrecque** [comment]
There's a bug with SteamVR that causes this currently as well

http://steamcommunity.com/groups/steamworks/discussions/0/135513421439536745/?ctp=2

**Comment by JorgeAiresJr** [comment]
This problem still persists for me:
- Windows 10
- Unity 5.6.0f3
- Steamworks.NET Release 9.1.0

I tried the Gruguir workaround but didn't works.
I published the game and the released version has this problem. Worried now!

**Comment by ajwalters** [comment]
I recently added Steamworks.NET to my project and I'm noticing this issue on macOS 10.13.5 with Unity version 2017.4.1f1 with the latest SDK.  When i stop the editor, it still says running.  I either need to quit steam or the unity app completely for it to go away.

I tried @Gruguir code and it didn't resolve the issue.

Has anybody else experienced this and have a workaround?

Thanks

**Comment by User199011** [comment]
Hi,
Great job with Steamworks.NET.

I got the latest version in Unity and haven't changed the SteamManager.

Shutdown seems to be called but it's still written as running in Steam (without the editor open). I've checked with Process explorer and can't see anything related to my game.

Any workaround to force Steam to think my game is closed ?

Thanks

**Comment by eyalfx** [comment]
Yes, everything is working absolutely great. Except the shutdown sequence.
I'm using unity5.6 without changing the SteamManager.

**Comment by JashanChittesh** [comment]
Just something I ran into using Unity 2018.3: I had Unity closed, Visual Studio closed, confirmed that adb wasn't running but it still showed my game is running. Using Process Explorer, I noticed VBCSCompiler.exe, which had a child called conhost.exe. When I killed that, Steam finally saw that the game / editor was no longer running.

Interestingly, a little while after restarting Unity, VBCSCompiler showed up again in Process Explorer - but Process Explorer doesn't seem to know that this process was started by Unity (it's shown as a root process). Unity does spawn a few processes that have conhost.exe as child, though, so maybe Steam gets confused by that. All the other processes that Unity starts on my machine seem to be properly closed when closing Unity.

**Comment by stonstad** [comment]
> Steam only knows that your app has shut down when the last child process quits. No way around that unfortunately.

OK, this should probably be mentioned in greater detail in the docs/FAQ for SteamWorks.NET.  It is still broken and devs need to know that killing their Unity editor is a known workaround.

**Comment by wappenull** [comment]
Just to add to future reader.
I got **VBCSCompiler.exe** still left running after exiting Unity 2019.3.15.
(C:\Program Files\Unity\Hub\Editor\2019.3.15f1\Editor\Data\Tools\Roslyn\VBCSCompiler.exe)

By terminating it, finally make Steam see me as stopped playing.

**Comment by pipliz** [comment]
I'd like to note here (I've not read all the comments, sorry if it's already said) that it is behaviour from steam itself that isn't related to the Steamworks.NET wrapper. Presumably it will not be changed since game behaviour can depend on it - if your game runs in multiple processes (say a hard client-server split) you may depend on steam waiting for both to be stopped before it will try to do stuff like cloud sync data which you may still be writing to from the server process, or updating the game.

**Comment by leonard4** [comment]
Has any headway been made on this? Built a standalone version, rebooted, launched Steam and launched my game, name shows up correctly. I exit out of the game and it still shows me as playing the game in steam. If I launch another game it updates, but once I exit it loads my game name right back in.

**Comment by stonstad** [comment]
It may not be a bug but it is the wrong behavior for a downstream SDK.  

The FacePunch SteamWorks SDK does not exhibit this behavior (https://github.com/Facepunch/Facepunch.Steamworks) and, since switching, I haven't had a problem.

**Comment by rlabrecque** [comment]
That's interesting @stonstad, was this with Unity? In a release build?

Facepunch.Steamworks FAQ suggests that it behaves exactly the same here, which is likely since it's a property of running the game through Steam, not even anything to do with any SDKs.

https://wiki.facepunch.com/steamworks/Installing_For_Unity#shuttingdown

**Comment by stonstad** [comment]
I have to profess my ignorance then. With the FacePunch wrapper I do not have issues with my Unity editor instance being force closed.  Similarly, I do not have to kill an external process for my debug/run cycle to work.  That I had these problems with SteamWorks.Net may be attributed to my user error.

**Comment by rlabrecque** [comment]
Darn, I was hoping they had some magic sauce for this!

If anyone reading this in the future also notices that this only happens with Steamworks .NET and not Facepunch.Steamworks I'd be interested to hear about it!

**Comment by zorkind** [comment]
This sucks, i wanted to use the SteamAPI to grab data from Steam, in a Launcher App BEFORE actually launching the game.

But since Steam considers the game as RUNNING, i can't Launch the game from my Launcher. :(

**Comment by AndrewNovakP** [comment]
> Darn, I was hoping they had some magic sauce for this!
> 
> If anyone reading this in the future also notices that this only happens with Steamworks .NET and not Facepunch.Steamworks I'd be interested to hear about it!

Same issue with Facepunch.Steamworks too

**Comment by vi-step** [comment]
Not solved for 9 years... having same issue

**Comment by stonstad** [comment]
Just use the Facepunch Steam SDK. I switched years ago and have had no trouble.

**Comment by Zerg73** [comment]
So,does anyone know how to fix it?

**Comment by gakkossphynx** [comment]
same

**Comment by stonstad** [comment]
SteamPunk API

**Comment by Zaknarfen** [comment]
Same, sigh....

**Comment by skullthug** [comment]
Uh oh.. I'm at the bottom of reading this long thread and nobody still knows a good solution?

**Comment by Ritbulau** [comment]
There is no way this issue is 10 years old and there is no good solution 💀

**Comment by lgs-website** [comment]
需要关闭Unity编辑器，Steam界面上正在玩的标记才会移除。
我用的是测试用例。
请看以下截图：
1.未启动Unity编辑器时候，Steam的状态
![image](https://github.com/user-attachments/assets/d8f9be17-f803-4a97-bd53-108bf92ccbaf)
2.启动Unity编辑器时候，Steam的状态
![image](https://github.com/user-attachments/assets/9bfe8efc-f6ed-44c9-81d4-bc443e124490)
3.停止播放Unity编辑器时候，Steam的状态
![image](https://github.com/user-attachments/assets/7f0dd57d-69a1-4964-9e69-81b4421af0bc)
4.关闭Unity编辑器，挺个3秒左右，Steam的状态
![image](https://github.com/user-attachments/assets/186cc6f7-ddb7-4429-b6ba-15e9c2669e81)
以下是我的代码:
![image](https://github.com/user-attachments/assets/f5a9fdb2-8798-4058-80a6-6226773da447)

**Comment by gakkossphynx** [comment]
> You need to close the Unity editor to remove the "playing" mark on the Steam interface. I used a test case. Please see the following screenshots: 1. Steam status when the Unity editor is not started 2. Steam status when the Unity editor is started 3. Steam status when the Unity editor is stopped 4. Steam status after the Unity editor is closed for about 3 seconds The following is my code: ![image](https://github.com/user-attachments/assets/d8f9be17-f803-4a97-bd53-108bf92ccbaf) ![image](https://github.com/user-attachments/assets/9bfe8efc-f6ed-44c9-81d4-bc443e124490) ![image](https://github.com/user-attachments/assets/7f0dd57d-69a1-4964-9e69-81b4421af0bc) ![image](https://github.com/user-attachments/assets/186cc6f7-ddb7-4429-b6ba-15e9c2669e81) ![image](https://github.com/user-attachments/assets/f5a9fdb2-8798-4058-80a6-6226773da447)

Finally is this issue over ?

**Comment by homelleon** [comment]
There is another relative problem. When I change steam_appid.txt file the Steamworks.Net starts always previous id. To solve that I have to manually exit Unity.
I'm trying to kill steam process and restart Unity automatically. But it doesn't help. On gameplay start steam shows test project even if I changed id in the file before killing steam processes and restarting Unity.
I think that there is still Steamworks.Net process is operating and it stops when Unity closed manually but doesn't with use of EditorApplication.OpenProject(System.IO.Directory.GetCurrentDirectory());
Or maybe it has some cashe that should be cleared.

**Comment by homelleon** [comment]
To reset app is still executing just restart steam:
```
System.Diagnostics.Process.Start("cmd.exe", "/C taskkill /im steam.exe /f");

string unityExePath = EditorApplication.applicationPath;
string projectPath = System.IO.Directory.GetCurrentDirectory();
int delay = 10;

System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
{
	FileName = "cmd.exe",
	Arguments = $"/C \"timeout /t {delay} > nul && start \"\" \"{GetSteamPath()}\"",
	CreateNoWindow = true,
	WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden
});
```
But it doesn't solve my problem.
