### ISSUE TITLE
Callback never called ?

### ISSUE THREAD

**Issue by User199011** [rlabrecque/Steamworks.NET#130]
Hello,
I'm trying to include the steam workshop to my WPF application. The overlay isn't working (because of WPF) and I'm not able to get any callresult from Steamworks.net. I call the RunCallbacks methods (from gameserver and SteamAPI) in a timer every 20ms.

I've called the init method on both steam API and gameserver (with Space wars default ports) and they return true. But When I create my item on the workshop the callresult is never fired and i'm not able to continue the upload process.

When I enable the overlay  (using a black sharpGL render on top on my application) the overlay's callback are working. But still no sign of the item's callresult.

Do you have any hint to make the callresult of the createItem work ?

Thanks

**Comment by rlabrecque** [comment]
Whew, I missed this, did you ever get it working?

Were you setting the SteamAPICall_t handle into the CallResult?
