### ISSUE TITLE
Add support Unity 4.7 

### ISSUE THREAD

**Issue by am1goo** [rlabrecque/Steamworks.NET#131]
Found some problem with Unity 4.7. Need use define UNITY_4_7 into CallbackDispatcher.cs and others scripts (if applied).

**Comment by rlabrecque** [comment]
Hey @am1goo, I just tried with Unity 4.7 again just now and everything still seems to be working, I added support for it in 8c548efb91903881d8f6e4cea8b2856eaffe53b9 back in June
