### ISSUE TITLE
SteamFriends.GetFriendCount() should document -1 return value

### ISSUE THREAD

**Issue by fredsa** [rlabrecque/Steamworks.NET#132]
Sample usage which is problematic:

    // May return -1
    int friendCount = SteamFriends.GetFriendCount (friendType);

    // Which can result in, say, OverflowException
    Friend[] friends = new Friend[friendCount];

Current help text:

    /// <summary>
    /// <para> friend iteration</para>
    /// <para> takes a set of k_EFriendFlags, and returns the number of users the client knows about who meet that criteria</para>
    /// <para> then GetFriendByIndex() can then be used to return the id's of each of those users</para>
    /// </summary>

I ran into this using:
- In the Unity editor on OSX
- Files from this repo @ commit `d617ccdb85db1ca72af8c020e55196d7e03a53bf`
   (applied on top of the `Steamworks.NET_7.0.0.unitypackage` stable release)

**Comment by fredsa** [comment]
To reproduce, tell Steam to not remember your password, then launch Steam, but leave the password login screen up while your app calls {{{SteamFriends.GetFriendCount}}}.

**Comment by fredsa** [comment]
Riley, I understand these code comments are straight from the Steam API source. What's the right place to file Steam API documentation bugs like this, so that we can get this fixed at the source?

**Comment by rlabrecque** [comment]
For now here isn't a terrible place. Hopefully there will be a smoother method soon enough!

**Comment by rlabrecque** [comment]
https://partner.steamgames.com/doc/api/ISteamFriends#GetFriendCount 👍 

Steamworks forum is now the better place for this.

The text in the header files may be updated one day but for now this new documentation site is the authoritative version.
