### ISSUE TITLE
SteamManager class is private, but should be public

### ISSUE THREAD

**Issue by bobmoff** [rlabrecque/Steamworks.NET#133]
When downloading the .assetpackage, the SteamManager class is private, instead of public which makes checking of the Initialized property not possible. I could not find the file in this repo so I could make a PR, so I hope it is ok to report the issue here

**Comment by rlabrecque** [comment]
This only ever happens when accessing SteamManager from a different compilation stage right?

This has been fixed on master already, it will be rolled into the next release.
https://github.com/rlabrecque/SteamManager/commit/71685313d9c7106cedd2dfa1fb62d46272080fcd
