### ISSUE TITLE
Problem with Unity 4.6.0f3 | Unity 4.7.2 Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location

### ISSUE THREAD

**Issue by vaccionesmad** [rlabrecque/Steamworks.NET#136]
Hi rlabrecque, I apologize if this has been asked before but here goes, I was initially working with the 4.6.x version of Unity mentioned above and always got this error: 

[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: CSteamworks
  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00005] in C:\xxxx\yyyyy\ttttt\hhhh\aaaaa\Assets\Plugins\Steamworks.NET\Steam.cs:41 

I read that perhaps this was caused beacuase it was an older Unity version, so I upgraded to 4.7.x above and still get this problem, I saw in the closed issues that it should be fine with this version of Unity (a issue of 4 days ago i think) but not for me apparently :( 

I've tried several solutions found here and still the error, so, am I missing something man?

Any help would be appreacited, so thanks.

**Comment by rlabrecque** [comment]
Unity 4 handled dependent dlls a little differently than Unity 5.1+, did the steam_api.dll successfully get copied into your project root (Next to the Assets/ and ProjectSettings/ folders)?

**Comment by vaccionesmad** [comment]
![folder capture](https://cloud.githubusercontent.com/assets/24719364/21438823/524315c0-c861-11e6-98a1-8b271bb08cf4.png)

Thats how the root folder looks, disregard all the trash please I plan to clean up after the game is finished.

I guess that is the steam_api.dll you mention, it did copy to that folder the second time I booted Unity after adding the assetpackage, but the error still pops up.

I don't really know much about this stuff honestly, so after a while I copied that file and replaced it with the steamworks sdk to test and still the error, then went back to the original file.

Is there something wrong there that I missed man?

**Comment by rlabrecque** [comment]
Oh! Update to the latest version of Steamworks.NET from github from here: https://github.com/rlabrecque/Steamworks.NET/archive/master.zip

First quit unity, and then unzip that file somewhere, and then copy the Editor/ and Plugins/ folders into your Assets folder, overwriting all the old files. I'd also recommend cleaning up all the steam .dll's, .so's, and .meta files in your screenshot before you do this, so they can get automatically updated too.

**Comment by vaccionesmad** [comment]
![after folder](https://cloud.githubusercontent.com/assets/24719364/21444588/6c9a253e-c885-11e6-85fa-4e703fa2b762.png)

Did All that and the error remains, I even deleted the Xinput dll's. 

I'm gonna keep trying any other solution you wrote here in issues Riley, something will eventually work I guess.

**Comment by vaccionesmad** [comment]
Hey Riley I think I got it to work, I grabbed the steam_api.dll and CSteamworks.dll , pasted them in both the root directory and the Unity editor folder ((Program Files)/Unity/Editor), So far I've gotten to the part of your "Getting Started" documentation that reads my user and it works in several scenes (that didn't happen before). 

Since it said that "System.DllNotFoundException: CSteamworks", I found this post http://answers.unity3d.com/questions/439376/dllnotfoundexception-multiple-c-and-c-dlls.html

I won't close the issue yet, just wanted to share the "so far so good" man.
