### ISSUE TITLE
GameServer.Init fails when other GameServers already running

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#138]
Hi Riley,

seems like there might be an issue with older SteamAPIs and the use of multiple game server instances on a single host. Doesn't affect everyone (e.g. can't repro myself) but got at least two reports by now stating that whenever they start our server second to any other Steam game server, e.g. Garry's Mod or even another instance of ours, GameServer.Init fails, rendering the whole thing useless.
One of the affected users now tried with an up to date SteamAPI64.dll (file version 3.75.32.7 from SDK 1.39; not touching anything else) and it seems to solve the issue. Obviously just replacing the DLL for our game doesn't feel like a good idea as it could break the linking from CSteamworks which might only show up at random times in the game?
Would it be possible to get a new Steamworks.NET release that is linked against the latest SDK?

Regards,
Chris

**Comment by rlabrecque** [comment]
Like this? ;)
e6e5c85899dcc3190f84a622ce97c52765dad95d

**Comment by Alloc86** [comment]
Yay, great :)
Any more precise statement on when "at some point soon" might be? ;)

**Comment by rlabrecque** [comment]
I won't be home for at least a week, so not until at least then.

**Comment by Alloc86** [comment]
Thank you, that's something to work with :)
