### ISSUE TITLE
Steamworks will not disconnect

### ISSUE THREAD

**Issue by Hanseshadow** [rlabrecque/Steamworks.NET#140]
I saw there was a previous issue about this, but it is not open.

Steamworks does not signal steam that the player has stopped playing.  Shutdown is being called fine.

I've tried switching it to OnDisable() and OnApplicationQuit(), without success.  I made a button to manually shut down and I fixed all the associated errors with that change, but no change.   SteamAPI.Shutdown() is being called, but once out of the game Steam still thinks I'm in it.

Steam won't shut down, if you attempt to shut down, so you have to end-task it.

I'm using Unity 5.5.0f3...

**Comment by rlabrecque** [comment]
Check out this thread: https://github.com/rlabrecque/Steamworks.NET/issues/13
