### ISSUE TITLE
Cloud Build fails due to NullRefException in RedistInstall

### ISSUE THREAD

**Issue by eintopf** [rlabrecque/Steamworks.NET#141]
Hi,

we are currently trying to get Unity Cloud Build running with Linux (other platforms including OSX and Windows are building fine). However: Our build fails because of this error:
```
269: [Unity] System.NullReferenceException: Object reference not set to an instance of an object
270: [Unity]   at RedistInstall.SetPlatformSettings () [0x00015] in /BUILD_PATH/.../Assets/Editor/Steamworks.NET/RedistInstall.cs:73 
271: [Unity]   at RedistInstall..cctor () [0x00011] in /BUILD_PATH/.../Assets/Editor/Steamworks.NET/RedistInstall.cs:25 
```
An update to newest version (this repo, not unitypackage) would fix this, but it doesn't.

Line 73 is `if(Path.IsPathRooted(plugin.assetPath)) {` - so the only thing that can be null here is "plugin". Why would `PluginImporter.GetAllImporters()` return a plugin that points to null? Any ideas?

Best regards,
Bennet

**Comment by rlabrecque** [comment]
Hey @eintopf, I tried this for myself with this project and I couldn't repro this, https://github.com/rlabrecque/UnityCloudTest, think you could fork and try that out as well?

I'm wondering if something in your project is gunking up the [pretty bad] plugin system.

There's a chance that it could also be that plugin.assetPath is null, which would also be weird, but I want to make sure I'm specifically filtering out one or the other.

**Comment by eintopf** [comment]
It just stopped happening without a visible reason. Hope it was just some hickup in Cloud Build.

**Comment by rlabrecque** [comment]
Thanks for the heads up, just reopen this if ever it happens again and see if you can log whether it's plugin or plugin.assetPath that is null.

**Comment by eintopf** [comment]
And it happens again - but now also for Windows. I'll add Debug Statements now to find out what excatly is null.

**Comment by eintopf** [comment]
So it is the actual plugin which is null, not the assetPath. I'll add a null check for the moment + a debug which plugins are NOT null (to be sure that all required plugins are processed).

**Comment by rlabrecque** [comment]
Kk, thanks,

Let me know if this fixes it then!

\> *unity*

**Comment by eintopf** [comment]
Build runs now. Still would be cool to find the cause of this issue :/

**Comment by rlabrecque** [comment]
Unity's plugin system is roughly on par with it's input system. It works, usually, but not well unfortunately. :(

Honestly the bigger issue for me personally is that I had to write that code at all. That loop just exists to fix Unity's plugin system in the first place. But ahh well, it should be good enough now!

**Comment by eintopf** [comment]
Ok, what a mess :( However: Big thanks for your efforts! Keep up the great work!
