### ISSUE TITLE
Unity: Steam Overlay over visual studio

### ISSUE THREAD

**Issue by xDura** [rlabrecque/Steamworks.NET#143]
To reproduce this: Open unity project, play (one time). Then open any visual studio file from the project.
press shift tab in visual studio. The steam overlay is mixed with visual studio UI.

Also when you stop Unity's playMode steam doesn't get that the game has stopped running (I guess because it is atatched to the UnityEditor executable.

Any one experiencing this? Any workaround?
Thanks

**Comment by rlabrecque** [comment]
Yeah, there's not really any direct fix for this. If you open VS before playing in the editor does that resolve it?

This is steams doing and not much that we can do about it. After a game is launched from steam, or initialized the SteamAPI the overlay injects itself into any new rendering windows that the process creates.

Now, I haven't actually had it happen to me for quite a while, but I'm not exactly sure why, maybe hardware acceleration? Mine has automatically been set to software mode for some reason.
http://www.meadow.se/wordpress/visual-studio-slow-try-disabling-hardware-acceleration/

**Comment by xDura** [comment]
Hi!
I tested opening VS before playing and it seems that overlay doesn't appear. 
Not really sure if this fixes it in all cases because it didn't happen every time.

If it keeps happening I will try disablin the hardware acceleration and post the result here.

Thanks, the wrapper is just amazing.
