### ISSUE TITLE
Getting the profile avatar

### ISSUE THREAD

**Issue by Crumbler** [rlabrecque/Steamworks.NET#144]
I want to display the user's steam avatar. I want to use SteamFriends.GetLargeFriendAvatar, but it returns an integer value. I noticed there was a method in SteamUtils called GetImageRGBA, but I have no idea how to convert rgba to system.drawing.image.

**Comment by rlabrecque** [comment]
Indeed GetImageRGBA returns the raw bytes for a steam image handle. I'm not immediately familiar with how System.Drawing.Image works but there might be a way create one from the raw RGBA bytes or use the byte array as the backing memory for it.
