### ISSUE TITLE
About Multiplayer Game.

### ISSUE THREAD

**Issue by newaxekub** [rlabrecque/Steamworks.NET#145]
Hi!. I want to know about multiplayer game, I want to connect to SteamServer or P2P , Do you have a example or advice for me.
Thank you very mush.

**Comment by rlabrecque** [comment]
@newaxekub Have you checked out this project? It's the only part of SteamGameServer that I really have. Most people use P2P unless they have a good reason to use dedicated servers though.
https://github.com/rlabrecque/Steamworks.NET-GameServerTest

**Comment by newaxekub** [comment]
Hi @rlabrecque  Thank you for your advice, Now I can use P2P in my game, I very fast I like it. :)
