### ISSUE TITLE
SteamFriends cannot be used on a GameServer?

### ISSUE THREAD

**Issue by NeistH2o** [rlabrecque/Steamworks.NET#146]
Hello and sorry if this is a stupid question but I'm trying to get the informations of the players joining my server, like their user name, from their CSteamID.

It seems that everybody uses SteamFriends to request and receive those infos, by calling SteamFriends.RequestUserInformation() for example.
But when I try to use SteamFriends on the server side (where GameServer is initialized and not SteamAPI if I'm not wrong) I always get the exception "InvalidOperationException: Steamworks is not initialized.".

I hope that makes sense...
I have spent days looking for a way to do that and I assume there must be a way to get those informations on the server side but I can't figure out how, maybe I m totally dumb, but it sounds weird to me that a game server can be limited over the infos Steam could provide to any client. Any help on this would be more than welcome.

And great job on this project btw! :)

**Comment by NeistH2o** [comment]
Okay, I continued my research, and I suppose that it is simply not possible on a server and that the server must only be used as a relay between the clients to share the steamIDs of the connected players.
If I'm wrong about that please tell me even if I close this issue. :)

**Comment by rlabrecque** [comment]
Yeah, that seems right. The name is pretty minor and the server shouldn't really need it other than possibly logging. You can use the WebAPI if you think you have a valid reason to have the player names on the server though!

**Comment by NeistH2o** [comment]
Actually I wanted the server to be able to find a player according to its nickname, like when an admin enters a command that targets a specific player, like "give item X to rlabrecque". The server receives the nickname and find the client thanks to it. The only thing that bothered me is, according to the fact that the clients cannot be trusted, I don't felt confortable letting the clients send their nickname to the server. But, after all, the SteamID is still sent by the clients to the server, just like the nickname would, so I suppose my first idea of having the server finding the client nickname with its steamID is just.. no sense x)
But thanks, I thought the web API and the SDK were just the same thing, so I left the web API stuff behind in my search.

**Comment by rlabrecque** [comment]
How I would do that is, the client has the list of the other clients, including their name and SteamID, you can have your like /giveitem X rlabrecque command. Do some basic sanity checking, then do an RPC call to the server with the SteamID instead of the name.

Then do user authentication on the server, ensure that the user that called that should be able to, ensure that the SteamID is in the game and can receive the item etc, then update all the clients with the new info.

But yeah the WebAPI has some additional stuff that you can use with GameServers that isn't exposed in the C++ API yet for some reason.

**Comment by NeistH2o** [comment]
I would be happy to discuss a moment with you in a more private way if you wanted to and if you have the time for it, but I never used gitHub before and I believe it doesn't have a private chat or messaging system ^^ Just let me know if you want to! I sent you an invite on LinkedIn.
(I will delete this comment in a few hours anyway)

**Comment by rlabrecque** [comment]
Don't really have time for that unfortunately :(

If you'll be at GDC next week you should come and find me though!

**Comment by NeistH2o** [comment]
I would be happy to be there but I live in France atm so I will not be able to do that ^^ Only wanted to ask you if you were working on another project than this one, because this project is open source so I suppose that you don't earn enough to live thanks to it. I saw that you were consulting for other companies on LinkedIn, so I'm curious about what you do, what you want and some stuff like that. Actually, I have a game sold on steam that could be a blast if I had more than two hands and I desperately need to find people to work with me if I don't want to spend my entire life working night and day on it to hardly keeping it working as it is a very ambitious project for just one person.
I m not asking you to join me, but as you seem to be kinda involved in the game industry, maybe you could help me. My game is Hide & Hold Out - H2o and you can contact me at alexis.jouanneaux@gmail.com if you change your mind. (and sorry for insisting ^^)

**Comment by rlabrecque** [comment]
Ah cool! But yes, I do contract with companies, my plate is full right now though sorry! Good luck with your game!

**Comment by NeistH2o** [comment]
OKay thanks for your time :) I m gonna delete my posts about this ;)
