### ISSUE TITLE
Join Friend Lobby

### ISSUE THREAD

**Issue by newaxekub** [rlabrecque/Steamworks.NET#147]
Hi @rlabrecque , I want to know how to get friend's lobby id or how to join friend's lobby. Now I use P2P to send their lobby id to caller, Do you have simple way to join friend's lobby.
Thank you very much. :)

**Comment by rlabrecque** [comment]
Hey @newaxekub this is probably a better question for the Steamworks discussion board, you'd get a better answer quicker there from someone like cyanic.

There's SteamMatchmaking.InviteUserToLobby() and SteamFriends.SetRichPresence() which should help you with that!

**Comment by newaxekub** [comment]
@rlabrecque  I use SteamFriends.SetRichPresence() it work , Thank you :)
