### ISSUE TITLE
Leaderboard is overwriting higher score when told not to.

### ISSUE THREAD

**Issue by Lewis-W** [rlabrecque/Steamworks.NET#148]
Hello! I'm pretty sure this is an issue specific to Steamworks.NET as other people seem to have success doing this, but I'm calling SteamUserStats.UploadLeaderboardScore and passing in "ELeaderboardUploadScoreMethod.k_ELeaderboardUploadScoreMethodKeepBest" yet it always overwrites higher scores with lower ones. Is there anything I can do to get this working as intended without having to implement a custom solution?

Thanks!

**Comment by rlabrecque** [comment]
Hmm, this shouldn't be a Steamworks.NET specific issue as that should just pass right though to Steam. Are you sure that your leaderboards are set up where a higher score is better? And are those changes published?

**Comment by Lewis-W** [comment]
Hey man, I did a bunch of testing and it turned out that the leaderboards were acting erratic no matter what, it wouldn't even push scores that WERE higher (No idea why but it's definitely on valve's side). I think you're right that it isn't a Steamworks.NET issue, sorry for wasting your time!

**Comment by rlabrecque** [comment]
Sounds like your ELeaderboardSortMethod is backwards!
