### ISSUE TITLE
Failed to call SteamGameServerStats.SetUserStat

### ISSUE THREAD

**Issue by woodsshin** [rlabrecque/Steamworks.NET#153]
SteamGameServerStats.GetUserStat is fine. I tested it with Client/GS/Official GS options. Is there any way to get errorcode?

**Comment by rlabrecque** [comment]
Failed in what way, just returning false?

If that's the case then that's just the value returned by steam, you'll probably get better answers from the Steamworks Developer forum.

**Comment by woodsshin** [comment]
Yeah. I opened thread on forum.
http://steamcommunity.com/groups/steamworks/discussions/6/135511027318128287/

**Comment by woodsshin** [comment]
It's my bad. SteamGameServerStats.SetUserStat is available when the steamid is online. I tried to update stat when player disconnected from server. It's working.

"Game servers can only set stats and achievements for users currently playing on the server."
https://partner.steamgames.com/documentation/ugs

**Comment by rlabrecque** [comment]
Nice!
