### ISSUE TITLE
SteamGameServer causing crash

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#154]
Hi,

got a new issue with updating to 9.0: Everytime we start a second game within the lifetime of our program (or the lifetime of Unity) the API stuff crashes in SteamGameServer code.
Basically what we do for each game is:
```
GameServer.Init
SteamGameServer.InitGameServer
SteamGameServer.LogOnAnonymous
...
// Run game
// On stoppping the game:
SteamGameServer.LogOff
GameServer.Shutdown
```

This has been working just fine prior to today's 9.0 update, now the second time we get to SteamGameServer.InitGameServer (I think that's what translates to ISteamGameServer_InitGameServer?) we get an access violation.

Is this something with Steamworks.NET? Or Steam itself? Do you know anything about it or how to fix/work around it?

Regards,
Chris

**Comment by Alloc86** [comment]
PS: I think this could be the issue: http://steamcommunity.com/groups/steamworks/discussions/0/360670708783560757/
Is there any way we cann do the call they mention as workaround with Steamworks.NET?

**Comment by rlabrecque** [comment]
Hey @Alloc86 so, this is a SteamAPI problem with the headers in 1.39 currently, I've looked into it and submitted a recommended fix to Valve, hopefully it lands and gets pushed out in the next week or two.

I can pass you along the patch if you want to compile CSteamworks with 1.39 yourself in the meantime

**Comment by Alloc86** [comment]
Confused now ;)
Are you saying the bug is in Steam's API or CSteamworks? Or would that CSteamworks patch only be a workaround til Valve fixes the Steam API?
As Valve typically take their time to fix anything, especially if it's serious (remember their Linux 64 bit issues with Unity? :( ) and I doubt we're the only ones using the gameserver interface, couldn't you build the lib with the patch? I'd assume it's way easier for you as you certainly got the tools and all set up anyway :)

**Comment by rlabrecque** [comment]
Yep, working on a patch right now!

**Comment by Alloc86** [comment]
Cool, thanks a lot!

**Comment by rlabrecque** [comment]
Done! 9ce3da5b991907e898907188a1ceaae9126438d4

Let me know if everything works out, it should!

**Comment by Alloc86** [comment]
Only did a quick test so far but this seems to have resolved it. Can't thank you enough :)

**Comment by rlabrecque** [comment]
Awesome!
