### ISSUE TITLE
Future Proof Engine Define -

### ISSUE THREAD

**Issue by byteasc** [rlabrecque/Steamworks.NET#158]
It would be prudent to move to using UNITY_5_3_OR_NEWER for the engine version checks going forward.

Looks like only 2 places that use these defines (CallbackDispatcher.cs and Packsize.cs)

**Comment by byteasc** [comment]
Nevermind, looks like it was added for 2017 strictly, but that works!

**Comment by rlabrecque** [comment]
Yeah, hopefully a lot of that stuff goes away as Unity improves native plugin support. There are definitely a couple places with 2017 that could use 5_3_OR_NEWER instead but I'll do that when 2018 rolls around ;)
