### ISSUE TITLE
PROBLEM with Unity: DllNotFoundExperience: csteamworks

### ISSUE THREAD

**Issue by kitftm** [rlabrecque/Steamworks.NET#159]
**Good morning everyone. First of all I want to clarify that I do not speak and I do not write in English, I use a translator right now.
 I tell you my situation. I want to make a skin for rust and I could do it and finish it, when trying to load the skin to the workshop I get this error:**

DllNotFoundException: CSteamworks
Steamworks.SteamAPI.Init () (at Assets/Plugins/Steamworks/Steamworks.NET/Steam.cs:58)
WorkshopBaseEditor.OnInspectorGUI () (at Assets/Scripts/Editor/WorkshopBaseEditor.cs:87)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1229)
UnityEditor.DockArea:OnGUI()

**How can I fix it? I was translating and reading many posts with similar errors on different websites and I can not find a way to solve it. Thanks first of all and I hope it's easy to fix it**

**Comment by kitftm** [comment]
is unity version 5.6.0

**Comment by rlabrecque** [comment]
Hey kitftm, I'm not sure how much I can help, how are you trying to upload it? I thought Facepunch switched to their own Steamworks stuff for Rust. But anyway, that means that CSteamworks.dll OR steam_api.dll are in the wrong place.

Do you get that error in the Unity editor, or running a .exe? Do you know if it's 64bit?

**Comment by kitftm** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/28095634/25502886/bbd401b4-2b6e-11e7-8309-8b51fa1995d0.png)
How are you? Thank you for taking the time. I'm trying to upload it from Unity. (Touching "Check the problems" "Charge and upload" is the subject project, it is called "goal"). And where do I place those .dlls correctly? I get the error in Unity, every time I try to upload it to the workshop. Yes, it is 64 bits, which is 64bits influences?

**Comment by rlabrecque** [comment]
Make sure CSteamworks.dll AND steam_api64.dll from here:
https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/x86_64/CSteamworks.dll?raw=true
https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/x86_64/steam_api64.dll?raw=true
Are in: Assets/Plugins/Steamworks.NET/x86_64

**Comment by kitftm** [comment]
**I hit them in that place, the strange thing is that it worked, the negative thing is that another error appears right now:**

EntryPointNotFoundException: InitSafe
Steamworks.SteamAPI.Init () (at Assets/Plugins/Steamworks/Steamworks.NET/Steam.cs:58)

**Comment by kitftm** [comment]
Need helpppppp friends (?

**Comment by martinkelly188** [comment]
I have the same problem, it is so frustrating. Did you ever find a fix?

**Comment by rlabrecque** [comment]
Are you both using Rust? They need to update their stuff.
