### ISSUE TITLE
Steam_appid error

### ISSUE THREAD

**Issue by MrQuaid** [rlabrecque/Steamworks.NET#160]
I get the below error. I tried manually adding into root folder but still get the error. I am using Unity 5.6.0f3 fresh install. On my previous game I had no issues, but also the folders all look different, perhaps since it was months ago.

[Steamworks.NET] Could not copy steam_appid.txt into the project root. steam_appid.txt could not be found in 'E:\Unity Games\My_Project\Assets/Plugins/Steamworks.NET/redist'. Place steam_appid.txt from the Steamworks SDK in the project root manually.
UnityEngine.Debug:LogWarning(Object)
RedistInstall:CopyFile(String, String, Boolean) (at Assets/Steamworks.NET-master/Editor/Steamworks.NET/RedistInstall.cs:40)
RedistInstall:.cctor() (at Assets/Steamworks.NET-master/Editor/Steamworks.NET/RedistInstall.cs:16)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

**Comment by rlabrecque** [comment]
Steamworks .NET expects a rigid folder structure, does
`E:\Unity Games\My_Project\Assets/Plugins/Steamworks.NET/redist` not exist?

**Comment by gityetao** [comment]
I get the same error, Unity version 5.5.1f1
