### ISSUE TITLE
InviteUserToGame stopped working

### ISSUE THREAD

**Issue by ivan-perfectparallel** [rlabrecque/Steamworks.NET#161]
Currently when you are trying to invite a friend to the game, he will not get the invite.
It seems like steam does not passes the invite to a friend.

To replicate that, simply start SteamFriendsTest from https://github.com/rlabrecque/Steamworks.NET-Test and click InviteUserToGame (I changed the ID to my friend ID in the code).

This stopped working recently, maybe yesterday, perhaps Steam changed some inner code.

**Comment by rlabrecque** [comment]
Hrm I haven't heard of this yet, Can you post this on the [Steamworks Discussion Board](http://steamcommunity.com/groups/steamworks/discussions/)?

**Comment by dylanh724** [comment]
@rlabrecque it's true -- @ivan-perfectparallel I've also reproduced this and posted on the SW discussion board. 

![image](https://cloud.githubusercontent.com/assets/8840024/26065592/0dfdcc98-39c7-11e7-85af-6e0ee929b7bc.png)

**Comment by ivan-perfectparallel** [comment]
Fixed by Valve.
