### ISSUE TITLE
SOLVED: Steam HUD not showing in OSX build (Unity) even when running trough Steam

### ISSUE THREAD

**Issue by juhojantunen** [rlabrecque/Steamworks.NET#162]
Hi!

Any ideas on why I cannot get Steam HUD to show in my OSX build? It shows correctly on the Windows built made with same assets and same Unity version. The strange thing is that it used to show correctly but somehow stopped working at some point. I'm trying with Unity 5.6.1 and 5.6.0p3 but same issue with both at the moment.

Trying to figure it out at the moment but any help is appreciated!

Best,
Juho

**Comment by juhojantunen** [comment]
Sorry about that, I had 64bit build settings on. That took a while to figure out :)

**Comment by BernsteinA** [comment]
@juhojantunen what was the fix??
