### ISSUE TITLE
can't get SteamUserStats.SetStat work for float data

### ISSUE THREAD

**Issue by amidofu** [rlabrecque/Steamworks.NET#164]
As title, SteamUserStats.SetStat work for float data **always return false**, but I can get SteamUserStats.SetStat for int data work.

I have the exactly same settings except the data type for my int data and float data on my steamworks settings, not sure if the settings will matter.

Thank you.

**Comment by rlabrecque** [comment]
If you open the steam console with steam://open/console and try to call SetStat with your float does it say anything in there?

And also check the Steam/logs folder to see if there's anything in there that is relevant.

**Comment by amidofu** [comment]
Hi rlabrecque ,

It turns out that we didn't publish the stat correctly on the stat settings web page. After publish the stat settings again it works fine.
Thanks for your help!
