### ISSUE TITLE
Steam Integration on Unity's roadmap?

### ISSUE THREAD

**Issue by Cosmas47** [rlabrecque/Steamworks.NET#165]
I saw this post early yesterday. Does anyone know if there's any validity that Unity will natively support Steam integration?

https://forum.unity3d.com/threads/timeline-for-integration-with-steam-networking-matchmaking.397042/

**Comment by rlabrecque** [comment]
First that I'm hearing about this, exciting! UNET+Steamworks.NET has always been pretty clumsy.

**Comment by Cosmas47** [comment]
Yea, very interesting. The Unity mod specifically states:

> Ok hack wees is almost over... I cannot promise for sure, but steam support has one of the top priority right now with nat punching solution. Hence, the most priority task is stabilizing library. I m personally not satisfyed with stability and performance... When? Good, again cannot promise here, 5.5 or 5.6 i guess. 5.5 optimistic, 5.6 realistic dates (for steam) 
> 
> Sorry if i disappoint you

Well if that's the case, then its just around the corner. This plus SteamDirect are going to be pretty monumental this year.

**Comment by rlabrecque** [comment]
Indeed, that was over a year ago though, so we'll see!

**Comment by rlabrecque** [comment]
I reached out to them, so I'm going to go ahead and close this since it's not super duper relevant to Steamworks .NET specifically.
