### ISSUE TITLE
Save data on Steam?

### ISSUE THREAD

**Issue by newaxekub** [rlabrecque/Steamworks.NET#167]
Hi @rlabrecque , Do you have any way to save data on Steam?
I want to save my data like Database on Steam. I want all players to get the same information from Steam and can save it. ( I don't know if Steam has a database )

**Comment by rlabrecque** [comment]
It depends on what you're trying to do but not generally no.

The stats system can act as pretty bad database, the inventory service services as a good database for items. Depending on what you're doing, if your database is read only and doesn't need to be very secure then just including it with the game and then just push updates to it would be fine.

**Comment by newaxekub** [comment]
Thank you @rlabrecque, I want to create a guild database to store guild information such as guild level, guild name, guild rating, guild member, and details. I want all players to get the same information, Now I'm trying the inventory service. I hope it helps.
