### ISSUE TITLE
GetCurrentGameLanguage()

### ISSUE THREAD

**Issue by mauricepape** [rlabrecque/Steamworks.NET#17]
Hi,

sorry if that's not the right section for such questions.

I'm currently trying to get the GetCurrentGameLanguage()-thing working. Basically, my app has other languages, which I have stored inside my app via Daikon Forge's LanguageManager (http://www.daikonforge.com/forums/threads/localization-support.418/#post-2680).

If a SteamUser has, for example, choosen German as his/her language on my app (MyAPP > Settings > Language), the app will check on startup, which language was set by the user and will then load the desired language .

My Script looks like this:

``` c#
using UnityEngine;
using System.Collections;
using Steamworks;

public class SteamLocalization : MonoBehaviour {

    //Steam Localization
    void Start() {
        if (SteamManager.Initialized) {
            if (SteamApps.GetCurrentGameLanguage() == "english") {
                Debug.Log("eng");
                SetLangEN();
            }

            if (SteamApps.GetCurrentGameLanguage() == "german") {
                Debug.Log("ger");
                SetLangDE();
            }

            if (SteamApps.GetCurrentGameLanguage() == "spanish") {
                Debug.Log("esp");
                SetLangES();
            }
        }
    }

    //AVAILABLE LANGUAGES
    void SetLangEN() {
        GetComponent<dfLanguageManager>().LoadLanguage(dfLanguageCode.EN);  
    }

    void SetLangDE() {
        GetComponent<dfLanguageManager>().LoadLanguage(dfLanguageCode.DE);  
    }

    void SetLangES() {
        GetComponent<dfLanguageManager>().LoadLanguage(dfLanguageCode.ES);  
    }

    void OnGUI() {
        GUILayout.Label("SteamApps.GetAvailableGameLanguages() = " + SteamApps.GetAvailableGameLanguages());
        GUILayout.Label("SteamApps.GetCurrentGameLanguage() = " + SteamApps.GetCurrentGameLanguage());
    }
}
```

But it doesn't seem to be right?! I honestly don't know if "if (SteamApps.GetCurrentGameLanguage() == "english")" is even written right... I'm not really that good in programming. Atleast my console prints out the "eng"-debug log. That seems to work.

Could someone enlighten me?

Regards,
Maurice

**Comment by MrCharli3** [comment]
@mauricepape How did you fix this? For me SteamApps.GetCurrentGameLanguage() returns nothing. Trying from Unity Editor.
