### ISSUE TITLE
Operator `==' cannot be applied to operands of type `Steamworks.CSteamID' 

### ISSUE THREAD

**Issue by SelectPluginDB** [rlabrecque/Steamworks.NET#170]
This cannot be converted either. How to solve this?

**Comment by LudereDev** [comment]
What kind of data are you trying to compare it to?

CSteamID is a very finicky data type. It cannot be converted from (as far as I know). But, you can convert to other data types. 

Here's how this would work:

- Checking Against String C#
for(int i = 0; i < SteamMatchmaking.GetNumLobbyMembers(m_lobby); i++) {
   if(SteamUser.GetSteamID().ToString() == "123456789") {
      // Do stuff
   }
}

And, as you know, strings can be converted to ints, floats, etc.

Good luck,
Ludere

**Comment by rlabrecque** [comment]
What are you trying to compare it against?

I could get this working just fine:
```
        if(new CSteamID() == new CSteamID()) { }
```

CSteamID is just a wrapper around a ulong, which you can get by accessing `CSteamID::m_SteamID` directly or casting it to a ulong like `(ulong)(new CSteamID())`.
