### ISSUE TITLE
Unity crashes when trying to use Steam Microphone functions from SteamUser

### ISSUE THREAD

**Issue by DarkWindowStudios** [rlabrecque/Steamworks.NET#174]
It appears that when using the latest version of Steamworks (10.0.0), Unity crashes when trying to run the test for the Steam Microphone. 

Windows 10 64-bit
Intel i5-4460k Quad Core
8GB RAM
Unity 5.6.0f3

**Comment by rlabrecque** [comment]
Thanks for the heads up! The voice functions had some changes and I took out the deprecated arguments but I might have messed that up!

**Comment by DarkWindowStudios** [comment]
You're welcome. Literally updated Steamworks.NET and then started working on voice :/ How soon can we expect a fix? We can always revert back to 9.0.0...

**Comment by rlabrecque** [comment]
Tomorrow!

**Comment by rlabrecque** [comment]
79ed7fad4b2958919175fd8bde9685c5da380f76 👍 

Let me know how it works out for you, I only tested it quickly, so reopen this if it doesn't quite fix it!

**Comment by DarkWindowStudios** [comment]
Thanks Riley! Upon initial testing in the Steamworks.NET-Testing, I'm not hearing anything over the loopback but I'm sure I've screwed up on my end this time lol. Thanks for the speedy fix!

**Comment by rlabrecque** [comment]
The implementation in Steamworks.NET-Test is pretty terrible, mostly just exists to make sure it doesn't crash.
