### ISSUE TITLE
Calls to InitTxn return status OK but overlay does not show

### ISSUE THREAD

**Issue by alex-sherman** [rlabrecque/Steamworks.NET#176]
I've been debugging an issue with Steam micro transactions which is similar to this issue on the discussion groups:

http://steamcommunity.com/groups/steamworks/discussions/4/215439774870797831/

I had been in contact with Valve support and they suggested I contact the developers of the wrapper before blaming the issue on Steam, so here goes.

I have been able to call InitTxn with our appid, key and my Steam user id with the game open and running through Steam. The result of InitTxn is as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE response>
<response>
        <result>OK</result>
        <params>
                <orderid>12935678944090872286</orderid>
                <transid>1273805343290106552</transid>
        </params>
</response>
```

However, the in game overlay never prompts the user to authorize the transaction. I'm sure the transactions are going through as calling QueryTxn with the same orderid returns the following:

```json
{
    "response": {
        "result": "OK",
        "params": {
            "orderid": "12935678944090872286",
            "transid": "1273805343290106552",
            "steamid": "76561198396978675",
            "status": "Init",
            "currency": "USD",
            "time": "2017-06-22T15:39:35Z",
            "country": "US",
            "usstate": "",
            "timecreated": "2017-06-22T15:39:35Z",
            "items": [
                {
                    "itemid": 253,
                    "qty": 500,
                    "amount": 1999,
                    "vat": 0,
                    "itemstatus": "Init"
                }
            ]
        }
    }
}
```

The solution that the Steam discussion board has is to release the game in a closed beta, and test from that release which is not possible as my company won't let us release the game in any capacity at this stage in the development. If anyone here has experience the same problem and has a solution that would be very helpful, otherwise my hunch is there is something else happening on Steam's side of things and I may follow up with Valve support more.

**Comment by NKnusperer** [comment]
Yes, as far as I know the only way to test Steamworks integration is to actually have released something (so you have an valid AppId). However this application does not need to be your real game, just upload a dummy application so Steam is happy and you have an AppId. Then you can just launch your game in a development environment on your local PC and initialize Steamworks with this AppId and everything should work. This is how I tested my Steamworks integration.

**Comment by alex-sherman** [comment]
Yeah so I'm not sure exactly how it works but we do have a valid AppId, but have not pushed out a build yet. My assumption was that, with a valid AppId which we have, something is going wrong with Steam recognizing our game client as the thing it should send purchase authorization requests to since it wasn't installed through Steam.

Can I just verify that it's possible, with only a valid AppId and not having the game installed directly through Steam, to receive these purchase authorization requests? Or are you saying that the game must be released in some form in order to receive the requests?

**Comment by NKnusperer** [comment]
> Or are you saying that the game must be released in some form in order to receive the requests?

Yes...I could be wrong but as far as I know this is true.
So the workflow for you to be able to test should be:
1. Release your game as closed beta (and upload a dummy binary if you are forced to do so)
2. Generate a [Dev Comp key](https://partner.steamgames.com/doc/features/keys) and activate it on your Steam account so the game is in your library
3. You should now be able to do in-game transactions from within your local developer build of the game

**Comment by alex-sherman** [comment]
Thanks so much for the help so far, and sorry for being so pedantic, I don't quite understand the Steam release system yet.

To clarify just a bit further, the game does show up in my library but we haven't released any kind of builds for it. Do you think releasing a build is a requirement for getting the transactions working? Or is the fact that it shows up in my library, and gets marked as "Running" when I launch the game, is that sufficient for Steam to recognize it for the purchase authorization popup?

Thanks so much again.

**Comment by NKnusperer** [comment]
> Or is the fact that it shows up in my library, and gets marked as "Running" when I launch the game, is that sufficient for Steam to recognize it for the purchase authorization popup?

I would say so and the fact that you are able to successfully call InitTxn confirms this.
Are you sure that you are frequently calling [SteamAPI.RunCallbacks](https://steamworks.github.io/steammanager/#steamapiruncallbacks) ?
If you are using some kind of custom game-engine also make sure that you that this is called by the render thread, otherwise no overlay will be displayed.

**Comment by alex-sherman** [comment]
Yeah this is all in Unity, and we're using the SteamManager script. I did verify the RunCallbacks is getting hit be setting a break point on it. Are there any gotcha's for the Unity case you know of?

**Comment by NKnusperer** [comment]
I haven't used it in Unity, only our own engine.
Is the default Steam overlay (Shift+Tab) working?

**Comment by alex-sherman** [comment]
Yeah overlay definitely works.

**Comment by NKnusperer** [comment]
Really strange, now I'am running out of ideas too.
Anyway, if you ever solve this issue it would be interesting to know the cause/solution of the problem.
Good luck :thumbsup:

**Comment by rlabrecque** [comment]
Hey guys, sorry this took so long for me to get to.

I do have some ideas how you could get this to work. The first thing I would try is to install your game on steam. It might work out of the box, or you might need to upload a dummy file (even just an empty text file) to the Steam depot. Then build your game into your steamapps/common/<yourgame> folder. And then run it from the Steam Library as if you uploaded it to Steam. You will have to set the launch options for your appid/platform and publish those changes too.

If that doesn't work then maybe using the Steam local content servers would help.

**Comment by Suvitruf** [comment]
Confirmed.

When you start game in Unity (even if you can see in Steam that app is running) you will not see overlay. 

So, yes, the only way I made it works: upload your build to Steam. And after that install it in Steam and run, there we go. Kinda slow, yeh, but at least you can test this functionality.

**Comment by alex-sherman** [comment]
Thanks for all the responses, at the very least I know it's not something with me specific use so that's good enough for me.

**Comment by HomoInanis** [comment]
The Steam documentation is really good, but there are some points that don't link quite right.

When you need to perform an asynchronous operation that has to communicate with the Steam API INTERNALLY use Steam's "CallResult".
However, when you need to perform an operation that requires the connection with an external element (such as the overlay to authorize a transaction) you have to use the "Callback".

Here you can see how both work: https://steamworks.github.io/gettingstarted/

**Comment by Raysangar** [comment]
Hello! I'm facing this issue too, but even after uploading a build to steam the overlay won't show after calling InitTxn. The overlay appears if I press SHIFT+Tab, any idea why this could happen?

**Comment by monsieurpooh** [comment]
Same issue here; game is already active but overlay won't show even after a successful initTxn.
