### ISSUE TITLE
Unity 2017 64 bit Callback error

### ISSUE THREAD

**Issue by gamesthemonkey** [rlabrecque/Steamworks.NET#177]
This is a very specific error, when building a 64 bit Windows game using steamworks callbacks for Lobby stuffs in Unity2017 the built version of the game will return wrong callbacks/callreturns.

A makeshift fix is to comment out lines 9-28 of CallbackDispatcher.cs then add a new line
#define THISCALL

I am sure the professionals can think of some way to work this into the actual system, I can not.

If you wish to build 32bit Windows again you will need to uncomment lines 9-28 again and remove #define THISCALL

**Comment by rlabrecque** [comment]
Hey @gamesthemonkey, Unity 2017 (and Unity beta support in general) is only supported with the latest Github master version, not a unitypackage release yet.

The changes for VS2017 are here:
https://github.com/rlabrecque/Steamworks.NET/commit/fa0510c7536ff5bbce93a9ba313dd03d10921c24
