### ISSUE TITLE
Leaderboard UploadLeaderboardScore not updating

### ISSUE THREAD

**Issue by flashmandv** [rlabrecque/Steamworks.NET#178]
I integrated leaderboards into my game, but SteamUserStats.UploadLeaderboardScore method does not update existing scores, although I pass k_ELeaderboardUploadScoreMethodForceUpdate.
Here is my full code:

```
m_callResultUploadScore = CallResult<LeaderboardScoreUploaded_t>.Create(OnScoreUploadResult);
leaderboardHandler = CallResult<LeaderboardFindResult_t>.Create(onLeaderBoard);

void onLeaderBoard(LeaderboardFindResult_t data, bool failure) {
        if (data.m_bLeaderboardFound == 0) {
            Debug.Log("Leaderboard not found");
            return;
        }
        var leaderBoard = data.m_hSteamLeaderboard;
        var res = SteamUserStats.UploadLeaderboardScore(leaderBoard, ELeaderboardUploadScoreMethod.k_ELeaderboardUploadScoreMethodForceUpdate, model.selfPlayerInfo.eloPoints, null, 0);
        m_callResultUploadScore.Set(res);
    }

    void OnScoreUploadResult(LeaderboardScoreUploaded_t pCallback, bool failure) {
        if (pCallback.m_bSuccess != 1 || failure)
            Debug.Log("There was an error uploading the LeaderboardScoreUploaded_t.");
        else
            Debug.Log("Score uploaded and m_nScore is : " + pCallback.m_nScore);
    }
```

OnScoreUploadResult is not always called. onLeaderBoard is always called and returns the correct Leaderboard, but UploadLeaderboardScore is simply not working.
If OnScoreUploadResult gets called, failure is false, and the callback m_bSuccess is 0.
m_nScore value is correct, but it does not get set.
![image](https://user-images.githubusercontent.com/2466808/27694271-52c220ae-5cf4-11e7-9780-6ec9ba6807e9.png)
My leaderboard is NOT trusted. The first call worked and the score was set ok..but then the updates failed all the time. 
Please help. **This is showstopper**

**Comment by flashmandv** [comment]
UPDATE: I think it was Valve server problem. After clearing the leaderboards also new record writing was not working. A day later it all worked OK. 
But despite servers, OnScoreUploadResult callback wasn't called even if it failed. In many cases it wasn't called at all. This should be fixed in the Unity API

**Comment by rlabrecque** [comment]
Hey @flashmandv, I'm glad you got it solved, this isn't something that I can do anything about unfortunately, either Steam sends a callback/callresult or it doesn't. This is definitely a problem on Valves end :(

**Comment by amigax** [comment]
did this work? my scores still update!

**Comment by v-star0719** [comment]
I'm having the same issue today and I'm going to try again in a day.

**Comment by LunaNiermann** [comment]
For everyone still figuring this out, Valve only allows 10 requests within 10 minutes. This is quickly consumed during testing. There does not seem to be a clear error. Just give it some time.  
https://partner.steamgames.com/doc/api/ISteamUserStats#UploadLeaderboardScore
