### ISSUE TITLE
Problem with UNITY: EntryPointNotFoundException: InitSafe

### ISSUE THREAD

**Issue by martinkelly188** [rlabrecque/Steamworks.NET#179]
Keep getting this error while trying to export a skin to the Steam workshop for Rust

EntryPointNotFoundException: InitSafe
Steamworks.SteamAPI.Init () (at Assets/Plugins/Steamworks/Steamworks.NET/Steam.cs:58)
WorkshopBaseEditor.OnInspectorGUI () (at Assets/Scripts/Editor/WorkshopBaseEditor.cs:87)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1240)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by rlabrecque** [comment]
Rust needs to update their stuff.
