### ISSUE TITLE
P2PSessionRequest_t not received 

### ISSUE THREAD

**Issue by JVasica** [rlabrecque/Steamworks.NET#181]
Hi, 

I've got issues regarding m_P2PSessionRequest  callback. The problem is that quite often when client, which is in the same lobby as the server player, sends the first message (reliably) then on the server the P2PSessionRequest_t callback is not fired and therefore they can't start sending messages between each other. In the connection phase I am sending message every 20 seconds and after minute if they are still not connected the client will leave the lobby. After this when I try to connect the second time everything works and after few seconds the client's message arrives to server.

**Comment by rlabrecque** [comment]
Sorry I missed this! It doesn't seem like something I personally can solve though, seems more like a Valve issue. Hopefully you got it working though!
