### ISSUE TITLE
Trying to get DeleteItem functionality

### ISSUE THREAD

**Issue by jongallant** [rlabrecque/Steamworks.NET#182]
So I noticed the latest code branch has DeleteItem implemented, but the DLL from the builds do not.  So I tried to build the DLL myself and I am unable to open the project, I don't know what is going on but it is stating that I do not have framework 4.0 installed, which I in fact do. 

Would it be possible to request a build, so that I can get a DLL with the DeleteItem functionality?  Thanks.

**Comment by rlabrecque** [comment]
Hey, sorry about that! Yeah, CSteamworks is a real pain to build. I can't rebuild it for all platforms since I'm away, so I just bit the bullet and went and removed it completely. See #183 for more info.

Can you try out the newest commit?

**Comment by jongallant** [comment]
Can't test now, not home at the moment.  But damn man, you removed the
dependency?  Cripes that is above and beyond.
I will definitely give this a go when I get back.  Thank you so very much!

**Comment by rlabrecque** [comment]
It's been a pain for a long time! Valve introduced something that let me remove it about 2 years ago but I wanted to make sure it was kept up to date before I removed this, and it seems like it has \o/
