### ISSUE TITLE
Removing CSteamworks

### ISSUE THREAD

**Issue by rlabrecque** [rlabrecque/Steamworks.NET#183]
It's finally time to attempt to completely get rid of CSteamworks. It's a constant pain, makes updating and testing much harder, hopefully Valve's flat C API continues to be stable.

Any commits from the one linked below onward may be unstable, I'm not home to test these changes out on all platforms, so please only update if you're willing to provide feedback.

The last commit before this point is: 7d079b2bfc2b40cc846af4edeb7c367680b14110

**Comment by rlabrecque** [comment]
Additional notes:

- You need to define STEAMWORKS_X64 or STEAMWORKS_X86 when you're not on Unity now. This is because Valve names the 64 bit version of their DLLs like: steam_api64.dll.

Pending work:

- RedistInstall should warn/remove old files like CSteamworks.dll/bundle/so.
- We could abstract everything away twice if we want to get 32/64 bit cross platform compat back, but I don't think it would be worth it. If that's something that is valuable to you then try out Facepunch.Steamworks.

**Comment by Alloc86** [comment]
Sounds great overall, just curious what this means:
> We could abstract everything away twice if we want to get 32/64 bit cross platform compat back, but I don't think it would be worth it.

**Comment by rlabrecque** [comment]
Something similar to what Facepunch.Steamworks/SteamNative is doing:

https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamNative/SteamNative.Platform.Win64.cs etc

The big difference between Facepunch.Steamworks/SteamNative and Steamworks.NET now is:

SteamNative is designed to be compiled into a universal/Any-CPU DLL, Steamworks.NET is still primarily Unity first and gets compiled into the platform specific builds.

Outside of Unity this isn't a /huge/ issue. XNA always only supported x86, continuing to build for x86 exclusively on Windows isn't a huge deal I don't think. Linux already has enough segregation where you pretty much only ever want to build on x64.
We won't get cross-OS binary compatibility without doing something like SteamNative does.

**Comment by Alloc86** [comment]
Hm, basically the interface of the libraries is the same? So the only issue here is the file name?
Couldn't you just set the library filename on the DllImport attribute to be based on something that's "calculated" on startup? Or actually couldn't we just rename the library files themselves to steam_api.dll and libsteam_api.so from the *64 variants as they are in different folders now anyway (x86_64 vs x86)?

**Comment by rlabrecque** [comment]
We can't set the filename at runtime unfortunately, it's compile time only. :/ We definitely could rename the library files but that's a whole mess of it's own and not really kosher.

**Comment by Alloc86** [comment]
Hm, would really only require to rename the steam_api64.so -> steam_api.so anyway? I mean for Windows it doesn't matter (Unity doesn't get its crap together to finally support a single 32/64 bit build like it does on OSX/Linux for years already...) and OSX has the fat binaries with both architectures anyway.
Dropping the 64/32 bit combined builds for Linux just to not rename a single file feels a bit wrong to me somehow :D
Though I have to admit I don't know how many people still require to run the 32 bit build for whatever compatibility reason they might have (as you said it's not really a matter of people running 32 bit Linux systems, but Unity had seemingly random compatibility issues sometimes which were fixed by running 32 bit ... this situation could have improved though).

**Comment by rlabrecque** [comment]
For Unity I actually think the 64/32 combined linux builds are still fine? They aren't /that/ combined right? Everything's still compiled twice, and then just has the two binaries (and a shell script to pick one of the two) in the output root.

Really this shouldn't be a problem for Unity at all if you use Steamworks.NET like Test/Example use it, It's mostly just an issue for non-Unity stuff :/

**Comment by Alloc86** [comment]
No, the OSX/Linux "universal" builds are really as combined as possibly. Two executables of course and everything native twice (or in case of OSX as fat binaries), but everything managed is there just once. That's the nice thing about those two and what I've been missing for the Win platform for a while, as it could be done the same way... but who cares if it's not a cool trendy new mobile platform :(

**Comment by rlabrecque** [comment]
Ah hrm, interesting! As it is now it still might work in that case? Since we only use STEAMWORKS_X86/X64 on Windows. libsteam_api.so is named the same on Linux already so as long as Unity copies both successfully and sets the library search path to *_Data/Plugins/x86_[64]/ then I think everything should be fine in that case?

**Comment by Alloc86** [comment]
Oh, right, totally forgot that the lib filename is the same for both on Linux :)
Yeah, everything should be fine that way.

**Comment by MichaelDePiazzi** [comment]
@rlabrecque I've got a quick fix to make a Windows AnyCPU build if you're interested...

Basically you just need to put the Steam API libraries in separate subfolders and rename the DLLs so they have the same filename. e.g.

- `x86\steam_api.dll`
- `x64\steam_api.dll` _(renamed from `steam_api64.dll`)_

Then you manually load the appropriate library using the [`LoadLibrary` function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx).
e.g. The following code could be placed in the `NativeMethods` class:
```csharp
[DllImport("kernel32", CharSet = CharSet.Unicode)]
private static extern IntPtr LoadLibrary(string lpFileName);

static NativeMethods()
{
    var fileName = (Environment.Is64BitProcess ? "x64" : "x86") + @"\steam_api.dll";
    LoadLibrary(Path.GetFullPath(fileName));
}
```
As long as this is done before any of the DLL imports are referenced, then they will see a "steam_api" library is already loaded in memory and use that instead.

I'm currently using this trick myself with Steamworks.NET and it works very well.
