### ISSUE TITLE
Calling SteamUserStats.GetStat( string, out float ) returns this exception...

### ISSUE THREAD

**Issue by RicardoDaForce** [rlabrecque/Steamworks.NET#185]
Message:
EntryPointNotFoundException: SteamAPI_ISteamUserStats_GetStat_

Callstack:
Steamworks.SteamUserStats.GetStat (System.String pchName, System.Single& pData) (at Assets/Plugins/Steamworks.NET/Plugins/Steamworks.NET/autogen/isteamuserstats.cs:36)
SteamStats.IterateStatValues (Steamworks.CSteamID steamID) (at Assets/Code/Online/SteamStats.cs:351)
SteamStats.OnUserStatsReceived (Steamworks.UserStatsReceived_t pCallback) (at Assets/Code/Online/SteamStats.cs:327)
Steamworks.Callback`1[T].OnRunCallback (System.IntPtr thisptr, System.IntPtr pvParam) (at Assets/Plugins/Steamworks.NET/Plugins/Steamworks.NET/CallbackDispatcher.cs:155)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception) (at Assets/Plugins/Steamworks.NET/Plugins/Steamworks.NET/CallbackDispatcher.cs:55)
Steamworks.Callback`1:OnRunCallback(IntPtr, IntPtr) (at Assets/Plugins/Steamworks.NET/Plugins/Steamworks.NET/CallbackDispatcher.cs:158)
Steamworks.NativeMethods:SteamAPI_RunCallbacks()
Steamworks.SteamAPI:RunCallbacks() (at Assets/Plugins/Steamworks.NET/Plugins/Steamworks.NET/Steam.cs:104)

**Comment by rlabrecque** [comment]
Ahh yeah, the overloads, temporarily can you change that to `SteamAPI_ISteamUserStats_GetStat0`?

**Comment by Mufalder** [comment]
> Ahh yeah, the overloads, temporarily can you change that to SteamAPI_ISteamUserStats_GetStat0?

I have same issue, but I don't understand what need to change, can you help?

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/Steamworks.NET/autogen/NativeMethods.cs#L2282

    -		[DllImport(NativeLibraryName, EntryPoint = "SteamAPI_ISteamUserStats_GetStat_", CallingConvention = CallingConvention.Cdecl)]
    + 		[DllImport(NativeLibraryName, EntryPoint = "SteamAPI_ISteamUserStats_GetStat0", CallingConvention = CallingConvention.Cdecl)]

Same thing with line 2290 for SetStat. I get home tomorrow and I'll get that fixed!

**Comment by Mufalder** [comment]
Its working now, thanks!
