### ISSUE TITLE
I cant get ownership info by Steam Web API

### ISSUE THREAD

**Issue by huseong** [rlabrecque/Steamworks.NET#189]
I am game developer with unity and socket.io. I want to use Steam API in order to check that client have ownership of my game. I want use Steam Web API. So I send test request like this because I don't know the format of response.

https://api.steampowered.com/ISteamUserAuth/AuthenticateUserTicket/v1/
?key=6**********&appid=22****&ticket=14000C9763018BF35*****
and I got error like this.

{
    "response": {
        "error": {
            "errorcode": 3,
            "errordesc": "Invalid parameter"
        }
    }
}
I can't find why the parameter is wrong. I tried all day for finding this error but i couldn't ㅠㅠ

**Comment by starbvuks** [comment]
what was the solution?

**Comment by Jay-ArBrouillard** [comment]
Also ran into same issue and still looking for solution. This is my gdscript code trying to convert the binary ticket data from GetAuthTicketForWebApi into a hexadecimal string. I'm passing hexadecimal value a parameter to https://partner.steam-api.com/ISteamUserAuth/AuthenticateUserTicket/v1/

```func on_get_ticket_for_web_api(auth_ticket: int, result: int, ticket_size: int, ticket_buffer: Array):
	var hexEncodedSessionTicket = "";
	for i in ticket_buffer:
		hexEncodedSessionTicket += "%X" % i;
	
	print(hexEncodedSessionTicket)```
