### ISSUE TITLE
Error installing Steamworks.NET on Unity 5.6.1

### ISSUE THREAD

**Issue by ktmlleska** [rlabrecque/Steamworks.NET#192]
Hi,

I just downloaded the Steamworks.NET from gitHub to set it up to my unity project, following the steps on http://steamworks.github.io/installation/.

But when I lunch the unity project, I get a couple of errors and the steam_appid.txt is not copied to the root folder.

The errors are the following:

Assets/Plugins/Steamworks.NET/autogen/isteamgameserverapps.cs(149,25): error CS1502: The best overloaded method match for `Steamworks.NativeMethods.ISteamApps_GetInstalledDepots(System.IntPtr, Steamworks.AppId_t, Steamworks.DepotId_t[], uint)' has some invalid arguments

------

Assets/Plugins/Steamworks.NET/autogen/isteamgameserverapps.cs(149,109): error CS1615: Argument `#3' does not require `out' modifier. Consider removing `out' modifier

Any idea of what could I do?

Thank you very much.
Cheers.

**Comment by rlabrecque** [comment]
Hey, that sounds pretty bad!

Could you try installing the latest version from github master? It should actually replace the old release version soon!

**Comment by ktmlleska** [comment]
Hi Riley,

Thank for your reply, this is actually with the github master.
Could the problem be related with the fact that I'm using OSX? 
(I'm creating a VR game with unity in mac with SteamVR asset package and compiling for Windows, and have no problems at all...)

Thank you very much.

**Comment by rlabrecque** [comment]
Opps, yeah, I see it!

Change this:
```
		public static uint GetInstalledDepots(AppId_t appID, out DepotId_t pvecDepots, uint cMaxDepots) {
			InteropHelp.TestIfAvailableGameServer();
			return NativeMethods.ISteamApps_GetInstalledDepots(CSteamGameServerAPIContext.GetSteamApps(), appID, out pvecDepots, cMaxDepots);
		}
```
To:
```
		public static uint GetInstalledDepots(AppId_t appID, DepotId_t[] pvecDepots, uint cMaxDepots) {
			InteropHelp.TestIfAvailableGameServer();
			return NativeMethods.ISteamApps_GetInstalledDepots(CSteamGameServerAPIContext.GetSteamApps(), appID, pvecDepots, cMaxDepots);
		}
```

I'll be able to get a fix out in a couple days. Thanks for the report!

**Comment by ktmlleska** [comment]
Thank you very much,

It is working perfectly!

Cheers!
