### ISSUE TITLE
SteamManager.cs crashing the game on Unity 5.6.1f1.

### ISSUE THREAD

**Issue by vitorfgd** [rlabrecque/Steamworks.NET#193]
Hello there. I'm following the SteamWorks.Net getting started (https://steamworks.github.io/gettingstarted/) and comparing it to the SteamWorks example (https://github.com/rlabrecque/Steamworks.NET-Example). 

The example runs fine but whenever I attach the SteamManager.cs to any GameObject in my game, Unity3D just freezes and crash the whole project. I already tried to comment the callbacks but that didn't solve my problem.

I imported the Steamworks.net to my project using the latest .unitypackage release.

[EDIT] Working on a MAC.

Can someone help me? Thank you!

**Comment by flashmandv** [comment]
Same problem here on Mac os x High Sierra. Using Unity 2017.1.2
