### ISSUE TITLE
I have problems with StoreStats()

### ISSUE THREAD

**Issue by adri1489** [rlabrecque/Steamworks.NET#194]
I'm having problems when I want to load the stats of a user. In the computer where I StoreStats I see the changes with GetStat in the moment that I StoreStats but in the computer where I'm loading the stats with:

`SteamUserStats.RequestUserStats(id);`

and after the callback

`SteamUserStats.GetUserStat(id, "NumGames", out aux);`

I only see the changes that the other user is doing when he closes the game (or if the time between one StoreStats() and the next is more than 6 minutes). To upload the stats I'm using: 

```
SteamUserStats.SetStat("NumGames", m_nTotalNumGames); 
bSuccess = SteamUserStats.StoreStats();

```
and in Update:
`
SteamAPI.RunCallbacks();
`
However, when I reset stats like this I can see the changes in the two sides:
```

SteamUserStats.ResetAllStats(true);
bSuccess = SteamUserStats.StoreStats();

```
What I'm trying to do is to have the uploaded stats at the same time in the 2 computers; the user that StoreStats() and the user that wants to see it with getuserstat.
Help me please!!!

**Comment by rlabrecque** [comment]
StoreStats is pretty heavily rate limited, and it's not designed to be used for instant updating. It could take a while for others to see the updated stats unfortunately.
