### ISSUE TITLE
Crash on OSX

### ISSUE THREAD

**Issue by ConjuredGraphics** [rlabrecque/Steamworks.NET#196]
Hey there. Mac support seems to be broken in my experience here.

I just installed Steamworks.NET to my Unity 5.6.3 project via the UnityPackage download. Successfully built an app targeting macOS x86_64, but after launching the app crashes just after the title screen. Running a 2017 15" Macbook Pro running macOS Sierra 10.12.6. 

Removing the SteamManager gameobject from the main/first scene resolves the problem, but that's clearly not a solution, I would love for the plugin to work. 

The build works fine on Windows.

**Comment by ConjuredGraphics** [comment]
Fixed it by moving libsteam_api.dylib from the root /Plugins folder to /Plugins/steam_api.bundle/Contents/MacOS. Perhaps the Unitypackage should be updated to include this?

**Comment by AdriaandeJongh** [comment]
I'm getting this error too, and considering I did a fresh reinstall I don't have the /Plugins/steam_api.bundle/Contents/MacOS to put the libsteam_api.dylib in!

**Comment by rlabrecque** [comment]
Is this the case with [11.0.0](https://github.com/rlabrecque/Steamworks.NET/releases/tag/11.0.0)? :(

**Comment by AdriaandeJongh** [comment]
correct

**Comment by rlabrecque** [comment]
Kk, on it tonight!

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/releases/tag/11.0.0

Can you guys redownload and try again?

**Comment by nmbryant** [comment]
Are you still working on a fix for this? This was causing the game I was working on to crash, so we removed it and steam achievement functionality for now. We would like to add steam achievements back in, any idea when the fix will be completed?

**Comment by rlabrecque** [comment]
It should be fixed.

**Comment by AdriaandeJongh** [comment]
I can confirm it now works!
