### ISSUE TITLE
SteamAPI.RestartAppIfNecessary() not working

### ISSUE THREAD

**Issue by ciwolsey** [rlabrecque/Steamworks.NET#197]
In my SteamManager script I have the following:

```
if (SteamAPI.RestartAppIfNecessary((AppId_t)APPID)) 
{
	Application.Quit();
	return;
}
```

Even when I run my build with Steam closed and logged out SteamAPI.RestartAppIfNecessary is returning false. I've used APPID here as a placeholder for my real app id.

I'm using Unity 2017.2p2

**Comment by rlabrecque** [comment]
Do you have a steam_appid.txt next to your executable? As that completely disables/overrides this function.
