### ISSUE TITLE
steam_appid.txt does not get copied when building artifacts

### ISSUE THREAD

**Issue by XaeroDegreaz** [rlabrecque/Steamworks.NET#198]
Hello,

As the title suggests, when building my game, the steam_appid.txt that exists in the project root does not get copied over to the build directory. Is there something that I'm missing from the documentation? I have to copy the file manually to the build directory.

**Comment by rlabrecque** [comment]
Yeah, Steamworks.NET will not copy it over automatically because it's only supposed to be for development.

**Comment by XaeroDegreaz** [comment]
So you're saying that I shouldn't use Steamworks.NET in my real project? I thought that was the point of it -- so one could integrate with Steamworks.

**Comment by sqrMin1** [comment]
@XaeroDegreaz You misunderstood him. He means that the **steam_appid.txt** file is just for development. It shouldn't be delivered together with your app build, that's why it is not automatically copied to the output directory.

**Comment by rlabrecque** [comment]
Indeed^ Sorry for being unclear, I was on my phone and had to make it quick.

steam_appid.txt allows you to run outside of the context of Steam. Steam automatically injects the AppId when you're running your game directly from Steam, You should then be using SteamAPI_RestartAppIfNecessary() with your AppId to relaunch through steam for your release version. This is all in Valve's Steamworks documentation though.
