### ISSUE TITLE
Cant get Overlay to work at all

### ISSUE THREAD

**Issue by otan9** [rlabrecque/Steamworks.NET#199]
Im trying to get the steam shift+tab overlay to work in Unity Editor and in the build .exe

I put both steam_appid.txt in the exe and the one that comes with the .unitypackage file. 

I dont have my own appid so using the default 480.

Trying to get this simple callback to work:

```
	protected Callback<GameOverlayActivated_t> m_GameOverlayActivated;

	private void OnEnable() {
		if (SteamManager.Initialized) {
			m_GameOverlayActivated = Callback<GameOverlayActivated_t>.Create
				(OnGameOverlayActivated);
		}
	}

	private void OnGameOverlayActivated(GameOverlayActivated_t pCallback) {
		if(pCallback.m_bActive != 0) {
			Debug.Log("Steam Overlay has been activated");
		}
		else {
			Debug.Log("Steam Overlay has been closed");
		}
	}
```

but it wont run if overlay doesnt even work.

Im trying to get the log to display

Any solutions?

**Comment by otan9** [comment]
nvm, it worked after attaching the .exe to steam, and looked into connected logs in unity editor.
It does work, just needs to be loaded from steam

**Comment by rlabrecque** [comment]
You can launch the editor via a Steam shortcut, so the overlay gets injected before the Unity editor graphics API initializes, you can see more about that here:
http://steamworks.github.io/faq/

But otherwise it's out of our control unfortunately!
