### ISSUE TITLE
Unity 2017.3 support

### ISSUE THREAD

**Issue by Arugin** [rlabrecque/Steamworks.NET#203]
There a lot of warnings right now:

    Steamworks.NET/RedistInstall.cs(165,62): warning CS0618: `UnityEditor.BuildTarget.StandaloneOSXIntel' is obsolete: `StandaloneOSXIntel has been removed in 2017.3'
    Steamworks.NET/RedistInstall.cs(166,62): warning CS0618: `UnityEditor.BuildTarget.StandaloneOSXIntel64' is obsolete: `StandaloneOSXIntel64 has been removed in 2017.3'

and etc

**Comment by AdriaandeJongh** [comment]
I commented out all the lines with warnings and that fixed it ;) Simple temporary fix!

**Comment by rlabrecque** [comment]
Thanks, should be fixed with 730ffad693bb6ca42d0976365029075eb21b23b2!
