### ISSUE TITLE
SteamInventory SetProperty bool/long/float all going through SetProperty0

### ISSUE THREAD

**Issue by SDGNelson** [rlabrecque/Steamworks.NET#209]
Caused a bit of head scratching before we found the culprit. ;)

**Comment by rlabrecque** [comment]
Doh! I'll try to get to it tonight!

In the meantime could you just locally change it to 0/1/2?

**Comment by SDGNelson** [comment]
No rush/worries! I locally changed it when I was tracking down the issue. Figured I'd post here so it could be fixed for everyone, too. :)

**Comment by rlabrecque** [comment]
Let me know if that fixes it! Thanks again Nelson!
