### ISSUE TITLE
Issue with BDecryptToken() (SDK v1.31)

### ISSUE THREAD

**Issue by aienabled** [rlabrecque/Steamworks.NET#21]
Hello! I found that SteamEncryptedAppTicket.BDecryptTicket() returns always false. It happens because native method has wrong signature - out pcubTicketDecrypted instead of ref pcubTicketDecrypted.
Correct method declaration resolved this issue:

public static extern bool BDecryptTicket(byte[] rgubTicketEncrypted, uint cubTicketEncrypted, byte[] rgubTicketDecrypted, ref uint pcubTicketDecrypted, [MarshalAs(UnmanagedType.LPArray, SizeConst=Constants.k_nSteamEncryptedAppTicketSymmetricKeyLen)] byte[] rgubKey, int cubKey);

**Comment by rlabrecque** [comment]
Thanks for the report @aienabled! Sorry it took so long to get to.
