### ISSUE TITLE
Permissions issue with steam_api.dll steam_api64.dll

### ISSUE THREAD

**Issue by golergka** [rlabrecque/Steamworks.NET#210]
I recently updated Steamworks API from the latest unity package, and spend a long time debugging a strange issue: I had the "DllNotFoundException: steam_api64" error, although the dll was placed and configured correctly.

In Editor log, I found an error that says "Plugins: Failed to load 'Assets/Plugins/x86_64/steam_api64.dll' with error 'Access is denied.'.`

In the end, I found out that the DLL file had strange ermissions with something that looked like NULL SID:

![image](https://user-images.githubusercontent.com/929735/34875110-f7cc76dc-f7ac-11e7-8ed4-556e5c55803e.png)

Also, when I was opening the permissions dialog, I got this warning:

![image](https://user-images.githubusercontent.com/929735/34875182-3d913e96-f7ad-11e7-9f02-55e9d7387915.png)

In advanced security settings, I also found this entry:

![image](https://user-images.githubusercontent.com/929735/34875484-76df49f8-f7ae-11e7-8481-eec777b96431.png)

Also, notice that security inheritance is disabled.

Another DLL in the same folder, which was loading OK, didn't have these entries:

![image](https://user-images.githubusercontent.com/929735/34875139-18b322ce-f7ad-11e7-8654-40f4a5e11bd2.png)

![image](https://user-images.githubusercontent.com/929735/34875495-849ec2f8-f7ae-11e7-86e7-2183d194ddb7.png)

Fixing the issue turned out pretty simple: delete everything in advanced dialog, and turn the inheritance back on. After that, the error goes away. Also, steam_api.dll has the same problem.

Since I just got the files from unity package, I think they're packed with these wrong permission overrides.

**Comment by Andr91** [comment]
Having the same problem, solved by creating a new project, but I'm just working on the scripts and not on my actual game.
I would also try to hard copy everything when Unity Editor is close.

**Comment by rlabrecque** [comment]
I'm closing this as part of cleanup, if anyone else runs into this please ping me here. I'm hoping it was a one off as part of that old release.
