### ISSUE TITLE
[Steamworks.NET] SteamAPI_Init() failed.  issue

### ISSUE THREAD

**Issue by woobyungtaek** [rlabrecque/Steamworks.NET#212]
hi, i have error this part
i use unity 5.6.2f1 ver
use debugView i find what is problem

in unity editor can't find "steam_appid.txt"file
![1234](https://user-images.githubusercontent.com/36003410/35630054-a3026760-06e3-11e8-9c30-48e64c08880f.JPG)

my folder now 
![12333](https://user-images.githubusercontent.com/36003410/35630083-ba56edb4-06e3-11e8-8988-0d8d8e8c1784.JPG)

this state 

i don't know what is problem
how fix?

**Comment by rlabrecque** [comment]
That's exclusively on Valve's end, but I'm wondering if it can't read that file for some reason, wrong permissions etc?

**Comment by woobyungtaek** [comment]
i find reason, txt file save ansi / only read utf-8
