### ISSUE TITLE
test in unity editor

### ISSUE THREAD

**Issue by woobyungtaek** [rlabrecque/Steamworks.NET#216]
When run by Unity
The steam is on.
The new game is on.
(Built into Steam)

Unity's editor is not connected to Steam.

Now, the status is
Unity Editor running
Running my project.exe.
Steam and my project.exe are connected
(steam status is running my project. [green]
When I exit my project.exe
Unity Editor still running
Steam state does nothing

Do you know how to use Unity Editor + steam so my project.exe doesn't run?

**Comment by rlabrecque** [comment]
Hey @woobyungtaek , unfortunately this is just how Steam works. It doesn't unhook from your application until the last executable stops running. In practice this doesn't cause problems though!
