### ISSUE TITLE
Access violation error on GetAchievement call

### ISSUE THREAD

**Issue by mukulabdagiri** [rlabrecque/Steamworks.NET#217]
Hi, 

I am testing my game on Steam for Achievements. I have set up all my Achievements on Steam and allocated appropriate string id for each Achievement in Unity. I am initializing Steam inside SteamManager with SteamAPI.Init(). For unlocking Achievements I call:

```
public void UnlockAchievement(string achievementId)
{
	bool isAchievementUnlocked;
	SteamUserStats.GetAchievement (achievementId, out isAchievementUnlocked);
        if (!isAchievementUnlocked)
        {
		SteamUserStats.SetAchievement (achievementId);
	        SteamUserStats.StoreStats ();
	}
}
```

But the game crashes when i call this function. Crash dump says:

**steam_api64.dll caused an Access Violation (0xc0000005)
in module steam_api64.dll at 0033:574b5853.
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.**

Also I gated all Steam calls inside if(SteamManager.Initialized). Before running the game through Unity editor, I am logged into steam with my account which is obvious when Steam is initialized and license is checked successfully.
Any idea why it might be failing on Achievement calls? Do I need to upload the game to Steam for testing Achievements or do I have to set any access permissions?

Thanks,
Mukul

**Comment by TheDJMAX** [comment]
Do the achievements / achievement keys that you're trying to set exist in
Steamworks for your app?

**Comment by mukulabdagiri** [comment]
I have integrated Steamworks in my Unity project by importing the Steamworks package. The achievement keys are string ids which I have declared in my AchievementManager code. These ids are same ones set up inside my game app on Steam. When I unlock an achievement in game, I just pass the string id to the Steamworks function
SteamUserStats.GetAchievement(achievementId, out isAchievementUnlocked);

I thought the function will communicate with my game app based on the Steam id. I hope i am doing it right?

**Comment by mukulabdagiri** [comment]
I have an update. I did some more tests and realized that problem is not with the get and set achievement functions and they do work and i was able to unlock all achievements by testing the calls inside

`void OnUserStatsReceived(UserStatsReceived_t pCallback) {}`

It crashes when i call any Steam function inside 

`UnlockAchievement(Achievement_t achievement){}`

eg. this fails:
```
private void UnlockAchievement(Achievement_t achievement) {
		achievement.m_bAchieved = true;

		// the icon may change once it's unlocked
		//achievement.m_iIconImage = 0;

		SteamUserStats.RequestCurrentStats ();
		// Store stats end of frame
		m_bStoreStats = true;
	}
```

I am calling UnlockAchievement() same as the SpaceWar example. Also SteamManager.Initialized returns true. Why are all Steam calls failing inside the function?

**Comment by rlabrecque** [comment]
What do your callbacks look like? Are your callbacks getting garbage-collected for example?

Like:
```
	protected Callback<UserStatsReceived_t> m_UserStatsReceived;
	protected Callback<UserStatsStored_t> m_UserStatsStored;
	protected Callback<UserAchievementStored_t> m_UserAchievementStored;

		m_UserStatsReceived = Callback<UserStatsReceived_t>.Create(OnUserStatsReceived);
		m_UserStatsStored = Callback<UserStatsStored_t>.Create(OnUserStatsStored);
		m_UserAchievementStored = Callback<UserAchievementStored_t>.Create(OnAchievementStored);
```

**Comment by mukulabdagiri** [comment]
`Callback<UserStatsReceived_t>.Create(OnUserStatsReceived)` is working fine. I do get that callback when i initially call `bool bSuccess = SteamUserStats.RequestCurrentStats();`

But if I call the same function or `SteamUserStats.SetAchievement(achievement.m_eAchievementID.ToString());` inside 
`void UnlockAchievement(Achievement_t achievement) {} `
when my achievement is triggered in game, it crashes.

I am not storing any stats so `Callback<UserStatsStored_t>.Create(OnUserStatsStored);` is not being used. `Callback<UserAchievementStored_t>.Create(OnAchievementStored)` is not yet reached since the game crashes before that.

**Comment by mukulabdagiri** [comment]
I think that's what is happening. The callbacks are getting garbage collected. How can I prevent that? I took out the onRender() function. Also instead of initiating the callbacks in onEnable() I do it in Start() function. Does that make a difference?
