### ISSUE TITLE
Achievements Popup not showing but everything is working

### ISSUE THREAD

**Issue by Andr91** [rlabrecque/Steamworks.NET#218]
As the title says I don't know why but achievements popup is not showing even if everything seems to work.
Steam says I'm playing Spacewar, as soon as I exit the game Steam says I'm not playing it, achievements are updated as soon as I unlock one (no need to exit the game) but still no popup shown when I open the game or when an achievement is unlocked.
I don't know if it's an actual bug or it's just me.
I'm using Unity2017.3.0f3 and this is happening both in the editor and in the built game.

*and that's ok since I'm working on spacewar before moving everything on my game.

**Comment by Andr91** [comment]
Created a frash new project, copied everything from the example project and having the same exact problem.

**Comment by TheDJMAX** [comment]
It sounds like your Steam Wrapper is not running properly. When you boot
the game, do you see the "press 'tab' to access steam" popup in the corner?
If not, you'll need to take another look at how you're initializing the
steam api.

[image: Inline image 1]

**Comment by Andr91** [comment]
I'm not seeing it everytime I launch the game. And I'm only seeing it in the editor once I exit from playmode.
If I launch a built project nothing is shown.
I'm not getting any error from both writing and reading from Steam.

**Comment by Andr91** [comment]
Solved! 
I only had to add the exe to my steam library. 
After that everything is working like a charm. 
Popup are all shown, Shift+Tab message shown at startup etc.

**Comment by Andr91** [comment]
Anyway I don't know if that's a bug or just the way Steamworks API works.

**Comment by TheDJMAX** [comment]
From the sounds of it you don't have the initialization working quite right
yet. You shouldn't have to launch the game from steam to have the wrapper
function properly. Perhaps you're just missing your steam_appid.txt file?

**Comment by Andr91** [comment]
steam_appid.txt file is present in the root folder of both the built game and Unity Project.
I'm using SteamManager.cs + my code but the Init process is all inside of SteamManager.cs.
No modification has been made to SteamManager.cs

That's all I added 
`

    private void OnApplicationCancelQuit() // (CUSTOM)
    {
        if (s_instance != this)
        {
            return;
        }

        s_instance = null;

        if (!m_bInitialized)
        {
            return;
        }

        SteamAPI.Shutdown();
    }

    private void OnApplicationQuit() // (CUSTOM)
    {
        if (s_instance != this)
        {
            return;
        }

        s_instance = null;

        if (!m_bInitialized)
        {
            return;
        }

        SteamAPI.Shutdown();
    }`

**Comment by rlabrecque** [comment]
I think I see what's going on here;

> Solved!
> I only had to add the exe to my steam library, and launch the game from Steam.
> After that everything is working like a charm.
> Popup are all shown, Shift+Tab message shown at startup etc.

The achievements are unlocking fine, but just the overlay isn't working right?

http://steamworks.github.io/faq/#the-steam-overlay-doesnt-work
