### ISSUE TITLE
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.

### ISSUE THREAD

**Issue by xnooztvFR** [rlabrecque/Steamworks.NET#219]
Hi,

I'm running Unity 5.6.3 Personal.
My game has not been published yet, my game is waiting for verification (but i have appid).

I imported the SteamWorks.NET Unity component as per the instructions here https://steamworks.github.io/installation/
steam_api.dll did not appear in the root, but the steam_appid.txt did and I edited it, making it my own appid. While poking around I found steam_api.dll under Assets/Plugins/x86.

So not 100% sure that the import went correctly.

When I have steam running and launch the game in Unity UI I get this error. Same if I run a stand alone build.

`[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
UnityEngine.Debug:LogError(Object, Object)
SteamManager:Awake() (at Assets/Scripts/Steamworks.NET/SteamManager.cs:101)
`

**Comment by xnooztvFR** [comment]
SteamWorks working fine with appid "780"
I think it's because my game is not published?

**Comment by rlabrecque** [comment]
Do you have a developer or prerelease license for your appid on your signed in Steam account?

**Comment by xnooztvFR** [comment]
How to see this?

**Comment by xnooztvFR** [comment]
I was wrong Steam account, actually it working :)
