### ISSUE TITLE
Support for 1.42

### ISSUE THREAD

**Issue by codecat** [rlabrecque/Steamworks.NET#221]
Will support for Steamworks SDK 1.42 be added soon?

Edit: Noticed the readme says it's compatible, but I haven't gotten that to work with the latest release of Steamworks .Net, it's saying there's a function missing.

**Comment by fallenstars** [comment]
it has been in fact, but not in the unity package, but if you check the last push, it say that it was updated for 1.42 :)

**Comment by codecat** [comment]
Well, I'm using the standalone version from the [releases page](https://github.com/rlabrecque/Steamworks.NET/releases) which says it supports 1.41. I haven't built it from source yet though.. :worried:

**Comment by fallenstars** [comment]
yup but look on the page you linked, there is a "7 commit since this release" and there you can download the latest version, at least that's what I'm trying to use but since it's the first time i'm not sure if it will work ^^"
(and a brohoof for vinyl ^^)

**Comment by sbeca** [comment]
Hello @rlabrecque, is there anything holding you back from creating a new release for SDK v1.42?

**Comment by rlabrecque** [comment]
This is the last thing that needs to be done before I push out a new release:
https://github.com/rlabrecque/Steamworks.NET/issues/205#issuecomment-376976201

**Comment by mgrogin** [comment]
Hey @rlabrecque is #205 still an issue? 
Is there going to be a new release for SDK v1.42?

Thanks!

**Comment by codecat** [comment]
Readme says it supports 1.43 at least, so I'll close this issue now.
