### ISSUE TITLE
GetDlcDownloadProgress does not work

### ISSUE THREAD

**Issue by Belleal** [rlabrecque/Steamworks.NET#226]
**GetDlcDownloadProgress** always returns _false_ and both the _downloadedBytes_ and _totalBytes_ output arguments are always 0 even as I am observing the Steam client downloading the DLC over the course of a minute or two. Can this be fixed, please?

**Comment by rlabrecque** [comment]
I noticed this too while trying it out, I think it's broken on Valve's end, and in C++. 😕
