### ISSUE TITLE
DllNotFoundException on OS X

### ISSUE THREAD

**Issue by merfolk** [rlabrecque/Steamworks.NET#23]
I am having trouble getting Steamworks.NET working on an OS X port of a Monogame-based game. The Steamworks integration is already working on Windows.

I have downloaded the complete **Steamworks.NET-Standalone_5.0.0 release** and added a reference to the **OSX-Linux-x86/Steamworks.NET.dll** in my project.

I have then manually copied **steam_appid.txt** (changing the appid to our own), **CSteamworks.bundle**, and **Steamworks.NET.dll.config** files inside our Game.app/Contents/MonoBundle/ folder, right next to the Game.exe.

However, when I launch the game I get this exception from **Steamworks.SteamAPI.Init()**:

**System.DllNotFoundException: CSteamworks.bundle/Contents/MacOS/CSteamworks**
  at at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_InitSafe () <IL 0x00011, 0x0008f>
  at at Steamworks.SteamAPI.Init () <IL 0x00005, 0x0002b>

What have I missed?

Any help would be highly appreciated, as this is one of the very last problems that our team has before releasing our first game on Steam. Thanks!

**Comment by Eversor** [comment]
Hey merfolk, where you able to solve the issue? I'm having some problem as well in Xamarin Studio.

**Comment by merfolk** [comment]
Unfortunately I have not had time to wrestle with this issue.

My best guess is that the Steamworks.NET dll is actually trying to find a file named "libCSteamworks" instead of "CSteamworks". That's what I would try next.

**Comment by strich** [comment]
FYI the lib prefix comes from Mono itself - It will attempt to find libs with that prefix along with a bunch of others (With and without extension, etc). More info here: http://www.mono-project.com/docs/advanced/pinvoke/dllmap/

Given the appid file error though I'd say there is some issue with Steamworks correctly determining the relative directory of your game.

**Comment by Eversor** [comment]
I finally had it to work on my Xamarin configuration.
The problem was the signing of the mac bundle. Removing signing did the trick. (working on debug and release, both without signing)

**Comment by rlabrecque** [comment]
Awesome! I'm glad to hear that you figured that out!

**Comment by RavenTravelStudios** [comment]
I'm having the same problem, removing signing did not worked to me.
Seems that on mac osx it can't find the relative path (absolute path works well).
Any help?

**Comment by RavenTravelStudios** [comment]
Ok i fixed it.
If you delete the CSteamworks.dll.config and place the CSteamWorks.Bundle in the same exe dir, it works.
Thank you!
