### ISSUE TITLE
Can't make Steamworks.Net 11 work when its up on Steam.

### ISSUE THREAD

**Issue by AgentMega** [rlabrecque/Steamworks.NET#230]
Hi, I have a crash problem with 11.0: [Steamworks.NET], as unity plugin. 

The program work fine with the steam achievements if I lauch it from the Unity editor. But when posted on Steam it crash just after the unity logo.

This is on PC while it work fine on Mac, didn't test Linux. And it only appears when my app is posted on Steam.
Steamworks.net version 11.0.0 and Unity 5.6.3.

I upgraded to Unity 2018.1 To see if it can fix the problem but without any luck.
I have Windows 7 64bit with an Nvidia Card.
I precise that, because very strangely If I launch Steam from my old laptop with the same operating system Win7 64bit an an old Radeon everything work fine without any crash while it crash with my 2 other computers.

Any workaround ? I tried an older version 6 I had working on an old project [Steamworks.NET. but it didn't work either.

When the app launch from steam, it close up automatically and I got this :

Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/.\steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/libsteam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/.\libsteam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/libsteam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/.\steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/steam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/libsteam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/.\libsteam_api
Fallback handler could not load library D:/_STEAM/steamapps/common/Paper Dungeons Crawler/PDC_Data/Mono/x86_64/libsteam_api
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: steam_api
at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)
at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00000] in :0
at SteamManager.Awake () [0x00000] in :0

**Comment by rlabrecque** [comment]
Sorry I missed this, did you ever get it working?

**Comment by AgentMega** [comment]
Not exactly, I had to downgrade my Unity to version 2017.3 and downgrade Steamwork to v10. It's working only with this setup, but I can't get it run with Steamworks.net v11 and unity 2018. It crash only once uploaded on steam, and only on windows. working fine on Mac.

**Comment by gwachnitz** [comment]
I am having a similar issue after updating from Steamworks v10 toSteamworks v12 but with mac instead of windows. Same error.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/pull/414
