### ISSUE TITLE
Second invitation doesn't work

### ISSUE THREAD

**Issue by Zen12** [rlabrecque/Steamworks.NET#238]
Hello, I am working on multiplayer invitation system and there is an issue with sending second invitation. 

Player 1 sends invitation to Player 2 -> After a minute, both player leaves the room (the room is killed) -> Player 1 sends another invitation (Player 2 doesn't get it in chat) -> Player 1 sends another invitation (3rd invitation) -> Player2 gets 3rd invitation.

For cleaning rooms, I use SteamMatchmaking.LeaveLobby.
Is this Steam issue? 

Thanks,
Andrei

**Comment by rlabrecque** [comment]
I'm not sure if it's a Steam issue, or if it's an issue with how you are calling these functions unfortunately. You could ask on the Steamworks Dev forum.

**Comment by Zen12** [comment]
I found the solution, each time the when users tries to connect, I disconnect from matchmaker and after a second I connect him and after goes regular logic of matchmaker.
