### ISSUE TITLE
How to use callbacks like OnUserStatsReceived?

### ISSUE THREAD

**Issue by Eversor** [rlabrecque/Steamworks.NET#24]
As far as i know in .Net Async methods use callbacks similar to the ones provided in SW c++ documentation. For instance the method SteamUserStats.requestCurrentStats() shouldn't have a way to communicate the callbacks to be called when it returns? 

I'm referring to the "https://partner.steamgames.com/documentation/bootstrap_achieve" sample code and it has 2 callbacks for managing the async method results.

**Comment by rlabrecque** [comment]
Sorry for the late reply, this kind of fell through the cracks!

It's done almost the exact same way in Steamworks.NET as it is in the C++ Steamworks. Documentation for them is available here: http://steamworks.github.io/gettingstarted/#steam-callbacks
