### ISSUE TITLE
Steam doesn't really download my app game and dont launch

### ISSUE THREAD

**Issue by XN4k33Db** [rlabrecque/Steamworks.NET#240]
Steam window pops up and prompts me to select installation directory "D:\Steam". I press Ok. It installs but doesn't really copy anything, just lights up my game in the Steam Library.
If I again start the .exe, or try to launch the game from the Steam client ... I always get the message "Failed to start game (invalid app configuration)"
![errorsteam](https://user-images.githubusercontent.com/23197865/42125330-fe2f9b58-7c4a-11e8-9dab-94a1fb83488a.png)

Can you help me?

**Comment by KelsamGames** [comment]
This would be an issue to get support from Steamworks / Valve
