### ISSUE TITLE
Steam Controller IGA (.vdf) File Not Recognized

### ISSUE THREAD

**Issue by Waffle-SS** [rlabrecque/Steamworks.NET#241]
I've managed to successfully compile a unity game that connects to my steam controller and its even able to send haptic feedback to the controller. 

However, I can't for the life of me get input from the controller. [SteamController.GetAnalogActionHandle(string)](https://partner.steamgames.com/doc/api/ISteamController#GetAnalogActionHandle) needs a action name to get analog input from the controller. I've been losing my mind trying to get my InGame Actions file (the [portal 2 sample](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/english/portal2_actions.vdf): ) to recognize analog or digital input ingame. The [Steamworks.Net-Test](https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamControllerTest.cs) sample has a tab for the steam controller but none of the inputs work, **not even the [motion data](https://partner.steamgames.com/doc/api/ISteamController#GetMotionData)**, only the vibration test. 

Currently im using "game_actions_480.vdf" in the [game_controller_config folder](https://partner.steamgames.com/doc/features/steam_controller/getting_started_for_devs#iga), and I've been able to confirm the api is recognizing it. It recognizes my "InGameControls" and "MenuControls" [Action Sets](https://partner.steamgames.com/doc/api/ISteamController#GetActionSetHandle), but not anything inside of them such as "Move" or "Camera", "Fire" or "Jump".

[Valve documentation](https://partner.steamgames.com/doc/features/steam_controller/getting_started_for_devs#iga)

**Comment by spajus** [comment]
Try making a build, uploading it to steam and running it from steam client. If you call `SteamController.ShowBindingPanel(controllerHandle)`, you'll see that a game that runs in Unity Editor, or just from desktop won't be showing your configuration, it will be "Desktop Configuration" instead (where right pad moves your mouse).

**Comment by Waffle-SS** [comment]
Is there any way to "upload to steam" or do this without having to pay to have your game on steam? I really just want to do this for personal testing purposes, I don't want to have to "release" a game on steam just to start programming it for a steam controller.
