### ISSUE TITLE
Detect other game launch/running through Steam

### ISSUE THREAD

**Issue by shubhank008** [rlabrecque/Steamworks.NET#242]
Do Steamworks provide any API or way to detect game launches/running other than your own ? Our game/app needs to detect when a user launches/playing a game so we can disable our app to save CPU/GPU usage.

**Comment by KelsamGames** [comment]
This would be a question for the Steamworks Documentation, not Steamworks.NET. Although, I'm not sure why something like that would involve the Steamworks API. You could just "disable" your app while not in focus (not the active foreground program)?

**Comment by shubhank008** [comment]
@KelsamGames the nature of the app is that it always stays in focus/over everything else. Its like a overlay so that approach would not work. 
Only thing close on "in-game" data I can find is through WebAPI getplayersumarries but even then in-game data is a private data so not available for most of the players.

**Comment by KelsamGames** [comment]
Ah. Well to do something like that you'll need to read the "status" of the Steam client. I would suggest checking out something similar along this path:

https://stackoverflow.com/questions/36649527/check-if-steam-is-running-and-user-is-logged-in

**Comment by rlabrecque** [comment]
Probably better to do this with the Windows API I think
