### ISSUE TITLE
Unity 2018.x+ Packge Format

### ISSUE THREAD

**Issue by james7132** [rlabrecque/Steamworks.NET#246]
It'd be great if this was importable as a Unity package. It appears that git URL support for packages is coming in the future.

I've already created a [fork](https://github.com/HouraiTeahouse/Steamworks.NET) with a matching file structure that can be imported as a git submodule, embedded in the Packages folder. Example of how to do this: https://github.com/HouraiTeahouse/FantasyCrescendo/tree/develop/Packages. 

I can make a PR out of this if need be.

**Comment by rlabrecque** [comment]
As soon as this happens I think I'll split Steamworks.NET into two, a Unity 2018.x+ version, and a legacy version. I'm really excited for it!

**Comment by james7132** [comment]
Is the plan to wait for git URL support then make this change?

Should I make a PR for this?

**Comment by rlabrecque** [comment]
Yeah, I'd want to wait until we get a little closer!

**Comment by james7132** [comment]
https://forum.unity.com/threads/git-support-on-package-manager.573673/#post-3819487

As of Unity 2018.3.0b7, there is now experimental git import support. Would it make much sense to support this now. It should work with the forked repo that I have already created, but I would rather this be officially supported from your end.

**Comment by MeikelLP** [comment]
Please make it happen. 2018.3 is now officially released.
I'd love to use this as a package dependency.

**Comment by james7132** [comment]
Friendly reminder about this. We're starting to near the 2019.1 release and this is still not open. Should I open a PR?

**Comment by rlabrecque** [comment]
I still need to think about this a little bit, I explicitly don't want SteamManager in this repo, because it's Unity specific, where as Steamworks.NET isn't. Would creating a specific branch, or separate repo which has both be best? Or do I need to just give in? What also happens with all the non-Unity files? I don't particularly want to ship any Standalone stuff in there. Any thoughts?

**Comment by KelsamGames** [comment]
My thoughts: being one of the non-Unity users of Steamworks.NET, I really do not want Unity-specific files integrated into the main repo. A Unity-specific repo seems like a good idea.

**Comment by MeikelLP** [comment]
I would say a repo for unity which implements on Steamworks.NET

IMO it's the cleanest way. Branches are for merging and then deleting them.

**Comment by james7132** [comment]
For those who are interested in a Unity Package Manager version, I have gone as far as to repackage this project on a public scoped package registry:
https://upm.houraiteahouse.net/-/web/detail/com.rlabrecque.steamworks, based off of the HouraiTeahouse fork.

**Comment by rlabrecque** [comment]
Progress has been made here:
https://github.com/rlabrecque/Steamworks.NET/pull/414

https://github.com/rlabrecque/Steamworks.NET/issues/389
