### ISSUE TITLE
Native library location in Unity 2018.2

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#248]
Hi Riley,

I don't know when this started as we don't regularly run the dedi without having Steam open during our dev phase but it seems that at least on Unity 2018.2.0 it does no longer find native libraries in <game>_Data/Plugins/x86_64/ like it used to before on Linux builds. This results in dedi builds failing to initialize the SteamAPI as it can not find steamclient.so. It apparently still finds libsteam_api.so though.

Have you experienced the same thing? Is there anything we can do other than copying steamclient.so to the game's root folder (meaning running the 32 bit executable would require manual file copy work as both libraries are called just steamclient.so without any bitness indicator in the name)?

Regards,
Chris

**Comment by Onutrem** [comment]
Hello. I have the same issue. Did you find any solution ?

**Comment by Alloc86** [comment]
No, didn't find any information regarding this. Hoped that Riley would chime in :)
What do you mean with "it does not always work"? I see no reason why it would fail if the library is in the same folder as the game binary.

**Comment by spajus** [comment]
> Unity 2018.2.0 it does no longer find native libraries in _Data/Plugins/x86_64/ like it used to before on Linux builds.
It's not true. In my case `Plugins/x86_64/libsteam_api.so` gets loaded, but apparently `steamclient.so` fails to load, while it exists in `~/.steam/x64/`. 

If you found a solution, please post an update.

**Comment by rlabrecque** [comment]
Hey sorry, I started to type up a reply and then forgot about it!

One thing you could try is placing it in the `Game_Data\Managed\` folder or `Game_Data\Mono\`

If we can't find a spot for it we might need to load steamclient.so manually. We could do that by P/Invoking any function on it before calling SteamAPI_Init()

**Comment by spajus** [comment]
Btw, I found out that everything works once you make a Linux build, upload it to steam and play it through steam client, no libraries are missing and steam API works just fine.

**Comment by Alloc86** [comment]
> One thing you could try is placing it in the Game_Data\Managed\ folder or Game_Data\Mono\
Neither makes a difference, still can't find it. Also wouldn't really help as those would still mean only one location for both 32 and 64 bit version of the library ;)

> If we can't find a spot for it we might need to load steamclient.so manually. We could do that by P/Invoking any function on it before calling SteamAPI_Init()
Sounds like an interesting approach that could work. Haven't looked at the steamclient exports so far though so no idea if there's anything that could safely be called.


> It's not true. In my case Plugins/x86_64/libsteam_api.so gets loaded, but apparently steamclient.so fails to load, while it exists in ~/.steam/x64/.
Yeah, that difference is probably as the libsteam_api is loaded from Mono (P/Invoked) whereas the steamclient.so is then loaded by native code from libsteam_api. Suppose the Mono code does have a manual lookup in different places of the game (as can sometimes be seen by a bunch of "could not find -somethinglib- in -some of the game subpaths_" whereas the native loading probably only depends on the OS mechanisms for finding libraries.

> Btw, I found out that everything works once you make a Linux build, upload it to steam and play it through steam client, no libraries are missing and steam API works just fine.
Of course, as the Steam API uses a running Steam instance if there is one. But that's no option for dedicated servers ;)

**Comment by rlabrecque** [comment]
I think `Steam_BConnected` or `Steam_BLoggedOn` are our best options, even if they return false at the time, should hopefully be enough to load it for steam_api.dll

**Comment by rlabrecque** [comment]
I hope this is fixed by https://github.com/rlabrecque/Steamworks.NET/pull/414 ? 🙏
