### ISSUE TITLE
New Steam Chat broke GetPlayerNickname

### ISSUE THREAD

**Issue by Tsury** [rlabrecque/Steamworks.NET#253]
Since the new update to Steam Chat, users have been introduced with a new way to display nicknames. 
The default setting completely hides the original name of the user, and only shows their nickname.
An additional setting allows to show the name and nickname side by side.

See the new settings here: https://gfycat.com/TiredTameAegeancat

Using the default settings, `GetPlayerNickname` will always return null, and `GetFriendPersonaName` will return the nickname.

Only when selecting the side-by-side setting will the API function as normal.
I don't know if it's even relevant to this project, but at least it may serve as an FYI.

**Comment by rlabrecque** [comment]
Interesting! Could you repost this on the Steam forums too? Trying to clean up issues here \o/
