### ISSUE TITLE
Steam overlay works but is invisible

### ISSUE THREAD

**Issue by feildpaint** [rlabrecque/Steamworks.NET#259]
My game is working with the correct steam build/depots, but when I activate the steam overlay, nothing appears. I know the overlay is working because it disables interaction with my game (which I can enable by pressing shift+tab again), and I can interact with the invisible over (like click and drag friends' pictures and the mouse cursor changes when hovering over a button).

**Comment by rlabrecque** [comment]
Hey @feildpaint, Steamworks.NET doesn't really interact in with the overlay in that way, this sounds like a more general Steam question for the Steamworks Developer forum. Are you doing anything interesting like rendering to a separate buffer first?
