### ISSUE TITLE
Unity 5: Some Callbacks never getting called (eg LobbyCreated_t, LobbyChatMsg_t)

### ISSUE THREAD

**Issue by topherredden** [rlabrecque/Steamworks.NET#26]
Steamworks SDK 1.31 64-bit
Steamworks.NET 5.0.0

I've verified the SteamAPI DLL is absolutely the correct version and size. I'm using the SpaceWar app ID.

When I run the example Steamworks.NET and create a lobby, the LobbyCreated_t Callresult is never called. However if I change it to a Callback it does get called, but the data in the structure seems invalid or uninitialised. It still creates and enters the lobby however.

Similarly if I create and enter a lobby, then use SendLobbyMsg the Callback LobbyChatMsg_t is never received.

A lot of the callbacks are working, but why are a few never getting called? I browsed through the Steam SDK and the headers don't indicate any change to the API that has slipped by.

**Comment by topherredden** [comment]
As a work-around switching the Calling convention from StdCall causes x64 version to work fine. Cdecl, or even enabling the THISPTR define (I noticed the Unity 64 condition which doesn't work atm due to no define by the editor).

**Comment by rlabrecque** [comment]
Woo good news, they actually just recently added UNITY_EDITOR_64 so I was able to fix up these issues!

Fixed up in commit: 6333a2c188cc16adfcf0aa09c520b1abc6a0c4e8
