### ISSUE TITLE
Steamworks SDK v1.42

### ISSUE THREAD

**Issue by Solarmender** [rlabrecque/Steamworks.NET#262]
New Steamworks SDK version released. Just wanted to notify you.

**Comment by KelsamGames** [comment]
v1.42 was released over a year ago.

![capture](https://user-images.githubusercontent.com/7027838/50732616-d5401480-113b-11e9-9b20-10cbe40b35f6.PNG)

**Comment by Solarmender** [comment]
Oh whoops. I read something wrong. My bad ill close this
