### ISSUE TITLE
Cannot launch game from Steam

### ISSUE THREAD

**Issue by smoroa14** [rlabrecque/Steamworks.NET#265]
I have the problem that I can't run my game from Steam, there is always the error "invalid app configuration". 
If I start the exe and Steam is closed the game runs, but it shouldn't.

I tried this Issue, but it didn't helped: ["https://github.com/rlabrecque/Steamworks.NET/issues/142"](https://github.com/rlabrecque/Steamworks.NET/issues/142)

What i have done:

* import the asset with the file "Steamworks.NET_12.0.0.unitypackage"
* add the SteamManager script to a empty GameObject in the startscene
* add the SetSteamId method from above and called it with the right id from the first row in Awake in the SteamManager script
* deleted the steam_appid.txt
* Deactivated "Display Resolution Dialog" (tried also with)
* downloaded SteamCLI and Steam SDK
* changed in sdk\tools\ContentBuilder\scripts\app_build_xxx.vdf
  --- appid
  --- depots -> id und filename
* changed in sdk\tools\ContentBuilder\scripts\debot_build_xxx.vdf
  --- DepotID
  --- ContentRoot
  --- LocalPath to ".\windows_content*"
* changed run_build.bat
  --- username password
  --- filename of app_build
* paste my project build in \content\windows_content
* run run_build.bat
* runns successfully
* published my changes in partner.steamgames.com
* downloaded my game from steam
* run it -> invalid app configuration error
* run the exe -> the game started and in steam friends i can see that i am in my game
  and the game knows my steam name
* In both i tried to open the steam overlay without success.
  Only if i run the game once in Unity and then build and run.

I also add a asset which i can see the console output in the build game and there is no error.

Please help

[Edit]
I tried to set the SteamManager script in the "Script Execution Order" on the top Position
-> helped nothing

**Comment by rafaelf82** [comment]
Did you properly set the launch option on steam ?

https://partner.steamgames.com/doc/sdk/uploading#Initial_Setup_New_App

**Comment by rlabrecque** [comment]
"Invalid app configuration" happens before your application is launched and doesn't require Steamworks SDK integration to get past. It's likely your launch options as rafaelf82 mentioned.

**Comment by Belegos** [comment]
In my case the "steam_appid.txt" with the appID was missing in the root directory. =)
