### ISSUE TITLE
SteamUGC.CreateItem callback not working.

### ISSUE THREAD

**Issue by rafaelf82** [rlabrecque/Steamworks.NET#266]
I'm trying to create an workshop item.

I already setup steam workshop according to the steam documentation, https://partner.steamgames.com/doc/features/workshop/implementation

The code (some parts removed for clarity) :

`
public class SteamWorkshopManager : MonoBehaviour
{
    private CallResult<CreateItemResult_t> OnCreateItemResultCallResult;

    void Start()
    {
        this.OnCreateItemResultCallResult = CallResult<CreateItemResult_t>.Create(this.OnCreateItemResult);
    }

    public void CreateItem()
    {
        SteamAPICall_t handle = SteamUGC.CreateItem(SteamUtils.GetAppID(), EWorkshopFileType.k_EWorkshopFileTypeCommunity);
        this.OnCreateItemResultCallResult.Set(handle);
        Debug.Log("SteamUGC.CreateItem(" + SteamUtils.GetAppID() + ", " + EWorkshopFileType.k_EWorkshopFileTypeCommunity + ") : " + handle);
    }

    private void OnCreateItemResult(CreateItemResult_t pCallback, bool bIOFailure)
    {
        Debug.Log("[" + CreateItemResult_t.k_iCallback + " - CreateItemResult] - " + pCallback.m_eResult + " -- " + pCallback.m_nPublishedFileId + " -- " + pCallback.m_bUserNeedsToAcceptWorkshopLegalAgreement);

        if (pCallback.m_eResult == EResult.k_EResultOK)
        {
            this.m_PublishedFileId = pCallback.m_nPublishedFileId;

            if (pCallback.m_bUserNeedsToAcceptWorkshopLegalAgreement)
            {
                //worked needs agreement
            }
            else
            {
                // item created successfully
            }
        }
        else
        {
            Debug.LogError(pCallback.m_eResult.ToString() + "  " + ("steamresult_" + (int)pCallback.m_eResult).TranslateNoError());
        }
    }`

The first debug.log on OnCreateItemResult is never called, the debug log at CreateItem works properly.

**Comment by rafaelf82** [comment]
I think I was missing SteamAPI.RunCallbacks();

It's working now with CallResult, but doesn't work with CallBack, I don't know why. Closing this issue.

**Comment by rlabrecque** [comment]
Hey @rafaelf82, functions that return `SteamAPICall_t` only work with CallResults (Specific Event Sinks), they don't produce Callbacks (Generic event sinks)

Glad you got it working though!
