### ISSUE TITLE
Requesting update for Steamworks SDK v1.43

### ISSUE THREAD

**Issue by KelsamGames** [rlabrecque/Steamworks.NET#268]
Requesting update for Steamworks SDK v1.43

Release details:
https://steamcommunity.com/groups/steamworks/announcements/detail/1751242076600910671

Namely, I need to take advantage of the new ISteamInput (new ISteamController) interface, it's updated enums, etc.

**Comment by KelsamGames** [comment]
Sorry about the derpiness on this issue's status. I don't use github that often.

**Comment by Arugin** [comment]
Yes, it would be great.

**Comment by rlabrecque** [comment]
This is on my calendar for Saturday!

**Comment by rlabrecque** [comment]
Done in: https://github.com/rlabrecque/Steamworks.NET/commit/3b370edd1404dbbdd99ec042089a95495913c48d \o/

Note that there's been limited testing of the new APIs so far.

**Comment by KelsamGames** [comment]
Thank you! :) This is going to help a lot
