### ISSUE TITLE
Missing ISteamInput?

### ISSUE THREAD

**Issue by KelsamGames** [rlabrecque/Steamworks.NET#270]
I don't see the implementation of the new ISteamInput API. I assume I'm just misunderstanding its implementation, since I see a couple SteamInput types (InputHandler_t and such), but it would appear that the actual SteamInput.Init()... etc is missing from the v1.43 implementation. The ISteamInput API is meant to replace ISteamController API (while still keeping the old one for backwards compatibility I guess), but new bug fixes and such will only be further developed for the ISteamInput API, so I need to be able to access that. Please advise :)

**Comment by KelsamGames** [comment]
Update: Looks like isteaminput.cs is in Plugins>autogen, the VS Solution in Standalone was just missing the link to it so it wasn't being compiled into the DLL. Easy fix, but should probably update the github version of Standalone :)

**Comment by rlabrecque** [comment]
Good call thanks!

**Comment by rlabrecque** [comment]
It's in: 3eeebd8af0e30a47c8b12694f17fe41f54a6867b
