### ISSUE TITLE
Steamworks Init Question

### ISSUE THREAD

**Issue by xelanoimis** [rlabrecque/Steamworks.NET#273]
Hi,

I saw the initialization flow in SteamworksManager.cs and, if the game was not started through the Steam client, it is quit (tested with RestartAppIfNecessary). However if the SteamAPI.Init fails, the application continue (without Steam support).

I wonder if this is correct. Or if we should quit the game id SteamAPI.Init fails too?

The case I imagine is that someone may copy the game from a friend, and add the file with the appID next to the executable (like developers do) and this would bypass the check from RestartAppIfNecessary. Then, SteamAPI.Init fails (because no steam client, and appID not owned anyway). If the app doesn't quit here, the player will play the game, without Steam features.

I saw a lot of people complaining the game doesn't start because of steamworks initialization. I don't want to cause problems to players but I don't want to make it too easy for pirating either.

So, should we quit the game if SteamAPI.Init fails?
Thanks!

**Comment by rlabrecque** [comment]
It's up to you and your game. The game I'm working on currently we have decided to require successful initialization.

**Comment by xelanoimis** [comment]
I guess quitting if init fails is useful as DRM if you don't have other solution for this. But if the game makes sence without Steam features, is there other advantages to quit (beside antipiracy). And are there any risks for true customers who might not be able to play in some particular circumstances?
