### ISSUE TITLE
ActivateGameOverlayToStore is working wrong.

### ISSUE THREAD

**Issue by PirateParrotSoftware** [rlabrecque/Steamworks.NET#274]
I'am using the following code:

SteamFriends.ActivateGameOverlayToStore(new AppId_t(SteamworksSettingsHolder.PurchaseAppId), EOverlayToStoreFlag.k_EOverlayToStoreFlag_AddToCartAndShow)

Expected result:
- General license has been added to the cart.

Result:
- Comercial license has been added to the cart.

Is there a chance I am doing something wrong?

**Comment by rlabrecque** [comment]
Did you ever figure this out?

I'm closing this because it seems like more of a general Steamworks question which should be asked on the Steamworks Developer Discussion board: https://steamcommunity.com/groups/steamworks
