### ISSUE TITLE
SteamManager.Initialized is never true

### ISSUE THREAD

**Issue by csanszan1** [rlabrecque/Steamworks.NET#277]
I'm trying to make a dedicated server to my game with Steam, without Unity, but SteamManager.Initialized always returns with false.
[Program.zip](https://github.com/rlabrecque/Steamworks.NET/files/3144813/Program.zip)

**Comment by rlabrecque** [comment]
SteamManager is Unity specific, it's gameplay code and uses Unity's Monobehaviour system etc.
