### ISSUE TITLE
Missing Executable and "DirectoryNotFoundException"

### ISSUE THREAD

**Issue by Meilha** [rlabrecque/Steamworks.NET#278]
When I try to upload a new build to Steam, the build does not work and displays an error saying that there is a missing executable. This doesn't happen unless I include Steamworks.NET 12.0.0 in my project.

Additionally, when I make my build I get an error as shown below, which could potentially be linked to my other problem.

![Screenshot (14)](https://user-images.githubusercontent.com/50975207/58299568-36901980-7da5-11e9-8dd8-5ca3472a5106.png)

**Comment by dglwilkins** [comment]
I'm currently getting the same issue when trying to build to Linux

**Comment by rlabrecque** [comment]
Thanks! Building Linux helped figure this out!

**Comment by Meilha** [comment]
Uh, this issue was closed before a solution was proposed, I’m not sure why.

Anyways, in case anyone gets this issue, I was able to fix this problem by using an older version of steamworks.net, it was only 12.0.0 that wasn’t working for me.

**Comment by rlabrecque** [comment]
Yep, it was fixed in: https://github.com/rlabrecque/Steamworks.NET/commit/9e168dfd46e382a2041ce73d174c4307d2447bb4
