### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by chull434** [rlabrecque/Steamworks.NET#279]
Hi,
We just released are game, Interstellar Transport Company on steam and are now getting a load of unity crash reports, game has been in early access for a while now and haven't seen these crashes before.

stack traces don't have much detail to go off, mostly I don't know what I am even looking at, only thing I am seeing is "CSteamworks"

Have a load of other crash reports that might have other information you need, let me know, thanks 

`Native StackTrace:

Thread 0 (crashed)
0   ntdll                              0x0000000076ea9e3a <system symbols missing> 
1   KERNELBASE                         0x000007fefca31420 <system symbols missing> 
2   kernel32                           0x0000000076d30260 <system symbols missing> 
3   UnityPlayer                        0x000007fed60f231d <system symbols missing> 
4   UnityPlayer                        0x000007fed60f23ce <system symbols missing> 
5   UnityPlayer                        0x000007fed6101768 <system symbols missing> 
6   kernel32                           0x0000000076dbb9b0 <system symbols missing> 
7   ntdll                              0x0000000076eb9015 <system symbols missing> 
8   ntdll                              0x0000000076e97388 <system symbols missing> 
9   ntdll                              0x0000000076eabf7d <system symbols missing> 
10  ntdll                              0x0000000076e8043a <system symbols missing> 
11  ntdll                              0x0000000076eab61e <system symbols missing> 
12  steam_api64                        0x00000001800210d0 <system symbols missing> 
13  CSteamworks                        0x000007fee510a5e3 <system symbols missing> `

**Comment by rlabrecque** [comment]
Did you ever figure out what this was?

CSteamworks/seam_api64 could show up in the case of a Steam callback given that we see UnityPlayer further down the stack trace. I suspect those are SteamAPI_RunCallbacks, with the first UnityPlayer stack frame being OnRunCallback/OnRunCallResult in CallbackDispatcher.cs
