### ISSUE TITLE
SteamUGC.GetSubscribedItems doesn't work

### ISSUE THREAD

**Issue by BrianMacIntosh** [rlabrecque/Steamworks.NET#28]
As I noted in [this discussion thread](http://steamcommunity.com/groups/steamworks/discussions/9/622954023412814452/), SteamUGC.GetSubscribedItems doesn't work - it never populates any items into the passed array.  I was able to get it to work on my end by applying the [Out] attribute to the p/invoke call:
`public static extern uint ISteamUGC_GetSubscribedItems([Out] PublishedFileId_t[] pvecPublishedFileID, uint cMaxEntries);`

I'm filing an issue rather than a pull request because I'm not too familiar with p/invoke and I'm not sure this is completely the right thing to do, but it fixed this issue for me.

Thanks for your wrapper, it's be very easy to implement in general!

**Comment by kinifi** [comment]
This has been causing me to go insane over the last week. I couldn't figure it out. Thank you

**Comment by rlabrecque** [comment]
This is quite scary as I've had no trouble with it for quite a long time. I went ahead and applied [In, Out] to all array arguments just to be on the safe side, hopefully preventing any future issues.
