### ISSUE TITLE
SetModDir summary incorrect

### ISSUE THREAD

**Issue by malkere** [rlabrecque/Steamworks.NET#280]
```
		/// <summary>
		/// <para>/ If your game is a "mod," pass the string that identifies it.  The default is an empty string, meaning</para>
		/// <para>/ this application is the original game, not a mod.</para>
		/// <para>/</para>
		/// <para>/ @see k_cbMaxGameServerGameDir</para>
		/// </summary>
		public static void SetModDir(string pszModDir) {
```
I believe this is incorrect. Navigating to the Dedicated Server section of Steamworks there is an input field for "Product Name" with a tooltip next to it. The tooltip says this is your modDir and needs to be passed to Steam. I had this populated with my game's name from day 1, and believing this summary left it blank in Steamworks.NET and was never able to get a server to show up on the internet list. Once I set the modDir to match my Product Name it immediately showed up on the internet server list.

**Comment by rlabrecque** [comment]
Those descriptions are automatically generated from Valve's C++ headers, unfortunately it's wrong there as well and I'm not in a position to rewrite them currently.
