### ISSUE TITLE
Getting a timeout error when sending P2P packets to a server

### ISSUE THREAD

**Issue by benjaben** [rlabrecque/Steamworks.NET#281]
So I'm trying to setup a dedicated server system. On my client I'm calling the following:

```
bool sent = SteamNetworking.SendP2PPacket(m_GameServers[i].m_steamID, data, (uint)data.Length, EP2PSend.k_EP2PSendReliable, 1);
                        
if(!sent)
{
    Debug.LogError("Failed to send packet to " + m_GameServers[i].m_steamID.m_SteamID);
}
```

This seems to be sending fine. I never get the error message. On my server I see the request and do the following:

```
private void OnP2PSessionRequest(P2PSessionRequest_t pCallback)
{
    if(SteamNetworking.AcceptP2PSessionWithUser(pCallback.m_steamIDRemote))
    {
        Debug.Log("Accepted P2P Session Request from " + pCallback.m_steamIDRemote.m_SteamID);
    }
}
```

This also seems to be working fine. The request goes through and I get the log saying it was accepted.

But then on the client this callback is firing
```
private void OnP2PSessionConnectFail(P2PSessionConnectFail_t response)
{
    Debug.Log("Failed to connect to " + response.m_steamIDRemote + " with error code: " + (EP2PSessionError)(response.m_eP2PSessionError));
    SteamNetworking.CloseP2PSessionWithUser(response.m_steamIDRemote);
}
```

The error code I'm getting here is: "k_EP2PSessionErrorTimeout"

I can't seem to find any information on this error other than it suggesting that the server didn't accept the request. Am I missing another step?

**Comment by benjaben** [comment]
It seems to be some kind of issue with the dedicated server system. I think I need to be testing through SteamCMD

**Comment by rlabrecque** [comment]
Hey benjaben, closing this issue as part of cleaning up, especially now that I believe those interfaces are largely deprecated.
