### ISSUE TITLE
Why all Leaderboard would always returns 72009 score value !

### ISSUE THREAD

**Issue by vencious** [rlabrecque/Steamworks.NET#282]
Hi, i am just trying to integrate steamworks in Unity and i can successfully Find leaderboards by name and add scores to them. I can see that in the Leaderboards stats in the steamworks website score values are correct. However if i want to download all the entries ( currently it's only mine entry ), "LeaderboardEntry.m_nScore" always returns a value of 72009. I entered the game id in steam_appid.txt and also changed it in the SteamManager as it should be. Is this any known behavior or i am probably doing something wrong. The leaderboard name is correct, but the number of the score entry is always that number of 72009. 

The callback i am using it like this and i am creating a new **private CallResult<LeaderboardScoresDownloaded_t> m_callResultDownloadScore;** variable to set the callback. Tested in Unity 2019.2 and Unity 2018.3.1 f11

```
void OnDownloadScore(LeaderboardScoresDownloaded_t pResult, bool bIOFailure)
    {
        if(!bIOFailure)
        {
            console.text += "\n" + ("Leaderboars name is: " + SteamUserStats.GetLeaderboardName(m_CurrentLeaderboard));

            SteamLeaderboardEntries_t m_nLeaderboardEntries = new SteamLeaderboardEntries_t( (ulong)Mathf.Min(pResult.m_cEntryCount, 10) );
            for (ulong i = 0; i < m_nLeaderboardEntries.m_SteamLeaderboardEntries; i++)
            {
                LeaderboardEntry_t LeaderboardEntry;
                
                if (SteamUserStats.GetDownloadedLeaderboardEntry(m_nLeaderboardEntries, 0, out LeaderboardEntry, null, 0))
                {
                    console.text += "\n" + LeaderboardEntry.m_cDetails;
                    console.text += "\n" + LeaderboardEntry.m_hUGC;
                    console.text += "\n" + LeaderboardEntry.m_nGlobalRank;
                    console.text += "\n" + LeaderboardEntry.m_nScore;       // always returns 72009
                    console.text += "\n" + LeaderboardEntry.m_steamIDUser;
                }
            }
        }
    }
```

**Comment by vencious** [comment]
It turns out the code only shows the value that has been requested first and then continue shows the same value until steam is restarted and then behavior is the same, only returns the first requested value until steam client is restarted again !

**Comment by DrGurka** [comment]
Instead of creating a new object of SteamLeaderboardEntries_t you should use the method  [GetDownloadedLeaderboardEntry](https://partner.steamgames.com/doc/api/ISteamUserStats#GetDownloadedLeaderboardEntry) to get info about the current leadboard

**Comment by vencious** [comment]
I thought i am using a wrong data but couldn't figure it out. I copied from some examples.
Got it working. Really much appreciate your help !
