### ISSUE TITLE
Invalid dll version

### ISSUE THREAD

**Issue by GkqqNkKC** [rlabrecque/Steamworks.NET#283]
I tried to install Steamworks.NET using NuGet. After getting it, I downloaded the prebuilt standalone, copied the 2 dlls related to my machine architecture, and when running I get the following error on `SteamApi.Init()`:

    System.Security.VerificationException: 'steam_api64.dll is the wrong version! Expected <3.62.82.82>, FileVersion <4.28.51.7>'

It should be something easy to solve but I'm a beginner at solving dependencies.

**Comment by DrGurka** [comment]
I didn't know there was a nuget packet. Could you link me to it?

**Comment by DrGurka** [comment]
That is a different project targeting a older version of steamworks sdk. If you want to use this project follow the install instructions [here](http://steamworks.github.io/installation/)

**Comment by GkqqNkKC** [comment]
Sry for late reply. Got it working, thx.
