### ISSUE TITLE
steam_api64.dll hangs on when changing git branches

### ISSUE THREAD

**Issue by stadoblech** [rlabrecque/Steamworks.NET#286]
(Unity) Here is problem: I have "develop" branch on git where i keep multiplatforms changes. In develop branch there is no steam api, only core game. Im using it for adding features, bugfixes etc. I have "STEAM" branch for steam platform. In that branch i keep steamworks.net, also other PC port related stuff. Whenever i change branch from "STEAM" to "develop", my file status says that i have unstaged files: Assets\Plugins.meta, Assets\Plugins\x86_64\steam_api64.dll, Assets\Plugins\x86_64\steam_api64.dll.meta and Assets\Plugins\x86_64.meta. Weird, it should not doing that but ok. Problem is, whenever i remove these files it always brings back Assets\Plugins\x86_64\steam_api64.dll . It will never remove. If i try to remove it from files explorer, it says that it cannot be removed because its used by other process(unity editor). So i cannot simply change branch (git overwriten error will poppup), i cannot remove steam_api64.dll (it always come back), only way to fix this issue is turn off unity, remove files manually and change git branch and restart unity. It does not happen if i change branch BEFORE i run game from editor in "STEAM" branch. Is there any fix for this annoyance? 
It does only for Assets\Plugins\x86_64\steam_api64.dll, Assets\Plugins\x86\steam_api.dll causes no problem at all

**Comment by rlabrecque** [comment]
I'm not sure how much can be done about this. Unity is loading the DLLs and just never unloads them until it quits.
