### ISSUE TITLE
Unity 2019.2 missing Mono folder for steam_api64.dll

### ISSUE THREAD

**Issue by starmindfr** [rlabrecque/Steamworks.NET#287]
Hello all is working fine in unity 2018 but after upgrading to 2019.2.0b7 the build run fine but on steam dll are all missing 

Fallback handler could not load library H:/SteamLibrary/steamapps/common/Su Hack/suhack_Data/Mono/steam_api64
Fallback handler could not load library H:/SteamLibrary/steamapps/common/Su Hack/suhack_Data/Mono/steam_api64.dll

Hotfix : add a Mono folder before sending file to steam build and move DLL steam_api64.dll

NB : 
- I am using the steam app valid key check if this have any link. 
- The source steam_api64.dll is still inside /plugins but steam is looking inside /mono

**Comment by dumearts** [comment]
Hi, I have the same issue, I tried the solution of #349 but still doesn't work for me. I'm using Unity 2018.4 ...

**Comment by rlabrecque** [comment]
Hopefully what ever this was is fixed with https://github.com/rlabrecque/Steamworks.NET/pull/414
