### ISSUE TITLE
Linux 64 bit: GameServer.Init crashing / LogOnAnonymous () not succeeding

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#29]
Hi there,

just posting this here so it's also known for others. Still not sure where it fails but earlier when calling GameServer.Init on a 64 bit Linux Unity build the game would simply crash. That seems to have been fixed (maybe a Steam client update or Unity update) so it does no longer crash.

Current state is that GameServer.Init() returns true but after calling SteamGameServer.LogOnAnonymous() and SteamGameServer.BLoggedOn() never returns true. This does work on all other tested platforms with the same code (MacOS 32, Win32, Win64, Linux 32) and even works with using SteamAPI with a native test app.

Unity test project: http://illy.bz/tmp/LinuxCrashTest.tar.bz2
Minimum working example for native C++: http://illy.bz/tmp/LinuxNativeTest.cpp

May as well be a problem in SteamAPI / SteamClient itself but as the native code works as well as the 32 bit build I'm not completely sure on this part.

Regards,
Chris

PS: Other than that issue it's really a great piece of software, works flawlessly as long as you don't forget to actually create the callbacks you want to get called ;)

**Comment by CapnAndy** [comment]
I'm still seeing a crash in Linux, except in the "Safe Init" function. No other relevant or helpful information. :( I'm using a SteamMachine for dev testing.

**Comment by Alloc86** [comment]
Safe Init of GameServer or the client Steam API?
Crash on GameServer.Init (which is actually the Safe version) was what I saw on some versions, not sure what made it "work" though. I suppose it's some versions of Unity that had this problem.

**Comment by hlop** [comment]
still no solution?

**Comment by Alloc86** [comment]
Nothing I know of. Unity5 doesn't change it either. I wouldn't mind that everyone who's got that problem would bug Valve on the forum, in this case http://steamcommunity.com//groups/steamworks/discussions/13/619569341053167298/#p2
;)

**Comment by hlop** [comment]
The Steam-Group is private, i can't join it.

**Comment by hlop** [comment]
I need 64 Bit. 32 Bit is stupid. I don't know why they don't bring a patch for 64 Bit. 32 Bit is out of date.

**Comment by Alloc86** [comment]
Well, if you are using the Steamworks API you must be a Steam dev. If you are a Steam dev you are allowed to view that group ;)
Also it's not 64 bit SteamAPI that's broken itself but the combination of SteamAPI + Steamworks.NET (not sure if this has anything effect in that equation though) + Unity3D. SteamAPI itself on a native Linux 64 bit build is fine.

**Comment by martindevans** [comment]
> Well, if you are using the Steamworks API you must be a Steam dev. If you are a Steam dev you are allowed to view that group ;)

That's not true actually. If you've paid for Greenlight you get access to the SDK but *not* access to the developer group :(

**Comment by gamenew09** [comment]
@martindevans Not according to me being able to log into without greenlight.

**Comment by martindevans** [comment]
It sounds like you have SDK access through some other non-green light channel? What I said only affects green light Devs who have not yet been greenlighted.

**Comment by gamenew09** [comment]
@martindevans I've gotten it directly through the partner website.

**Comment by martindevans** [comment]
I just found a post on the greenlight forum which clarifies who has access to the steamworks dev group, according to Alden (steam employee) on [this thread](http://steamcommunity.com/groups/greenlightbeta/discussions/0/617329505859864384/) (requires greenlight discussion group access to view):

 > You need to complete the digital paperwork, including the Steam Distribution Agreement, and create your app within Steamworks before you can join the group.

So that explains it. I'm a greenlight dev but I haven't done that stage yet.

**Comment by raphaelbaldi** [comment]
Same happens to us. We were trying to get Ballistic Overkill to Linux but couldn't do so. We're currently seeing LogOnAnonymous timed out errors when trying to create a server. Is it an issue on the Steam API, Steamworks.NET or both?

**Comment by Alloc86** [comment]
It seems like this issue is fixed with one of the latest Steam client updates. Copy over the latest steamclient.so from your Steam installation (typically ~/.local/share/Steam/linux64/) to the <yourgame>_Data/Plugins/x86_64/ folder of the game and see if it helps. At least with 5.3.3p2 builds of our game this seems to be fine (but it is fixed by the steamclient-update as updating only Unity didn't change anything).

If there's any confirmation on this fix I suppose we can finally close this ticket :)

**Comment by raphaelbaldi** [comment]
Hey there, sorry for not replying earlier. We'll try your workaround and get back to you as soon as possible ;)

**Comment by rlabrecque** [comment]
Still working @Alloc86? Did it work for you @raphaelbaldi?

I'm closing this for now, hopefully for good!
