### ISSUE TITLE
SteamMatchmaking.SetLobbyGameServer only triggers callback once per lobby

### ISSUE THREAD

**Issue by XaeroDegreaz** [rlabrecque/Steamworks.NET#290]
My use-case is:

1. Players join a friend's lobby
2. Party leader calls `SteamMatchmaking.SetLobbyGameServer` to set the address of the server
3. Callback gets triggered, and all players launch into the game
4. Players complete the game, and return to the "staging scene"
5. Party leader calls `SetLobbyGameServer` again, and nothing happens

I can also recreate this issue by calling `SetLobbyGameServer` every few seconds and looking for a callback to trigger.

Could this be an issue with Steamworks.NET, or is this something to do with Steam? Are we only allowed to set the game server once per lobby?

I don't want to have all players leave the Steam lobby when joining a game, because then everyone needs to get re-invited to a new one.

I could, but I'd rather not, resort to using `SteamMatchmaking.SetLobbyData` to store the server information. However there are some tricky edge-case surrounding the accidental replaying of that data, it's more maintenance, and I'd prefer to use the method dedicated to this purpose.

**Comment by rlabrecque** [comment]
I think this is a Steamworks issue unfortunately. I'm going to close this as part of cleaning up around here.
