### ISSUE TITLE
SteamApps.GetCurrentGameLanguage() returns empty

### ISSUE THREAD

**Issue by MrCharli3** [rlabrecque/Steamworks.NET#291]
Any idea why SteamApps.GetCurrentGameLanguage() returns empty when I try to Debug.Log it?

Can it not be used from inside Unity editor?

**Comment by rlabrecque** [comment]
I'm seeing that as well. I'm wondering if it doesn't work unless launched from the Steam client, or if it's just outright broken. The implementation in Steamworks.NET looks correct, and "GetAvailableGameLanguages" is returning correctly.

**Comment by rlabrecque** [comment]
I believe this ended up being a Steamworks bug?
