### ISSUE TITLE
Unity 2019.2 no longer supports 32 bit linux

### ISSUE THREAD

**Issue by Linnun** [rlabrecque/Steamworks.NET#293]
It looks like Unity 2019.2 no longer supports 32 bit versions of linux. The project is filled with warnings like:

> Assets\Editor\Steamworks.NET\RedistCopy.cs(34,8): warning CS0618: 'BuildTarget.StandaloneLinux' is obsolete: 'StandaloneLinux has been removed in 2019.2'
> Assets\Editor\Steamworks.NET\RedistCopy.cs(39,8): warning CS0618: 'BuildTarget.StandaloneLinuxUniversal' is obsolete: 'StandaloneLinuxUniversal has been removed in 2019.2'

Consider dropping support for Linux 32 bit in the next version to avoid those warnings.

**Comment by KelsamGames** [comment]
Steamworks.NET is used for more than just Unity. Unity users can simply choose to not use the Linux x86 build. There is no reason to drop support for it entirely.

**Comment by Linnun** [comment]
I see. The thing is that currently it throws alot of warnings in the Unity Editor though because it refers to invalid BuildTargets.
I created a pull request which should fix those warnings for Unity 2019.2+ while not changing compatibility with older Unity versions or non-Unity projects.

**Comment by Arugin** [comment]
+1
