### ISSUE TITLE
SteamUserStats.DownloadLeaderboardEntriesForUsers() returning 0 entries.

### ISSUE THREAD

**Issue by spraycanmansam** [rlabrecque/Steamworks.NET#297]
Hi,

We are trying to download the leaderboard entry for our user like so:
`var userIDs = new CSteamID[] { SteamUser.GetSteamID() };
SteamAPICall_t request = SteamUserStats.DownloadLeaderboardEntriesForUsers(new SteamLeaderboard_t(leaderboard.Id), userIDs, userIDs.Length);`

It returns 0 entries event though we can see an entry for our user in the Steam web interface. The leaderboard is not set to 'Trusted'. Confirmed the leaderboard id correct. We've tried various methods to retrieve data for our user and they all return zip (GlobalAroundUser not working either...).

Thanks.

**Comment by rlabrecque** [comment]
Did you ever figure this out?
