### ISSUE TITLE
IsSteamRunning() doesn't work on Linux

### ISSUE THREAD

**Issue by MaximSchoemaker** [rlabrecque/Steamworks.NET#30]
I use IsSteamRunning() to check if I should execute Steamworks code when I need it (better than try catching everything :P). I was wondering if this is a correct usage, or if I should use the result of SteamAPI.Init() to determine whether to run additional Steamworks code?

Anyway, that works fine on Windows, but on Linux (Ubuntu) IsSteamRunning() seems to always return true, even if the Steam client is not running and SteamAPI.Init() returns false.

**Comment by rlabrecque** [comment]
I'd definitely recommend using the result of SteamAPI.Init() for that, there are times where IsSteamRunning() would return true, and SteamAPI.Init() would return false.
Are you using Unity? If so I'd actually use the [SteamManager](https://github.com/rlabrecque/SteamManager/blob/master/SteamManager.cs) MonoBehavior instead.

I wasn't actually able to replicate this issue though. Using a simple test it seemed to work fine:
![image](https://cloud.githubusercontent.com/assets/2047188/5971062/510a697c-a803-11e4-8a41-f39a69988a6d.png)

**Comment by MaximSchoemaker** [comment]
I have the same problem on certain Windows PC's. We're running a beta right now and whenever the game crashes on anyone's PC I get an automated email with the log and crash report. I've received reports like this multiple times:

17:25:01.657 ||   ! could not init SteamAPI!
17:25:01.658 ||   > steamAPI is running
17:25:01.658 ||   ! exception during load content: Steamworks is not initialized.
17:25:02.021 ||   Stack trace:    at Steamworks.InteropHelp.TestIfAvailableClient()
   at Aril.MainController.Init()
   at Aril.Main.LoadContent()

The "SteamAPI is running" log comes from this code:

if (SteamAPI.IsSteamRunning() )
{
ConsoleSingleton.WriteLine("> steamAPI is running");
}

**Comment by MaximSchoemaker** [comment]
Oh wait! Nvm, I get it. Like you said, it is possible for IsSteamRunning to be true while the init failed. These testers will all have the Steam client running, but something else is going wrong then. Is there a way to figure out why the SteamAPI.Init() failed?

**Comment by rlabrecque** [comment]
Sometimes it gives you good info in stdout, like when I ran it from the console in the picture above.

The only real documentation I have for that is this comment:
https://github.com/rlabrecque/SteamManager/blob/master/SteamManager.cs#L74

I would probably stop using IsSteamRunning() all together, it doesn't really help with anything.

**Comment by MaximSchoemaker** [comment]
k, thx. I'll check it out :)
