### ISSUE TITLE
Beacon don't work properly

### ISSUE THREAD

**Issue by NicholasFalcone** [rlabrecque/Steamworks.NET#300]
Hi,
I'm a game developer, I currently working on Unity and I try to create a party using the creation of a beacon of your framework, but currently I'm stuck with a weird problem.
When I create a beacon I will never receive the callback.
I search on the documentation but it still not clear what is the problem, I follow all the instruction but nothing is change.
I leave the snippet of my code where I try on 2 different way to receive the callback of the creation of the beacon.
I hope someone can help me to resolve this problem.

Thank you
Cheers
Nicholas

` using System;
using Steamworks;
using UnityEngine;
   public class PartyManager : MonoBehaviour
    {
        /// <summary>
        /// Party Callback
        /// </summary>
        private CallResult<CreateBeaconCallback_t> m_beaconCreated;
        private Callback<CreateBeaconCallback_t> m_beaconCreate;
        private Callback<ReservationNotificationCallback_t> m_reservation;
        private PartyBeaconID_t m_partyId;
        private SteamPartyBeaconLocation_t m_location;
        private uint m_partySize = 4;

        private void Start()
        {
            m_beaconCreated = CallResult<CreateBeaconCallback_t>.Create(OnBeaconCreated);
            m_beaconCreate = Callback<CreateBeaconCallback_t>.Create(OnBeaconCreate);
            m_reservation = Callback<ReservationNotificationCallback_t>.Create(OnUserJoinParty);
        }

        private void OnUserJoinParty(ReservationNotificationCallback_t param)
        {
            Debug.Log("User joined");
            SteamParties.OnReservationCompleted(param.m_ulBeaconID, param.m_steamIDJoiner);
        }

        private void CreateGroup()
        {
            if (SteamParties.GetAvailableBeaconLocations(out m_location, SteamParties.GetNumActiveBeacons()))
            {
                SteamAPICall_t t = SteamParties.CreateBeacon(m_partySize, out m_location, SteamNetworkManager.Instance.LobbyID.ToString(), "aaaaaa");
                m_beaconCreated.Set(t, OnBeaconCreated);
            }
        }
        private void OnJoinParty(JoinPartyCallback_t param, bool bIOFailure)
        {
            Debug.Log(param.m_ulBeaconID);
        }
        private void OnBeaconCreated(CreateBeaconCallback_t param, bool p)
        {
            Debug.Log(param.m_ulBeaconID);
        }
        private void OnBeaconCreate(CreateBeaconCallback_t param)
        {
            Debug.Log(param.m_ulBeaconID);
        }
}`

**Comment by rlabrecque** [comment]
I pushed out some changes in https://github.com/rlabrecque/Steamworks.NET/commit/3cfb06a163b592849dbf354552a32823ffae07f8

But I couldn't get it working in my test application. GetNumAvailableBeaconLocations only ever returns 0 for me on AppId 480 (Spacewar). Not sure if it's just not enabled on spacewar or what.

The tests are available here, maybe you'll have better luck with it?
https://github.com/rlabrecque/Steamworks.NET-Test
