### ISSUE TITLE
Nested api callresult callbacks getting lost

### ISSUE THREAD

**Issue by spajus** [rlabrecque/Steamworks.NET#302]
I'm trying to implement some Steamworks API use cases in a stateless way, like this:

```
private static void FindOrCreateLeaderboard(string leaderboardName, ELeaderboardSortMethod sortMethod, ELeaderboardDisplayType displayType, Action<SteamLeaderboard_t, bool> callback) {
    var apiCall = SteamUserStats.FindOrCreateLeaderboard(leaderboardName, sortMethod, displayType);
    var result = new CallResult<LeaderboardFindResult_t>();
    result.Set(apiCall, (res, isFailure) => {
        callback(res, failure);
    });
}
```

In `callback` I can pass another method which also makes some Steamworks.NET API call, and does something inside a callback, resulting in nested calls to Steam API.

The problem is that 60% of the time it works all the time. For the rest 40%, callbacks are never called, no errors are shown, callbacks just get lost.

I have to add that I often run those inside coroutines, and multiple coroutines can be running multiple calls.

Is it the issue of thread safety, callbacks getting executed on non-Unity threads, anything like that? 

@rlabrecque perhaps you have an idea what could be happening?

**Comment by rlabrecque** [comment]
When `result` gets GC'd that lambda won't get called anymore

**Comment by spajus** [comment]
That could be the case. I started tracking call and result state in a separate coroutine using `SteamUtils.IsAPICallCompleted` and `CallResult.IsActive`, and everything seems to be working properly.

**Comment by spajus** [comment]
Closing the issue, as keeping `CallResult` alive solves it completely. I believe the fact that GC can silently kill the callback could be worth mentioning in FAQ.
