### ISSUE TITLE
macOS Notarization

### ISSUE THREAD

**Issue by rlabrecque** [rlabrecque/Steamworks.NET#305]
Some work needs to be done to get macOS Notarization working, it's unclear what that is exactly.

When we do this we will likely assume that we're running on a modern version of Steam and macOS.

Steam minimum OS level: macOS 10.11 ("El Capitan")
64 bit only: https://support.apple.com/en-us/HT208436

Open questions:

- What is the oldest stable version of Unity that supports macOS Notarization out of the box?
- What work needs to be done? (Someone mentioned renaming the steamapi.dylib to steamapi.bundle. Steam 2019.2(?) supports loading .dylibs natively without renaming them as well.)
- Objections?

**Comment by Alloc86** [comment]
My first question would be: Has anyone actually confirmed that notarization is *required* when running an app *from Steam*?
Officially it was already required before to sign (or notarize? not sure) your app if you wanted to run it manually without having to do the right-click>open bullshit, and so far I haven't found a place that definitely says "10.15 *requires* notarization", even less so a place that says it would also affect running from Steam :)

(Can't test myself as the only macOS device I have won't be updated in a long time as I want to be able to easily compile against older library versions ...)

**Comment by rlabrecque** [comment]
There's this, but I agree, this isn't super clear.
https://steamcommunity.com/groups/steamworks/announcements/detail/3632639303428097613

**Comment by Alloc86** [comment]
Yeah, read this and the linked Apple documents (as well as a bit of google search), but nothing said "you need it", only "you can do it".

Still hoping it's not actually a requirement as the added overhead on the workflows would probably stop a lot of devs bringing their games to macOS. Doubt we would continue with that too. Uploading every 10+ GiB build to Apple, regularly paying money, vast extensions to the build workflows ... Don't see that worth it actually. And that's from someone who's always fought for supporting as many platforms as possible :(

**Comment by Alloc86** [comment]
Had a friend test our game on macOS 10.15 (beta 11) and starting our non-signed and non-notarized  game was a non-issue (Unity, if that makes a difference), neither from Steam nor directly from the .app-Folder.
Obviously might change in a future version, but so far it seems like Apple just confused people.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/issues/312

**Comment by berMip** [comment]
Are there any news on this issue? I managed to solve most of the sandbox problems by using entitlements (most of them listed here: https://www.reddit.com/r/gamedev/comments/di61ms/have_a_mac_game_on_steam_heres_a_guide_to_signing/) but the library still fails to initialize properly (SteamAPI.Init()). I didn't find any further logs that might pinpoint to the actual issue.

Are there any entitlements that are missing? Does anyone know what the actual issue is?

**Comment by rlabrecque** [comment]
This should be completely resolved now with https://github.com/rlabrecque/Steamworks.NET/commit/53758506856db59ac41b0eef900e43416902ec68
