### ISSUE TITLE
SteamInventory.GetResultItems issue

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#309]
You should be able to call SteamInventory.GetResultItems passing a null array in, this according to documentation and in your tests is how you get the count of items returned via the referenced out items array size paramiter.

However:
In testing we get a null reference exception when calling for example `SteamInventory.GetResultItems(param.m_handle, null, ref count)` this occurs on line 44 of isteaminventory.cs which is 
`public static bool GetResultItems(SteamInventoryResult_t resultHandle, SteamItemDetails_t[] pOutItemsArray, ref uint punOutItemsArraySize) {
			InteropHelp.TestIfAvailableClient();
            if (pOutItemsArray.Length != punOutItemsArraySize)
            {
                throw new System.ArgumentException("pOutItemsArray must be the same size as punOutItemsArraySize!");
            }
            return NativeMethods.ISteamInventory_GetResultItems(CSteamAPIContext.GetSteamInventory(), resultHandle, pOutItemsArray, ref punOutItemsArraySize);
		}`

This assumes that pOutItemArray will not be null which is incorrect it can be null in the event the caller is trying to assertane the count of items to be retrieved.

We tested this by commenting out the if statement that starts on line 44 and the call did work as expected.

**Comment by rlabrecque** [comment]
Ugh, thanks for the heads up

https://github.com/rlabrecque/Steamworks.NET/commit/370f8588a09cd5b755ee29051324a44b09466757

This commit broke it, was trying to use the STEAM_ARRAY defines in the Steam headers, but :/

**Comment by JamesMcGhee** [comment]
Think we have a workaround that will do for now.

we are simply passing it a large array (bigger than the actual result set should be) this results in the ref punOutItemsArraySize getting the correct size on that call and the rest of our code can funciton as normal.

For other readers, I wouldn't normally patch this in this way except that we need to insure that our code works for others without edit and on the latest release build of Steamworks.NET so we didn't have the option to simply edit isteaminventory.cs or role back to a previous build at least not without other issues.

**Comment by rlabrecque** [comment]
Should be fixed! Just did the simple thing for now.
