### ISSUE TITLE
FileReadAsync callbacks sometimes doesn't gets called on Mac

### ISSUE THREAD

**Issue by andremarques-gamedev** [rlabrecque/Steamworks.NET#310]
Hello, I have been having a problem with the FileReadAsync method while cross-testing between mac and windows. And at a certain point that I couldn't figure it out yet, It stops returning file read async callback. I already had this problem on windows but it only stops working after testing playing the game between platforms. Because while doing this only on windows I haven't had problems yet. So I think its a mac problem.

Can anyone guess why this is happening?

Right now, I am testing in windows and I am getting callbacks, but mac never gets.

**Comment by spajus** [comment]
See #302, it could be your issue as well

**Comment by rlabrecque** [comment]
Closing as part of cleanup, please ping me here if this issue is still coming up.
