### ISSUE TITLE
steam_appid.txt needs to be updated

### ISSUE THREAD

**Issue by sator-imaging** [rlabrecque/Steamworks.NET#311]
As you know, Steam's app id is not a secret number.
It is public, you can see software's app id in store page's URL.

I think text file content needs to be updated to something else.

**Comment by antigravities** [comment]
The provided steam_appid.txt specifies appID 480 (Spacewar), which is the generally-used appID for testing Steamworks features. It's not supposed to be secret.

**Comment by sator-imaging** [comment]
antigravities,

I know No.480.
I've tested my app with no txt, and add that in right place, with # retrieved from store URL, it works.

yes, using strmwks.net or not is a not public, but simply try and launch to unlck app.

**Comment by sator-imaging** [comment]
follow-up

I've login with another steam id, then launch app, so that licensing error appears (expected).

then, download free content, and take that app's # retrieved from store page url, and create txt and save right place.

licensing are passed with another free apphs #.

**Comment by rlabrecque** [comment]
The steam_appid.txt is just how Steam works, we have little control over that. What we can do is use things like `if (SteamUtils_GetAppID() != (AppId_t)480) { Application.Quit(); }`

**Comment by sator-imaging** [comment]
rlabrecque,

sorry for re-opening, reason for casual-copying protection.

case:
1. Purchase software in legal way.
2. Copy downloaded files from local steam folder.
3. add txt file with app # retrieved from store url.
4. append it to local downloaded folder
5. send that files to friends.


yes, it's open for stmworks.net developler but not for casual-users, anyway it's good idea to determine in debug mode or not.


anyway I'd added code like this for windows app.

```
bool IsDebugMode()
{
    var result = false;

    var debugTxt = System.IO.Path.Combine(System.IO.Directory.GetParent(Application.dataPath).ToString(), "steam_appid.txt");
    if(System.IO.File.Exists(debugTxt))
    {
        result = true;
    }

    return result;
}
```

**Comment by GMMan** [comment]
> 1. Purchase software in legal way.
> 2. Copy downloaded files from local steam folder.
> 3. add txt file with app # retrieved from store url.
> 4. append it to local downloaded folder
> 5. send that files to friends.
That's not how any of that works. The API will fail to init if the user does not own the app ID in question. They may use app ID 480, but that's what `SteamAPI.RestartAppIfNecessary()` is for. Additionally, `steam_appid.txt` may be written by Steam itself in certain circumstances (I haven't researched into which), so if you're doing something weird when the file is present, you may be preventing legitimate players from playing.

I think this is a big fat `WONTFIX`.
