### ISSUE TITLE
Remote play together

### ISSUE THREAD

**Issue by johnnyjr** [rlabrecque/Steamworks.NET#313]
I originally though the implementation was built against an older version of the API, but it seems to be built against 1.46 but the call to invite to Remote Play Together (BSendRemotePlayTogetherInvite in ISteamRemotePlay) is missing. Is there an easy way to add it to the implementation myself or could the code be updated with this part of the API?

Sorry for closing and re-opening, I was a little to fast...

**Comment by rlabrecque** [comment]
Hmm, where are you seeing `BSendRemotePlayTogetherInvite`? I just grabbed Steamworks SDK 1.46 again to look for it, but there was no results at all. :?

**Comment by johnnyjr** [comment]
No you are quite right. The call is in the documentation  (https://partner.steamgames.com/doc/api/ISteamRemotePlay) but seems to be missing in the header file?

**Comment by rlabrecque** [comment]
SteamAPI_ISteamRemotePlay_BGetSessionClientResolution
SteamAPI_ISteamRemotePlay_GetSessionClientFormFactor
SteamAPI_ISteamRemotePlay_GetSessionClientName
SteamAPI_ISteamRemotePlay_GetSessionCount
SteamAPI_ISteamRemotePlay_GetSessionID
SteamAPI_ISteamRemotePlay_GetSessionSteamID

Those are the ISteamRemotePlay functions exported in steam_api.dll as well. I wonder if they had it, then removed it or held it back? I'll reach out to someone and ask about it!

**Comment by johnnyjr** [comment]
That is strange. Let me know if you can't find an answer and I can reach out to my contacts as well.

**Comment by johnnyjr** [comment]
Did you get any answers on this?

**Comment by rlabrecque** [comment]
Hey, yeah, It's been added in Steamworks SDK 1.47!

Unfortunately 1.47 didn't work on the public Steam client last weekend, hopefully it does this weekend and I'll get that up there!

**Comment by johnnyjr** [comment]
> Hey, yeah, It's been added in Steamworks SDK 1.47!
> 
> Unfortunately 1.47 didn't work on the public Steam client last weekend, hopefully it does this weekend and I'll get that up there!

Hi again!
Do you have any idea when 1.47 will be available?

**Comment by rlabrecque** [comment]
Heh, they actually pulled 1.47 back because it wouldn't work on non-beta versions of Steam! So we're stuck in limbo, until it's rereleased. On the upside as soon as they rerelease it, Steamworks.NET will be ready within 24 hours!

**Comment by psychonic** [comment]
It was re-released a few days ago.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/commit/5eaa256456c4199a6f233093d50b52f4363cb4bf

👍

**Comment by love451990105** [comment]
BSendRemotePlayTogetherInvite always return false? Is there any extra reason for it to return false?

**Comment by KelsamGames** [comment]
> BSendRemotePlayTogetherInvite always return false? Is there any extra reason for it to return false?

Make sure your Steam Client is the latest version, perhaps even the beta build. If so, you should see an error pop-up in the Steam overlay when it fails (giving a reason). But generally, it should work and return true if both the inviter and invitee are "Online" and there was no issue sending the request (connection timeout, server stuff, etc).

However, for the purpose of info, it's likely this call will change in the future to return something a bit more descript than a boolean. https://steamcommunity.com/groups/steamworks/discussions/0/1751268210976269094/
