### ISSUE TITLE
pOutItemsArray NullReferenceException

### ISSUE THREAD

**Issue by FoxCastz** [rlabrecque/Steamworks.NET#314]
I am trying to setup a check for steam inventory items, this is the code I have that is causing the issue with Steamworks.NET

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Steamworks;

public class SteamStuff : MonoBehaviour {
    SteamInventoryResult_t myInventoryHandle;
    public static List<int> inventoryItemDefs = new List<int>();
    private Callback<SteamInventoryFullUpdate_t> updateResult;
    Steamworks.SteamInventoryResult_t result;
	// Use this for initialization
	void Start () {
        //
        //Steamworks.SteamInventory.GetAllItems(out results);
        StartCoroutine(WaitForSteam());
	}
	IEnumerator WaitForSteam() {
        yield return new WaitForSeconds(3);
        Debug.Log("Started");
        updateResult = Callback<SteamInventoryFullUpdate_t>.Create(OnInventoryFullUpdate);
        SteamInventory.GetAllItems(out result);
        Debug.Log(result.ToString());
    }
	void OnInventoryFullUpdate(SteamInventoryFullUpdate_t fullUpdate) {
        Debug.Log("Test");
        inventoryItemDefs.Clear();
        uint itemCount = 0;
        SteamItemDetails_t[] itemDetails;

        if(SteamInventory.GetResultItems(myInventoryHandle,null,ref itemCount)) {
            Debug.Log("Item Count:" + itemCount);

            itemDetails = new SteamItemDetails_t[itemCount];
            SteamInventory.GetResultItems(myInventoryHandle,itemDetails,ref itemCount);

            foreach(SteamItemDetails_t itemDetail in itemDetails) {
                int itemDef = (int)itemDetail.m_iDefinition;
                inventoryItemDefs.Add(itemDef);
                if(inventoryItemDefs.Contains(1))
                    Debug.Log("Inventory has the Classic Engine");
                else {
                    Debug.Log("Generating Classic Engine");
                    Steamworks.SteamItemDef_t[] newItems = new Steamworks.SteamItemDef_t[]{ (SteamItemDef_t)1};
                    uint[] newAmounts = new uint[] { 1 };
                    SteamInventory.GenerateItems(out result,newItems,newAmounts,(uint)1);
                }
            }
        }
    }
}
`

**Comment by rlabrecque** [comment]
Sorry! This should be fixed!
