### ISSUE TITLE
A package manager version?

### ISSUE THREAD

**Issue by yuyang9119** [rlabrecque/Steamworks.NET#315]
@rlabrecque Hi, I'm looking for a Steamworks package version for Unity, but can't find one. So I fork this and modify it to a package. I would like to know if you are planning to do this so I needn't maintain the package by myself. Anyway, thanks for your sharing.

**Comment by rlabrecque** [comment]
Yes, I'm planning on it, can you link me what you have so I could use it as a starting point? 👍

**Comment by yuyang9119** [comment]
This is my repository:
https://github.com/yuyang9119/UnityExtensionsSteamworks

I just move all stuff into the Steamworks package folder and modify 'Plugins' folder name to 'Runtime'. There's some path problem to handle, so I add 'Utilities' class:
```
#if UNITY_EDITOR

using System.IO;

namespace UnityExtensions.Steamworks.Editor
{
    public struct Utilities
    {
        public static readonly string RuntimeDirectory = Path.GetFullPath("Packages/com.yuyang.unity-extensions.steamworks/Runtime");
    }
}

#endif // UNITY_EDITOR
```
Because 'Editor' folder in package is not a special folder, I use `#if UNITY_EDITOR ... #endif` wrap all editor-only script. I add a 'SteamworksHelper' class to simplify steamworks integration last.

Because git package is not available on old versions of Unity, you can remove the support code for old versions of Unity in this package version. I will delete my repository once you compete the package version.

One last thing, I found a mistake in the documentation: 
> If you pause the game by setting Time.timeScale to 0 then Update() functions will no longer run.
In fact Update() will still run just with a 0 deltaTime. The FixedUpdate will no longer run.

**Comment by yuyang9119** [comment]
This is custom package documentation if you need: https://docs.unity3d.com/2019.3/Documentation/Manual/CustomPackages.html

**Comment by rlabrecque** [comment]
Thanks!

**Comment by crdmrn** [comment]
Is there any update on this @rlabrecque?

**Comment by demonixis** [comment]
Hi,
I'm also very interested by a package manager version. I can submit a PR if you're interested

**Comment by JoaoBorks** [comment]
Also interested on this

**Comment by nightrise** [comment]
Same here -- this would facilitate updates, as well as references from other packages. Currently because it's in the main assembly, it's difficult for packages that depend on Steamworks to reference it.

**Comment by rlabrecque** [comment]
Updates and progress has been made here 👍 : https://github.com/rlabrecque/Steamworks.NET/issues/389
