### ISSUE TITLE
Can't access the server query after query PlayerDetails or Ping

### ISSUE THREAD

**Issue by labanau** [rlabrecque/Steamworks.NET#316]
So I am trying to integrate Steamworks.NET with my discord bot, however, when I request PlayerDetails or Ping the server I get the response as a bool (1 - which means that I got the response as I understand). I am not sure how to get that response to print it out. Any help?

**Comment by labanau** [comment]
I am trying to use the functions in the standalone package and the OnServerRespon methods are not getting called and I think it is because I don't have an OnUpdate in my discord bot. Any suggestions?

**Comment by rlabrecque** [comment]
Yeah, I believe you'll need to call `SteamAPI.RunCallbacks();` for steam to call those.

Alternatively you might want to try out SteamKit, it would provide much more flexibility for non-game Steam integration since it's basically an open source C# implementation of Steam (sans UI)
https://github.com/SteamRE/SteamKit

**Comment by labanau** [comment]
> Yeah, I believe you'll need to call `SteamAPI.RunCallbacks();` for steam to call those.
> 
> Alternatively you might want to try out SteamKit, it would provide much more flexibility for non-game Steam integration since it's basically an open source C# implementation of Steam (sans UI)
> https://github.com/SteamRE/SteamKit

I tried running the `SteamAPI.RunCallbacks();` and for some reason, they still don't get run. Maybe you will see the issue if I post my code, if not I will close the issue.

`
    public class Commands : ModuleBase {
        //Matchmaking Interface
        private HServerListRequest m_ServerListRequest;
        private HServerQuery m_ServerQuery;
        private ISteamMatchmakingPingResponse m_PingResponse;
`

Same as the test example I initialize the variables, then instead of putting the assigning in the update method, I put it in the function which gets called by discord command.
`
        [Command("server")]
        public async Task Server(int serverNumber)
        {
            m_ServerQuery = HServerQuery.Invalid;

            m_PingResponse = new ISteamMatchmakingPingResponse(OnServerResponded, OnServerFailedToRespond);
`
Later on in that function I call the method
`
if (!SteamAPI.Init())
            {
                Console.WriteLine("SteamAPI.Init() failed!");
                return;
            }
SteamAPI.RunCallbacks();
m_ServerQuery = SteamMatchmakingServers.PingServer(TestConstants.k_IpAddress208_78_165_233, 
    TestConstants.k_Port27015, m_PingResponse);
Console.WriteLine("SteamMatchmakingServers.PingServer(" + 
    TestConstants.k_IpAddress208_78_165_233 + ", " + TestConstants.k_Port27015 + ", " + 
    m_PingResponse + ") : " + m_ServerQuery);
SteamAPI.RunCallbacks();
`
And even with the RunCallbacks, it still doesn't run the `OnServerResponded` even though, it gets the respond and the query changes to 1

**Comment by rlabrecque** [comment]
Did you end up figuring this out?

**Comment by labanau** [comment]
Yeah, so if you use Steamworks.NET in standalone (Without Unity) you would need to run the `SteamAPI.RunCallbacks();` every interval, in my case it worked to run it every 5 milliseconds on a different thread and then the callbacks got triggered properly. I was thinking that Unity OnEnable gets triggered all the time when the object gets changed, so I thought, is the "listening" part is the problem test it out and it was. If needed can post code snippet

**Comment by CamxxCore** [comment]
A code snippet would help @labanau . Currently experience this exact problem :|

**Comment by labanau** [comment]
Hi, sorry I just noticed your reply.
`
timer = new System.Threading.Timer(RunSteamCalbbacks, null, 0, 50);

private static void RunSteamCalbbacks(object state) {
  try {
    SteamAPI.RunCallbacks();
    GameServer.RunCallbacks();
  } catch {
    Console.WriteLine("Callbacks crashed");
  }
}
`
However, with this implementation I noticed that steam builds up on memory and eventually if you run it long enough it crashes your whole pc, never went back to investigate why
