### ISSUE TITLE
SteamManager is a component, but DISABLESTEAMWORKS disables the entire file causing errors.

### ISSUE THREAD

**Issue by st33d** [rlabrecque/Steamworks.NET#317]
Unity 2019 requires filenames to be the same as class names for MonoBehaviour components to work. Otherwise the IDE reports a warning or does something worse.

The current implementation of the DISABLESTEAMWORKS define creates a broken component in certain versions of Unity. This causes some real head-scratching bugs as Unity throws a little tantrum whenever I try to put other components on the same gameobject. The SteamManager class will of course not declare itself as the cause because DISABLESTEAMWORKS has hidden the entire class and left nothing in its place. Upgrading Unity is also a nightmare as the project has a fit trying to figure out what the broken component is.

Ideally I would like the component to be empty, but not report warnings or errors when referenced. When I looked at how my coworkers had implemented Steamworks.NET they had rewritten the SteamManager class to avoid this issue.

Eg:
`#if UNITY_ANDROID || UNITY_IOS || UNITY_TIZEN || UNITY_TVOS || UNITY_WEBGL || UNITY_WSA || UNITY_PS4 || UNITY_WII || UNITY_XBOXONE || UNITY_SWITCH || UNITY_EDITOR
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using UnityEngine;
using System.Collections;
using Steamworks;

... etc.

#else
// my coworker's addition
using UnityEngine;
public class SteamManager : MonoBehaviour {
	public static bool Initialized {get { return false;}}

}
#endif // !DISABLESTEAMWORKS
`

Please consider making the SteamManager a bit more conscientious.

**Comment by FakeByte** [comment]
I can't reproduce your error.
I changed #if !DISABLESTEAMWORKS to #if DISABLESTEAMWORKS so that it will be disabled, when I run it unity complains about a missing script, but other scripts on that game object run fine without problems.

**Comment by spajus** [comment]
When you have a missing script, you cannot save the prefab anymore (if you're using prefabs). And that breaks the workflow on different platforms. So this is a valid issue.

**Comment by rlabrecque** [comment]
Yeah, that makes sense!

Done in:

https://github.com/rlabrecque/Steamworks.NET-SteamManager/commit/812313bab6747d4a389d666303724b4013732fb8
