### ISSUE TITLE
Firing OnLobbyChatMsg, OnLobbyChatMsg, OnLobbyKicked and OnLobbyDataUpdate

### ISSUE THREAD

**Issue by pavelkux** [rlabrecque/Steamworks.NET#318]
I might be really just missing something obvious but I was googling for about two hours and I was not able to find proper example for these calls using Steamworks.NET.

I am setting up the lobby functionality. So far everything went quite well, I can create lobby, set lobby data, join lobby with another client and I am even able to change lobby data and get this on client (via periodic call of GetLobbyDataCount and following GetLobbyDataByIndex).

Now, I am trying to get the chat and LobbyDataUpdate callbacks working.
Unfortunately, I cannot get anything out of this working. What should I do to bind these callbacks? 
What I have:

CallResult<LobbyDataUpdate_t> m_LobbyDataUpdateResult;
CallResult<LobbyChatMsg_t> m_LobbyChatMsgResult;
CallResult<LobbyChatUpdate_t> m_LobbyChatUpdateResult;        

internal void Start()
{
            ...
            m_LobbyDataUpdateResult = CallResult<LobbyDataUpdate_t>.Create(OnLobbyDataUpdate);
            m_LobbyChatMsgResult = CallResult<LobbyChatMsg_t>.Create(OnLobbyChatMsg);
            m_LobbyChatUpdateResult = CallResult<LobbyChatUpdate_t>.Create(OnLobbyChatMsg);
            ...
}
void OnLobbyChatMsg(LobbyChatMsg_t pCallback, bool bIOFailure)
{
            //never fired
}

void OnLobbyChatMsg(LobbyChatUpdate_t pCallback, bool bIOFailure)
{
            //never fired
}

void OnLobbyDataUpdate(LobbyDataUpdate_t pCallback, bool bIOFailure)
{
            //never fired
}

for other calls like LobbyEnter_t, I obviously call also Set methods. E.g. m_LobbyEnterCallResult.Set(SteamMatchmaking.JoinLobby(new CSteamID(lobbySteamID)));      
but for these updates, there is no SteamAPICall_t to set (Am I right?).
That's probably why it is not fired at all.

Anyone was implementing this? 
Just to clarify - I am not using Unity.         
Thank you in advance.

**Comment by rlabrecque** [comment]
Callbacks which aren't bound to SteamAPICall_t's are Callbacks, opposed to CallResults.

If you switch these parts:
CallResult<LobbyChatUpdate_t> m_LobbyChatUpdateResult;
m_LobbyChatUpdateResult = CallResult<LobbyChatUpdate_t>.Create(OnLobbyChatMsg);

from CallResult to Callback then you should start receiving stuff (assuming another client joins the lobby, sets the data, sends a chat message, etc.)

I'd recommend reading this: https://partner.steamgames.com/doc/sdk/api#callbacks

**Comment by pavelkux** [comment]
Thank you very much @rlabrecque for such a quick answer.
Indeed you are correct. That's why I thought I might have been missing something.
Thank you very much for such a great project!
