### ISSUE TITLE
Encoding issue of SteamUGCDetails_t.m_rgchTitle

### ISSUE THREAD

**Issue by heqw11** [rlabrecque/Steamworks.NET#319]
When getting SteamUGCDetails_t.m_rgchTitle by calling SteamUGC.GetQueryUGCResult(), non-English values (in my case Japanese and Chinese) will cause an encoding issue.
It seems to be affected by "Administrative Language Settings" in Windows 10.
The return value only appears to be correct when "Beta: Use Unicode UTF-8 for worldwide language support" is enabled.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/pull/347
