### ISSUE TITLE
CreateQueryAllUGCRequest Not Working

### ISSUE THREAD

**Issue by ClonzEh** [rlabrecque/Steamworks.NET#321]
SteamUGC.CreateQueryAllUGCRequest()
When using the filter EUGCMatchingUGCType.k_EUGCMatchingUGCType_All it returns 0 items
but when using the filter EUGCMatchingUGCType.k_EUGCMatchingUGCType_Items, it works fine :(

**Comment by rlabrecque** [comment]
The latest Steamworks SDK now states:

k_EUGCMatchingUGCType_All				 = ~0,		// @note: will only be valid for CreateQueryUserUGCRequest requests

Not sure why that is, but the update to 1.47 will have that comment at least.
