### ISSUE TITLE
Steam Login

### ISSUE THREAD

**Issue by PAYALzariya** [rlabrecque/Steamworks.NET#324]
hi
I am trying to login in steam using 480 appid, but issues are when I am login in unity editor, it work fine. when I make exe build and run it showing error like below :

[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.

What I can do?

Please give me a suggestion, I need help to solve this issue.

Thanks, advance.
![Untitled](https://user-images.githubusercontent.com/45392865/71073268-06c3bb80-21a6-11ea-916c-6313dff81642.png)

**Comment by FakeByte** [comment]
Make sure the steam_appid.txt is in the folder your standalone build is in, you will have to copy it in there.
