### ISSUE TITLE
SteamUGC.GetSubscribedItems does not populate the array

### ISSUE THREAD

**Issue by Swan** [rlabrecque/Steamworks.NET#325]
When calling `SteamUGC.GetSubscribedItems()`, the array of ids never gets populated. The number of items seem to be correct however.

Not sure if I'm doing something wrong here, but this is the code I am using: 

```cs
var numSubscribed = SteamUGC.GetNumSubscribedItems();

PublishedFileId_t[] ids = {};
var items = SteamUGC.GetSubscribedItems(ids, numSubscribed);
```

Not sure if this is a regression from these two past issues: https://github.com/rlabrecque/Steamworks.NET/issues/28, https://github.com/rlabrecque/Steamworks.NET/issues/33

**Comment by rlabrecque** [comment]
Your ids array is 0 length, you need to allocate it with the number of elements in numSubscribed ala:

PublishedFileId_t[] ids = new PublishedFileId_t[numSubscribed];
