### ISSUE TITLE
Where is GameCoordinator?

### ISSUE THREAD

**Issue by codefather-labs** [rlabrecque/Steamworks.NET#326]
https://partner.steamgames.com/doc/api/ISteamGameCoordinator

I can't find this handler in your library. Help please

**Comment by rlabrecque** [comment]
ISteamGameCoordinator is deprecated, and has no real use outside of Valve

I implemented it in a branch here a long time ago, you could grab it and fix it up if you need it, but I won't be supporting it.

https://github.com/rlabrecque/Steamworks.NET/commit/e217e9b2293b3045b5104d67a2e668a524c6f131
