### ISSUE TITLE
GetSubscribedItems bug

### ISSUE THREAD

**Issue by botman99** [rlabrecque/Steamworks.NET#33]
ISteamUGC's GetSubscribedItems() isn't filling the array with the items.  The number of items returned is correct, but the array isn't populated.

Looking at the 5.0.0, NativeMethods.cs, the call looked like this:

public static extern uint ISteamUGC_GetSubscribedItems(PublishedFileId_t[] pvecPublishedFileID, uint cMaxEntries);

The 'pvecPublishedFileID' should be [In, Out], like so:

public static extern uint ISteamUGC_GetSubscribedItems([In, Out] PublishedFileId_t[] pvecPublishedFileID, uint cMaxEntries);

Great product by the way.  Keep up the good work.  :)

**Comment by botman99** [comment]
Looks like this is a duplicate of #28

**Comment by rlabrecque** [comment]
Yep, all fixed up! Just grab the latest from the master branch. There will be a new release/unitypackage pushed hopefully later this week.
