### ISSUE TITLE
Building a Mac-build from OSX can't Init Steam on startup.

### ISSUE THREAD

**Issue by guldlock** [rlabrecque/Steamworks.NET#330]
Hello!

I've always build for Windows, Mac and Linux from my Windows but now that Apple need to have the Mac builds notarised I need to build the Mac version from my MacBook Pro (2015). I've got the notarisation part fixed. But my builds won't initialise Steam properly.

I'm using **Unity 2019.1.9f1** and **Steamworks.NET_13** 
My OS is **Catalina 10.15.2**

I've tried to move out the **libsteam.api** and rename it to **steam_api.bundle** but that doesn't work.

**Comment by rlabrecque** [comment]
Hey @guldlock do you have logs? Which part fails exactly? Does it work without Steamworks .NET?
