### ISSUE TITLE
How To implement inapp purchasing in steam? 

### ISSUE THREAD

**Issue by PAYALzariya** [rlabrecque/Steamworks.NET#331]
Hi,
I am trying to implement in-app purchasing in the steam game. I'm using steamwroks.net SDK in-game. but it not working. And I have no idea how to implement in-app in the steam network.
please, anyone, give suggestions.

Thanks in advance.

**Comment by KelsamGames** [comment]
https://partner.steamgames.com/doc/features/microtransactions

**Comment by rlabrecque** [comment]
There isn't too much you have to do on the game client side for Steam Microtransactions. The difficult part is that I'm pretty sure you need a secure backend server, which needs to talk to the Steam WebAPI. Very much outside of the realm of Steamworks.

Here's the primary piece you need, and an example of how to use it: `MicroTxnAuthorizationResponse_t`
https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserTest.cs#L19
