### ISSUE TITLE
Stack Trace with no file error lines

### ISSUE THREAD

**Issue by drHogan** [rlabrecque/Steamworks.NET#332]
Hi,

I recently realized that while a local build of my game seems to report the stack trace correcly for exceptions and debugs, the steam build doesn't. I did try to dig a bit into google and forum, but I couldn't find anything, a supposedly my setup should allow for it.
I tried both with the Steam DRM and without, and the result is the same, so I am wondering if Steamworks.NET could be involved and if you know anything about it.

My exceptions have this look in the  Player.log

> Uploading Crash Report
> ArgumentException: An item with the same key has already been added. Key: TowerPrefab(Clone) (TowerManager)
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <599589bf4ce248909b8a14cbe4a2034e>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0 
>   at MagicTowerManager.AuraOnTower (TowerManager target) [0x00065] in <48ef621f693548e0a355ff6419e173d2>:0 
>   at MagicTowerManager.FixedUpdate () [0x0013d] in <48ef621f693548e0a355ff6419e173d2>:0 
>  
> (Filename: <599589bf4ce248909b8a14cbe4a2034e> Line: 0)

and my manual prints have the following one

> 3
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> KeyboardManager:Update()
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

I am using 2019.2.8f1 in Debug Mode, with Stack trace set to ScriptsOnly and Scripts Debugging activated (and Mono backend). Do you think it could depend on Steamworks.NET? And if so would there be any workaround? (we are about to release in Early Access, and full debug mode would be vital for us)

Thanks in advance for your time!
H

**Comment by drHogan** [comment]
Upon some more testing, the Steam DRM is not influencing the problem, but Steamworks.NET those.

This is the local build (same identical build and setup)

> Unlocked Chapter 2
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> CampaignManager:Update() (at C:\EmpiresInRuins\EmpiresInRuins\EmpiresInRuins\Assets\Scripts\Global\Campaign\CampaignManager.cs:999)
> (Filename: C:/EmpiresInRuins/EmpiresInRuins/EmpiresInRuins/Assets/Scripts/Global/Campaign/CampaignManager.cs Line: 999)

and this one is the one integrating Steamworks.NET as online beta

> Unlocked Chapter 2
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> CampaignManager:Update()
>  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by drHogan** [comment]
Hi guys, I opened a a bug report with Unity, it'd appreciate if you could upvote and maybe it iwll give them a bit of a push (they already mentioned it doesn't seem to be too much a priority for them)

https://issuetracker.unity3d.com/issues/builds-with-steamworks-dot-net-dont-show-the-errors-files-and-lines-details-in-the-stacktrace

**Comment by rlabrecque** [comment]
> An important part of the repro steps is that it only occurs with Unity Cloud builds.

Did you guys ever figure this out or get this sorted? :(

**Comment by davidrochin** [comment]
I'm having the same problem. Did you figure it out? @drHogan @rlabrecque

**Comment by davidrochin** [comment]
Turns out the default depot building script has this:
![image](https://user-images.githubusercontent.com/7517516/103422225-96dc6500-4b5d-11eb-9425-64d7ee4a7c5b.png)

**Comment by rlabrecque** [comment]
Hmm that must be different than the other issue which only occurs with Unity Cloud Build. Unless Unity Cloud Build isn't providing pdb's (only when Steamworks .NET is enabled?) or Unity Cloud Build is uploading directly to Steam?

Just a note though, be careful with that, you wouldn't want to ship your pdb's to external players (including press, etc!) as it's close enough to just releasing your source code.

**Comment by davidrochin** [comment]
> Hmm that must be different than the other issue which only occurs with Unity Cloud Build. Unless Unity Cloud Build isn't providing pdb's (only when Steamworks .NET is enabled?) or Unity Cloud Build is uploading directly to Steam?
> 
> Just a note though, be careful with that, you wouldn't want to ship your pdb's to external players (including press, etc!) as it's close enough to just releasing your source code.

Thanks for the heads up

**Comment by rlabrecque** [comment]
After talking to Unity about Issue 1215261 this does seem to have been caused solely by the pdb stripping during uploading!
