### ISSUE TITLE
GetLobbyMemberByIndex giving cached result

### ISSUE THREAD

**Issue by Karawasa** [rlabrecque/Steamworks.NET#333]
We're using Unity3D and have run into a problem with results seemingly being cached. Specifically around index of players in the lobby.

I set up a 3 player lobby, with player A, B, & C, where A is the creator and B & C join in that order, and then have B leave.

Calling GetLobbyMemberByIndex and comparing the steamID with the local user steamID on each client at this point gives me 2 players in the lobby, with player A still at index 0, and player C now at index 1.

If I then have player B join again then both player B and player C are now at index 1 in the lobby. Player A and C both think C is index 1 and B is index 2. But B thinks he is still index 1!

Is there a missing Steamworks API call needed? Anyone run into this with players rejoining lobbies?

**Comment by rlabrecque** [comment]
Hey @Karawasa I'm going to close this as part of cleaning up, I suspect this might be a bug with Steamworks itself.
