### ISSUE TITLE
Getting friend's lobby ID by SteamFriends.SetRichPresence()?

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [rlabrecque/Steamworks.NET#335]
Hello! I want to get the lobby ID where a friend is connected using the SteamFriends.SetRichPresence(), but I don't really know how, you can only set a string, how can I convert from SteamID to String and viceversa?

**Comment by rlabrecque** [comment]
You can convert a SteamID to string via `CSteamID.ToString()`, and a string to a SteamID by doing `CSteamID(Convert.ToUInt64(SteamIDString))`

But you should probably be using https://partner.steamgames.com/doc/api/ISteamFriends#GetFriendGamePlayed instead. This gets you a friends lobby directly.
