### ISSUE TITLE
System.DllNotFoundException: steam_api

### ISSUE THREAD

**Issue by DukeofDiamonds** [rlabrecque/Steamworks.NET#336]
Hi there, I'm working on a Steam game in Unity, that uses Steamworks.Net, I have had no problems like this using Windows, the issue came on a Mac. I've had 3 Mac testers not have this issue, but for one, she plays the game, it works fine until the scene using this SteamManager script is opened, then it closes abruptly and it logs the following error:
---------------------------------

[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(Steamworks.AppId_t)
  at Steamworks.SteamAPI.RestartAppIfNecessary (Steamworks.AppId_t unOwnAppID) [0x00005] in <d5515ff9ba334adbb313ce156d9dc8aa>:0 
  at SteamManager.Awake () [0x00076] in <9133661ce507431abbaeea82a5112881>:0 

-------------------------

I am using the Steamworks 13.0.0 release, and Unity version: 2019.3.0f6 Personal.
The Mac in question was OS X Yosemite, Version 10.10.5 (iMac 27-inch, Late 2012)

Is there any way to fix this issue? I am desperate for a solution so it doesn't repeat for other users on Mac once my game is released next month.

(P.S thank you for an otherwise brilliant script, it's very helpful)

**Comment by rlabrecque** [comment]
Steam and thus Steamworks.NET don't support OS X Yosemite anymore.

https://support.steampowered.com/kb_article.php?ref=5953-QTIO-1764

https://github.com/rlabrecque/Steamworks.NET/issues/205#issuecomment-443541040

**Comment by DukeofDiamonds** [comment]
Thank you so much, this information is vital. It's very appreciated!!
(I did read around these forums but must've missed that comment)

**Comment by rlabrecque** [comment]
Reopened to provide this info in a better clearer way, in the readme and/or on the website!

**Comment by rlabrecque** [comment]
Finally got around to this: http://steamworks.github.io/faq/#what-operating-systems-does-steamworksnet-support
