### ISSUE TITLE
CreateItemResult_t k_iCallback incorrect in SteamCallbacks.cs

### ISSUE THREAD

**Issue by MarconiusDMM** [rlabrecque/Steamworks.NET#338]
```
//-----------------------------------------------------------------------------
// Purpose: result for ISteamUGC::CreateItem()
//-----------------------------------------------------------------------------
[StructLayout(LayoutKind.Sequential, Pack = Packsize.value)]
[CallbackIdentity(Constants.k_iClientUGCCallbacks + 3)]
public struct CreateItemResult_t {
  public const int k_iCallback = Constants.k_iClientUGCCallbacks + 3;
  public EResult m_eResult;
  public PublishedFileId_t m_nPublishedFileId; // new item got this UGC PublishFileID
  [MarshalAs(UnmanagedType.I1)]
  public bool m_bUserNeedsToAcceptWorkshopLegalAgreement;
}
```

In this bit of code, the `+ 3` values seem to be causing issues.
Specifically in the implemented callback, `bIOFailure` becomes true, and Steam API gives the following error:
`[S_API WARN] Mismatched callback requested in GetAPICallResult(), asked for callback of type 3403, but received 3402`

Changing the `+ 3` to `+ 2` seems to solve the issue for this case, but not sure if there are others.

This is my test code for reference:
```
private CallResult<CreateItemResult_t> testCallResult;


void Awake()
{
    this.testCallResult = CallResult<CreateItemResult_t>.Create(TestCreate);
}

void Update()
{
    if (Input.GetKeyDown(KeyCode.Space))
        Test();
}

public void Test()
{
    var handle = SteamUGC.CreateItem(new AppId_t(this.platformController.appId), EWorkshopFileType.k_EWorkshopFileTypeCommunity);
    this.testCallResult.Set(handle, TestCreate);
}

public void TestCreate(CreateItemResult_t callback, bool bIOFailure)
{
    if (bIOFailure)
        Debug.Log("error " + callback.m_nPublishedFileId + " " + callback.m_eResult + " " + callback.m_bUserNeedsToAcceptWorkshopLegalAgreement);
    else
        Debug.Log(callback.m_eResult + " " + callback.m_nPublishedFileId);
}
```

**Comment by rlabrecque** [comment]
Hrm, interesting find!

Seems like this has always been + 3 even in the C++ Steamworks SDK, so that's odd...

https://github.com/rlabrecque/SteamworksSDK/blob/master/public/steam/isteamugc.h#L399

**Comment by MarconiusDMM** [comment]
Interesting... is it possible `+ 3` is correct, but the code is shifting the number somewhere?

Since then, I've also noticed that the `eResult` of the `CreateItem` is giving a weird value too... I was expecting `k_EResultOK`, but instead it gets set to AppId, which is very odd. But the thing is, all the other parameters are being set correctly, far as I can tell, it correctly returns `m_nPublishedFileId` and everything.

**Comment by MarconiusDMM** [comment]
Upon further investigation, I believe I was working with an outdated version of the .dll, and that was causing the above issues. Updating it correctly seems to make it work correctly with `+ 3` now.

I'm guessing the outdated .dll was making all kinds of references messed up. I did notice the autogen code hasn't been changed in ages, but I guess some other parts of code may have offset the index or something.

Sorry for the trouble!
