### ISSUE TITLE
Small nit pick at the FAQ

### ISSUE THREAD

**Issue by GMMan** [rlabrecque/Steamworks.NET#34]
On the item "Does the Steam DRM wrapper work with Unity or XNA/Monogame?", the FAQ says Unity games can't be wrapped. This is not true; I've seen a number of Unity games wrapped with Steam DRM. Steam DRM can't wrap .NET assemblies because newer Windows versions (XP and above) never executes the native code stub and directly starts up the .NET runtime. Unity, however, is a pure native code program with embedded support for Mono, and is thus wrappable. It is still true XNA/MonoGame executables can't be wrapped, unless the developer writes a native code loader for the assemblies first.

**Comment by rlabrecque** [comment]
I've seen a few as well, at the same time I've personally had trouble getting it working with Unity in the past and have seen other people struggle with it as well. Might be worth re-investigating, and definitely worth updating the FAQ
