### ISSUE TITLE
Suggestion for stadia platform

### ISSUE THREAD

**Issue by l4dnigel** [rlabrecque/Steamworks.NET#342]
Yes, this is a suggestion, not an issue.
First, thanks for sharing this awesome plugin about steam api.

The point that I check the if define like 
#if UNITY_ANDROID || UNITY_IOS || UNITY_TIZEN || UNITY_TVOS || UNITY_WEBGL || UNITY_WSA || UNITY_PS4 || UNITY_WII || UNITY_XBOXONE || UNITY_SWITCH
And then, define it DISABLESTEAMWORKS.

Could you add the stadia to the list at later update?
Stadia is stream game service, maybe it will popular recently.
Thank you.

**Comment by rlabrecque** [comment]
I think we actually need to invert this now. IIRC there was a reason I did it this way originally, hopefully what ever it was has been solved by now.

It needs to be something like `#if !(UNITY_WINDOWS || UNITY_LINUX || UNITY_MACOS)`

**Comment by l4dnigel** [comment]
Glad to listen this news, thanks for your responding. I will look forward to next update!
