### ISSUE TITLE
Plugin 'libsteam_api.so' is used from several locations

### ISSUE THREAD

**Issue by GabLeRoux** [rlabrecque/Steamworks.NET#343]
Building for different platforms such as `SWITCH` breaks with following error:

```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.
```

**Comment by GabLeRoux** [comment]
Solution:

Locate `libsteam_api.so` and only enable libraries for Editor and Standalone:

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/1264761/77838799-13f92a80-7145-11ea-8380-9d2a95869f0e.png">

**Comment by Clpsplug** [comment]
Although I was using a beta version of Unity, I ran into the same issue with 2020.1.0b11. The platform selection checkbox is different from what is shown in the screenshot above (which is from 2018.4.11f1,) but the same thing can be done by:

1. Select all `libsteam_api.so.`
2. In 'Select platforms for plugin' section, _uncheck_ `Any platform.` This will turn the next heading from '**Exclude Platforms**' to '**Include Platforms.**'
3. Select `Editor` and `Standalone.` You should be able to build your project.

NOTE: Excluding does not work. Only including does.

![Screenshot.](https://i.gyazo.com/5cb414b2f40b316a260a89092e2cdd05.png)
