### ISSUE TITLE
import settings of x86/libsteam_api include macOS x64 by default

### ISSUE THREAD

**Issue by joonjoonjoon** [rlabrecque/Steamworks.NET#344]
I was unable to make builds on macOS until I disabled the macOS - x64 checkbox in the import settings of libsteam_api inside the x86 folder.
The x86_64 folder has a file with the same name which _should_ remain included of course.

![image](https://user-images.githubusercontent.com/1086635/78555368-677e0f00-77fc-11ea-9a5b-966061570f66.png)

**Comment by rlabrecque** [comment]
Hey @joonjoonjoon Which version of Unity are you running? They keep changing that stuff :(

**Comment by zephyo** [comment]
Yep same!!! Thanks for a solution

**Comment by muclem** [comment]
> Hey @joonjoonjoon Which version of Unity are you running? They keep changing that stuff :(

Hey there @rlabrecque, I got the same error from Unity 2019.3.11f1 up until now Unity 2019.4.2f1 LTS

**Comment by rlabrecque** [comment]
I believe this is fixed as of #414 now, because we include the .meta files to explicitly set this consistently now 🎉
