### ISSUE TITLE
Include Unity .meta files for easy submodule integration

### ISSUE THREAD

**Issue by crdmrn** [rlabrecque/Steamworks.NET#348]
Adding plugin repos as submodules is one of the great things about using git; this way, one is sure to integrate other developers code without messing with it, and having always the most recent version.
The Steamworks.NET repo works great from this point of view, but it's missing one big thing: meta files.
As it get imported in Unity, meta files are generated and are marked as uncommited changes on the submodule repo, potentially creating confusion.
Would it be possible to include them in the repo so it would be "changes-free" once added as submodule to another git repo?

Thanks for the awesome work btw, I hope my explanation wasn't too confused ^^"

**Comment by rlabrecque** [comment]
This is being tracked here: https://github.com/rlabrecque/Steamworks.NET/issues/389

Some progress has been made!
