### ISSUE TITLE
CallResult not working

### ISSUE THREAD

**Issue by rex644** [rlabrecque/Steamworks.NET#352]
This has been giving me issues for a long time. I am calling this function CreateWorkshopItem() and I hit a breakpoint in this function. I hit play and the program keeps running; But CreateItemResult breakpoint never gets called. What could cause that?

Steamworks Steamworks.NET:
1.20.0.0
v1.20 - 1.32
v4.0.30319
7.0.0.0

Steam Client API
2.59.51.43

I was following this example:
https://community.monogame.net/t/facepunch-steamworks-monogame-framework-the-easiest-steamapi-integration-for-your-app/11635/7

My C# code:

```

/// <summary>
    /// Create an item in the Steam Workshop (you must then Register it with registerFileInfo). Returns a SteamAPICall_t handle. m_bUserNeedsToAcceptWorkshopLegalAgreement The m_bUserNeedsToAcceptWorkshopLegalAgreement variable should also be checked and if true, the user should be redirected to accept the legal agreement. See the Workshop Legal Agreement section for more details. https://partner.steamgames.com/?goto=%2Fdocumentation%2Fugc#Legal
    /// </summary>
    /// <returns>Returns a SteamAPICall_t handle</returns>
    public SteamAPICall_t CreateWorkshopItem()
    {
        ////1. Request a handle 
        //SteamAPICall_t handle;
        //handle = SteamUGC.CreateItem(SteamUtils.GetAppID(), EWorkshopFileType.k_EWorkshopFileTypeCommunity);
        //OnCreateItemResultCallResult.Set(handle); //not sure if this allows more than 1 upload at a time.
        ////2. CreateItemResult_t will be called via a callback.
        //Console.WriteLine("CreateWorkshopItem (SteamAPICall_t): " + handle);
        //return handle;
        var steamAPICall = SteamUGC.CreateItem(SteamUtils.GetAppID(), EWorkshopFileType.k_EWorkshopFileTypeCommunity);
        var steamAPICallResult = CallResult<CreateItemResult_t>.Create();
        steamAPICallResult.Set(steamAPICall, CreateItemResult);
        return steamAPICall;
    }

    private void CreateItemResult(CreateItemResult_t param, bool bIOFailure)
    {
        if (param.m_eResult == EResult.k_EResultOK)
        {
            //publishedFileID = param.m_nPublishedFileId;
            //UpdateItem();
        }
        else
        {
            //Debug.Log("Couldn't create a new item");
        }
    }

```

**Comment by ItemME** [comment]
Have you tried to refresh your calls?

`SteamAPI.RunCallbacks();`

You need to call this on a regular basis in order for callresults and callbacks to work properly.

**Comment by rlabrecque** [comment]
I think your CallResult object is getting GC'd before it gets called by Steam.
`var steamAPICallResult = CallResult<CreateItemResult_t>.Create();`

steamAPICallResult must stay around, you should assign it to a member variable or such.

**Comment by Akarinnnnn** [comment]
> I think your CallResult object is getting GC'd before it gets called by Steam.
> `var steamAPICallResult = CallResult<CreateItemResult_t>.Create();`
> 
> steamAPICallResult must stay around, you should assign it to a member variable or such.

Yes. I had made this mistake before.

**Comment by rex644** [comment]
Yes, that was my mistake. Thanks :)
