### ISSUE TITLE
Steamworks assembly only found when game assembly is called "Assembly-CSharp"

### ISSUE THREAD

**Issue by bneumann** [rlabrecque/Steamworks.NET#358]
Since I have some unit testing in my game, I added an assembly definition file to my scripts and called it "Game".
I added Steamworks as a unitypackage and it complained, that it can't find the reference to Steamworks.
I loaded your example project and found it working. So I saw, the only difference is the assembly name. I removed the definition and it works (my unit tests won't though).

I would try and fix it, if you point me in the right direction.

**Comment by gekidoslair** [comment]
You need to manually add the DLL reference to your ASMDef. Select the ASMDef and uncheck 'auto referenced':

https://docs.unity3d.com/Manual/class-AssemblyDefinitionImporter.html

This will expose a new set of properties that let you manually define DLL references that your assembly requires.
