### ISSUE TITLE
Callback hack

### ISSUE THREAD

**Issue by Nanorock** [rlabrecque/Steamworks.NET#36]
Hello,

I'm having trouble to make achievements working, even while using the example provided :^/
When I'm getting the callback from OnUserStatsReceived, the m_GameID is different than the pCallback.m_nGameID, I never get one with my correct game id :^( (And by passing this test, of course none of my achievements are loaded)

And I stumbled upon this:
// This is a temporary hack to preserve backwards compatability with the old CallbackDispatcher.
// If this is still here in 5.0.0 yell at me.
;^) I won't yell at you, would be silly from me, but I figured out I could remind you that + ask if you encountered such problem, or have any idea why I don't get my achievements ^^'

Nanorock

**Comment by Nanorock** [comment]
As usual, when I ask stuff, I find my answers -_- I need to publish my changes in order to have Achievements (I'm a Steam noob \o/). Anyway, the temporary hack is still a thing, ignore the rest ;^)

**Comment by rlabrecque** [comment]
Upgrade your Steamworks.NET ;) That was valid to yell at me for it about two months ago, but it's removed now!

Glad that you got it working!
