### ISSUE TITLE
'Enter Play Mode Settings' causes SteamManager to "load Steamworks DLL twice"

### ISSUE THREAD

**Issue by Clpsplug** [rlabrecque/Steamworks.NET#362]
# Summary
Having 'Project Settings > Editor > Enter Play Mode Settings' enabled for quick playtests of the game causes the `SteamManager` class to fail every time after the first playtest.

# Steps to reproduce

1. Check the 'Project Settings > Editor > Enter Play Mode Settings' checkbox. Leave both options below unchecked (hence "_do not reload_ domain or scene.")
2. Play the game, making sure to fire at least one SteamManager method (example: `SteamManager.Initialized`)
3. Exit the play mode.
4. Re-enter the play mode and fire any call to the SteamManager methods.

# Expected result

Both calls that happen at step 2. and 4. succeed.

# Actual result

An exception is observed:

```
Exception: Tried to Initialize the SteamAPI twice in one session!
Presenter.Domain.SteamManager.Awake () (at Assets/Scripts/Presenter/Domain/SteamManager.cs:144)
UnityEngine.GameObject:AddComponent()
Presenter.Domain.SteamManager:get_Instance() (at Assets/Scripts/Presenter/Domain/SteamManager.cs:39)
Presenter.Domain.SteamManager:get_Initialized() (at Assets/Scripts/Presenter/Domain/SteamManager.cs:52)
Presenter.DataManager.InitialLoader:Start() (at Assets/Scripts/Presenter/DataManager/InitialLoader.cs:39)
```

(Ignore the namespace, that is where I placed the SteamManager for my convenience)

# Comment

Although Steamworks.NET documentation [points to `SteamManager.cs` file](https://raw.githubusercontent.com/rlabrecque/SteamManager/master/SteamManager.cs) (which looks like a raw link to a file in the repository,) I cannot find it in the repository here, so PR is not possible at this moment. Also, 'disabling domain reload' itself is an experimental feature of Unity (since 2019.3,) so I'd like to make sure if we're really supporting it. But if we were to fix it the fix will look like the following:

----

I don't know why the stack trace points to the end of the `Awake()` method, but I suspect the reason for crashes to be the `s_EverInitialized` flag being `static.` [Anything static won't be initialized back to their default value if "Domain Reload" is disabled](https://blogs.unity3d.com/2019/11/05/enter-play-mode-faster-in-unity-2019-3/) like this case.  
We should be able to fix it by adding the following method to `SteamManager.cs.`

```csharp
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
private static void InitOnPlayMode()
{
    Debug.Log("Resetting initialization status.");
    s_EverInitialized = false;
    s_Instance = null;
}
```

---

# Tested with

Unity 2020.1.0b12
(commit 4aa0ee8, but the file in question does not exist.)

**Comment by rlabrecque** [comment]
Hey @Clpsplug Good find!

The file in question lives over here, it's in a separate repo because this one is supposed to be non-Unity specific. And SteamManager is technically what I'd consider "user code".

https://github.com/rlabrecque/Steamworks.NET-SteamManager/blob/master/SteamManager.cs

Could you make a PR on that repo? Do we need to wrap that InitOnPlayMode() method in #if UNITY_VERSION_SOMETHING_OR_NEWER ?

**Comment by Clpsplug** [comment]
@rlabrecque 

> The file in question lives over here, ...

Got it. I should've traced the repo from your profile... 😅 I'll reference this issue from the PR, but should I also file a ticket over there?

> Do we need to wrap that InitOnPlayMode() method in #if UNITY_VERSION_SOMETHING_OR_NEWER ?

Yes, according to the blog I linked, "Domain Reload" is something new from the version 2019.3 era. 2019.2 or earlier have always reloaded the domain every time, so that method is not necessary. Also, this code will most likely fail to compile in pre-2019 Unities because `RuntimeInitializeLoadType.SubsystemRegistration` is undocumented before 2019.x. So we need:

```csharp
#if UNITY_VERSION_2019_3_OR_NEWER
```

My Jetbrains Rider is not really cooperating when it comes to such a directive later than the 5.3.4 era, which it claims that it's not defined. But when I test with Unity, it seems to be working.

**Comment by Clpsplug** [comment]
Closing because the change is merged.

https://github.com/rlabrecque/Steamworks.NET-SteamManager/pull/2

**Comment by rlabrecque** [comment]
Thanks a lot for this!

Followup question; I wonder if we want to avoid shutting down and let the SteamAPI context live across play sessions?

**Comment by Clpsplug** [comment]
I can't really think of such use cases - it's just my 2 cents, but I believe the sole purpose of developers shutting the play mode down in Unity3D is to 'demolish' that game session and start anew. Actually, if it were not for the experimental features in question, the context will never survive between sessions because the script domain is totally reset. So at least for using this code for Unity games, the persistent context does not make much sense.

**Comment by Clpsplug** [comment]
@rlabrecque, I just realized that my fix is never going to work. I misunderstood the naming convention of the version directives. Instead of

```
UNITY_VERSION_2019_3_OR_NEWER
```

it is now (since 2017.x)

```
UNITY_2019_3_OR_NEWER
```

I will issue a hotfix to the SteamManager repository right away.
