### ISSUE TITLE
Add support for Export XCode Project

### ISSUE THREAD

**Issue by wagenheimer** [rlabrecque/Steamworks.NET#365]
To easily send the resulting project for Apple for Notarizing, SteamWorks should support the Export XCode Project when generating the Unity Project. Unity 2019.3+ supports generating a XCode Project for Mac Builds.

I have two errors:

When Exporting the Project from Unity - 
DirectoryNotFoundException: Could not find a part of the path "/Users/cezarwagenheimer/Documents/Builds/Steam/Secrets 3/Secrets of Magic 3 - Happy Halloween.app/Contents/Plugins/Steamworks.NET.txt".
RedistCopy.OnPostprocessBuild (UnityEditor.BuildTarget target, System.String pathToBuiltProject) (at Assets/Editor/Steamworks.NET/RedistCopy.cs:80)

When running the game on XCode - System.DllNotFoundException: steam_api

**Comment by rlabrecque** [comment]
I believe the first one is fixed from this:

https://github.com/rlabrecque/Steamworks.NET/commit/354bb21e39e2fb65f5a242c3d4036e51aa99eb20

Not sure about the second issue yet though.

**Comment by rlabrecque** [comment]
Second should be fixed on master at least. Likely some DLL copying issue that was solved with the refactor to ship .meta files.
