### ISSUE TITLE
Clarify Release 14.0.0 for Unity and .Net 2.1

### ISSUE THREAD

**Issue by rur15** [rlabrecque/Steamworks.NET#366]
Can you clarify the new Release 14.0.0 for unity.
It says Update .NET Standard version to .NET Standard 2.1

I am using Unity 5 and I don't think that support .net 2.1, I don't want to upgrade this if that is going to cause problems.
Which versions of Unity are supported?

**Comment by Akarinnnnn** [comment]
> Update .NET Standard version to .NET Standard 2.1  
Only standalone's .csproj file was updated. Don't worry about Unity part.

**Comment by rlabrecque** [comment]
Yep, it's a little confusing, But the Standalone project is for non-Unity projects. 👍
