### ISSUE TITLE
error CS0246: The type or namespace name 'Steamworks' could not be found 

### ISSUE THREAD

**Issue by ClementineAccount** [rlabrecque/Steamworks.NET#369]
Assets\Editor\Steamworks.NET\RedistCopy.cs(19,7): error CS0246: The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)
---

Not sure what I am missing? I followed Install instructions fine.

**Comment by benjp1** [comment]
I encountered this issue, it was only due to my current platform being on android instead of pc

**Comment by udvaritibor** [comment]
I'm getting this in VS Code, but if I reload the project in Visual Studio, and then open Code, it works for a session.

But switching IDE all the time, opening IDE, closing IDE, etc... és a bit frustrating after a while. Wonder why it does this. :\

**Comment by rlabrecque** [comment]
I believe this is fixed as of https://github.com/rlabrecque/Steamworks.NET/commit/7afbbe59b65900b8273b1803a21caf49178062cb

**Comment by RestlessSwords** [comment]
I get this error as well (trying to compile/run inside unity editor), and am close to giving up on steamworks + facepunch.

It is august-2021, I am using unity LTS-2020-12f, and imported the latest steamworks.net-15.0.1
- do I have to do anything to install/use facepunch-2.3.2 somehow?

Any recommendation or solution ?

**Comment by jcardussi** [comment]
Using Unity 2021.2.19f1 I have to back out since I can't do anything until I fix it.

I got it from Github.

**Comment by jcardussi** [comment]
> Using Unity 2021.2.19f1 I have to back out since I can't do anything until I fix it.
> 
> I got it from Github.

I saw where you said to copy the one folder (com.rlabrecque.steamworks.net) into a folder in my project named Steamworks.NET and so far that is working.

**Comment by SLotman** [comment]
I'm on Unity 2021 LTS and I have this issue with the latest release of Steamworks.net (2025.162.1)
TONS of errors in Unity.
