### ISSUE TITLE
Steamworks.NET + Windows Store/ Windows Phone 8 builds

### ISSUE THREAD

**Issue by ospiewok** [rlabrecque/Steamworks.NET#37]
Hi there,

iam using your plugin in my cross platform project, which handles a lot of platforms, including windows store and windows phone 8.

While the windows standalone builds, android and ios builds are working as intented, troubles shows up as soon as I set the target to windows store or windows phone 8.

This is easily been reproducable by using your example project.

Assets\Plugins\Steamworks.NET\InteropHelp.cs(107,31): error CS0246: Type or namespace "ICustomMarshaler" could not been found.

----

Error building Player: Exception: Error: method `System.String System.Text.Encoding::GetString(System.Byte[])` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.String Steamworks.InteropHelp::PtrToStringUTF8(System.IntPtr).
Error: method `System.Void System.Runtime.InteropServices.Marshal::Copy(System.IntPtr[],System.Int32,System.IntPtr,System.Int32)` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Void Steamworks.InteropHelp/SteamParamStringArray::.ctor(System.Collections.Generic.IList`1<System.String>).
Error: type `System.Runtime.InteropServices.ICustomMarshaler` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at Steamworks.UTF8Marshaler.
Error: method `System.String System.Text.Encoding::GetString(System.Byte[])` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Object Steamworks.UTF8Marshaler::MarshalNativeToManaged(System.IntPtr).
Error: type `System.Runtime.InteropServices.ICustomMarshaler` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Runtime.InteropServices.ICustomMarshaler Steamworks.UTF8Marshaler::GetInstance(System.String).
Error: type `System.Diagnostics.FileVersionInfo` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Boolean Steamworks.DllCheck::CheckSteamAPIDLL().
Error: type `System.Diagnostics.FileVersionInfo` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Boolean Steamworks.DllCheck::CheckSteamAPIDLL().
Error: method `System.Diagnostics.FileVersionInfo System.Diagnostics.FileVersionInfo::GetVersionInfo(System.String)` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Boolean Steamworks.DllCheck::CheckSteamAPIDLL().
Error: type `System.Diagnostics.FileVersionInfo` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Boolean Steamworks.DllCheck::CheckSteamAPIDLL().
Error: method `System.String System.Diagnostics.FileVersionInfo::get_FileVersion()` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.Boolean Steamworks.DllCheck::CheckSteamAPIDLL().

I could fix those issues by appending the compiler flags to handle the builds, but maybe you have already come around this issue!? (and maybe a better way to handle those builds, beside adding UNITY_METRO & UNITY_WP8)

**Comment by wagenheimer** [comment]
I have the same problem! There is a easy way of fixing this?

**Comment by ospiewok** [comment]
Well, it is easy to fix these issues.  But you have to add "#if (!UNITY_METRO && !UNITY_WP8)" around all steamworks.net api classes manually. So in the end it is just copy paste work, which takes around an hour or two and is not the best solution, since we had to manually change things of the library.

But since i've hoped to get some kind of response from Mr. Labrecque, about this issue, or maybe a consideration of this topic in an upcoming version of the Steamworks.net library - this workaround may help you in the end

**Comment by Pinkerator** [comment]
More general solution is write Steamworks.net lines like
#if UNITY_STANDALONE
    //Necessary code
#endif

So you'll get Steamworks support only on PC/Mac/Linux builds where STEAM is presented :)

**Comment by rlabrecque** [comment]
I think this is cleared up completely with the new 7.0.0 release, let me know if it isn't!
