### ISSUE TITLE
DLL can't be found on MacOS

### ISSUE THREAD

**Issue by mthreis** [rlabrecque/Steamworks.NET#370]
I'm having a hard time making Steamworks.NET work on a Mac machine. I'm getting the usual:

`<Steamworks.NET> Couldn't load the steamAPI DLL. It's likely not in the correct location. `

This is what my game's .app looks like:

Contents/
Contents/Resources/game.pck
Contents/Resources/icon.icns
Contents/MacOS
Contents/MacOS/data_game/Mono... -> some unimportant folders
Contents/MacOS/game --> I assume this is basically the executable, it has no extension
Contents/PkgInfo
Contents/Info.plist

Considering I assumed the 'game' file w/o extension is the executable, I dropped all the files from OSX-Linux-x64 Standalone (steam_api.bundle, steam_appid.txt, Steamworks.NET.dll, Steamworks.NET.dll.config, libsteam_api.so) there on MacOS, no luck. I also put them all on Resources folder. Same error. It happens when I remove Steamworks.NET.dll or steam_api.dll from the Windows bin folder, for example (or use the 64bits dll instead of 32, since the game was uploaded, for that specific platform, in 32bits). I also tried pasting the .dylib in the MacOS folder and it didn't work.

*The reason I also tried putting everything on Resources is because in Windows binaries, the .pck, .exe files and the data_game folder come all in the same folder and in the Mac export, the .pck comes in another folder

**To make it work in Windows, all I had to do was drop the correct Steamworks.NET.dll and steam_api.dll in its output folder (next to its .exe); for Linux, I had to place the libsteam_api.so and the dll in its output folder, next to the .x86 file

Any ideas? I'm using Godot engine by the way but it has no direct integration with Steamworks.NET.dll, so I did everything under .NET.

**Comment by Akarinnnnn** [comment]
Maybe you should put dylib next to Steamworks.NET.dll

**Comment by mthreis** [comment]
Turns out all I had to do was put the DLLs next to the .app, not inside it.

**Comment by rlabrecque** [comment]
That doesn't sound like a great long term solution. We should work towards better Godot support. I didn't realize it supported C#!
I wonder if there's a better way for Godot's C# Assembly/dll search path to function. Seems like they may be able to search inside the .app somehow.

Glad you've got it figured out for now though!
