### ISSUE TITLE
EntryPointNotFoundException: SteamAPI_ISteamUserStats_GetStatInt32

### ISSUE THREAD

**Issue by MigrantP** [rlabrecque/Steamworks.NET#372]
I haven't seen this myself, but our Unity Dashboard diagnostics has many exception reports for the following:

EntryPointNotFoundException: SteamAPI_ISteamUserStats_GetStatInt32
from Steamworks.SteamUserStats.GetStat (System.String pchName, System.Int32& pData) (at <0150cea4608b44e2831ac62f07100fcf>:0)

100% of the reports are from Windows 10 64 bit (we don't ship 32 bit for this game).

We're using Steamworks.NET 14.0.0, SDK version 1.48, DLL version 05.69.73.98, Unity 2019.4.0f1.

**Comment by rlabrecque** [comment]
How many hits of that have you seen? I wonder if it's someone trying to 'crack' your game by replacing the steam_api.dll with an [old] stub to get around RestartAppIfNecessary and the like.

If you're able to release patches quick and easily enough, I'd try doing some validation like this, but perhaps more rigorous. Then just printing out the difference between the expected DLL and the loaded one, so you have it in your crash log if that's available

https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/Steamworks.NET/InteropHelp.cs#L226-L261

**Comment by Akarinnnnn** [comment]
https://github.com/rlabrecque/Steamworks.NET/blob/d5fdc4f014c1a4c43231a9d12b3c0a2a24af0c51/Plugins/Steamworks.NET/InteropHelp.cs#L212
I suggest that "CharSet = Unicode"

**Comment by MigrantP** [comment]
In the last month, 1997 times from 86 unique users. I'll take a look at including that and seeing if we can get more info. I can include custom metadata in every report so just recording in the steam DLL size/version there might be useful too.

**Comment by MigrantP** [comment]
While I'm putting that in I found this interesting project, could be used to check for Valve's signature on the DLL. https://github.com/darvell/SteamAPIValidator

**Comment by MigrantP** [comment]
I've got it recording the DLL size/version (on Windows only) so will let you know what transpires once we ship the update =)

**Comment by rlabrecque** [comment]
Hey @MigrantP any improvement? 🙏

**Comment by MigrantP** [comment]
Thanks for the reminder! We just put out the update on Wednesday. Haven't seen any of the exceptions yet from the new version, but will keep an eye on it.
