### ISSUE TITLE
EntryPointNotFoundException: SteamAPI_ISteamClient_GetISteamGameSearch

### ISSUE THREAD

**Issue by MigrantP** [rlabrecque/Steamworks.NET#373]
Similar to #372 we are seeing this exception in the wild:

EntryPointNotFoundException: SteamAPI_ISteamClient_GetISteamGameSearch
from Steamworks.SteamClient.GetISteamGameSearch (Steamworks.HSteamUser hSteamuser, Steamworks.HSteamPipe hSteamPipe, System.String pchVersion) (at <823ab5e989744fada285478e509214b8>:0)
Steamworks.CSteamAPIContext.Init () (at <823ab5e989744fada285478e509214b8>:0)
Steamworks.SteamAPI.Init () (at <823ab5e989744fada285478e509214b8>:0)
SteamManager.Awake () (at <d058bb05329f45d9a511a5bff3be913c>:0)

This one is much more rare, we've only seen it 5 times from 3 unique users.

**Comment by arzi42** [comment]
I'm getting this in Unity (2019.3.14f1)  and in a build but seems like other team members don't.

**Comment by rlabrecque** [comment]
Do you hit this every time @arzi42 ? 👀 

Can you send me a log or crash dump at support@rileylabrecque.com ? 🙏

**Comment by rlabrecque** [comment]
Do you hit this every time @arzi42 ? 👀 

Can you send me a log or crash dump at support@rileylabrecque.com ? 🙏

**Comment by arzi42** [comment]
I sent the stack trace. It appears my teammate does get the same error, but I still see the "is playing x" Steam notification when she runs the game.

**Comment by lux** [comment]
We're consistently seeing the same issue in editor with the latest release (15.0.1). Fortunately, builds appear to work fine.

Any suggestions on how to fix it?

Here's the relevant trace info:

```
EntryPointNotFoundException: SteamAPI_ISteamClient_GetISteamGameSearch
Steamworks.SteamClient.GetISteamGameSearch (Steamworks.HSteamUser hSteamuser, Steamworks.HSteamPipe hSteamPipe, System.String pchVersion) (at Assets/Plugins/Steamworks.NET/autogen/isteamclient.cs:210)
Steamworks.CSteamAPIContext.Init () (at Assets/Plugins/Steamworks.NET/Steam.cs:345)
Steamworks.SteamAPI.Init () (at Assets/Plugins/Steamworks.NET/Steam.cs:38)
SteamManager.Awake () (at Assets/Scripts/Steamworks.NET/SteamManager.cs:118)
UnityEngine.GameObject:AddComponent()
SteamManager:get_Instance() (at Assets/Scripts/Steamworks.NET/SteamManager.cs:31)
SteamManager:get_Initialized() (at Assets/Scripts/Steamworks.NET/SteamManager.cs:42)
Social.Platforms.OpenVR.<Initialize>d__11:MoveNext() (at Assets/_Social/Scripts/Platforms/OpenVR/Manager.cs:98)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
```

And the line that triggers the error is just:

```c#
yield return new WaitUntil (() => SteamManager.Initialized);
```

Thanks!

**Comment by lux** [comment]
Any ideas what could be causing the above initialization error when running in editor? We're using Steamworks 15.0.1 and Unity 2019.4.5f1. This is really impacting our ability to test on Steam for the past few weeks.

**Comment by rlabrecque** [comment]
Hey sorry I had missed this, this issue tended to be a mismatch version of the Steamworks.NET C# code and the steam_api.dll version.

In your case specifically I'd double check that you don't have any old versions of steam_api.dll in your DLL search path, like for example in your project root, and you're using the steam_api.dll that came with Steamworks.NET 15.0.1. It could also be an extra version floating around in some other folder in your project?

**Comment by lux** [comment]
Thank you! That got it working again!

I had to copy steam_api64.dll into the project root from Assets/Plugins/x86_64 (with Unity closed so the dll would be refreshed) and that got it to run again. Deleting the dll from the root so there was only one instance did not, since then it wasn't finding it at all.

**Comment by JannickLeismann** [comment]
> Thank you! That got it working again!
> 
> I had to copy steam_api64.dll into the project root from Assets/Plugins/x86_64 (with Unity closed so the dll would be refreshed) and that got it to run again. Deleting the dll from the root so there was only one instance did not, since then it wasn't finding it at all.

Also worked for me. Took the steam_api64.dll from the .zip standalone x64 release, shut down unity, deleted the old .dll and replaced it with the new one.

Thanks! :-)

**Comment by rlabrecque** [comment]
What version of Unity are you two running? @lux @JannickLeismann

I was under the impression that Unity didn't actually need the .dll in the project root anymore. (as of around 2019.4)

**Comment by lux** [comment]
@rlabrecque we're on 2019.4.5f1 and working on patching up to the latest 2019.4.x currently. I ran into the issue again the other day after switching branches and replacing the dll in the root fixed it again but deleting it altogether broke things. Maybe that's in a later 2019.4 patch?

**Comment by rlabrecque** [comment]
Hrm, yeah, I'd be very curious to know if updating to 2019.4.32f1 fixes this?

Using https://github.com/rlabrecque/Steamworks.NET-Example with a fresh clone of it, on 2019.4.32f1, I had no problems with the following:

1. Cloning
2. Opening the project with Unity
3. Switching to the "Main Scene"
4. Playing in the editor

Instantly resulted in playing SpaceWar in steam, and all stats/achievement logic in it started populating correctly.

If you're on an older version of Steamworks .NET it could also be an issue around this stuff, which has been corrected around Steamworks.NET 20.0.0:
![image](https://user-images.githubusercontent.com/2047188/150700674-1df5955b-c412-4bc0-b3e4-1c09f595ef54.png)

**Comment by rlabrecque** [comment]
Hey @lux, I got to try this out with Unity 2019.4.5f1 today, and was able to open up and run the project in the editor out of the box.
I was thinking maybe it's due to the Package Manager version, so I tried with the .unitypackage version, and that worked fine as well.

My thinking at this point is maybe the .meta files aren't being updated with the .dll import settings for the Plugins folder above, that would make sense if you are updating, and had manually imported Steamworks.NET into the project and created your own .meta files, or maybe .meta files just don't get updated?

It could also be the case that you could have two installs of Steamworks.NET after upgrading since the folder structure changed to support the Unity Package Manager; Assets\com.rlabrecque.steamworks.net\Plugins and Assets\Plugins\x86
