### ISSUE TITLE
Compilation fails due to case-sensitivity issue in "SteamRemoteplay" directory name

### ISSUE THREAD

**Issue by StagnationPoint** [rlabrecque/Steamworks.NET#374]
Thanks for all your hard work! Ran into a tiny issue with a trivial fix.

I'm building Standalone (on Ubuntu 18.04, Rider 2020.2, Steamworks.NET at latest commit as of today) and getting the following error:

Source file '/home/huh/git/Steamworks.NET/Standalone/../Plugins/Steamworks.NET/types/SteamRemotePlay/RemotePlaySessionID_t.cs' could not be found.

Renaming as follows fixes it:

/Plugins/Steamworks.NET/types/SteamRemoteplay -> /Plugins/Steamworks.NET/types/SteamRemotePlay

**Comment by rlabrecque** [comment]
Thanks @StagnationPoint ! Case sensitivity is an unsolved problem in computer science. :(
