### ISSUE TITLE
NotSupportedException with IL2CPP 

### ISSUE THREAD

**Issue by garv3** [rlabrecque/Steamworks.NET#377]
When an IL2CPP build is launched, the Debugger logs

---
NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition. The method we're attempting to marshal is: SteamManager::SteamAPIDebugTextHook
  at Steamworks.NativeMethods.ISteamClient_SetWarningMessageHook (System.IntPtr instancePtr, Steamworks.SteamAPIWarningMessageHook_t pFunction) [0x00000] in <00000000000000000000000000000000>:0 
  at SteamManager.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

---

**Comment by garv3** [comment]
Really? Nothing on this?
This bug makes the Plugin completely useless for IL2CPP which should be the way to go.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET-SteamManager/pull/5

This has been fixed here, and will be in the next release! Could you grab that version to validate that this fix worked for you?

**Comment by garv3** [comment]
@rlabrecque 
I just added line 48 of the pull request you linked. Seems to have fixed the issue. Thanks!
