### ISSUE TITLE
Steamworks always copies the plugins to an architecture specific folder on windows, this causes issues on editors prior to 2019.3

### ISSUE THREAD

**Issue by LeeHammerton** [rlabrecque/Steamworks.NET#379]
Editors prior to 2019.3 copy windows native plugins to the root of the Plugins folder. They don't place them into architecture specific folders. While Unity will happily run with either approach, a conflict arises if both styles are used :

E.g. a windows 64 bit standalone player will look for all plugins in Plugins/x86_64 if the x86_64 folder exists, otherwise it looks in the root. 

So, if i have a native plugin dll in my build in addition to the steamworks package, then the plugin will never be loaded because it is copied to Plugins  but steamworks has created a Plugins/x86_64 folder, and thus the player looks for all plugins in this location. 

I believe on versions prior to 2019.3 the code in RedistCopy should be placing the native dlls Plugins folder directly and not in architecture specific folders.

**Comment by rlabrecque** [comment]
This is being tracked here: https://github.com/rlabrecque/Steamworks.NET/issues/389

Some progress has been made!
