### ISSUE TITLE
System.AccessViolationException when requesting current user stats

### ISSUE THREAD

**Issue by AngeloG** [rlabrecque/Steamworks.NET#38]
On my machine, running the following code produces an `AccessViolationException` in the `RunCallbacks` method:

```C#
    Environment.SetEnvironmentVariable("SteamAppId", NW.STEAMAPPID.ToString());
    SteamAPI.Init();
    var cb = Callback<UserStatsReceived_t>.Create((UserStatsReceived_t pCallback) => {
      Console.WriteLine(pCallback.m_eResult);
    });
    bool bSuccess = SteamUserStats.RequestCurrentStats();
    SteamAPI.RunCallbacks();
    System.Threading.Thread.Sleep(1000);
    SteamAPI.RunCallbacks();
```

This also happens when I run with the Spacewar AppID.

Also, `bSuccess == true`, and the callback never gets called. The exception occurs on the second `RunCallbacks()` call.

If I don't set the callback, the exception does not get thrown.

**Comment by AngeloG** [comment]
I've updated it to the latest version and it still throws the exception.

**Comment by rlabrecque** [comment]
I've got a repro, looking into it!

**Comment by AngeloG** [comment]
Awesome, thank you!
