### ISSUE TITLE
How to check for DLC?

### ISSUE THREAD

**Issue by mauricin** [rlabrecque/Steamworks.NET#382]
I'm a newbie coder and I couldnt find the right function in any of the classes; SteamUser, SteamUserStats, SteamUtils or SteamVideo, I'm trying to check if a DLC is purchased and installed ( with C++ one would use  ISteamApps::BIsDlcInstalled to check it).

I've found however `Steamworks.DlcInstalled_t` callback but I can't get it to run on my script, probably because "Steamworks" is a namespace and not a class.
How can I run this or turn it into a function inside one of the classes?

**Comment by KelsamGames** [comment]
SteamApps.BIsDlcInstalled(new AppId_t(APP_ID)) or SteamApps.BIsSubscribedApp(new AppId_t(APP_ID))
