### ISSUE TITLE
Documentation still references needing CSteamworks even though it's not needed.

### ISSUE THREAD

**Issue by vchelaru** [rlabrecque/Steamworks.NET#383]
The documentation states to include CSteamworks in the project:

https://steamworks.github.io/installation/

![image](https://user-images.githubusercontent.com/729631/95669512-c96a5900-0b3e-11eb-8a94-22340220ed7c.png)

However, it seems like this is no longer needed.

![image](https://user-images.githubusercontent.com/729631/95669517-e99a1800-0b3e-11eb-96be-7b59d72616d7.png)

This causes confusion unless the user happens to search through the releases. The docs should be updated to no longer reference this file.

**Comment by rlabrecque** [comment]
Thanks for the heads up! This has been fixed!

https://github.com/rlabrecque/Steamworks.NET-Docs/commit/1ac351e1bba2e0da0d6e60dc988516c028914b42
