### ISSUE TITLE
Steam IAP?

### ISSUE THREAD

**Issue by webyilmaz-services** [rlabrecque/Steamworks.NET#386]
Can i create Steam IAP my Game on Steamworks.NET?

**Comment by rlabrecque** [comment]
Sort of -- really just need to use this on the game side.

https://partner.steamgames.com/doc/api/ISteamUser#MicroTxnAuthorizationResponse_t

Steam IAP requires some non-game infrastructure to work though which is not covered by/relevant to Steamworks.NET.

https://partner.steamgames.com/doc/features/microtransactions/implementation

**Comment by webyilmaz-services** [comment]
why don't you have your own document? C ++ document in steam.

**Comment by KelsamGames** [comment]
Steamworks.NET is a wrapper that makes interfacing with Steamworks SDK via C# really easy and clean. For implementation details, consult the Steamworks SDK documentation (as linked in Riley's comment)
