### ISSUE TITLE
Steam Inventory Always Return 0

### ISSUE THREAD

**Issue by samety-dev** [rlabrecque/Steamworks.NET#387]
Can i try steam get user item on inventory but always return 0 but have 1 item.

![image](https://user-images.githubusercontent.com/67427246/98297210-1cf88700-1fc5-11eb-9958-caf6f529a50e.png)
![image](https://user-images.githubusercontent.com/67427246/98297229-2550c200-1fc5-11eb-9259-4a369f1c41ab.png)

**Comment by KelsamGames** [comment]
Steamworks.NET is a C# wrapper for the Steamworks SDK. Please direct your Steamworks implementation questions here: https://steamcommunity.com/groups/steamworks

**Comment by rlabrecque** [comment]
Are you able to reproduce this with Steamworks.NET-Test?

I tried it out over there on the Inventory tab with the following results:

```
SteamInventory.GetAllItems(out m_SteamInventoryResult) : True -- 0

[4701 - SteamInventoryFullUpdate] - 0

[4700 - SteamInventoryResultReady] - 0 -- k_EResultOK

SteamInventory.GetResultItems(0, m_SteamItemDetails, out OutItemsArraySize) - True -- 2
0 - 374133949306211768 - 102 - 1 - 0
1 - 375259540656310777 - 100 - 1 - 0
```

https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamInventoryTest.cs#L76-L93
