### ISSUE TITLE
steam init fails on unity4.3 mac osx 

### ISSUE THREAD

**Issue by madpoet1** [rlabrecque/Steamworks.NET#39]
I'm using the Steamworks.NET -Test-master in Unity 4.3.4 on OS X10.8.5 and I always get the
SteamAPI_Init() failed in the console. I've tried using my app id from the
store page and the default one 480 from the steam_appid.txt file but it
never connects. What have I missed? Do i need to copy dlls to root folder?
if so,  where are the instructions for doing that?

Any tips very appreciated.

**Comment by dylanh724** [comment]
Heya - what was done to resolve this? In 2018, still getting this on osx. They can't init
