### ISSUE TITLE
SetStats returns false, but stat seems to be set anyway

### ISSUE THREAD

**Issue by habitoti** [rlabrecque/Steamworks.NET#391]
Hi,

I am struggling a bit with my first Steam integration for achievements for a Unity app. I have a progressive achievement tied to a stats counter. I think I have all the prerequisites correctly in place, and RequestCurrentStats fires the callback and announces success. Then I do a SetStats on the progress counter, but this returns false. Doing StoreStats anyway, however, succeeds, and when I later on (after a restart) read the same stats, the new value is properly returned. So it all seems to work, however SetStats returns false halfway. All the conditions listed for getting true here are met, I think. 
Any hint what I can try to dig deeper? How can I use  the steam console to get more low-level information? Haven't found anything how to do that. Or are there any server side logs to get more details?

Thanks, habitoti

**Comment by rlabrecque** [comment]
Hmm you seem to have everything set up on the Steamworks.NET side. Did you ever figure out what this was?

Searching the forum for answers I found this:

```
Yeah, they're in the backend, and published.

EDIT: DOH! Just found the problem. I had set the MaxValue for the stats in the dashboard to greater than int.max. 
```

One other thing could be checking that you're running under the correct appid.

There might be some info in: `Steam\logs\stats_log.txt` and this might help as well: https://partner.steamgames.com/doc/sdk/api/debugging
