### ISSUE TITLE
Upgraded to Steamworks.NET 6.0.0, and SteamAPI.Init() doesn't work on a Mac anymore

### ISSUE THREAD

**Issue by jkarkkainen** [rlabrecque/Steamworks.NET#40]
Trying to init SteamAPI on mac results in the following error:

[S_API FAIL] SteamAPI_Init() failed; ipcserver GetSteamPath failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dylib.
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.

The game was started from Steam, so Steam was definitely running. This used to work properly on version 4.0.0. I checked the documentation and didn't see anything pertaining to this specific problem.

**Comment by jkarkkainen** [comment]
Weirdly, restarting Steam fixed, at least for now.

**Comment by Wargog** [comment]
You should probably close the issue for now until you encounter the issue again.

**Comment by jkarkkainen** [comment]
Oops, sorry. Closing for now.
