### ISSUE TITLE
DllNotFoundException: steam_api on macos

### ISSUE THREAD

**Issue by artiszinbergs** [rlabrecque/Steamworks.NET#400]
I am using macos 11.2 with the new m1 apple chip and I'm trying to bring the official OSX support to my game made using Unity 2020.2.1 but I'm getting this issue.

I've already used #393 to get the bundle copied over into the app but it's still failing to find the dylib. I've copied several versions all over the place but it still won't find it.

Here's my log, at least the relevant part

Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/steam_api
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library /Users/artiszinbergs/Desktop/UZD.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Uploading Crash Report
DllNotFoundException: steam_api
  at (wrapper managed-to-native) Steamworks.NativeMethods.SteamAPI_GetHSteamUser()
  at Steamworks.SteamAPI.GetHSteamUser () [0x00007] in /Users/artiszinbergs/development/UltimateZombieDefense/Project/Assets/Plugins/Steamworks.NET/Steam.cs:143 
  at Steamworks.CSteamAPIContext.Init () [0x00001] in /Users/artiszinbergs/development/UltimateZombieDefense/Project/Assets/Plugins/Steamworks.NET/Steam.cs:308 
  at Steamworks.InteropHelp.TestIfAvailableClient () [0x0001b] in /Users/artiszinbergs/development/UltimateZombieDefense/Project/Assets/Plugins/Steamworks.NET/InteropHelp.cs:40 
  at Steamworks.SteamUtils.IsSteamChinaLauncher () [0x00001] in /Users/artiszinbergs/development/UltimateZombieDefense/Project/Assets/Plugins/Steamworks.NET/autogen/isteamutils.cs:284

**Comment by yaakov-h** [comment]
I don't believe Steam/Steamworks ships arm64e slices yet?

**Comment by artiszinbergs** [comment]
Shouldn't the x64 counterpart still be found? Tthe game is built using the x64 configuration so it should be using the rosetta process to work

**Comment by artiszinbergs** [comment]
Actually, if I forcefully set the app to run with rosetta it manages to find it but fails to initialise steam, which is a completely different problem I guess

**Comment by LeandroExhumed** [comment]
Do you guys found any solution for this?
