### ISSUE TITLE
Missing SteamNetworkingUtils.InitRelayNetworkAccess

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#403]
https://partner.steamgames.com/doc/api/ISteamNetworkingUtils.InitRelayNetworkAccess

This method is missing ... working on learning SteamNetworkingSockets and expected to see this

**Comment by AG4W** [comment]
Second this, method is also referenced in the comments of other methods where it's suggested to use it, could be worth editing those docs aswell.
