### ISSUE TITLE
Platforms and defines

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#404]
At current the head of your files all have a check for platform and define DISABLESTEAMWORKS if one is true ... the issue with this is Unity likes to add/change the platforms it has so for example P5 and Xbox SX or whatever else they go with is missing from your current checks

#if !UNITY_STANDALONE
#define DISABLESTEAMWORKS
#endif

The above check however should cover all your bases

**Comment by NikMikk** [comment]
You can also create an Assembly Definition which only is compiled for the Standalone platforms

![image](https://user-images.githubusercontent.com/19763760/108637945-31399480-748d-11eb-91a2-0d4778d63f54.png)

**Comment by rlabrecque** [comment]
This should have been fixed by: https://github.com/rlabrecque/Steamworks.NET/pull/384 👍
