### ISSUE TITLE
RunCallbacks throws AccessViolationException

### ISSUE THREAD

**Issue by Pyroblasted** [rlabrecque/Steamworks.NET#41]
When calling CreateLobby and setting the handle of the CallResult of LobbyCreated_t then RunCallbacks throws AccessViolationException.

```
CallResult<LobbyCreated_t> m_LobbyCreated;

SteamAPI.Init();
m_LobbyCreated = CallResult<LobbyCreated_t>.Create((LobbyCreated_t t, bool failure) =>
{
    Console.WriteLine("callresult");
});
SteamAPICall_t t1 = SteamMatchmaking.CreateLobby(ELobbyType.k_ELobbyTypePublic, 2);
m_LobbyCreated.Set(t1);

SteamAPI.RunCallbacks();
```

This applies to the standalone version.

**Comment by rlabrecque** [comment]
Is it on Windows?

This commit fixes it. Not fixed in the prebuilt dll's yet, sorry!

https://github.com/rlabrecque/Steamworks.NET/commit/5b4261c1cee6543e74aeabb3e1b4d2aa474269ac

**Comment by Pyroblasted** [comment]
I downloaded the updated version and compiled it. I then tried it in two different project, one of which was a Console Application and the other one an XNA Application, and the error only happens when running it in an XNA Application interestingly enough. The code and build settings are identical, but the XNA one will throw the exception
