### ISSUE TITLE
[v15.0.0 - 15.0.1] Missing CCallbackBase and CCallbackBaseVTable classes in unitypackage

### ISSUE THREAD

**Issue by Allexeee** [rlabrecque/Steamworks.NET#416]
Hi!
In version 15.0.0 and 15.0.1, the CCallbackBase and CCallbackBaseVTable classes are missing from unitypackage.

I had to add them from version 14.0.0.

**Comment by rlabrecque** [comment]
Hey there @Allexeee, could you explain your use case? The entire CallbackDispatcher got rewritten to support Unity's IL2CPP and the whole process is accomplished in C#.

Were you running a custom callback loop or something like that?

**Comment by rlabrecque** [comment]
Hey there, what version of Unity are you on, and which version were you coming from? I can't reproduce this. On a fresh project with Unity 2020.3 Importing 15.0.1 from the UnityPackage seemed to work without issues, then additionally tried doing an upgrade from 14.0.0 -> 15.0.1 and it seemed to be fine.
