### ISSUE TITLE
Duplicate libsteam_api.so error on Building for Mac from Windows 

### ISSUE THREAD

**Issue by wagenheimer** [rlabrecque/Steamworks.NET#417]
When I try to create a build for Mac from Windows using SteamWorks.NET it fails with the following error!

Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

The only way I can complete the build is by deleting the  Assets/Plugins/x86 folder. But this does not solve my problem because I need this folder for Windows Build.

How is the correct behavior to fix this?

**Comment by wagenheimer** [comment]
Even completing the build, I have to manually copy steam_api.bundle file to the resulting App to make it work.

**Comment by zephyo** [comment]
I also get this error

**Comment by rlabrecque** [comment]
Yeah the default settings for importing .bundle's and .so's regressed in Unity 2019+ unfortunately. The latest version on master has a fix by bundling the .meta files so they don't explicitly go through the import pipeline. Should make it's way into a release soon. You can manually fixup the Unity settings as outlined here: https://github.com/rlabrecque/Steamworks.NET/issues/393#issuecomment-764801885
