### ISSUE TITLE
LobbyChatMsg_t doesn't get called.

### ISSUE THREAD

**Issue by 3GamersStudios** [rlabrecque/Steamworks.NET#418]
My script looks like this and when I make a build and test (by myself) it doesn't call HandleIncomingMessage 
 protected Callback<LobbyChatMsg_t> IncomingMessage;

    byte[] PvChat = new byte[1024];
    int CubeData;
    int CHatID;

    [SerializeField] private GameObject ChatMessageButton = null;
    [SerializeField] private Transform Content = null;
    [SerializeField] private TMP_InputField Input = null;

    public static CSteamID HostID;

    // Start is called before the first frame update
    void Start()
    {
        IncomingMessage = Callback<LobbyChatMsg_t>.Create(HandleIncomingMessage);
    }

    // Update is called once per frame
    void Update()
    {
        SteamAPI.RunCallbacks();
    }

    [ServerCallback]
    private void HandleIncomingMessage(LobbyChatMsg_t callback)
    {
        Debug.Log("RecivedMessage");
        CHatID = (int)callback.m_iChatID;
        int Bytes = SteamMatchmaking.GetLobbyChatEntry(
            new CSteamID(callback.m_ulSteamIDLobby),
             CHatID,
             out CSteamID PlayerID,
             PvChat,
             CubeData,
            out EChatEntryType peChatEntryType
            );
        string message = PvChat.ToString();
        ChatHandle(message, PlayerID);
        
    }
    [Server]
    private void ChatHandle(string message, CSteamID Id)
    {
        string name = SteamFriends.GetFriendPersonaName(Id);
        GameObject prefabInstance = Instantiate(ChatMessageButton, Content);
        TMP_Text text = prefabInstance.GetComponentInChildren<TMP_Text>();
        text.text = $"{name}: {message}";
        NetworkServer.Spawn(prefabInstance);
    }
    [Client]
    private bool SendChatMessage(string Message, CSteamID ID)
    {
        
        byte[] message = new byte[1024];
        message = Encoding.ASCII.GetBytes(Message);
        return SteamMatchmaking.SendLobbyChatMsg(ID, message, message.Length);
    }
    public void ButtonSendPress()
    {
        Debug.Log("Yes");
        string Message = Input.text;
        Debug.Log( SendChatMessage(Message, HostID));
    }

**Comment by rlabrecque** [comment]
Just checking is `HostID` the lobby's CSteamID, or the host of the lobby's CSteamID?

It should probably be the Lobby's CSteamId

**Comment by 3GamersStudios** [comment]
Yeah I got it all figured out, I had callbacks disabled somehow! If you were going to communicate with the other players in a lobby you would send a packet via send p2p, I want to implement voice chat and have everything but the actual send, and is reliable better or no delay or what are your recommendations? Thanks!

**Comment by AG4W** [comment]
@3GamersStudios The steamworks docs recommend `Unreliable | NoDelay | NoNagle` for audio, see here: https://partner.steamgames.com/doc/api/steamnetworkingtypes
