### ISSUE TITLE
Win & Linux doesn't launch Steam Client if it is not launched.

### ISSUE THREAD

**Issue by Samuraisa** [rlabrecque/Steamworks.NET#42]
SteamManager script for Unity3D (we are using 4.6 Pro version) does not launch Steam client with SteamAPI.RestartAppIfNecessary(appId) call on Win and Linux builds.

**Comment by rlabrecque** [comment]
Wow, I'm sorry that I missed this!

My guess is that you had/have a steam_api.txt next to your exe which causes SteamAPI.RestartAppIfNecessary() to essentially do nothing. Largely a Steamworks issue and out of my control though.
