### ISSUE TITLE
Segfault on `SteamGameServerNetworkingSockets.SendMessages`

### ISSUE THREAD

**Issue by IvMisticos** [rlabrecque/Steamworks.NET#421]
When calling `SteamGameServerNetworkingSockets.SendMessages` the Segmentation fault occurs in the following code:

```cs
// Fields
byte[] Data;
HSteamNetConnection Connection;
int SendFlags;

void Send() {
// The send method
var message = Marshal.PtrToStructure<SteamNetworkingMessage_t>(SteamGameServerNetworkingUtils.AllocateMessage(Data.Length));

message.m_conn = Connection;
message.m_nFlags = SendFlags;

Marshal.Copy(Data, 0, message.m_pData, Data.Length);

var messages = new[] {message};

var messagesr = new long[messages.Length]; // Just so that it exists, idk what to do with it
SteamGameServerNetworkingSockets.SendMessages(messages.Length, messages, messagesr);
}
```

What could go wrong, what am I doing wrong? Same happens when I use `SteamGameServerNetworkingSockets.SendMessageToConnection`.

**Comment by IvMisticos** [comment]
Is this an issue with my C# code, or I misunderstand the Steamworks documentation, or an issue with Steamworks itself?

**Comment by yaakov-h** [comment]
I suspect it is both, this looks extremely tricky.

The immediate point of suspicion is that `PtrToStructure` does not map that memory to a .NET struct, but _copies_ it.

Then, and I might be reading the method signatures wrong here, but `SendMessages` appears to want a pointer to a set of pointers, but Steamworks.NET is instead passing it a pointer (marshalled array) to a set of structs.

It also looks like you're not setting some of the fields on `SteamNetworkingMessage_t` - such as the function to free the data, which looks particularly sus.

Lastly, since the data is not pinned or in any way retained for the native Steamworks components, the .NET memory manager is free to move the data around in memory and garbage-collect it while Steam is still trying to use it, which is bound to crash eventually.

**Comment by IvMisticos** [comment]
The free function is managed by Steamworks itself if I specify amount of bytes in `SteamGameServerNetworkingUtils.AllocateMessage()` method arguments, pretty sure I don't have to unless I specify 0 or such.

**Comment by IvMisticos** [comment]
I'm copying the data to the buffer Steam allocated and does manage and will free on its own with Marshal.Copy (at least that's what I think it should do), means .NET should not free the data that is.. not even managed, it's Steamworks allocated memory, unmanaged. I just copy my data to a pointer Steamworks gives me.

**Comment by IvMisticos** [comment]
@rlabrecque and I do agree that it looks weird that the Steamworks documentation requires pointers, but we are passing an array of structs.

**Comment by yaakov-h** [comment]
I’m not sure if your game engine supports it or not, but Unsafe.AsRef is probably more correct here than PtrToStructure. Unless you want to copy it back with StructureToPtr?

**Comment by IvMisticos** [comment]
Alright, used Unsafe.AsRef, but don't think it helped still. Might consider passing array of pointers with custom Steamworks.NET build to see if it works.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/issues/411

This may help you, I can't quite take a look at this deeper yet though

**Comment by IvMisticos** [comment]
So far NOT calling `message.Release` helped us move a bit further, still testing.

**Comment by rlabrecque** [comment]
Hmm can you check this one out too: https://github.com/rlabrecque/Steamworks.NET/issues/388

**Comment by fghl** [comment]
I have this working. I'm writing a Unity MLAPI SteamNetworkingSockets transport, and I can get it to send messages.

It's likely got all kinds of issues, but I can at least get it to send and receive the MLAPI internal handshake.

This is the relevant code
```
    IntPtr sendBuffer = Marshal.AllocHGlobal(65536);
    
    ...
    
    
    // Send a message to a specific client (or the server, if you are a client)
    public override void Send(ulong clientId, ArraySegment<byte> data, NetworkChannel channel)
    {
      int nSendFlags = ChannelSendFlags[channel];
      HSteamNetConnection sendToHConn = isServer ? steamIdToHConn[clientId] : serverHConn;

      Debug.Log($"Send(clientId {clientId}, data {data}, channel {channel});");

      try
      {
        Marshal.Copy(data.Array, 0, sendBuffer, data.Array.Length);
        SteamNetworkingSockets.SendMessageToConnection(sendToHConn, sendBuffer, (uint)data.Array.Length, nSendFlags, out _);
      }
      catch
      {
        Marshal.FreeHGlobal(sendBuffer);
      }
    }
```

**Comment by IvMisticos** [comment]
This is due to Release indeed. Can we have it fixed so that it passes what it actually should, or make it accept an argument?

**Comment by IvMisticos** [comment]
Also please expose `m_pfnFreeData` since it's supposed to be settable by users, unless you're willing to make a pooling and stuff helper.
