### ISSUE TITLE
steam_api.bundle for macOS does not support arm64 architecture (aka Apple Silicon)

### ISSUE THREAD

**Issue by jason-yak** [rlabrecque/Steamworks.NET#422]
Hi there,

Can the steam_api.bundle please be rebuilt with Build Setting to include arm64 architecture? it's currently only set to i386 and x86_64. 

I've used this command to inspect the dylib found within the plugin bundle:
_lipo -info libstream_api.dylib_

which gives me the result:
_Architectures in the fat file: libsteam_api.dylib are: i386 x86_64_ 

It "should" be a relatively simple change to rebuild adding the architecture to the build settings (hopefully it's that simple). This one thing is preventing all devs that use this wrapper from being able to build a mac app that natively supports Apple Silicon (arm64) for mac Steam users.

Thanks!

**Comment by rlabrecque** [comment]
Hey Jason, unfortunately it's not quite that simple; that file comes from the Steamworks SDK, so we'll need to wait for them to update. Might be worth asking on the Steamworks Dev forums

**Comment by jason-yak** [comment]
ahh of course, I'll post there and see if I can get some traction, thanks =)

**Comment by rlabrecque** [comment]
https://steamcommunity.com/groups/steamworks/discussions/0/3105773861187611710/

Discussion has moved here, hopefully this just works once Steam itself supports arm64!
