### ISSUE TITLE
Instant Crash on MacOS when app is launched

### ISSUE THREAD

**Issue by piesliceproductions** [rlabrecque/Steamworks.NET#423]
I had some problems with this error:

```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

```
I read some other bug reports and I downloaded the latest master branch _(as of June 1st 2021)_ of the SDK and integrated it to my project. 
The project compiled successfully after the integration but when I tried to launch it, it crashed instantly.

The Steam client being running or not makes no difference.

If I build with the DISABLESTEAMWORKS everything works but of course I can't use the Steam features.

My machine is 2015 Macbook Pro Retina with Big Sur.
Unity version is the latest 2019 LTS of this date (2019.4.27f1).

br, Pieslice

**Comment by piesliceproductions** [comment]
I created a Xcode project. It does not compile at all.
The **steam_api.dll** and **steam_api64.dll** files in the PlugIns/ folder are marked as red.

Both of the files throw this error when I try to compile the build
`error: <my project folder>/PlugIns/steam_api.dll: No such file or directory
`

I am using the latest version of the Xcode.

**Comment by piesliceproductions** [comment]
I was able to get the Xcode project to compile just by removing the two dll files (as far as I know the dll files are not relevant for Mac systems anyway).

I also got the app running as well. Looks like there is sort of chicken-and-egg problem - you need to have some sort of executable uploaded to Steam before the Steamworks SDK starts to work - it can't connect to Steam without a build being present.

As I've developed the game for Windows systems before starting to port it for MacOS I did not have a Mac binary in Steam before I started to test the builds. By uploading a beta build _(compiled with DISABLESTEAMWORKS just in case)_ I was able to get the local builds with Steamworks SDK to work as well.

This might be useful information for someone.

Br, Pieslice

**Comment by rlabrecque** [comment]
Hmm, I'm thinking that it's probably [SteamAPI_RestartAppIfNecessary](https://partner.steamgames.com/doc/sdk/api#SteamAPI_RestartAppIfNecessary)'s doing. Presumably the application is not necessarily shutting down, but gracefully quitting to be relaunched by Steam?

**Comment by piesliceproductions** [comment]
> Hmm, I'm thinking that it's probably [SteamAPI_RestartAppIfNecessary](https://partner.steamgames.com/doc/sdk/api#SteamAPI_RestartAppIfNecessary)'s doing. Presumably the application is not necessarily shutting down, but gracefully quitting to be relaunched by Steam?

Yes I think that is the case ☝️ 

The Windows build does the same thing as well. If you run a build that has the Steamworks SDK enabled the build executable actually runs the version that is in Steam - if you want to run the builds with the Steamworks features you must upload them as Steam beta builds every time you do a testing outside the editor.

Luckily in my codebase all code referencing the Steamworks is accessed by an interface - I just inject a mock implementation of the Steamworks wrapper if I build with the DISABLESTEAMWORKS preprocessor define so I can do local builds without much hassle.

I am closing this issue since it is not really a bug in the .NET Steamworks SDK, but more like a quirk how the actual Steamworks implementation works.

Br, Pieslice

**Comment by rlabrecque** [comment]
Yep that sounds like the perfect way to do it with the mock interface!

Would logging when restarting with RestartAppIfNecessary in the default SteamManager implementation have helped? I think that's going to be part of the solution to improve this. Just a little note that it's shutting down and Steam should be restarting it.
