### ISSUE TITLE
Segfault on `SteamNetworkingMessage_t.Release()`

### ISSUE THREAD

**Issue by fghl** [rlabrecque/Steamworks.NET#424]
Hi there,

I'm running the latest (giturl) install of Steamworks.NET and am sending and receiving messages just fine it seems.

However when I call the recommended `Release` method on a `SteamNetworkingMessage_t`, I get a segfault.

My code is here:
```
        try
        {
          SteamNetworkingMessage_t netMessage = Marshal.PtrToStructure<SteamNetworkingMessage_t>(receiveBuffers[0]);
          byte[] message = new byte[netMessage.m_cbSize];
          Marshal.Copy(netMessage.m_pData, message, 0, message.Length);


          payload = new ArraySegment<byte>(message);
          clientId = netMessage.m_identityPeer.GetSteamID64();

          Debug.Log($"PollEvent(); // message received at {receiveTime} from {clientId}");

          netMessage.Release(); // <----- Commenting this line prevents segfault
        }
        finally
        {
          Marshal.DestroyStructure<SteamNetworkingMessage_t>(receiveBuffers[0]);
        }
```

Any ideas? Happy to share more code if needed.

**Comment by rlabrecque** [comment]
Are these helpful?

https://github.com/rlabrecque/Steamworks.NET/issues/421

https://github.com/rlabrecque/Steamworks.NET/issues/388

**Comment by AG4W** [comment]
> 
> 
> Hi there,
> 
> I'm running the latest (giturl) install of Steamworks.NET and am sending and receiving messages just fine it seems.
> 
> However when I call the recommended `Release` method on a `SteamNetworkingMessage_t`, I get a segfault.
> 
> My code is here:
> 
> ```
>         try
>         {
>           SteamNetworkingMessage_t netMessage = Marshal.PtrToStructure<SteamNetworkingMessage_t>(receiveBuffers[0]);
>           byte[] message = new byte[netMessage.m_cbSize];
>           Marshal.Copy(netMessage.m_pData, message, 0, message.Length);
> 
> 
>           payload = new ArraySegment<byte>(message);
>           clientId = netMessage.m_identityPeer.GetSteamID64();
> 
>           Debug.Log($"PollEvent(); // message received at {receiveTime} from {clientId}");
> 
>           netMessage.Release(); // <----- Commenting this line prevents segfault
>         }
>         finally
>         {
>           Marshal.DestroyStructure<SteamNetworkingMessage_t>(receiveBuffers[0]);
>         }
> ```
> 
> Any ideas? Happy to share more code if needed.

You can wrangle NativeMethods in this way to expose the underlying method (internal to public) and call it through the API.

`#region SteamNetworkingMessage_t Accessors
		[DllImport(NativeLibraryName, EntryPoint = "SteamAPI_SteamNetworkingMessage_t_Release", CallingConvention = CallingConvention.Cdecl)]
		public static extern void SteamAPI_SteamNetworkingMessage_t_Release(IntPtr self);
#endregion`

I use some extension methods to do it.

`public static class MessageExtensions
{
    public static T To<T>(this IntPtr pointer) => Marshal.PtrToStructure<T>(pointer);
    public static void Read(this IntPtr pointer, NetworkBuffer buffer) => Marshal.Copy(Marshal.PtrToStructure<SteamNetworkingMessage_t>(pointer).m_pData, buffer.Payload, 0, buffer.Payload.Length);
    public static void Release(this IntPtr pointer) => NativeMethods.SteamAPI_SteamNetworkingMessage_t_Release(pointer);
}
`

**Comment by fghl** [comment]
Thanks, that's really helpful. For now I've paused my Steamworks.NET work and am porting to Facepunch.Steamworks until there's an official fix here. They may also have issues, in which case I'll come back and try this.

**Comment by fghl** [comment]
Their interface is [even more broken](https://github.com/Facepunch/Facepunch.Steamworks/issues/455). Trying this.

**Comment by fghl** [comment]
@AG4W This worked as advertised, thanks for the help!
