### ISSUE TITLE
Why not pullable from package manager? 

### ISSUE THREAD

**Issue by loeffel-io** [rlabrecque/Steamworks.NET#427]
`[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/rlabrecque/Steamworks.NET.git]:
  [https://github.com/rlabrecque/Steamworks.NET.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()`

**Comment by rlabrecque** [comment]
Steamworks.NET supports non-Unity projects as well, so you need the full path to the unity project itself:

`https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net`

Note that this is still pretty early, and you'll need to get SteamManager separately still: https://github.com/rlabrecque/Steamworks.NET-SteamManager/blob/master/SteamManager.cs
