### ISSUE TITLE
What callback for InviteUserToGame?

### ISSUE THREAD

**Issue by MaximSchoemaker** [rlabrecque/Steamworks.NET#43]
I use InviteUserToGame to invite others to join my game. I don't use Steam game lobbies for matchmaking so I want to be able to send a string with a match ID from my own system. My setup works for when the other player hasn't opened the game yet. InviteUserToGame makes your friend get a match request in his steam chat, which he can accept and that prompts him if he wants to open the game with the matchId as a command line argument. And that's great :)

But I want this to work when your friend already has the game opened. I'm guessing there's a callback that gets called and I tried using the GameLobbyJoinRequested_t, but it won't trigger. I was wondering what callback I should register to receive a InviteUserToGame message.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/blob/591a93519d789cb28b07e809fb6c710ebaeb40d2/Plugins/Steamworks.NET/autogen/isteamfriends.cs#L453

;)

This isn't and shouldn't be a general support 'forum', it's not specific to Steamworks.NET and you would have gotten a much quicker answer on the Steamworks discussion board!

**Comment by MaximSchoemaker** [comment]
Sorry about that! And thx :)
