### ISSUE TITLE
New Achievements added to Steam Works dont show up.

### ISSUE THREAD

**Issue by sbmhome** [rlabrecque/Steamworks.NET#435]
I currently have 14 achievements in Steam Works for my game, but they all don't show up in the APIs...only 1 does.

I have published the changes (many times trying to fix this issue),.yet, the API continually shows only 1 achievement.

Making the below call returns false on all 13 of the 14 achievements.
SteamUserStats.GetAchievement(name, out unlocked);  

Making the below call only returns 1.
SteamUserStats.GetNumAchievements()

Notes: 
1. The one achievement that is recognized fully works, I can unlock and lock it and all APIs work correctly for it.
2. My game is currently not in production, I'm releasing it within the next few weeks.

![Screenshot (185)](https://user-images.githubusercontent.com/13279145/127597612-469d3457-7a18-4703-9039-99d91fdfda91.png)

**Comment by sbmhome** [comment]
I just deleted all of my achievements and it still shows 1 achievement. Is there anything special I need to do either in Steam Works or in Steamworks.NET in order for the data to be refreshed?

**Comment by KelsamGames** [comment]
This is a question for the Steamworks SDK dev forums, not Steamworks.NET. That said...

To award an achievement, you need to call SteamUserStats.SetAchievement(achievementId) and SteamUserStats.StoreStats() (read the docs for proper use on both).

Perhaps you're not calling SteamAPI.RunCallbacks() regularly?

**Comment by sbmhome** [comment]
Thanks for the response. I'll close this out.

It seams like it was not an issue with Steamworks.NET, but rather a caching issue on Steams side.
