### ISSUE TITLE
Max 2 libsteam_api loaded

### ISSUE THREAD

**Issue by hookkshot** [rlabrecque/Steamworks.NET#437]
When I try and build I get the issue on a mac build where it tries to include both packages.

![image](https://user-images.githubusercontent.com/3970820/128265227-b37c2e70-d325-4883-9169-1488fa1576c8.png)

This is the 64bit plugin I am certain should be loading for mac

![image](https://user-images.githubusercontent.com/3970820/128265275-78299ab0-e69c-4bea-bb48-5e2124cf3525.png)

The 32bit is set to none for the mac build, so why is it still being included. I don't believe I have changed any settings after importing.

Any assistance would be great.

**Comment by rlabrecque** [comment]
This should be fixed as of 20.0.0 now that we include the .meta files for all plugins 🙏
