### ISSUE TITLE
UGCDetailsRequest description incomplete

### ISSUE THREAD

**Issue by CaseBody** [rlabrecque/Steamworks.NET#438]
SteamUGCDetails_t's m_rgchDescription property returned from SendQueryUGCRequest callback is incomplete. It only returns the first 255 charachters of the workshop item's description.

**Comment by rlabrecque** [comment]
I feel like that may be the way Steamworks API works, it's supposed to be for a "blurb" that you can display on a menu with multiple, I think there's an alternate way to get the full description

**Comment by CaseBody** [comment]
Hi, thank you for the swift response. Would you know where i could find out more about this alternate method?

**Comment by rlabrecque** [comment]
Looks like it might be this:

https://partner.steamgames.com/doc/api/ISteamUGC#SetReturnLongDescription

**Comment by CaseBody** [comment]
It seems so, thank you!
