### ISSUE TITLE
Installation instructions are confusing

### ISSUE THREAD

**Issue by jhorneman** [rlabrecque/Steamworks.NET#44]
I find the instructions on https://steamworks.github.io/installation/ confusing: 

"Download the .unitypackage Stable (6.0.0) or Clone from Github
Extract and copy Steamworks.NET’s Plugins/ and Editor/ folders into your Assets/ folder.
Launch your Unity project. The included editor scripts will copy steam_appid.txt (and steam_api.dll if your on windows) into the root of your project.
Open steam_appid.txt which now resides in the root of your Unity project and replace 480 with your own AppId."

"Extracting" a Unity package is unclear. Does it mean opening it with Unity? Does it mean renaming it to ZIP and extracting it that way?
"copy Steamworks.NET’s Plugins/ and Editor/ folders into your Assets/ folder" suggests manual file copying (which makes the previous line more ambiguous). The most logical step seemed to be to open the package with Unity and just import the Plugins and Editor folders. But that didn't work at all.

When I watched the video here https://www.youtube.com/watch?v=3FJzehQrqJE it became clear what I had to do.

Is it possible this was written before there was Unity bundle?

May I suggest: "Open the package with Unity and import everything"?

**Comment by jhorneman** [comment]
Also - I won't open a new issue for this - in https://steamworks.github.io/gettingstarted/ "signifigently" should be "significantly". (Is there a way to make pull requests on the documentation? :))

**Comment by rlabrecque** [comment]
Hey, thanks for the report, And yeah absolutely that is exactly the cause of the issue. Fixing this up. I should also have installation videos up soonish.
