### ISSUE TITLE
SteamUserStats.DownloadLeaderboardEntries doesnt return right amount of entries

### ISSUE THREAD

**Issue by zygisn** [rlabrecque/Steamworks.NET#444]
Hey guys,

I have a leaderboard and I want to get Leaderboard entries around a user.

In this specific case:
User A is in the First place;

When I try to get Entries around the user:  [UserA_Rank - 1, UserA_Rank, UserA_Rank+1], 
Using:
SteamAPICall_t hSteamAPICall_surroundings = SteamUserStats.DownloadLeaderboardEntries(leaderboard, ELeaderboardDataRequest.k_ELeaderboardDataRequestGlobalAroundUser, -1, +1);

I expect to get 2 rows: UserA_Data and UserA+1_Rank, or at least: [null, UserA_Data, UserA+1]

However, I get 3 rows as a return:  [UserA_Data, UserA+1, UserA+2]

Is it supose to be working like this, or am I doing something wrong?

**Comment by rlabrecque** [comment]
Hey there, I'm genuinely not too sure. this is probably a question better suited for the Steamworks Development Discussion board
