### ISSUE TITLE
Upgrade to v1.52

### ISSUE THREAD

**Issue by jacquesleemans** [rlabrecque/Steamworks.NET#445]
v1.52 was released on 14th September 2021, any ETA on when these changes will be implemented into this repo?

**Comment by rlabrecque** [comment]
By this weekend it should be integrated!

**Comment by BG-AlexMcFarlane** [comment]
Hi is there a new Unity package to install this version?

**Comment by JamesMcGhee** [comment]
@BG-AlexMcFarlane 
You can install directly from the master using Unity's Package Manager assuming you have Git installed on your machine so Unity Package Manager can install from Git. There are a number of fixes in the master that are not present in the current release unitypackage. Important ones if your using 3rd party assets that are built on top of Steamworks.NET like Mirror, MLAPI, FishNet, Heathen's Steamworks, etc.

1. Open the Package Manager
2. Click the "+" (plus) button located in the upper left of the window
3. Select the "Add package from git URL..." option
4. Enter the following URL: 
    https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net
6. Click the "Add" button and wait several seconds for the system to download and install the Steamworks.NET package from GitHub.
