### ISSUE TITLE
SteamGameServerXXXX vs SteamXXXX

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#451]
Less of an issue more of a question

there are a number of SteamGameServerXXXXX interfaces in Steamworks.NET that are not documented in Steam's documentation e.g.

SteamGameServerApp vs SteamApp

The assumption might be that SteamGameServerApp variant is applicable only when the SteamGameServer API is initalized vs the usuall client side initalization.

The confusion comes in when you see things like SteamGameServer.App.BlsGetSubscribed(appId) ... that cant work ... Subscribed is testing if the local user is subscribed Steam Game Server API doesn't have a user so confused.

Also the fact that most of these are not documented by Steam API and Steamworks.NET doens't have a SteamGameServer for every SteamAPI but seemengly for most.

Is it nessisary at all to call SteamGameServerXXXX vs SteamXXXX?
The assumption is yes, SteamXXX test if the client API is available which will throw an exception on server builds
and
SteamGameServerXXX tests if the server API is available which will throw ann exception on client builds

... by question is why not

#if UNITY_SERVER
SteamGameServerXXXXX
#else
SteamXXXXX
#endif
.TargetMethod(...)

This layer of of SteamAPI vs SteamGameServer is not present in Steam's documentation, and is confusing as it includes API calls that just cant work on a server initalization without a logged in Steam user

**Comment by rlabrecque** [comment]
I'll reach out to someone from Valve about the GameServerInventory stuff specifically as well

**Comment by JamesMcGhee** [comment]
Thanks ....
That is likely the approch we will take building out what we know and use our selves and what is clearly documented then filling gaps as they appear. 

That said part of the drive to do this is discovery, we have used Steam API for a few years now and discover new things all the time ... in fact sitting down and working on wrapping all its various bits I have discovered a few I plan on putting to good use.... and I do like reading sterio instructions and have read I thought over all the documents a few times at this point ... yet I keep discovering new bits.

By creating this API wrapper we hope to make it much easier to discover features of Steam through normal use of your IDE ... we are also copying in relivent documentation from Steam's documentation site, addeing in references so you can drill back into the web documentation and adding in our own remarks to help clarify a bit all using Visual Studio's XML comments meaning intelisince and object explorer should let users that know how to use it discover features of Steam API without needing to sit down an make an acadimic study and exploration of Valve's documentation. We will also of course add this API wrapper to our own Knowledge Base which should help as well.
