### ISSUE TITLE
Unity 3.4.2f3: CallbackDispatcher.cs error

### ISSUE THREAD

**Issue by karennk** [rlabrecque/Steamworks.NET#457]
Hi,
I have a game built in Unity 3.4.2f3.
I'm integrating Steamworks.Net but it gives me an error:
**Steamworks You need to define STEAMWORKS_WIN, or STEAMWORKS_LIN_OSX. Refer to the readme for more details.' in CallbackDispatcher.cs**
 
How to resolve it?
Please guide.
Thanks!

**Comment by karennk** [comment]
Ohh so can't I upload an old unity version 3.xxxx game on Steam?

**Comment by karennk** [comment]
Can you please guide in this? 
What If I upload a game without Steamworks.Net integration

**Comment by rlabrecque** [comment]
Yeah, you can upload anything to Steam, you do not need to use the Steamworks SDK unless you need features from it.

**Comment by karennk** [comment]
Thanks @rlabrecque
