### ISSUE TITLE
Callback<Steamworks.GameOverlayActivated_t>' does not contain a definition for `Create'

### ISSUE THREAD

**Issue by laurelhach** [rlabrecque/Steamworks.NET#46]
Hi Guys,

Sorry for asking this question (it's probably something really simple to fix), but I can't figure it out.

I have implemented your SteamScript like on your page, but when I add the Callbacks I get this error:
Assets/Scripts/Steamwork.NET/SteamScript.cs(12,83): error CS0117: `Callback<Steamworks.GameOverlayActivated_t>' does not contain a definition for `Create'

Did I miss something?
Thanks.

PS: Obviously I have imported the unity package 6.0.0 and followed the tutorials.
I can run the game with steam (the shift - tab menu works), etc.

**Comment by rlabrecque** [comment]
Hey @laurelhach, I think I've seen this once or twice. Could you try prefixing the line with "Steamworks."
I.E. Steamworks.Callback<Steamworks.GameOverlayActivated_t>.Create();

Sometimes this happens when there's a name collision.

**Comment by laurelhach** [comment]
Hi @rlabrecque,

Thanks, it works :) it was so simple! 
Btw, your work is amazing! I'll have to start digging into all the different options as I am not familiar with all of that but it's a relief that you made it easy to use for us.

Thanks again for your quick answer and your work!
