### ISSUE TITLE
Errors on Unity 2020.3.21f1

### ISSUE THREAD

**Issue by sk3tcherrs** [rlabrecque/Steamworks.NET#460]
Hello.

I have wanted to import Steamworks.NET to my Unity project, but when it finished, 2 errors have appeared that I couldn't resolve. The console says that one thing is missing from a script (0 information's, 2 errors, 0 warnings). When I try to start the game from editor, it says that I need to fix those errors before starting the game. After this, I had to remove Steamworks.NET from my project and now I can play the game again. I was using Steamworks.NET 15.0.1 and I was using Unity 2020.3.21f1 (LTS). Are there any solutions for this?

One more question: Does Steamworks.NET 15.0.1 support Unity 2020.3.21f1 (LTS)?

**Error 1:** _Assets\Scripts\Steamworks.NET\SteamManager.cs(46,12): error CS0433: The type 'SteamAPIWarningMessageHook_t' exists in both 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'com.rlabrecque.steamworks.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'_

**Error 2:** _Assets\Scripts\Steamworks.NET\SteamManager.cs(48,34): error CS0433: The type 'SteamAPIWarningMessageHook_t' exists in both 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'com.rlabrecque.steamworks.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'_

Thanks.

Sincerely,
sk3tcherrs @rlabrecque

**Comment by FreeMotion45** [comment]
These are not Steamworks.NET errors, but script errors. Just explicitly type in the type instead of using an ambiguous one.

**Comment by rlabrecque** [comment]
It looks like you might have two different versions of Steamworks.NET installed side by side, both the 15.0.1 unitypackage version and the package manager version.
