### ISSUE TITLE
SteamUnifiedMessage.meta

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#464]
> Couldn't delete Packages/com.rlabrecque.steamworks.net/Runtime/types/SteamUnifiedMessages.meta because it's in an immutable folder.

You need to remove the Packages/com.rlabrecque.steamworks.net/Runtime/types/SteamUnifiedMessages.meta file or PackageMannager will throw warnings for user's installing the package

**Comment by Tanek81** [comment]
As a temporary workaround I've deleted it manually in: 
*project dir*\Library\PackageCache\com.rlabrecque.steamworks.net@4dafa26fbd\Runtime\types

**Comment by JamesMcGhee** [comment]
aye easy enough to just ignore even wont hurt anything but our users raise it and ask about it so thought I would point it out

Package manager wont create metadata files or remove them because package manager imported things are treated as imutable

**Comment by rlabrecque** [comment]
Can you make a PR with this, I can merge it quickly, but won't be able to do it until tonight (PST)

**Comment by JamesMcGhee** [comment]
I have that sorted 
Note that PR also includes a new script defien STEAMWORKS_NET this has been requested by other Unity Asset developers that integrate with Steamworks.NET so they can detect when it is installed

```csharp
#if STEAMWORKS_NET
// Compile your dependent code
#else
// Instruct the user to install Steamworks.NET from Git
#endif
```

**Comment by JamesMcGhee** [comment]
The PR I have open has a new addition to it in the form of a Sample scene available from the Package Manager

This new Sample Scene demonstrates initalizing the Steam API but doesn't use SteamManager for several reasons. The new example scripts are verbose, have more comments and are meant to be more of a tutorial on how to do it your self.

The new script model also tollerates single and multi-scene architectures and doesn't force the use of Do Not Destroy On Load but does have it available if the user wants.

The new scripts are also marked as Obsolete so they are falgged with a bright yellow message in the Unity expector that they are examples only and not designed for production use.
