### ISSUE TITLE
Steamworks SDK 1.5.3

### ISSUE THREAD

**Issue by fender** [rlabrecque/Steamworks.NET#468]
Any chance of an update to add support for the latest Steamworks SDK 1.5.3?
https://store.steampowered.com/news/group/4145017?emclan=103582791433666425&emgid=3145196846681410422

**Comment by rlabrecque** [comment]
Done as of 27b1a1561c9b9ace7de1f8da17454d29547a63f7 👍

Sorry it took a little while, was some intricacies and poor timing.
