### ISSUE TITLE
CS0433: Issue preventing fix

### ISSUE THREAD

**Issue by SynapsUsr** [rlabrecque/Steamworks.NET#469]
Assets\Scripts\Steamworks.NET\SteamManager.cs(46,12): error CS0433: The type 'SteamAPIWarningMessageHook_t' exists in both 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'com.rlabrecque.steamworks.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by rlabrecque** [comment]
It's likely that you have two copies of Steamworks.NET installed. In the latest version on the `master` branch and the beta 20.0.0 release the layout of the plugin has changed to facilitate the Unity Package system, so you'll need to remove your old version.

**Comment by krisenteryes** [comment]
Hi, I seem to be having the same issue. How do I remove the old version. I deleted the steam manager script and the files in the editor before re installing but this didn't work.

Thanks - Kris
