### ISSUE TITLE
SteamManager destroys itself if the game object has the component two or more times

### ISSUE THREAD

**Issue by ellioman** [rlabrecque/Steamworks.NET#47]
Hey,

Just thought I'd let you know that your singleton approach for the SteamManager has an issue if the game object has more than one instance of the component.

This code:

    if (s_instance != null) {
      Destroy(gameObject);
      return;
    }

destroys the game object, making the s_instance null.

To prevent this, Unity has a nice class attribute you can add to the script:

    [DisallowMultipleComponent]

http://docs.unity3d.com/ScriptReference/DisallowMultipleComponent.html

Of course this is just a minor thing, but I thought I'd share, especially since it's such a simple fix :)

**Comment by rlabrecque** [comment]
This is way late but thanks for sure, I've added this now!
