### ISSUE TITLE
Changelog releases url not found

### ISSUE THREAD

**Issue by Saucy** [rlabrecque/Steamworks.NET#470]
Hi. Minor thing, the url on the changelog page on docs links to a broken page.
Link text is correct but the actual link is broken.

Current actual link: https://steamworks.github.io/changelog/Releases
Correct link (is the text of the link): https://github.com/rlabrecque/Steamworks.NET/releases

**Comment by rlabrecque** [comment]
Thanks! Updated here:

https://github.com/Steamworks/steamworks.github.io
