### ISSUE TITLE
Steam wrappers with plug/unplug issues

### ISSUE THREAD

**Issue by diegoaraujo443** [rlabrecque/Steamworks.NET#471]
Hi, I'm having a serious problem that is preventing me from lauching my game. 
And as mle-ii noted on this issue: 
https://github.com/rlabrecque/Steamworks.NET/issues/380
it's no only for my game.

Via Unity, my controller works perfectly fine, but via Steam, I have to plug after the game initialized.

I have run a lot of tests, and that's what's happening (game lauching via steam):

If I plug any controller AFTER the game initialized, it will work normally.
If I initialize the game with any controller plugged, it will only work if I unplug and plug it again.
If I intialize the game with more than one controller plugged, they will only work if I unplug ANY controller.
Resuming: Let's say I have 3 controllers connected, none of them will work if I launch the game, but if I Plug a new controller OR unplug one of the 3 previously plugged, all of them starts working. I made those tests whith XBox360, PS4 and generic USB controllers, the same happens for all of them. They all work perfectly if I do any plug/unplug.

I first uploaded the game with Steamworks.NET, so when I found no solution for this issue, I changed to Facepunch and the EXACTLY same problem occured. So I believe it's a Steam problem.

I'm really desperate. Right now that's the only thing preventing me from launching my game. Any help would be greatly aprecciated.

**Comment by rlabrecque** [comment]
Let's keep it in the mentioned thread, as you've found this is likely due to how Steam, Unity's Input handling, and the Steamworks API work together, and this is very likely in Valve's hands to figure out
