### ISSUE TITLE
ProcessMessage function based on the current release version of Steamworks.NET

### ISSUE THREAD

**Issue by TiyashaisTiyasha** [rlabrecque/Steamworks.NET#472]
Hi, I'm using Steamworks.net(v15.0.0) and facing this issue while joining with SteamMatchmaking.JoinLobby(CSteamID) and Mirror. 

![s](https://user-images.githubusercontent.com/96490526/146968910-7ccfc49a-1a48-4348-af08-dac8298cbac5.png)

Though it didn't showed up in the example project that I used for learning [https://fatrodzianko.com/2021/08/02/gamedev-blog-using-mirror-steamworks-net-to-create-multiplayer-lobbies-in-unity/](url) . Does it happens with this version or am I Missing Something? Any help is greatly appreciated!

thanks
Tiyasha

**Comment by rlabrecque** [comment]
Hey there, I'm not really sure where that message comes from, or what "NextCommon.cs" is, this might need to be something you ask Mirror about, and have them post what they need from me or have them open a pull request 👍
