### ISSUE TITLE
steamworks issue 7 days to die

### ISSUE THREAD

**Issue by robo3232** [rlabrecque/Steamworks.NET#480]
Hi there, steamworks seems to be blocked on certain ip range at ovh any ideas on this, is it possible this range is being blocked some how had several issues, 

https://gyazo.com/eb249ab5221ef3d0aa392ee57de81c82

ip range 198.244.178

if you see screen shot there steamworks.net connection error at the end, everything is whitelisted in firewall etc even turned firewall off to test.

**Comment by rlabrecque** [comment]
I'd recommend posting on the Steam forums, I can not help with this at all.

**Comment by robo3232** [comment]
They said they can't help with third party software since it's Steam works
error

**Comment by robo3232** [comment]
It seems signing in with steam client on the Dedi box then signing out has
fixed the issue for now

**Comment by rlabrecque** [comment]
Valve created Steamworks. This is just a wrapper around it for Unity games.

Glad that fixed it though 👍
