### ISSUE TITLE
Cannot access SteamNetworkingMessages on Standalone version [Version 20.0]

### ISSUE THREAD

**Issue by TeddySJ** [rlabrecque/Steamworks.NET#483]
Hey, thanks for all the great work on this project!

I'm porting my existing UDP-style network code to the new interface, so using SteamNetworkingMessages seems like the best option.

However, using the Standalone DLLs I can't seem to access the interface at all, even though the callbacks exist.

![image](https://user-images.githubusercontent.com/98830225/152148700-4cd29e3d-ea1c-4613-a651-9e37b8de5c4a.png)

Has that interface not been ported, is there an issue with the standalone package, or is the problem sitting in front of my monitor?

**Comment by rlabrecque** [comment]
Can you recheck this with 20.1.0 ?

https://github.com/rlabrecque/Steamworks.NET/releases/tag/20.1.0


https://github.com/rlabrecque/Steamworks.NET/blob/53d17180582752d7d8c9a757742da3a52dfc33d4/com.rlabrecque.steamworks.net/Runtime/autogen/isteamnetworkingmessages.cs#L18

It's definitely generated, and should be included in the package.

**Comment by TeddySJ** [comment]
Some more info: the class is indeed included in the Steamworks.NET.Standard solution, but not in the Steamworks.NET solution and the prebuild binaries!

**Comment by TeddySJ** [comment]
To conclude, I added the include line in the Steamworks.NET project file and could then build the binaries.

**Comment by rlabrecque** [comment]
Yep, good call, I got confused by both the .NET Standard and legacy csproj!

I'll try to see if making the change that #481 made to the regular csproj works as well.

**Comment by definitelyokay** [comment]
I think I'm having this problem with the latest release on GH, linking with the macOS/Linux version of the Steamworks.NET.dll on my mac. Unfortunately, I'm still learning with regards to how packages and imports with regards to .NET so I am open to suggestions.

**Comment by Yazir** [comment]
Prebuild release package had not been updated since the changes which would fix the issue ; Current prebuilt dlls don't contain SteamNetworkingMessages.

--

Managed to build the project from source and have SteamNetworkingMessages class available
1. git clone repo
2. navigate to Standalone 
3. follow README.md instructions
