### ISSUE TITLE
Same Unity Problem as Previously Closed Issue: Plugin 'libsteam_api.so' is used from several locations 

### ISSUE THREAD

**Issue by RileySampson** [rlabrecque/Steamworks.NET#485]
Hello. Am I asking this question in the right place? If I'm not, sorry for the inconvenience. 

Otherwise: I have the same problem as a previously closed issue:
https://github.com/rlabrecque/Steamworks.NET/issues/402

None of the solutions in this forum worked. When I attempt to build my Unity application for macOS(Intel 64-bit + Apple Silicon) the following error occurs:
```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.
```

I am using Unity 2021.1.6f1 and I downloaded the newest Steamworks plugin a month ago. Apparently, the issue is fixed but for me it still persists. Perhaps I must update Unity or revert back to the 2019 Long Term Support version of Unity, but I don't know.

Any help or comment would be greatly appreciated.

**Comment by rlabrecque** [comment]
Hey there, the issue with pre-20.0.0 releases was that both those libsteam_api.so's defaulted to being included on macOS, when they shouldn't be at all. 20.0.0 fixes this by bundling the .meta file with those options setup inside them.

If you're using a version pre-20.0.0 you can just set those two .so's to not be included in a package via the inspector. (Though you might still run into issues with Intel 64-bit + Apple Silicon, I forget how well that was supported prior to 20.0.0, you might need just Intel 64-bit)

If you're on 20.0.0 or newer, then you need to clean out any old Steamworks.NET files from before the Unity Package Manager folder structure change. (I.E. Everything moved from Assets/Plugins/, Assets/Editor/Steamworks.NET, and Assets/Steamworks.NET to just Assets/com.rlabrecque.steamworks.net)

Steamworks.NET should work on latest versions of Unity just fine as well though, no need to revert.
