### ISSUE TITLE
steam_api.dll caused an Access Violation

### ISSUE THREAD

**Issue by ssk9208** [rlabrecque/Steamworks.NET#49]
I am getting an error "steam_api.dll caused an Access Violation" upon launch (downloaded via Steam)
The game crashes.
What should I do?

**Comment by rlabrecque** [comment]
Are you using non-Unity?

There is an issue with the Prebuilt standalone DLL's in the release on Windows. A new release is coming shortly but in the meantime you can recompile Steamworks.NET.dll yourself from the latest version of [master](https://github.com/rlabrecque/Steamworks.NET/archive/master.zip).

**Comment by ssk9208** [comment]
@rlabrecque I sorted it out. There was a PlayMaker script in the same GameObject as SteamManager, and it has caused the issue.
If anyone get the same issue as me, make sure that the GameObject with SteamManagaer doesn't have any other script.
Thanks!

**Comment by rlabrecque** [comment]
Ah weird good to know!
