### ISSUE TITLE
TriggerSimpleHapticEvent doesn't work on SteamDeck

### ISSUE THREAD

**Issue by isonil** [rlabrecque/Steamworks.NET#490]
The TriggerSimpleHapticEvent's method summary says 
> Send a haptic pulse, works on Steam Deck and Steam Controller devices

However, it looks like currently it's not possible to make it work on a SteamDeck. The method requires InputHandle_t, but from what I've seen SteamDeck doesn't have InputHandle_t. GetConnectedControllers() returns an empty array and there's no any special method to get the SteamDeck's InputHandle_t. `new InputHandle_t(0)` doesn't seem to work either.

**Comment by trevyn** [comment]
Apparently you have to call [`RunFrame`](https://partner.steamgames.com/doc/api/isteaminput#RunFrame), after which `GetConnectedControllers()` returns a handle. Then the haptics calls work.
