### ISSUE TITLE
How to check if the user has purchased a DLC

### ISSUE THREAD

**Issue by Shamahan262** [rlabrecque/Steamworks.NET#502]
I can check if the DLC is installed with `SteamApps.BIsDlcInstalled(new AppId_t(APP_ID))` but it will return false if the user has not checked the "install" box for this DLC.

I would like to know if there is a possibility to check if the player has purchased a DLC but has not installed it.

**Comment by Justusvh** [comment]
`bool hasGame = SteamApps.IsSubscribedToApp(#AppId#);`

**Comment by Shamahan262** [comment]
> `bool hasGame = SteamApps.IsSubscribedToApp(#AppId#);`

It seems to have the same problem, it returns true if the DLC is enabled but false if it's disabled

**Comment by Justusvh** [comment]
Try `SteamApps.IsAppInstalled(AppId);` The comments look like it checks if owned not installed

**Comment by Shamahan262** [comment]
The same problem as previously :/
I think that `SteamUser.UserHasLicenseForApp(SteamID, AppID)` should work properly, but I'm not quite certain on how to set it up to work correctly

**Comment by Justusvh** [comment]
Oh nice, that one should do it. have you tried using the players Steam ID and the DLC APP ID?

**Comment by Shamahan262** [comment]
I couldn't figure it out because I don't have a lot of experience with callbacks and stuff like that.
BUT
I did find a solution for my problem with `SteamApps.GetEarliestPurchaseUnixTime(AppID)`, if the DLC is not purchased then it will return a 0. This could probably be abused with a refund, but that's not a huge problem for my game.

Thank you for trying to help me out though!
