### ISSUE TITLE
How to get the filename from FileReadAysnc callresult from ISteamRemoteStorage API?

### ISSUE THREAD

**Issue by unfu99** [rlabrecque/Steamworks.NET#505]
In `RemoteStorageFileReadAsyncComplete_t` there isn't any information about the filename I am reading, how am I suppose to decide what filename I am saving to the disk?

**Comment by rlabrecque** [comment]
I'm not sure if the SteamAPI provides an easy way to do this directly, that would be a question for the Steam Developer Forum.

But a few things you could do are:

1. Create a new object which abstracts away the call, when you instantiate the object (as a member variable on some manager type), it starts the FileReadAsync call, it automatically sets a callback function internally, stores off the info you passed in to the constructor (file name), stores off the CallResult handle, and you also pass in a custom delegate of your own which gets called when it completes.
2. Store the call result handle in a dictionary with your file name, so you can look it up in the callresult's callback function when it completes
