### ISSUE TITLE
CS:S Game Crashes

### ISSUE THREAD

**Issue by ModMordu** [rlabrecque/Steamworks.NET#506]
I have the extension loaded on a Linux Counter Strike:Source server with SteamWorks-git132-linux.tar.gz utilizing the [Discord Call Admin API](https://forums.alliedmods.net/showthread.php?t=292663) and now with certain plugin calls (isolated to TE_Setup in SourceMod) I get client crashes with the following dump error: "Parent cvar in server.dll not allowed (steamworks_sessionid_client)"

**Comment by rlabrecque** [comment]
I think you might be lost. This doesnt seem related
