### ISSUE TITLE
ValidateAuthTicektResponce_t doesn't callback on servers

### ISSUE THREAD

**Issue by JamesMcGhee** [rlabrecque/Steamworks.NET#509]
When we initialize as SteamGameServer and call BeginAuthSession
The ValidateAuthTicektResponce_t never responds

We have been doing a lot of troublshooting on this and I finally took the mind to check the definitions ... I noted that there is no SteamGameServer version of this callback there is only the one `ValidateAuthTicektResponce_t` defined in SteamCallbacks.cs and that definition sets the callback ID as 

```csharp
public const int k_iCallback = Constants.k_iSteamUserCallbacks + 43;
```

should there be a GameServerValidateAuthTicketResponce_t where in 

```csharp
public const int k_iCallback = Constants.k_iSteamGameServerCallbacks + 43;
```

If that is the case it would explain why we dont get the callback as expected and would sugest there is also an issue with `GetAuthSessionTicketResponse_t` similar thing ... should have a GameServer variant

Then again I could be insain and something else is preventing the callback from returning but this works perfrectly on the Client API should be the same code for Server the only difference being 

```csharp
SteamGameServer.BeginAuthSession
```
as oppsed to 

```csharp
SteamUser.BeginAuthSession
```

**Comment by francoios** [comment]
Highly waiting to know how to fix that also ! :)

**Comment by Jusremo** [comment]
Also having this problem, will be waiting, thanks.

**Comment by XuX26** [comment]
Me too! 👍

**Comment by areynolds04** [comment]
Might as well throw my name in there ;)

**Comment by rlabrecque** [comment]
I won't be able to check this out for at least a couple more days, but if you duplicate `ValidateAuthTicektResponce_t` (even into your project) and change the k_iCallback, then register that new callback, does that work?

**Comment by JamesMcGhee** [comment]
All the users on my side would be using Package Manager install 
They can modify the code but need to do that in the package cashe within the project ... half the point of Package Manager is no in advertently changing the code :)

I'll check with a couple of them in our Discord see how it goes and update you

**Comment by JamesMcGhee** [comment]
For anyone looking to do it

You simply need to create a new responce type such as

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 4)]
[CallbackIdentity(Constants.k_iSteamGameServerCallbacks+ 43)]
public struct GameServerValidateAuthTicketResponse_t 
{
        public const int k_iCallback = Constants.k_iSteamGameServerCallbacks + 43;
        public CSteamID m_SteamID;
        public EAuthSessionResponse m_eAuthSessionResponse;
        public CSteamID m_OwnerSteamID; // different from m_SteamID if borrowed
}
```

Then you need to modify Heathen's Authentication API as follows

On line 38 change this
```csharp
private static Callback<GetAuthSessionTicketResponse_t> m_GetAuthSessionTicketResponceServer;
```
to this
```csharp
private static Callback<GameServerValidateAuthTicketResponse_t> m_GetAuthSessionTicketResponceServer;
```

then on line 93 change this
```csharp
m_GetAuthSessionTicketResponceServer = Callback<GetAuthSessionTicketResponse_t>.CreateGameServer(HandleGetAuthSessionTicketResponce);
```
to this
```csharp
m_GetAuthSessionTicketResponceServer = Callback<GameServerValidateAuthTicketResponse_t>.CreateGameServer(HandleGameServerAuthSessionTicketResponce);
```

finally add the following method above line 184

```csharp
private static void HandleGameServerAuthSessionTicketResponce(GameServerValidateAuthTicketResponse_tpCallback)
{
    if (ActiveTickets != null && ActiveTickets.Any(p => p.Handle == pCallback.m_hAuthTicket))
    {
        var ticket = ActiveTickets.First(p => p.Handle == pCallback.m_hAuthTicket);
        ticket.Authenticate(pCallback);
    }
}
```

Those steps are untested at current, I am working with others in a ticket on the Discord server to get this tested out. If you do this and have any issues ... or find it works please let us know.

**Comment by JamesMcGhee** [comment]
Initial testing isn't a hit .. yet ... still playing with it
@rlabrecque 

where is it exsactly that you source the value to add to the constant ... e.g.  in the following
```csharp
[StructLayout(LayoutKind.Sequential, Pack = 4)]
[CallbackIdentity(Constants.k_iSteamUserCallbacks + 43)]
public struct ValidateAuthTicketResponse_t {
	public const int k_iCallback = Constants.k_iSteamUserCallbacks + 43;
	public CSteamID m_SteamID;
	public EAuthSessionResponse m_eAuthSessionResponse;
	public CSteamID m_OwnerSteamID; // different from m_SteamID if borrowed
}
```

Where did you get `43` from?
We are assuming that the GameServer version will be a `+ 43` just like the client but that is a blind assumption

**Comment by areynolds04** [comment]
I'm starting to wonder if I've just lost it or what. I want to make sure with y'all I'm understanding the documentation correctly so we're not going down the wrong path(still lacking a callback being called either way though). It actually says 2 different things when you read it. 

Important Links:
https://partner.steamgames.com/doc/features/auth
https://partner.steamgames.com/doc/api/ISteamUser#BeginAuthSession
https://partner.steamgames.com/doc/api/steam_api#EBeginAuthSessionResult
https://partner.steamgames.com/doc/api/ISteamUser#ValidateAuthTicketResponse_t

So basic order of things should be:

- Client gets a ticket
- Client passes ticket to the server
- Server calls BeginAuthSession
- EBeginAuthSessionResult is immediately returned (no callback like auth page mentions). 
- It then registers the callback for ISteamUser:ValidateAuthTicketResponse in the event a user goes offline/cancels ticket
- As long as we get k_EBeginAuthSEssionResulOK then the user is approved to move forward. 

When a user disconnections we call EndAuthSession and the callback above is supposed to be called right? 

Here is where things got weird in the docs --
The auth page says it will perform the check and then call ISteamUser:ValidateAuthTicketResponse with the results. 
But then the BeginAuthSession page says it returns a EBeginAuthSessionResult(which is working properly) and that ValidateAuthTicketResponse_t is used if a entity goes offline or cancels the ticket(does not work). 

For now I'm assuming the BeginAuthSession page is correct and that the auth page is misleading/wrong. As I keep poking around I'll update this with anything I think might be helpful.

**Comment by JamesMcGhee** [comment]
The workflow is this

1. entity (user) generates a ticket
2. entity sends said ticket along with the entiteis CSteamID to that which is going to validate them (can be a server or another user)
3. That authenticating entity (server or other user) calls BeginSession ... now which is called depends on if this authenticating entity is a Steam Game Server or a user e.g. `SteamUser.BeginAuthSession(authTicket, authTicket.Length, user);` would be called by the client e.g. when a user is validating another user and `SteamGameServer.BeginAuthSession(authTicket, authTicket.Length, user);` would be called by a Steam Game Server when authenticating a user

So the callbacks need to already be registered

That is the entity doing the authenticating (server or client) needs to already have registered the callback on `Callback<ValidateAuthTicketResponse_t>.Create(handler);` before the `BeginAuthSession` is called

**Comment by JamesMcGhee** [comment]
@rlabrecque 
So I did some more digging to understand what k_iCallback was/is

I think I understand that it simply needs to be a unique ID such that when registering a callback no 2 callbacks have the same ID.

If that is the case then `Constants.k_iSteamGameServerCallbacks` and the client equivalent values of 100 and 200 are arbitrary and are not responsible for the issue we are seeing in Steam Game Server where the callback is not being returned. So long as the ID is unique which of course it will be since only 1 is ever registered either client or server but never both ... then we know its always unique.

Also I did more digging in the Valve documents

The [SteamUser API](https://partner.steamgames.com/doc/api/ISteamUser#BeginAuthSession) references that it will trigger the `ValidateAuthTicketResponse_t` callback

The [SteamGameServer API](https://partner.steamgames.com/doc/api/ISteamGameServer#BeginAuthSession) simply says
> This registers for [ValidateAuthTicketResponse_t](https://partner.steamgames.com/doc/api/ISteamUser#ValidateAuthTicketResponse_t) callbacks if the entity goes offline or cancels the ticket. See [EAuthSessionResponse](https://partner.steamgames.com/doc/api/steam_api#EAuthSessionResponse) for more information.

So then is it intended behaviour that Steam Game Server Begin Auth Session does not raise the `ValidateAuthTicketResponse_t` callback. And if that is the case is that not a glaring issue?

**Comment by JamesMcGhee** [comment]
Some more reading and working on this

I am fairly well convinced now that this is a bug with Steam API ... though not sure how we could be the first to complain about it :)

![image](https://user-images.githubusercontent.com/31243736/172055988-4d7e4be3-0587-4b42-be8a-3a6c82d1bdd6.png)

While the documentation for SteamGameServer.BeginAuthSession doesn't explicitly say it triggers the ValidateAuthTicketResponce_t callback ... the EAuthSessionResponce does 

So it seems like SteamGameServer.BeginAuthSession is using the ValidateAuthTicketResponce_t which is defined in the SteamUser.h ... which why ... but okay

Also this unless I am mistaken means there is nothing Steamworks.NET is doing wrong here. Its simply that Steam API isn't invoking the callback for SteamGameServer but it does for SteamUser

**Comment by JamesMcGhee** [comment]
I have a ticket off to Steam my self but haven't heard back yet

This is still a problem for us and the rest of our users as far as I am aware. Does anyone else have any progress they can share?

**Comment by rlabrecque** [comment]
Hey James, sorry I haven't really been able to get to this much.

The callback numbers themselves are defined by Steam and are available via the Steamworks API here:

https://github.com/rlabrecque/Steamworks.NET/blob/master/CodeGen/steam/steam_api_internal.h#L247-L290=

It looks like all of the `k_iSteamGameServerCallbacks` callbacks are defined in isteamgameserver.h:

https://github.com/rlabrecque/Steamworks.NET/blob/f5c8f33c4fc4493f47d9a15c904b7025843c4fc7/CodeGen/steam/isteamgameserver.h#L283=

The callback Id is pretty arbitrary but -- it must match on both sides, it's basically the key to lookup what type of struct to use because Steam basically just sends (callbackId, binaryDataBlob, binaryDataBlobSize) to games, but then we (Steamworks code in the game) have to do deserialization from that blob into an actual struct.


I think one thing to try is enabling `log_callbacks` in Steam as documented here, would be interesting to see what kind of callbacks are /attempted/ to be sent when we call these functions:

https://partner.steamgames.com/doc/sdk/api/debugging

**Comment by TXMerc** [comment]
I can try this on Thursday night and let y'all know what happens.

**Comment by JamesMcGhee** [comment]
@rlabrecque 

Taking a look at the istemgameserver.h again and nothing, it still looks like a bug either with the code which I get is unlikely someone would have hit this by now ... more likely with the documentation

```c
// Authenticate ticket ( from GetAuthSessionTicket ) from entity steamID to be sure it is valid and isnt reused
// Registers for callbacks if the entity goes offline or cancels the ticket ( see ValidateAuthTicketResponse_t callback and EAuthSessionResponse )
virtual EBeginAuthSessionResult BeginAuthSession( const void *pAuthTicket, int cbAuthTicket, CSteamID steamID ) = 0;	
```

That is the comment in the server about the method in question. That notes the ValidateAuthTicketResponce_t callback which doesn't exist in this header. It only exists in the SteamUser header and starts with 100 being the steam user segment of call-back IDs

The closest thing we have is 
```c
struct GSClientApprove_t
{
	enum { k_iCallback = k_iSteamGameServerCallbacks + 1 };
	CSteamID m_SteamID;			// SteamID of approved player
	CSteamID m_OwnerSteamID;	// SteamID of original owner for game license
};


// client has been denied to connection to this game server
struct GSClientDeny_t
{
	enum { k_iCallback = k_iSteamGameServerCallbacks + 2 };
	CSteamID m_SteamID;
	EDenyReason m_eDenyReason;
	char m_rgchOptionalText[128];
};
```

These are documented as belonging to `SendUserConnectAndAuthenticate` which has the note
> NOTE: This is part of the old user authentication API and should not be mixed with the new API.
This tells me I shouldn't be using this with the AuthSession system ... will have to wait and see what @TXMerc finds in his test 

I think worst case we see a callback ID 201 which would be `GSClientApprove_t` or ID 202 which would be `GSClientDeny_t` I call this worst case as these do not have the information we would expect and get from the session callback

The other option is we see a callback ID that isn't listed in iSteamGameServerCallbacks ... we know the server callbacks segment on 200 and that 9 are listed covering 1 to 11 skipping 4 and 5.

PS:
I noticed something odd in the header ... This is in the isteamgameserver header ... but its using a callback ID on the user segment
```c
// received when the game server requests to be displayed as secure (VAC protected)
// m_bSecure is true if the game server should display itself as secure to users, false otherwise
struct GSPolicyResponse_t
{
	enum { k_iCallback = k_iSteamUserCallbacks + 15 };
	uint8 m_bSecure;
};
```

Also of those structures that are prefixed with `k_iSteamGameServerCallbacks` they count { 1, 2, 3, 6, 7, 8, 9, 10, 11 }

So 4 and 5 are skipped and we see a "15" in the game server header that is just out of place all together.

**Comment by JamesMcGhee** [comment]
@rlabrecque 
log_callbacks is a Steam Client command line, the issue is the Steam Game Server callback ... so far we haven't been able to find a way to log the callbacks for the server

**Comment by JamesMcGhee** [comment]
Still nothing on this one, no response from Valve, no results from attempting to log callbacks

**Comment by JamesMcGhee** [comment]
I have had a ticket open with Valve for 20 days now and no response :) that's a record for me.

I have started a forum post ... course Steamworks developer forum is in my experience completely useless generally no one responds
https://steamcommunity.com/groups/steamworks/discussions/1/3409802983878249925/

I am completely out of ideas on this one

**Comment by JamesMcGhee** [comment]
Still looking for any support we can on this one. 

Its been exactly one month since I reached out to Valve ... still no initial response from them.
Posted on the Steamworks Developer forum and no response there at all either

Any ideas at all are welcome

**Comment by JamesMcGhee** [comment]
Just checking in on this one again

Still no word from Valve on my side nor the Steamworks Developer community

Help me @rlabrecque your our only hope :)
Star Wars reference but seriously any help you can offer or maybe any ideas on where else to search would be greatly appreciated

**Comment by francoios** [comment]
Yep kinda annoying that Valve etc putting this issue under the carpet

**Comment by JamesMcGhee** [comment]
Coming up on 2months now no response from Valve not even an initial response, to the point I submitted a support case about my support case to see if Valve even does support anymore.

Anyway

I think from our point of view we are going to have to say Steamworks.NET doesn't support Steam Game Server at least not fully.

Would be very happy to help work on this in the future if anyone is keen to engage, happy to pay as well.

**Comment by TXMerc** [comment]
I just added another comment to my ticket as well. I'll let y'all know if I get anything but so far I've been surprised, even wowed at how unresponsive they are.

**Comment by JamesMcGhee** [comment]
It is an unusual level of unresponsiveness. I am used to them taking a few days maybe a week but this is 2 months and not even an initial response

**Comment by francoios** [comment]
@rlabrecque ? any news ?

**Comment by JamesMcGhee** [comment]
I poked around Facepunch and best I can see they aren't doing anyhting different but I am told it works through them

I confirmed the callback ID as well 143 rather its on client server that is just the callback ID

**Comment by JamesMcGhee** [comment]
@rlabrecque any idea why Valve has stopped responding to support requests. I submitted a ticket well more than 2 months ago at this point. I have updated it just once a week or so with new testing results, etc. but I still haven't gotten an initial response from them.

To my knowledge none of the devs I have been working with on this issue has gotten a response either.

**Comment by rlabrecque** [comment]
I haven't been able to look deeper yet unfortunately.

Do we have a minimal repro of this, and has anyone tried recreating it with the C++ SDK?

**Comment by JamesMcGhee** [comment]
Lot of testing been done by the group let me get them to chime in

As for my own testing 
I tried the callback ID, reporting the callbacks and at current and am making our kit agnostic between Steamworks.NET and Facepunch as someone said Facepunch works ... which would tell us its not something with Steam API its self and would maybe give us a working example to cheat off of :)

That said Facepunch is a pin in my backside with some of the differences and missing bits so that is taking longer to do than I expected.

I'll ask the others to chime in here with the testing they have done and there results

**Comment by JamesMcGhee** [comment]
If you want to get into our Discord on the subject
https://discord.gg/6X3xrRc

That is our server there you will find a channel #Steamworks and a ticket under that called "Steam Game Server Configuration" which has our conversation on the topic

**Comment by JamesMcGhee** [comment]
@rlabrecque working with @TXMerc to get you a repo set up that reproduces the issue 
Will be a private repo we'll invite you to once ready

**Comment by JamesMcGhee** [comment]
@rlabrecque 
I have just set up a repo with an example project from @TXMerc 
It is set to private and I sent you an invite to join the repo with write permission, you may also need access to our source repo to get at Steamworks Complete, I will invite you to that private repo as well

**Comment by francoios** [comment]
It's been a while, we still have 0 news regarding this issue @rlabrecque have you investigated ?

**Comment by francoios** [comment]
Would like to see this thread up ! :)

**Comment by JamesMcGhee** [comment]
Hi @rlabrecque 
Checking to see if you have had any issues running the example project or if there is anything else we can get or do for you

I still haven't heard back from Valve on my ticket with them 3+ month after submitting it so I think Valve has just checked out on the topic.

**Comment by JamesMcGhee** [comment]
Checking in on this, still hoping we can get it resolved

**Comment by francoios** [comment]
well seems like @rlabrecque doesn't have time for this.... it is indeed really annoying.

**Comment by JamesMcGhee** [comment]
Just bumping this one again its still an outstanding issue

We have a repo set up that reproduces the error using the raw API if anyone has any ideas do let us know

**Comment by rlabrecque** [comment]
So I got to look into this again, I had to make one change in the test repo, and then it seemed to work fine:

`m_ValidateAuthSessionTicketResponce = Callback<ValidateAuthTicketResponse_t>.Create(TestCB);`
To
`m_ValidateAuthSessionTicketResponce = Callback<ValidateAuthTicketResponse_t>.CreateGameServer(TestCB);`

To match the usage in C++ that Spacewar has where they create it with `STEAM_GAMESERVER_CALLBACK`


These seem to be the only usages of the GameServer callback though for what ever reason:

```
// Tells us when we have successfully connected to Steam
STEAM_GAMESERVER_CALLBACK( CSpaceWarServer, OnSteamServersConnected, SteamServersConnected_t );

// Tells us when there was a failure to connect to Steam
STEAM_GAMESERVER_CALLBACK( CSpaceWarServer, OnSteamServersConnectFailure, SteamServerConnectFailure_t );

// Tells us when we have been logged out of Steam
STEAM_GAMESERVER_CALLBACK( CSpaceWarServer, OnSteamServersDisconnected, SteamServersDisconnected_t );

// Tells us that Steam has set our security policy (VAC on or off)
STEAM_GAMESERVER_CALLBACK( CSpaceWarServer, OnPolicyResponse, GSPolicyResponse_t );

// Tells us a client has been authenticated and approved to play by Steam (passes auth, license check, VAC status, etc...)
STEAM_GAMESERVER_CALLBACK( CSpaceWarServer, OnValidateAuthTicketResponse, ValidateAuthTicketResponse_t );

// All connection changes are handled through this callback
STEAM_GAMESERVER_CALLBACK(CSpaceWarServer, OnNetConnectionStatusChanged, SteamNetConnectionStatusChangedCallback_t);
```

**Comment by JamesMcGhee** [comment]
@rlabrecque 

Thank you ... that will make a lot of devs happy

**Comment by JamesMcGhee** [comment]
Em at least so far I am not getting TestCB to respond

**Comment by JamesMcGhee** [comment]
![image](https://user-images.githubusercontent.com/31243736/204085581-82bab758-12ec-428f-a8ef-37543920a402.png)

As you can see from the output on the server the TestCB is never called.

Here are the calls to Debug I have that explain each printed message
```csharp
Debug.Log($"Initalized {nameof(m_ValidateAuthSessionTicketResponce)}, IsGameServer = {m_ValidateAuthSessionTicketResponce.IsGameServer}");
```
This is called when we initialize the callback and simply prints the state of IsGameServer for us

```csharp
Debug.Log($"BeginAuthSession result: {tResult}");
```
This prints right after we call Begin Session and reports the return that we got from it

```csharp
Debug.Log($"TestCB called params: responce = {param.m_eAuthSessionResponse}, User Id = {param.m_SteamID}, Owner Id = {param.m_OwnerSteamID}");
```
This should have printed when we received the callback on the server and should have told us the response, user and owner ... unfortunately it is never called indicating that we are in fact not receiving the callback.


My testing methodology is simple and is what I would expect the typical Unity developer to do.
The "server" was built locally and ran, the client is ran from within the Unity editor

**Comment by JamesMcGhee** [comment]
Delay that a bit ... I am chasing an initialization issue in my test environment

**Comment by JamesMcGhee** [comment]
![image](https://user-images.githubusercontent.com/31243736/204087563-e658a030-efdb-4edf-a2bf-e65e7f38329d.png)
Finally got it

My previous issue was down to an initialization issue ... something was holding the port so the init for GameServer couldn't bind and failed to init

**Comment by JamesMcGhee** [comment]
I have updated the test repo and our asset this issue should now be resolved

Thank you everyone
