### ISSUE TITLE
Issues in Steamworks.NET when targeting other platforms

### ISSUE THREAD

**Issue by ben-roberts** [rlabrecque/Steamworks.NET#51]
Hi, first, thanks for all the time and effort you've put into this! The issue is when selecting web player as the target, this gives a compile error in InteropHelp.cs and compile errors for several of the 32/64bit dlls (libsteam_api and CSteamworks). 

These can be worked around by wrapping CheckSteamAPIDLL() in a platform check and making sure the dlls are only targeting Editor/Standalone rather than all platforms.

**Comment by rlabrecque** [comment]
Thanks for the report! I'm going to combine this one with #37, It should be done tomorrow, some cleanup like this is a priority right now.
