### ISSUE TITLE
Everything OK in the editor, but I can't build game

### ISSUE THREAD

**Issue by hooker99** [rlabrecque/Steamworks.NET#511]
Error:
`Assets\_Heathen Engineering\Assets\Steamworks\Scripts\Foundation\SteamSettings.cs(281,29): error CS1061: 'SteamSettings' does not contain a definition for 'evtSteamInitalizationError' and no accessible extension method 'evtSteamInitalizationError' accepting a first argument of type 'SteamSettings' could be found (are you missing a using directive or an assembly reference?)`

Unity version: 2021.1.21f1
Steamworks V2 (free version https://assetstore.unity.com/packages/tools/integration/steamworks-v2-foundation-186949)

**Comment by JamesMcGhee** [comment]
@hooker99 
This is an issue your having with our kit not Steamworks.NET

that is an older bug that should be resolved but note that Steamworks Foundation has been deprecated off Unity Asset Store and is only available here on GitHub

Please make sure your on the latest version.
https://github.com/heathen-engineering/SteamworksFoundation

If you have any more questions about support for Heathen's Steamworks please contact us not rlabrecque

You can find our Discord here
https://discord.gg/6X3xrRc
