### ISSUE TITLE
Using SDR on other platforms and stores

### ISSUE THREAD

**Issue by chrisnobrega** [rlabrecque/Steamworks.NET#515]
Valve's documentation indicates the SteamNetworkingSockets / SDR can be used outside of Steam:

> A Networking API and DDoS solution for a cross-platform game is useless if it only works on one platform. In most cases, your players on other platforms and stores can access the relay network, provided that your game meets some basic conditions...

https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay

Does Steamworks.NET support this?

**Comment by rlabrecque** [comment]
Hey there, sorry, no not really.

This is probably the closest: https://github.com/nxrighthere/ValveSockets-CSharp

I'd honestly probably recommend using the above assuming it's updated frequently enough, over the bundled Steamworks version even if you're using Steamworks.NET, for kind of this reason.
