### ISSUE TITLE
Unity 5.1.1f1 Error -> Failed to load 'Assets/Plugins/x86_64/CSteamworks.dll'

### ISSUE THREAD

**Issue by laurelhach** [rlabrecque/Steamworks.NET#52]
Hi,

I have installed Unity 5.1.1f1 and I get this error after I've reimported the project. When I was using 5.0.2 it wasn't happening. I've also updated Steamworks to 6.0.0.

The issue happens only the first time I launch the game in the editor. Launching the game a second time doesn't create the issue.

Here is the error:
Failed to load 'Assets/Plugins/x86_64/CSteamworks.dll' with error 'L’opération a réussi.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
SteamManager:Awake() (at Assets/Scripts/Steamwork.NET/SteamManager.cs:92)
SteamManager:Awake() (at Assets/Scripts/Steamwork.NET/SteamManager.cs:62)
UnityEngine.GameObject:AddComponent()
SteamManager:get_Instance() (at Assets/Scripts/Steamwork.NET/SteamManager.cs:20)
SteamManager:get_Initialized() (at Assets/Scripts/Steamwork.NET/SteamManager.cs:27)
SteamStatsAndAchievements:OnEnable() (at Assets/Scripts/Steamwork.NET/SteamStatsAndAchievements.cs:225)

Thanks for your help!

**Comment by rlabrecque** [comment]
Hey @laurelhach, I think that I've got this fixed up with the latest commit. could you grab the latest master, replace all the files to upgrade and try again?

https://github.com/rlabrecque/Steamworks.NET/archive/master.zip

**Comment by CptPilot** [comment]
Just tried the fix myself. It fixes the above issue but will then fail the DllCheck.Test(). Despite this, the API continues to work. Specifically, the line:

if (fInfo.Length != fileBytes) {

**Comment by laurelhach** [comment]
@rlabrecque thanks for the update, I didn't try it cause @CptPilot seems to have some issues. Do you still want me to try? @CptPilot, did you use the fix with Unity 5.1.1f1 ?

**Comment by rlabrecque** [comment]
You can just comment out the DllCheck.Test() call in SteamManager for now, It's purely just to ensure that the right DLL is loaded but with the rearranging it can no longer find it. I'm updating it to be more robust right now.

**Comment by CptPilot** [comment]
Yep, 5.1.1f1 Personal

**Comment by darkbox** [comment]
I got the same error in the editor (running 5.1.1f1 personal) and when I lunch a build (development build) a get a different log error: [Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information. 
SteamManager:Awake() (at D:\Unity\myProject\Assets\Scripts\Steamwork.NET\SteamManager.cs:88)

**Comment by yakmyakmyakm** [comment]
Same error with me on Unity 5.1.2f1.

commenting out the lines
if (!DllCheck.Test()) removes the red error.

**Comment by darkbox** [comment]
Ok, I'll try it out.

**Comment by yakmyakmyakm** [comment]
I tried running a standalone build and the game closes after the first frame, anyone's standalone working?

**Comment by rlabrecque** [comment]
Have you checked the player log? SteamAPI probably couldn't Init due to a missing steam_api.txt is my guess.

**Comment by darkbox** [comment]
Build works for me, no errors. Only a message console (Development build) if I'm not running steam on background (on Init() method) which is normal from what I understand.

**Comment by rlabrecque** [comment]
The new release has DllTest disabled for now along with a bunch of other stuff. Hopefully this is solved.
https://github.com/rlabrecque/Steamworks.NET/releases/tag/7.0.0
