### ISSUE TITLE
Standalone dedicated server not listing / no heartbeat option?

### ISSUE THREAD

**Issue by BRStevens** [rlabrecque/Steamworks.NET#527]
Good day - coming back to Steamworks.Net after a few years and finding that most things still work as they did, but standalone dedicated servers don't seem to list. They're there, can be connected to via the server's CSteam ID, but client OnRefreshComplete returns eNoServersListedOnMasterServer. I also noticed that SteamGameServer no longer seems to permit heartbeats to be enabled (with #define USE_GS_AUTH_API). Just wondering what might have shifted to prevent server listing?

Any quick thoughts? Thanks in advance.

**Comment by BRStevens** [comment]
It's due to the heartbeat function being renamed. Odd this didn't pop up in my searches. Working now.

**Comment by quimodotcom** [comment]
If anyone is looking at this and realizing that this doughnut forgot to tell people what the solution was. The old EnableHeartbeats function was removed and replaced with a simpler name. just place "SteamGameServer.SetAdvertiseServerActive(true);" after your server has been created and changed its info.

**Comment by rytiex** [comment]
@BRStevens Yes, I know it's been years, but how did you solve this problem?
