### ISSUE TITLE
Fallback handler could not load library

### ISSUE THREAD

**Issue by edencorbin** [rlabrecque/Steamworks.NET#53]
I followed the instructions to add the package to Unity, and then setup some simple scripts with the excellent documentation. Everything works great in the editor, I could debug my Steam user name and see that I was in game when loaded in editor. I updated steam_appid.txt with my app id and confirmed dll locations. I then uploaded to steam on a private alpha channel. App crashes as soon as I try to load SteamManager (before any custom scripts). Odd thing is I looked and confirmed the files it says could not load are indeed in the locations its looking for them in. I was originally using Unity 5.0.1f, but I tried updating to 5.1.1 (latest version), same error.

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll

  at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (Steamworks.AppId_t)

  at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00000] in <filename unknown>:0 

  at SteamManager.Awake () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/.\libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Mono/libC:/Program Files (x86)/Steam/steamapps/common/Quadrant/quadrant_Data/Plugins/CSteamworks.dll

**Comment by Alloc86** [comment]
This looks more like the common wrong fallback handler spam as for example discussed here: http://forum.unity3d.com/threads/native-plugin-not-found-on-standalone-player-windows-x86.326868

I.e. the fallback handler stuff could be ignored but looks like it is actually missing a dependency of CSteamworks.dll. Did you put the steam_api.dll (or steam_api64.dll) in the root folder of the game? Eventually it also requires tier0_s.dll and vstdlib_s.dll (or their 64 bit counterparts), haven't tested that in a while.

**Comment by edencorbin** [comment]
steam_api64.dll is in my root folder. It occurred to me, could the problem be that I have steamapi64.dll, not steam_api.dll in my root folder, and in my build settings I'm selecting x86 architecture? Where do I find, and how can I configure tier0_s.dll and vstdlib_s.dll, this wasn't mentioned in the setup procedure to my knowledge.

**Comment by Alloc86** [comment]
I'm not sure whether it was SteamAPI that required those additional libraries or only Steamclient.dll. No matter what you can get all of them from a normal Steam installation.

Regarding the API: It has to be named exactly steam_api(64).dll (including the underscore) and it has to match the Unity build type (32 / 64 bit).

**Comment by rlabrecque** [comment]
Hey guys I'm looking into this right now, it seems like Unity went and mucked things up in 5.1 :(

The good news is it seems like the steam_api[64].dll no longer has to be in the project root to run in the editor. Having it in Assets/Plugins/x86[_64]/ next to CSteamworks.dll works fine now! Unfortunately it does not work that way when building the project...

**Comment by edencorbin** [comment]
Okay, my issue has to be a routing/file location issue, if I run the game uploaded from steam it crashes, if I run the game in my content folder (where I upload to steam), it crashes, if I run the game from my desktop (where it initially builds), it runs fine. Where can I adjust/make the references properly relative?

**Comment by Alloc86** [comment]
No idea, but the player's log file and a listing of both working and failing directory trees may be helpful. On the other hand Riley might have an idea without that information, I'm just a user of this stuff too ;)

**Comment by edencorbin** [comment]
Uploading to steam, then downloading through the client to the following location results in a crash:
C:\Program Files (x86)\Steam\SteamApps\common\Quadrant\quadrant_Data\Plugins
(note that CSteamworks.dll, steam_api.dll, and steam_api64.dll are all in this location)

Running directly from my desktop however, at C:\Users\Eden\Desktop\quadrant_Data\Plugins works without error (same files are present).

Is there an absolute path specified somewhere that needs to be made relative? Where is the player log file, I'm aware of output.txt, which is what I pasted above? Any general troubleshooting ideas?

**Comment by edencorbin** [comment]
Is there a known issue associated with this? I'm not sure what to try next to troubleshoot.

**Comment by LightningManMedia** [comment]
I am also encountering this problem. It only occurs on my windows machine, not my Mac. Has anyone found a solution yet?

**Comment by edencorbin** [comment]
Never figured this out, I still want to integrate steamworks.net but am awaiting a suggestion on this thread.

**Comment by LightningManMedia** [comment]
Try this: move steam_api and steam_api64 dlls next to your executable. Then it should work.

**Comment by smithmj5** [comment]
I was having this same issue, and realized that it was because I still had steam_appid.txt in the same directory as the game's executable - but you are only supposed to have that during development.

I also noticed this comment in the function RestartAppIfNecessary in Steam.cs: 
return false if your executable was started through the Steam client or a steam_appid.txt file
is present in your game's directory (for development). Your current process should continue.

So for me, because I had steam_appid.txt, RestartAppIfNecessary was returning false, which meant that the code to stop the game, start Steam, and relaunch the game would never be run.

Maybe you're having the same issue?

**Comment by rlabrecque** [comment]
Cool, glad that you guys are getting it sorted. I just pushed out a new release which should clear this up quite a bit.

https://github.com/rlabrecque/Steamworks.NET/releases/tag/7.0.0

**Comment by edencorbin** [comment]
This issue was just closed, I updated to 7.0 and had the same issue, I ended up moving the steam_api next to the executable and it seems to be working. That's good news, but I thought I should mention it, perhaps the documentation could include a reference to this.

**Comment by rlabrecque** [comment]
Whoops, yep, you're completely correct, minor error at the last minute. Fixing it right now.

**Comment by rlabrecque** [comment]
Given that it's been out for such a short amount of time, hasn't been announced yet and only affected an editor script I just bundled the fix right into 7.0. Redownloading the unitypackage or latest zip should have this resolved now.

The steam_api.dll should automatically move itself next to the executable again.

**Comment by edencorbin** [comment]
Fantastic, thanks for this amazing product, very helpful, looking forward to digging into more of the features now that it is up and running.

**Comment by keithbrewer1337** [comment]
@rlabrecque - seems that Unity 2017 doesn't copy the steam_api64.dll to the exe directory anymore.

**Comment by rlabrecque** [comment]
It shouldn't be required there anymore, Unity as of 5.3 or so can load dependent DLL's from the %GameName%_Data/Plugins/*/ folders.

That being said, I'm currently removing CSteamworks completely, so the next few git master commits might be slightly unstable, but hopefully should get rid of a lot of this sort of mess.

**Comment by keithbrewer1337** [comment]
That seems to be correct, however, the only dll that was copied into the plugins folder of the build was CSteamworks.dll, the steam_api64.dll did not copy over and I had to move it manually.
