### ISSUE TITLE
SteamAppList functions don't work with any other app id besides 480

### ISSUE THREAD

**Issue by Joao-RI** [rlabrecque/Steamworks.NET#534]
We have an app that fetches the list of installed games and listens to new installs/uninstalls.
This works great in editor and in build if build with the app id 480.

If we use our application app id, it doesn't work but Steamworks is initialized correctly.
Our application is available and has been approved by Steam.

Is there any setting that I'm missing or are these functions no longer available for non-480 apps? Looking through Steamworks API, I can't find any reference to these functions.

**Comment by rlabrecque** [comment]
Whelp; they've removed SteamAppList now so ¯\_(ツ)_/¯
