### ISSUE TITLE
In Unity Editor SteamManager.cs cannot Launch Steam if User Does not have an active session

### ISSUE THREAD

**Issue by ElijahMansur** [rlabrecque/Steamworks.NET#537]
Hello I am testing my game and I was trying to test the feature where when a user is not logged into Steam, SteamManager.cs launches steam and closes unity. Hypothetically, SteamManager.cs should launch steam and require me to log in before launching the game correctly.

Unfortunately in my testing environment, SteamManager.cs does not launch steam. Instead SteamAPI.RestartAppIfNecessary((AppId_t)example) returns false even when I am not logged into steam on my device. Why is this behavior not occurring as expected? I want to be able to test the feature when SteamManager.cs launches Steam if the user is not actively logged in. 

I get this error: [Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.

**Comment by rlabrecque** [comment]
Any chance you have a steam_appid.txt in there? RestartAppIfNecessary will always return false in that case by design.

**Comment by ElijahMansur** [comment]
@rlabrecque So I deleted the steam_appid.txt file but the RedistInstall Class gets ran when ever I run unity recreating the text file. Can I delete the lines responsible for creating the text file again?  
![image](https://user-images.githubusercontent.com/76127050/210603049-581af28f-335b-4104-9eb6-34e0f170aff9.png)

**Comment by ElijahMansur** [comment]
I commented WriteSteamAppIdTxtFile and everything worked.
