### ISSUE TITLE
SteamApps.GetCurrentGameLanguage() always returns "english"

### ISSUE THREAD

**Issue by SidusBr** [rlabrecque/Steamworks.NET#539]
Hi,
my game supports localizations and I wanted to read Steam's language instead of letting the user choose the language manually.
I'm using Unity and I've been calling the function "SteamApps.GetCurrentGameLanguage()". This function unfortunately always return "english" even if my language on Steam is "Italian". I also checked the game properties to make sure the language was Italian and it was...

Can you please help me? Thank you!

**Comment by emberfish** [comment]
Hi! I'm having the same issue, how did you fix it?

**Comment by SidusBr** [comment]
Hi.
If I'm not mistaken I managed to fix this issue but I don't remember
how, maybe I didn't initialize Steamwork before calling the function...
I'll let you know when I'll have access to the source code.

Il giorno mer 2 ago 2023 alle ore 22:48 Doug ***@***.***> ha
scritto:

**Comment by SidusBr** [comment]
> Hi! I'm having the same issue, how did you fix it?

Make sure SteamManager component starts before the components that checks for the language, you can check the [script execution order](https://docs.unity3d.com/Manual/class-MonoManager.html).

After that, you better test if the manager is initialized before using the method, like this:
```
        if (SteamManager.Initialized) {
            steamLanguage = Steamworks.SteamApps.GetCurrentGameLanguage();
        }
```

It should work as expected.

**Comment by emberfish** [comment]
Thank! I manage to make it work. My issue was that I haven't set the languages in the steamworks webpage.
