### ISSUE TITLE
Switch folder structure to have Steamworks files in one place

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#54]
Hi Riley,

not sure if you even want to do this as it would break compatibility with older Unity versions ... but with Unity 5 we finally could have everything regarding Steamworks(.NET) in one place, e.g.
- Assets/Steamworks.NET
  - Editor (Editor only scripts)
  - Scripts (Normal scripts that are currently in Plugins/Steamworks.NET)
  - Plugins
    - x86
    - x64

At least according to the docs this should work fine and would make management a bit easier IMHO. Maybe the only thing left open would be the native Windows Steam libraries that seem to still have to go to the project root in standalone builds but that could be a postbuild script.

Regards,
Chris

**Comment by rlabrecque** [comment]
Yeah, this is definitely something that I want to do when ever we break compatibility with 4.x.

I think we'll start shipping .meta files for the dll's as well since Unity can't seem to get that right... Can't do that currently as then they break on 4.x. :/

**Comment by Alloc86** [comment]
Hi Riley,

as I was just doing the update to 11 I was wondering if Unity 4 compatibility is still required or if it was time to move the files into one place like described above. Having the files all over the place is quite disturbing with updates and stuff ;)

Regards,
Chris

**Comment by rlabrecque** [comment]
So, I definitely know there's still people on Unity 4, definitely might be time to do a Unity 2017+ only version though.

**Comment by rlabrecque** [comment]
The plan is once the Unity Package Manager supports third party assets we'll do a big clean up pass for that.

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/pull/414
