### ISSUE TITLE
20.2.0 SDK 1.57 GetAuthTicketForWebApi EntryPointNotFoundException

### ISSUE THREAD

**Issue by RugbugRedfern** [rlabrecque/Steamworks.NET#558]
Hi, after upgrading to the newest version of the SDK via the .unitypackage with Unity 2019.4.17f1 in order to use the GetAuthTicketForWebApi method, I recieve the following error when I call GetAuthTicketForWebApi:

```
EntryPointNotFoundException: SteamAPI_ISteamUser_GetAuthTicketForWebApi
Steamworks.SteamUser.GetAuthTicketForWebApi (System.String pchIdentity) (at Assets/com.rlabrecque.steamworks.net/Runtime/autogen/isteamuser.cs:207)
SteamAuthenticationManager.Start () (at Assets/_Scripts/SteamAuthenticationManager.cs:35)
```

This is the code I'm running to produce the error:

```csharp
static Callback<GetTicketForWebApiResponse_t> getTicketForWebApiResponse;
static HAuthTicket authTicket;

void Start()
{
	getTicketForWebApiResponse = Callback<GetTicketForWebApiResponse_t>.Create(OnGetTicketForWebApiResponse);
	authTicket = SteamUser.GetAuthTicketForWebApi("");

	Debug.Log("getting auth ticket");
}
```

**Comment by watchdogac** [comment]
> Hi, after upgrading to the newest version of the SDK via the .unitypackage with Unity 2019.4.17f1 in order to use the GetAuthTicketForWebApi method, I recieve the following error when I call GetAuthTicketForWebApi:
> 
> ```
> EntryPointNotFoundException: SteamAPI_ISteamUser_GetAuthTicketForWebApi
> Steamworks.SteamUser.GetAuthTicketForWebApi (System.String pchIdentity) (at Assets/com.rlabrecque.steamworks.net/Runtime/autogen/isteamuser.cs:207)
> SteamAuthenticationManager.Start () (at Assets/_Scripts/SteamAuthenticationManager.cs:35)
> ```
> 
> This is the code I'm running to produce the error:
> 
> ```cs
> static Callback<GetTicketForWebApiResponse_t> getTicketForWebApiResponse;
> static HAuthTicket authTicket;
> 
> void Start()
> {
> 	getTicketForWebApiResponse = Callback<GetTicketForWebApiResponse_t>.Create(OnGetTicketForWebApiResponse);
> 	authTicket = SteamUser.GetAuthTicketForWebApi("");
> 
> 	Debug.Log("getting auth ticket");
> }
> ```

Hello, I believe this is caused due to your steam_api64.dll version, The "EntryPointNotFoundException" occurs when C# fails to find an exported function, old versions of the steam_api64.dll do not have "SteamAPI_ISteamUser_GetAuthTicketForWebApi" exported, Hence you're receiving this error.

Try updating the DLL to the latest version. It should be located at "sdk\redistributable_bin\win64\steam_api64.dll".

**Comment by cephalo3** [comment]
Before you install the latest version of Steamworks.NET over a pre 20.0 version, make sure to clean up all the old stuff first. It's a bit easier said than done because the old versions were spread throughout your project. I'm sure you're just finding the old dll.
