### ISSUE TITLE
Crash inside SteamAPI_RunCallbacks

### ISSUE THREAD

**Issue by dcarrigg** [rlabrecque/Steamworks.NET#56]
When creating standalone builds of our Unity game, we get a hard crash. This doesn't happen while running the game inside the editor. This happens when building the app with the development build flag off as well as on.

Below is the end of the output_log generated

Thanks,
-Dave

Finished updating steam avatar
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
PlayerPanel:UpdateSteamInfo() (at D:\Upsilon Circuit Kiln\Game\Assets\PlayerPanel.cs:203)
PlayerPanel:UpdatePlayerInfo(Int32, String, Int32, Int32, UInt64) (at D:\Upsilon Circuit Kiln\Game\Assets\PlayerPanel.cs:163)
UCClient:UpdatePlayerInformation(Int32, String, Int32, Int32, Int64) (at D:\Upsilon Circuit Kiln\Game\Assets\UCNetwork\UCClient.cs:438)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
ClientNetwork:RecieveRPC(NetIncomingMessage) (at D:\Upsilon Circuit Kiln\Game\Assets\Networking\ClientNetwork.cs:288)
ClientNetwork:HandleMessage_Data(NetIncomingMessage) (at D:\Upsilon Circuit Kiln\Game\Assets\Networking\ClientNetwork.cs:81)
UCNetwork:Update() (at D:\Upsilon Circuit Kiln\Game\Assets\Networking\UCNetwork.cs:105)
ClientNetwork:Update() (at D:\Upsilon Circuit Kiln\Game\Assets\Networking\ClientNetwork.cs:46)
 
(Filename: /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs Line: 222)

Object reference not set to an instance of an object

Crash!!!
SymInit: Symbol-SearchPath: '.;D:\Upsilon Circuit Kiln\Game\Builds;D:\Upsilon Circuit Kiln\Game\Builds;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'David'
OS-Version: 10.0.10158 () 0x100-0x1
D:\Upsilon Circuit Kiln\Game\Builds\UCClient.exe:UCClient.exe (00320000), size: 20254720 (result: 0), SymType: 'PDB', PDB: '.\player_win_development_x86.pdb', fileVersion: 5.1.2.53814
C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (77000000), size: 1540096 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ntdll.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\KERNEL32.DLL:KERNEL32.DLL (74E50000), size: 983040 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\KERNEL32.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\KERNELBASE.dll:KERNELBASE.dll (75340000), size: 1531904 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\KERNELBASE.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\WS2_32.dll:WS2_32.dll (75670000), size: 376832 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WS2_32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\sechost.dll:sechost.dll (745E0000), size: 270336 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\sechost.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\RPCRT4.dll:RPCRT4.dll (75160000), size: 708608 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\RPCRT4.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\HID.DLL:HID.DLL (60FA0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\HID.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\SspiCli.dll:SspiCli.dll (74030000), size: 122880 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SspiCli.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\msvcrt.dll:msvcrt.dll (75210000), size: 778240 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\msvcrt.dll', fileVersion: 7.0.10158.0
C:\WINDOWS\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (74020000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPTBASE.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll:bcryptPrimitives.dll (73FC0000), size: 368640 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\NSI.dll:NSI.dll (75150000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\NSI.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\USER32.dll:USER32.dll (74050000), size: 1310720 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\USER32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\GDI32.dll:GDI32.dll (743A0000), size: 1363968 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\GDI32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\ole32.dll:ole32.dll (744F0000), size: 958464 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ole32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\VERSION.dll:VERSION.dll (73840000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\VERSION.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\combase.dll:combase.dll (74F90000), size: 1814528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\combase.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\SHLWAPI.dll:SHLWAPI.dll (74F40000), size: 278528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SHLWAPI.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\PSAPI.DLL:PSAPI.DLL (74C90000), size: 24576 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\PSAPI.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\ADVAPI32.dll:ADVAPI32.dll (74230000), size: 503808 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ADVAPI32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\SHELL32.dll:SHELL32.dll (75C40000), size: 20668416 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SHELL32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\windows.storage.dll:windows.storage.dll (756D0000), size: 5099520 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\windows.storage.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (74220000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\kernel.appcore.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\shcore.dll:shcore.dll (75BB0000), size: 577536 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\shcore.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\powrprof.dll:powrprof.dll (74700000), size: 278528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\powrprof.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\profapi.dll:profapi.dll (75330000), size: 61440 (result: 0), SymType: '-nosymbols-', PDB: 'C:\WINDOWS\SYSTEM32\profapi.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\OLEAUT32.dll:OLEAUT32.dll (74630000), size: 598016 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OLEAUT32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\OPENGL32.dll:OPENGL32.dll (63A00000), size: 917504 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OPENGL32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\IMM32.dll:IMM32.dll (746D0000), size: 176128 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\IMM32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\MSCTF.dll:MSCTF.dll (74900000), size: 1179648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSCTF.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\WINMM.dll:WINMM.dll (736A0000), size: 147456 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMM.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\GLU32.dll:GLU32.dll (63610000), size: 151552 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\GLU32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\MSACM32.dll:MSACM32.dll (707A0000), size: 98304 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSACM32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\DDRAW.dll:DDRAW.dll (63520000), size: 962560 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DDRAW.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\DNSAPI.dll:DNSAPI.dll (70A80000), size: 540672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DNSAPI.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (73810000), size: 196608 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\WINHTTP.dll:WINHTTP.dll (73740000), size: 679936 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINHTTP.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (73510000), size: 143360 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMMBASE.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\cfgmgr32.dll:cfgmgr32.dll (748C0000), size: 221184 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\cfgmgr32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\DCIMAN32.dll:DCIMAN32.dll (63510000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DCIMAN32.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\WINNSI.DLL:WINNSI.DLL (737F0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINNSI.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (73460000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DEVOBJ.dll', fileVersion: 10.0.10158.0
D:\Upsilon Circuit Kiln\Game\Builds\UCClient_Data\Mono\mono.dll:mono.dll (10000000), size: 2293760 (result: 0), SymType: '-exported-', PDB: 'D:\Upsilon Circuit Kiln\Game\Builds\UCClient_Data\Mono\mono.dll', fileVersion: 1.0.0.1
C:\WINDOWS\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (73620000), size: 319488 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSWSOCK.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL:dhcpcsvc6.DLL (717B0000), size: 77824 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL:dhcpcsvc.DLL (71770000), size: 81920 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\napinsp.dll:napinsp.dll (65580000), size: 73728 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\napinsp.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\pnrpnsp.dll:pnrpnsp.dll (65420000), size: 90112 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\pnrpnsp.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\NLAapi.dll:NLAapi.dll (717D0000), size: 77824 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\NLAapi.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\System32\winrnr.dll:winrnr.dll (65410000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\winrnr.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\uxtheme.dll:uxtheme.dll (70720000), size: 479232 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\uxtheme.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\dwmapi.dll:dwmapi.dll (6FD80000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\dwmapi.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\d3d9.dll:d3d9.dll (703E0000), size: 1884160 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\d3d9.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\nvd3dum.dll:nvd3dum.dll (6A660000), size: 12926976 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\nvd3dum.dll', fileVersion: 10.18.13.5330
C:\WINDOWS\system32\nvspcap.dll:nvspcap.dll (07A70000), size: 1425408 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\nvspcap.dll', fileVersion: 2.5.11.45
C:\WINDOWS\SYSTEM32\SETUPAPI.dll:SETUPAPI.dll (754C0000), size: 1716224 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SETUPAPI.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\system32\nvapi.dll:nvapi.dll (6F930000), size: 3100672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\nvapi.dll', fileVersion: 10.18.13.5330
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL:MMDevAPI.DLL (6D230000), size: 348160 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MMDevAPI.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\PROPSYS.dll:PROPSYS.dll (6D2E0000), size: 1335296 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\PROPSYS.dll', fileVersion: 7.0.10158.0
C:\WINDOWS\SYSTEM32\wdmaud.drv:wdmaud.drv (60F50000), size: 229376 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wdmaud.drv', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\AVRT.dll:AVRT.dll (70150000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AVRT.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\ksuser.dll:ksuser.dll (6D1B0000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ksuser.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (6BDF0000), size: 421888 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AUDIOSES.DLL', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\wintypes.dll:wintypes.dll (6BD20000), size: 790528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wintypes.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\msacm32.drv:msacm32.drv (60F40000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\msacm32.drv', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\midimap.dll:midimap.dll (60F30000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\midimap.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\dsound.dll:dsound.dll (6E0A0000), size: 520192 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dsound.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\clbcatq.dll:clbcatq.dll (74DC0000), size: 532480 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\clbcatq.dll', fileVersion: 2001.12.10941.0
C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10158.0_none_cc2b0781713f447f\comctl32.dll:comctl32.dll (72AA0000), size: 2154496 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10158.0_none_cc2b0781713f447f\comctl32.dll', fileVersion: 6.10.10158.0
C:\WINDOWS\SYSTEM32\xinput1_3.dll:xinput1_3.dll (0FA80000), size: 90112 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\xinput1_3.dll', fileVersion: 9.18.944.0
C:\WINDOWS\SYSTEM32\WINTRUST.dll:WINTRUST.dll (74350000), size: 270336 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINTRUST.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\MSASN1.dll:MSASN1.dll (741B0000), size: 57344 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSASN1.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\CRYPT32.dll:CRYPT32.dll (74A20000), size: 1527808 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPT32.dll', fileVersion: 10.0.10158.0
D:\Upsilon Circuit Kiln\Game\Builds\UCClient_Data\Plugins\CSteamworks.dll:CSteamworks.dll (677A0000), size: 143360 (result: 0), SymType: '-exported-', PDB: 'D:\Upsilon Circuit Kiln\Game\Builds\UCClient_Data\Plugins\CSteamworks.dll', fileVersion: 1.20.0.0
D:\Upsilon Circuit Kiln\Game\Builds\steam_api.dll:steam_api.dll (67760000), size: 204800 (result: 0), SymType: '-exported-', PDB: 'D:\Upsilon Circuit Kiln\Game\Builds\steam_api.dll', fileVersion: 2.59.51.43
C:\Program Files (x86)\Steam\steamclient.dll:steamclient.dll (38000000), size: 9617408 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamclient.dll', fileVersion: 2.81.34.6
C:\WINDOWS\SYSTEM32\imagehlp.dll:imagehlp.dll (74190000), size: 102400 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\imagehlp.dll', fileVersion: 10.0.10158.0
C:\Program Files (x86)\Steam\tier0_s.dll:tier0_s.dll (64810000), size: 1118208 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\tier0_s.dll', fileVersion: 2.81.34.6
C:\WINDOWS\SYSTEM32\Secur32.dll:Secur32.dll (73710000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\Secur32.dll', fileVersion: 10.0.10158.0
C:\Program Files (x86)\Steam\vstdlib_s.dll:vstdlib_s.dll (63EE0000), size: 339968 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\vstdlib_s.dll', fileVersion: 2.81.34.6
C:\Program Files (x86)\Steam\steam.dll:steam.dll (67620000), size: 1273856 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steam.dll'
C:\Program Files (x86)\Steam\Steam2.dll:Steam2.dll (5C3A0000), size: 2887680 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\Steam2.dll', fileVersion: 2.0.2117.156
C:\WINDOWS\SYSTEM32\DbgHelp.dll:DbgHelp.dll (6BA70000), size: 1306624 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DbgHelp.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\dbgcore.DLL:dbgcore.DLL (675F0000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dbgcore.DLL', fileVersion: 10.0.10158.0
C:\Program Files (x86)\Steam\CSERHelper.dll:CSERHelper.dll (60000000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\CSERHelper.dll', fileVersion: 4.50.0.0
C:\Program Files (x86)\Steam\gameoverlayrenderer.dll:gameoverlayrenderer.dll (5C240000), size: 1380352 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\gameoverlayrenderer.dll', fileVersion: 2.81.34.6
C:\Windows\System32\rasadhlp.dll:rasadhlp.dll (70B10000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\rasadhlp.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\System32\fwpuclnt.dll:fwpuclnt.dll (70A30000), size: 286720 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\fwpuclnt.dll', fileVersion: 10.0.10158.0
C:\WINDOWS\SYSTEM32\bcrypt.dll:bcrypt.dll (73600000), size: 110592 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\bcrypt.dll', fileVersion: 10.0.10158.0

========== OUTPUTING STACK TRACE ==================

6776531F (steam_api) SteamAPI_vr_IHmd_WillDriftInYaw
67764AB5 (steam_api) SteamAPI_vr_IHmd_WillDriftInYaw
677670D1 (steam_api) SteamAPI_RunCallbacks
061434D3 (Mono JIT Code) [D:\Upsilon Circuit Kiln\Game\Assets\Plugins\Steamworks.NET\Steam.cs:90] Steamworks.SteamAPI:RunCallbacks () 
061434B6 (Mono JIT Code) [D:\Upsilon Circuit Kiln\Game\Assets\SteamManager.cs:136] SteamManager:Update () 
060DEFB9 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
100F066B (mono) mono_set_defaults
1005D872 (mono) mono_runtime_invoke
004BE2AE (UCClient) scripting_method_invoke
005ABB7C (UCClient) ScriptingInvocationNoArgs::Invoke
005AB845 (UCClient) ScriptingInvocation::Invoke
004ABB3A (UCClient) MonoBehaviour::CallMethodIfAvailable
004AD778 (UCClient) MonoBehaviour::Update
00568C11 (UCClient) PlayerLoop
006820D1 (UCClient) PlayerMainWndProc
00684018 (UCClient) PlayerWinMain
00A63148 (UCClient) WinMain
00AA4D58 (UCClient) _aullrem
74E62E74 (KERNEL32) BaseThreadInitThunk
77059511 (ntdll) RtlGetCurrentProcessorNumber
770594DC (ntdll) RtlGetCurrentProcessorNumber

========== END OF STACKTRACE ===========

**** Crash! ****

**Comment by rlabrecque** [comment]
Hey, sorry @dcarrigg I had missed this! Are you still running into this?

I wonder, are the steam_api.dll's that you're using ones that came along side the copy of Steamworks.NET?

**Comment by kharder** [comment]
I had this issue as well and I fixed it by updating the scripts in Steamworks.NET like CallbackDispatcher.cs (probably the one causing the issue).

**Comment by dcarrigg** [comment]
We found a workaround by switching by to 64 bit builds, which work fine.

Sometime over the next few days I'll update my scripts and test out a 32 bit build.

**Comment by etodd** [comment]
I ran into this issue. SteamWorks.NET is set up to use the correct calling convention based on Unity's platform-specific defines. Since I'm an XNA user, none of those were present. Added STEAMWORKS_WIN to the project defines, and all was well.

I believe the project is set up to work on Windows 64-bit by default, which explains why @dcarrigg was able to get it working in a 64-bit build.
