### ISSUE TITLE
Working with Unity Editor windows shell flicker

### ISSUE THREAD

**Issue by rever96** [rlabrecque/Steamworks.NET#562]
Hi, with Unity 2021.3.26f1 on windows add the SteamManager and play launches a background shell that keeps opening and closing over time ever after exit playmode. closing Unity kills definitly the process.
This is a bad behaviour.
Did you noticed it?
Could you fix it?

https://github.com/rlabrecque/Steamworks.NET/assets/19595534/a69f83d3-4341-4dbd-9469-a30bdf7fb680

**Comment by magicjar** [comment]
It happened to me too.
For now, i just disabled the Awake method in SteamManager using UNITY_EDITOR define symbol.

**Comment by GeonhanLee** [comment]
Any fix on this? this is so annoying

**Comment by rlabrecque** [comment]
> I solved the issue by removing all unnecessary files and let unity to regenerate it. No flickering is happening now.
