### ISSUE TITLE
Issues when importing package with Unity Package manager

### ISSUE THREAD

**Issue by nick5454** [rlabrecque/Steamworks.NET#568]
On Unity version 2020.3.15f2 when importing i'm getting a lot of GUID errors with the latest version 20.2.0.

Location in project:
![image](https://github.com/rlabrecque/Steamworks.NET/assets/5711577/6a05588f-0f8e-4cd4-beb3-5504ff725084)

GUID [32162149a7c3138479f074b56fd5fcbf] for asset 'Packages/com.rlabrecque.steamworks.net/Runtime/types/SteamRemoteStorage' conflicts with:
  'Assets/com.rlabrecque.steamworks.net/Runtime/types/SteamRemoteStorage' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

How should I resolve this? Do I need to move it directly into an asset/resources folder?

**Comment by rlabrecque** [comment]
I imagine you've sorted this out by now but if anyone else is running into this it seems to be because there's 2 versions installed; one via the Package Manager, and one in the Assets directory. The solution would be to remove one or the other.
