### ISSUE TITLE
DllNotFoundException for CSteamWorks.dll on mac osx

### ISSUE THREAD

**Issue by RavenTravelStudios** [rlabrecque/Steamworks.NET#57]
Hi guys,
i'm struggling with this error:
https://github.com/rlabrecque/Steamworks.NET/issues/23

That topic was closed but no solution was provided (unsigning the app just didn't worked for me).

If i use the absolute path on CSteamworks.dll.config, it works.
However, if i try to set the relative path, it doesn't work, no matter how i set it.

The question is: whats the folder that Mono uses as root when you set the relative path?

Please answer, because i need to put my game on steam and this is clearly a bug.

Thank you so much :)

**Comment by RavenTravelStudios** [comment]
Fixed. Just copy the CSteamworks.bundle in the same .exe dir and don't use the config file at all.

**Comment by rlabrecque** [comment]
Hmm, I couldn't reproduce that, it would be nice but this is what I ended up with:
http://i.imgur.com/CE5c0r1.png


Moving "CSteamworks" and libsteam_api.dylib out from [CSteamworks.bundle/Contents/MacOS](https://github.com/rlabrecque/Steamworks.NET/tree/master/Plugins/CSteamworks.bundle/Contents/MacOS) next to the .exe and renaming that "CSteamworks" to "libCSteamworks" also seemed to work well and did not need the CSteamworks.dll.config.
http://i.imgur.com/0YjEP9M.png
