### ISSUE TITLE
SteamApps.GetCurrentGameLanguage() always returns "english" 

### ISSUE THREAD

**Issue by emberfish** [rlabrecque/Steamworks.NET#572]
Hi! I'm having an issue with GetCurrentGameLanguage(). It's always returning "english" even though my steam is in another language.
Tested on Editor and build.
Currently on version 20.1.0.

**Comment by stoora** [comment]
what's the language of the game being debugged?

**Comment by emberfish** [comment]
I tried several languages, I'm also trying with GetCurrentGameLanguages()

![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/dd30a9d5-d0de-472f-a377-043f7e5f72cb)
![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/5ba0d9a2-5756-44b0-b8ba-58d6f93cb5aa)
![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/c41e12af-4a23-4201-95cf-1a43f9a19909)

Already rebooted steam client, PC, also tried uninstalling the game.

**Comment by emberfish** [comment]
Tried updating the Steamworks via package manager to the latest version. Didn't work.

**Comment by stoora** [comment]
try changing unity language restart unity and see what is gives you.

**Comment by emberfish** [comment]
still didn't work 🤔 

![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/8fc560ce-4211-47f8-bae1-2fa25c874048)
![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/86151c93-ac0f-4b95-a881-85cf1e99f4de)

**Comment by emberfish** [comment]
Also tried setting the steam UI to another language 
![image](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/a8257e34-7250-453b-94c4-43c3d094cb54)

**Comment by emberfish** [comment]
I asked gpt, and he fixed it :P

I might have missed that you need to include the languages on the Managing Base Languages section:
![msedge_IJFG8UTQe7](https://github.com/rlabrecque/Steamworks.NET/assets/27040349/52c14472-7b3f-4884-a6bb-436806d50db8)

here is the full gpt answer:
```
SteamApps.GetAvailableGameLanguages() is a method provided by the Steamworks.NET API, which returns a list of the languages that the active application supports.

It's important to note that this method does not return the language that is currently set in Steam or for a specific user, but rather the languages that the game itself supports. So, if you're getting "English" as the only response, it could be because the game you're currently working with only has support implemented for English language.

If you're developing a game and you want it to support more languages including Brazilian Portuguese, you'll have to implement localization support for these languages in your game. Once you've done that, SteamApps.GetAvailableGameLanguages() should return these new languages as well.

On the other hand, if you want to get the language the user has set in their Steam client, you can use the SteamApps.GetCurrentGameLanguage() method. Make sure that the game has support for the user's current language, or else it might default to the fallback language set in the game (often English).

In conclusion, it seems like your issue is likely due to the game only having support for English language, rather than an issue with the API or your user settings. Please double check the game's supported languages.
```

Thank you for the help!

**Comment by rlabrecque** [comment]
Holy shit dude, what was the gpt prompt? 🎉

**Comment by emberfish** [comment]
Here is the full conversation:

> User
> are you familiar with steamworks.net?
> 
> ChatGPT
> Steamworks.NET is a C# wrapper for Valve's Steamworks API, and is available on platforms like GitHub. Developers often use it when they're creating games with Unity that they plan to distribute on Steam.
> 
> This library allows developers to integrate their games with the full suite of Steam features, such as achievements, user authentication, microtransactions, multiplayer networking, and more.
> 
> As an AI developed by OpenAI, I can provide information about how these kinds of libraries work and how you might use them in your own projects, but remember that specific code advice might require a more up-to-date source or an expert in that particular library. As of my last training data in September 2021, I don't have the capacity to understand or interact with the Steamworks.NET library directly.
> 
> User
> SteamApps.GetAvailableGameLanguages() is only returning me "english" even though I have my steam set to "brazilian"
>
> ChatGPT
>
> SteamApps.GetAvailableGameLanguages() is a method provided by the Steamworks.NET API, which returns a list of the languages that the active application supports.
> 
> It's important to note that this method does not return the language that is currently set in Steam or for a specific user, but rather the languages that the game itself supports. So, if you're getting "English" as the only response, it could be because the game you're currently working with only has support implemented for English language.
> 
> If you're developing a game and you want it to support more languages including Brazilian Portuguese, you'll have to implement localization support for these languages in your game. Once you've done that, SteamApps.GetAvailableGameLanguages() should return these new languages as well.
> 
> On the other hand, if you want to get the language the user has set in their Steam client, you can use the SteamApps.GetCurrentGameLanguage() method. Make sure that the game has support for the user's current language, or else it might default to the fallback language set in the game (often English).
> 
> In conclusion, it seems like your issue is likely due to the game only having support for English language, rather than an issue with the API or your user settings. Please double check the game's supported languages.
