### ISSUE TITLE
Could not load [lib]steam_api.dll

### ISSUE THREAD

**Issue by DetectiveMittens** [rlabrecque/Steamworks.NET#58]
I am getting the error "[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: Assets/Plugins/x86_64/CSteamworks.dll
"

I have steam_api.dll in the root folder at the same level as "Assets" folder

**Comment by DetectiveMittens** [comment]
Turns the current repo just wont work with any version of Unity other than the latest.
I fixed the issue by upgrading to Unity 5.1

**Comment by rlabrecque** [comment]
I'm going to reopen this, as we do want to keep Unity 5.0 support for now.

**Comment by rlabrecque** [comment]
This was fixed in bf853a48181e4ffd4178fe8b812a6d0a94d50ec5
