### ISSUE TITLE
Can't open Steam Overlay on Friends List (Unity)

### ISSUE THREAD

**Issue by TheFatalBlack** [rlabrecque/Steamworks.NET#583]
Hi,
I'm posting here because I couldn't find the answer anyway. I wanted to open the steam overlay on "Friend List" with an UI button on UNITY. I use Steamworks.net,FizzySteamworks and Heathens-steamworks.
I already initialized the Steam API and created a lobby. (With Mirror and Steam Peer To Peer as transport).

It's openning the overlay but not on the friends list.
Here my code : 

```
public void OpenFriendsList()
    {
        SteamFriends.ActivateGameOverlay("friends");
     
    }
```

Here what I want to have (From Baldur's gate 3:

@
![steam](https://github.com/rlabrecque/Steamworks.NET/assets/47038952/1dc5e4db-2da8-47f0-920b-37048d0c2acd)

I also tried " SteamFriends.ActivateGameOverlayInviteDialog(User.Client.Id);" and don't work too.
As CSTEAMID I used my lobby ID.

Thanks in advance !

**Comment by StaleC00kie** [comment]
Hey, did you end up getting this to work? I'm having the same issue.

**Comment by StaleC00kie** [comment]
> Hi ! I ended up to figure it out...
> 
> You need to initialize the Steamworks API with a Steam Manager. After this, using this code : "public void OpenFriendsList() { SteamFriends.ActivateGameOverlay("friends");
> 
> ```
> }"
> 
> And you need to have a steamworks page for your game and push your build on it. This is a feature that cannot been tested by "Adding a no steam game" you absoluty need to push it to steam ! That's why
> ```

Thanks mate, I'll look into it.
