### ISSUE TITLE
How do I use SteamAPI_SetMiniDumpComment

### ISSUE THREAD

**Issue by molingyu** [rlabrecque/Steamworks.NET#590]
I want used `SteamAPI_SetMiniDumpComment` and `SteamAPI_WriteMiniDump` on win32.

I found that these two functions already exist in NativeMethods but are not exported. And NativeMethods is a internal class.

**Comment by rlabrecque** [comment]
I'm going to close this out and say just don't; those are some of the least supported API's exposed by Steam. Use something like Sentry, Backtrace, Bugsplat, etc instead.
