### ISSUE TITLE
SteamNetworkingSockets.ConfigureConnectionLanes has incorrect parameter types; can't be called correctly

### ISSUE THREAD

**Issue by Idles** [rlabrecque/Steamworks.NET#597]
The last two parameters for `ISteamNetworkingSockets.ConfigureConnectionLanes` are [supposed to](https://partner.steamgames.com/doc/api/ISteamNetworkingSockets#ConfigureConnectionLanes) allow passing arrays by pointer into native code. They're currently exposed to C# as [out parameters](https://github.com/rlabrecque/Steamworks.NET/commit/27b1a1561c9b9ace7de1f8da17454d29547a63f7#r139000696), which makes the method unusable. Calling the method from C# returns `k_EResultInvalidParam`.

**Comment by ha-ves** [comment]
Not sure if we can put PR for this, seem the repo almost out of life.
Add this in [`CodeGen/src/interfaces.py`](CodeGen/src/interfaces.py):
```python
g_SpecialArgsDict = {
    ...
    "ISteamNetworkingSockets": {
        "pLanePriorities": "ref int",
        "pLaneWeights": "ref ushort"
    }
    ...
}
```

**Comment by Idles** [comment]
Thanks for the tip. `ref int` and `ref ushort` would only allow passing 1 int and 1 ushort, which also doesn't match the native method signature. Is it valid to specify `int[]` and `ushort[]`? I've seen some other methods that have parameters with the `byte[]` signature

**Comment by ha-ves** [comment]
oh right sorry, didn't see the header file completely, yeah then that works

**Comment by rlabrecque** [comment]
Can you verify that int[] and ushort[] work?

If so we can get that change in this weekend. I think the spot to make a change is in `g_SpecialArgsDict`

**Comment by Idles** [comment]
I'll give it a try and see if I can put a PR together; might not happen until the work week

**Comment by rlabrecque** [comment]
I don't need a full PR, I can do that pretty quickly, what I can't really do right now is verify that it works.

To test locally without having to regenerate everything you'd need to make two manual changes to both:

https://github.com/rlabrecque/Steamworks.NET/blob/c918592d417cc1efbe63f88d1a26616978cc500d/com.rlabrecque.steamworks.net/Runtime/autogen/isteamnetworkingsockets.cs#L549-L551

https://github.com/rlabrecque/Steamworks.NET/blob/c918592d417cc1efbe63f88d1a26616978cc500d/com.rlabrecque.steamworks.net/Runtime/autogen/NativeMethods.cs#L2144

Ultimately they should probably end up looking like say this: https://github.com/search?q=repo%3Arlabrecque%2FSteamworks.NET%20pvecDepots&type=code

**Comment by Idles** [comment]
Thanks Riley

I made a mutable local copy of the Unity package and compiled successfully with the edits shown below. The method call succeeds at runtime and received k_EResultOK using this invocation:

Invocation:
```
var lanesResult = SteamNetworkingSockets.ConfigureConnectionLanes(conn, 3, new int[] {1, 2, 3}, new ushort[] {4, 5, 6});
```

Package edits:
```
[DllImport(NativeLibraryName, EntryPoint = "SteamAPI_ISteamNetworkingSockets_ConfigureConnectionLanes", CallingConvention = CallingConvention.Cdecl)]
public static extern EResult ISteamNetworkingSockets_ConfigureConnectionLanes(IntPtr instancePtr, HSteamNetConnection hConn, int nNumLanes, [In, Out] int[] pLanePriorities, [In, Out] ushort[] pLaneWeights);
```

```
public static EResult ConfigureConnectionLanes(HSteamNetConnection hConn, int nNumLanes, int[] pLanePriorities, ushort[] pLaneWeights) {
	InteropHelp.TestIfAvailableClient();
	return NativeMethods.ISteamNetworkingSockets_ConfigureConnectionLanes(CSteamAPIContext.GetSteamNetworkingSockets(), hConn, nNumLanes, pLanePriorities, pLaneWeights);
}
```

```
public static EResult ConfigureConnectionLanes(HSteamNetConnection hConn, int nNumLanes, int[] pLanePriorities, ushort[] pLaneWeights) {
	InteropHelp.TestIfAvailableGameServer();
	return NativeMethods.ISteamNetworkingSockets_ConfigureConnectionLanes(CSteamGameServerAPIContext.GetSteamNetworkingSockets(), hConn, nNumLanes, pLanePriorities, pLaneWeights);
}
```

**Comment by rlabrecque** [comment]
Thanks @Idles ! Whenever you get a chance can you make sure that new commit fixes this accurately?

**Comment by Idles** [comment]
I updated Steamworks.NET in the Unity Package Manager window and can now successfully call the API. Thanks for getting this fixed so quickly!
