### ISSUE TITLE
SteamNetworkingSockets.SendMessages has incorrect parameter types; can't be called successfully

### ISSUE THREAD

**Issue by Idles** [rlabrecque/Steamworks.NET#598]
I was trying to put to use the newly-fixed connection lanes API and ran into something else; getting SIGSEGV in Unity when trying to call `SteamNetworkingSockets.SendMessages`.

The native method has this signature:
```
void SendMessages( int nMessages, SteamNetworkingMessage_t *const *pMessages, int64 *pOutMessageNumberOrResult );
```

The Steamworks.NET binding for that method has the signature:
```
public static void SendMessages(int nMessages, SteamNetworkingMessage_t[] pMessages, long[] pOutMessageNumberOrResult)
```

So looks to me like there's an issue with the `pMessages` parameter type. For other native APIs that take `**` parameters, Steamworks.NET appears to use `IntPtr[]`. Seems like the fix should be similar to the one for #597 

I did a search and wasn't able to find any projects on Github calling this method using Steamworks.NET, so it might not be in use by anyone else and thus went unnoticed

**Comment by rlabrecque** [comment]
The `pOutMessageNumberOrResult` parameter definitely sounds wrong in the exact same way as 597 was; and I agree about `pMessages` as well.

In interfaces.py we do have this line: `"SteamNetworkingMessage_t **": "IntPtr[]",` assuming that `SteamNetworkingMessage_t *const *` is basically the same as ** in this case, then hopefully we end up with IntPtr[] as you suggest. (Note that IntPtr[] itself is probably not actually ideal -- but alas that's where we are.)

Same story as last time, if you get it working just let me know what signature you ended up with 👍

**Comment by Idles** [comment]
Just tested with a locally-edited copy of the package and succeeded in sending a message at runtime.

* `pOutMessageNumberOrResult` parameter type is fine as-is
* `pMessages` needs to change to `IntPtr[]`

The working, full signature in NativeMethods.cs is:

```C#
public static extern void ISteamNetworkingSockets_SendMessages(IntPtr instancePtr, int nMessages, [In, Out] IntPtr[] pMessages, [In, Out] long[] pOutMessageNumberOrResult);
```

For anyone from the future interested in how to call this method, this (roughly) works:
```C#
public bool Send(byte[] messageBytes, int sendFlags, ushort lane, HSteamNetConnection recipient)
{
    var msgPtrsToSend = new IntPtr[] { IntPtr.Zero };
    var ptr = IntPtr.Zero;
    try
    {
        ptr = SteamNetworkingUtils.AllocateMessage(messageBytes.Length);
            
        var msg = SteamNetworkingMessage_t.FromIntPtr(ptr);

        // Unfortunately, this allocates a managed SteamNetworkingMessage_t,
        // but the native message currently can't be edited via ptr, even with unsafe code
        Marshal.Copy(messageBytes, 0, msg.m_pData, messageBytes.Length);

        msg.m_nFlags = sendFlags;
        msg.m_idxLane = lane;
        msg.m_conn = recipient;

        // Copies the bytes of the managed message back into the native structure located at ptr
        Marshal.StructureToPtr(msg, ptr, false);

        msgPtrsToSend[0] = ptr;
    }
    catch (Exception e)
    {
        // Callers only have responsibility to release the message until it's passed to SendMessages
        SteamNetworkingMessage_t.Release(ptr);
        return false;
    }

    var msgSendResult = new long[] { default };
    SteamNetworkingSockets.SendMessages(1, msgPtrsToSend, msgSendResult);
    EResult result = msgSendResult[0] >= 1 ? EResult.k_EResultOK : (EResult)(-msgSendResult[0]);

    return result == EResult.kEResultOK;
}

```

**Comment by rlabrecque** [comment]
`public static extern void ISteamNetworkingSockets_SendMessages(IntPtr instancePtr, int nMessages, [In, Out] IntPtr[] pMessages, out long pOutMessageNumberOrResult);`

```
    long msgSendResult;
    SteamNetworkingSockets.SendMessages(1, msgPtrsToSend, out msgSendResult);
    EResult result = msgSendResult >= 1 ? EResult.k_EResultOK : (EResult)(-msgSendResult);
```

Would this not be better?

**Comment by Idles** [comment]
The API returns 1 messagenumber/error code per message sent (and the API supports sending multiple messages at once, though my examples only show sending 1), so that parameter needs to be an array.

**Comment by rlabrecque** [comment]
That makes sense! Let me know if you run into any problems with this

**Comment by canb227** [comment]
This solution doesn't work currently, as the method signatures don't match (IntPtr[] to SteamMessage[]). Does @Idles 's solution require locally editing the package? SendMessages() would seem to be unusable in it's current state, unless I'm missing something.
