### ISSUE TITLE
SteamNetworkingMessage_t isn't an unmanaged type, blocking optimized API calls

### ISSUE THREAD

**Issue by Idles** [rlabrecque/Steamworks.NET#600]
The C# definition for `SteamNetworkingMessage_t` is (accidentally?) a managed type, which necessitates an unneeded GC allocation and some copies when using it to call `SteamNetworkingSockets.SendMessages`. See the sample code provided in #598.

The root cause making it a managed type is its `SteamNetworkingIdentity` field, which is itself a managed type because of its field `m_reserved`. Until struct inline arrays arrive and can be broadly used (incl. Unity), replacing `m_reserved` with 32 individual `uint` fields transitively makes `SteamNetworkingMessage_t` an unmanaged type.

This one (tedious) code change in `SteamNetworkingIdentity` allows an optimized call to `SteamNetworkingSockets.SendMessages` shown in the (unsafe) sample code below. I've tested it successfully at runtime using my other local modifications to Steamworks.NET discussed in #598.

```C#
var ptr = SteamNetworkingUtils.AllocateMessage(messageBytes.Length);
var msg = (SteamNetworkingMessage_t*)ptr.ToPointer();

Marshal.Copy(messageBytes, 0, msg->m_pData, messageBytes.Length);
msg->m_nFlags = flags;
msg->m_idxLane = lane;
msg->m_conn = conn; 

var msgPtrsToSend = new IntPtr[] { ptr };
SteamNetworkingSockets.SendMessages(1, msgPtrsToSend, null);
```

**Comment by rlabrecque** [comment]
That makes complete sense, I wonder if there's any other shenanigans we can pull instead 🤔
