### ISSUE TITLE
The need to keep callbacks "alive" by maintaining a C# reference could be more clear

### ISSUE THREAD

**Issue by AllenPestaluky** [rlabrecque/Steamworks.NET#61]
Hi Riley, first off: thanks for all your work on Steamworks.NET -- definitely much nicer than trying to use the seemingly unsupported steam_api_interop.cs

I struggled for a while with one simple thing that I feel you might want to know about. I think the documentation could be improved on this:

I was not receiving my UserStatsReceived_t callback because I was not storing the result of the call to Callback<UserStatsReceived_t>.Create(...) in a member variable. Instead I was just doing something like this:

Callback<UserStatsReceived_t>.Create(myCallbackMethod);

This would result in my callback method never being called. The documentation says "To use Callbacks in Steamworks.NET you first declare a protected Callback<> at class scope as a member variable to hold onto the Callback." -- But this ends up sounding like it's just a part of a tutorial and an optional requirement.

I think my main problem was I assumed that Callback<T>.Create(...) would assign the delegate internally, so it can be called again later. I have spent so much time assigning delegates in C# that I assumed Steamworks.NET callbacks would be no different. I see now that the callback object itself is the only thing keeping reference to the delegate, but this was a surprise to me.

Even just a /// < summary >  on the Create method saying that a reference to the result must be kept alive for the callback to be called would be helpful.

Anyway, hopefully that's helpful in making the docs more clear to other new users.

Thanks again,
Allen

**Comment by rlabrecque** [comment]
Yeah, the problem stems from all the different types, it's not really feasible to expose all the delegates directly. Steam is holding onto a reference to it as well, unfortunately the garbage collector doesn't know that. :(

I both cleaned up the wording in the docs a little bit, and and provided some documentation on the Create method itself.
https://github.com/Steamworks/steamworks.github.io/commit/074a25a48dd19f07cfda0e4efb95b33c35edc5e2
and
286331d17d48a393c110df90270bc361d8c0d0ef

How's that looking?

**Comment by AllenPestaluky** [comment]
Definitely looks more clear to me. Unfortunately, all reasonable solutions require the user to actually read documentation, but I think this is an improved best-effort on the side of Steamworks.Net. Hopefully that's helpful to the next new user!
