### ISSUE TITLE
Adding Multiplayer to game

### ISSUE THREAD

**Issue by ThatDevBee** [rlabrecque/Steamworks.NET#611]
Hello, I am planning to add multiplayer to my game in Unity, and I wanted to know how I can start.

Are there any tutorials I can access using Steamworks.NET or guides available? For example, how to create a server, how to connect two players, how to set up lobbies etc.

Thanks, 
ThatDevBee

**Comment by KelsamGames** [comment]
https://partner.steamgames.com/doc/features/multiplayer

**Comment by rlabrecque** [comment]
I'd probably recommend using something like [Mirror](https://github.com/Chykary/FizzySteamworks) rather than trying to do low level networking with the Steamworks API yourself
