### ISSUE TITLE
can this be used in a WinUI project?

### ISSUE THREAD

**Issue by PYSX-Physix** [rlabrecque/Steamworks.NET#612]
I’ve been working on a project and wanted to integrate the Steamworks api in that project. The problem is that I can’t import it into my project so I’m wondering if this is possible or not.

**Comment by BoBoBaSs84** [comment]
@PYSX-Physix I do not see any reason why should not be able to use it.

**Comment by PYSX-Physix** [comment]
Ok thank you! 😊

**Comment by rlabrecque** [comment]
It might require a slight amount of effort just to get it going; but definitely should be possible.
