### ISSUE TITLE
SteamAPI_Init function doesn't exist in the steam_api64.dll from their sdk

### ISSUE THREAD

**Issue by ehoward0018** [rlabrecque/Steamworks.NET#618]
I'm not sure if I'm just going crazy or not, but I've been attempting to use this package with a .Net Maui app, and I've installed the nuget package and made sure the steam_api64.dll from the steam developer SDK download is added to my build.

Calling SteamAPI.Init() indeed calls the steam_api64.dll_Init function but that was failing so I took a look at the functions in the DLL (Version 1.59) and that function doesn't exist in the DLL.

Is the steam_api64.dll I got from Steamworks incorrect?

**Comment by rlabrecque** [comment]
> Is the steam_api64.dll I got from Steamworks incorrect?

Basically yeah; you need to use the dll that Steamworks.NET is built against; the latest release version supports 1.57; the latest on the master branch supports 1.59 though.

But -- Steamworks.NET ships with those dlls included, so you shouldn't need the Steamworks SDK for anything other than uploading your product! https://github.com/rlabrecque/Steamworks.NET/tree/master/com.rlabrecque.steamworks.net/Plugins
