### ISSUE TITLE
Update to Steamworks SDK 1.60

### ISSUE THREAD

**Issue by rlabrecque** [rlabrecque/Steamworks.NET#619]
Tracking issue

Release notes
https://store.steampowered.com/news/group/4145017?emclan=103582791433666425&emgid=6489204638529587038

**Comment by MigrantP** [comment]
Looking forward to this, the timeline integration looks like a nice thing to integrate!

**Comment by rlabrecque** [comment]
This should be usable with the https://github.com/rlabrecque/Steamworks.NET/tree/rlabrecque/update-to-1.60 branch in #623; I'm working on upgrading Steamworks.NET-Test and Example before I merge it in to main though; should be within the next couple days.

**Comment by rlabrecque** [comment]
Funny story; calling GetNumBetas crashes Steam because it's not supposed to be called from outside of the Steam process. 🙈
