### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by rlabrecque** [rlabrecque/Steamworks.NET#620]
Tracking Issue

This won't happen until #619 is done

**Comment by zackman0010** [comment]
Hi! I was just wondering if the new release would be built soon, now that 619 was merged? I'm looking forward to playing with the Timeline features!

**Comment by ElryDeveloper** [comment]
#619 is done, so can we please have an update, it already got asked for a week ago, please.
@rlabrecque

**Comment by KelsamGames** [comment]
@ElryDeveloper you can build this lib yourself from the source that is here. With the merging of #619, you can even use Steamworks v1.60. The next full release will be made available when it is ready. @rlabrecque created and maintains this for the community in his free time, exercise some patience.

**Comment by rlabrecque** [comment]
This issue appears to be the only outstanding regression from v1.60: https://github.com/rlabrecque/Steamworks.NET/issues/632

Fixing that before we craft a release should be a priority I think. I haven't had a chance to look into that issue yet though.

**Comment by zackman0010** [comment]
@rlabrecque Are you able to cut a release now that we fixed 632?

**Comment by ElryDeveloper** [comment]
yes please

**Comment by vstrg** [comment]
@rlabrecque it would be great if you could release the new version when you are available, thank you

**Comment by rlabrecque** [comment]
Hopefully this weekend!

**Comment by vstrg** [comment]
@rlabrecque thanks for your answer, I am writing a standalone plugin for a game server, but since it is incompatible with steamworks, I pinvoke the steam api, but I don't know how to pinvoke the ValidateAuthTicketResponse_t callback, how can I do this? thanks

**Comment by rlabrecque** [comment]
https://github.com/rlabrecque/Steamworks.NET/releases/tag/2024.8.0

**Comment by zackman0010** [comment]
@rlabrecque Awesome, thanks!
Do you know when the new version will be available from nuget.org?

**Comment by rlabrecque** [comment]
cc: @thetestgame

**Comment by rlabrecquefsg** [comment]
I should also note the new numbering format here; I personally had no idea what 20.2.0 meant anymore; so I just went YYYY.MM.Patch#. So at least we roughly know how 'old' a release is.

**Comment by rlabrecque** [comment]
I should also note the new numbering format here; I personally had no idea what 20.2.0 meant anymore; so I just went YYYY.MM.Patch#. So at least we roughly know how 'old' a release is.
