### ISSUE TITLE
windows command prompt flickering on unity editor 

### ISSUE THREAD

**Issue by GeonhanLee** [rlabrecque/Steamworks.NET#624]
![bug](https://github.com/rlabrecque/Steamworks.NET/assets/37390116/2b86e72d-de3e-4cf2-9490-2f14b5ea94df)
This was a problem since I started using the package.
It never stops until I close unity, and I have to restart the computer and pray to not have the bug next time.

Same issue here : #562

**Comment by GeonhanLee** [comment]
I actually found out maximizing any window stops the flickering, but undoing it will start the flickering again.
![bug2](https://github.com/rlabrecque/Steamworks.NET/assets/37390116/93cf889b-a398-4f47-b201-3ee3cdeb9361)

**Comment by GeonhanLee** [comment]
I solved the issue by removing all unnecessary files and let unity to regenerate it. No flickering is happening now.

**Comment by FredGithub** [comment]
I have the same issue. Unity 2021.3.39. From what I understand it's Unity spam opening C:\Program Files (x86)\Steam\bin\x86launcher.exe

I removed the Library folder but the issue persists. @GeonhanLee can you please explain what you removed exactly? 🙏

**Comment by GeonhanLee** [comment]
> I have the same issue. Unity 2021.3.39. From what I understand it's Unity spam opening C:\Program Files (x86)\Steam\bin\x86launcher.exe
> 
> I removed the Library folder but the issue persists. @GeonhanLee can you please explain what you removed exactly? 🙏

I am using git for my project, so I deleted my project and re-cloned the repository.
Hope it helps!

**Comment by FredGithub** [comment]
Thanks! I did a clean clone of the git repository and the bug is no longer happening. So there is something else other than the Library folder that was causing the issue

Hopefully this doesn't happen too often!

**Comment by hekk-naoya-kishimoto** [comment]
In my environment, this problem was not fixed by re-cloning the project.
Closing the tab of Unity's Android Logcat solved this problem.
But re-open the tab of Android Logcat, the problem reappears.

Windows 11
Unity 2022.3.33f1
Steamworks.NET 2024.8.0
Android Logcat 1.4.2

Hope this helps.

**Comment by JimmyWoodhouse** [comment]
I have this when a controller is connecting/disconnecting. It flicks up around 8 times.
