### ISSUE TITLE
ReceiveMessagesOnPollGroup returns proper count of messages with empty pointers array

### ISSUE THREAD

**Issue by GordiNoki** [rlabrecque/Steamworks.NET#626]
I'm trying to use P2P SteamNetworkingSockets, but I'm running into issue with code like this:
```C#
IntPtr[] pointers = [];
var count = SteamNetworkingSockets.ReceiveMessagesOnPollGroup(pollGroup, pointers, 100);
// ...
for (var i = 0; i < count; i++)
{
    var steamMessage = Marshal.PtrToStructure<SteamNetworkingMessage_t>(pointers[i]);
    // ...
    steamMessage.Release();
}
```
Which throws index out of range error on `Marshal.PtrToStructure` line because `pointers` array is empty. I am using .NET 8 if this will help.

**Comment by rlabrecque** [comment]
`IntPtr[] pointers = [];`

It's declared as empty, I imagine you probably need something like `IntPtr[] pointers = new IntPtr[100];` ?

**Comment by GordiNoki** [comment]
Oh, I thought it was overwriting my array, didn't think it has to have any length. It works now, thanks.

**Comment by rlabrecque** [comment]
That last 100 value you pass in should really be something like pointers.Count or such 👍
Pretty common pattern in the Steamworks API where it will fill a pre-allocated array for you, and you pass in the length of that array. You could wrap this into something that just does Array.Length for you

**Comment by rlabrecque** [comment]
Made a small improvement to this with this change: https://github.com/rlabrecque/Steamworks.NET/pull/627
