### ISSUE TITLE
In,Out attributes on data heavy methods

### ISSUE THREAD

**Issue by Alloc86** [rlabrecque/Steamworks.NET#63]
Hi Riley,

I think we discussed this a while ago on Skype, but the current version still has the [In, Out] on a lot of the method arguments which has proven to highly increase execution time (which is especially important on the networking methods as they get called hundreds to thousands calls per second). We have been running our game without all of those since we discussed this and didn't have any issues. Would be glad if those were removed in the official builds too so I don't have to patch them out ;)

Regards,
Chris

**Comment by rlabrecque** [comment]
With the new codegen this should be a quick and easy fix now.

I think this is the only piece of documentation we had on it?
http://stackoverflow.com/questions/14366066/are-p-invoke-in-out-attributes-optional-for-marshaling-arrays/14366422#14366422

For the most part this is undoing:
0767a8c5aafebd90ccc91cb65ee6dae6b38987f6
and
3368c64170c730099ac717ff404ac13ed507d96a

**Comment by Alloc86** [comment]
Yeah, I think that was the only ref back then. Maybe this should only be removed for primitive types (byte[] probably being the only one) though? Haven't tested those that e.g. have a CSteamID array...

**Comment by Alloc86** [comment]
What's the status here? Has this been fixed for the next release? (Just noticed this wasn't closed as we forgot to remove those attributes this time and so our release was way worse with Steam Networking than before ;) )

**Comment by Alloc86** [comment]
In release 9.0 this is still in, still have to check & modify the NativeMethods.cs on updates. Just missed it or is there any reason this can't be removed?

**Comment by Alloc86** [comment]
PS: This is only about the byte[] for now, I have seen there are some other primitive arrays (int, uint, long, double) as well as some structs. Would assume at least for the primitives it's always ok but haven't tested/used any of these APIs so I can't confirm that.

**Comment by rlabrecque** [comment]
Hey Illy, sorry this took so long! I threw this in now. Initially I was waiting to do a more in depth pass/investigation over it, but I should have just done the byte[] arrays first a long time ago!

Let me know how it works out!

I'm leaving this open until it's removed from all primitive types. Also somewhat related is string arrays. We might be able to do something quicker with those too. But that will require a bunch of additional testing/verification.

**Comment by Alloc86** [comment]
Yeah, this looks good, thank you :)
Haven't noticed any issues with my own edit and I think it's exactly the same places I removed it. But we don't use most of that, as for buffers/strings I think the next most used methods after the P2P stuff would be the achievements/stats. No idea though if string handling could really be optimized though, would expect the native C++ stuff to use a different encoding than the internal encoding in .NET? Also native encoding could be different on the three platforms (no idea, just thinking out loud) possibly causing other issues.

**Comment by rlabrecque** [comment]
Yep, I made that change in the code generator so it should have everything.

I'm not sure how much this effects #106, but there might be some cool optimization stuff that we can do there.

**Comment by Alloc86** [comment]
I had actually looked at that back when we tried to figure out the issue with the byte[] performance. Didn't seem to help at all. Not sure if Unity's Mono runtime even considers that attribute ;)

**Comment by rlabrecque** [comment]
Yep, we already do that here: https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/Steamworks.NET/autogen/NativeMethods.cs#L14

But yeah, I'm not sure if it helped at all.
