### ISSUE TITLE
SteamInternal_GameServer_Init_V2 requires valid pszInternalCheckInterfaceVersions as of version 1.58

### ISSUE THREAD

**Issue by RodGreen** [rlabrecque/Steamworks.NET#632]
With latest 1.60 I'm getting an error k_ESteamAPIInitResult_VersionMismatch when running GameServer.Init.

According to another reference, I found they mentioned that SteamWorks 1.58+ requires a valid pszInternalCheckInterfaceVersions  header built the same as the one defined in the SteamGameServer_InitEx

```c++
	const char *pszInternalCheckInterfaceVersions = 
		STEAMUTILS_INTERFACE_VERSION "\0"
		STEAMNETWORKINGUTILS_INTERFACE_VERSION "\0"

		STEAMGAMESERVER_INTERFACE_VERSION "\0"
		STEAMGAMESERVERSTATS_INTERFACE_VERSION "\0"
		STEAMHTTP_INTERFACE_VERSION "\0"
		STEAMINVENTORY_INTERFACE_VERSION "\0"
		STEAMNETWORKING_INTERFACE_VERSION "\0"
		STEAMNETWORKINGMESSAGES_INTERFACE_VERSION "\0"
		STEAMNETWORKINGSOCKETS_INTERFACE_VERSION "\0"
		STEAMUGC_INTERFACE_VERSION "\0"
		"\0";
```

**Comment by RodGreen** [comment]
Tried using this and still getting the error, any idea what might be the issue, I've confirmed all the versions match the DLLs.
```c#
var sb = new StringBuilder();
sb.Append(Constants.STEAMUTILS_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMNETWORKINGUTILS_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMGAMESERVER_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMGAMESERVERSTATS_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMHTTP_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMINVENTORY_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMNETWORKING_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMNETWORKINGMESSAGES_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMNETWORKINGSOCKETS_INTERFACE_VERSION).Append('\0');
sb.Append(Constants.STEAMUGC_INTERFACE_VERSION).Append('\0');
sb.Append('\0');

InteropHelp.UTF8StringHandle pszInternalCheckInterfaceVersions = new InteropHelp.UTF8StringHandle(sb.ToString());
```

**Comment by zackman0010** [comment]
@RodGreen @rlabrecque I've found the issue with this. The definition of `SteamInternal_GameServer_Init_V2` did not match the header file, so the arguments being passed to the function were incorrect. That's why RodGreen's attempt was unsuccessful. I submitted PR #633 to correct this.

**Comment by rlabrecque** [comment]
Thanks zackman! That would have not been fun to figure out!

I put up an alternative version based on yours here if you have time could you two take a look? Primarily because we needed to make the changes outside of the autogen folder as well.

https://github.com/rlabrecque/Steamworks.NET/pull/634
