### ISSUE TITLE
Cant get SetStat() to work :(

### ISSUE THREAD

**Issue by Ritbulau** [rlabrecque/Steamworks.NET#636]
Maybe I am a bit dumb, but i've spent a lot of time, trying to get `SteamUserStats.SetStat("MyStat", count);` to work.
I have this piece of code:

```
count++;

if (SteamManager.Initialized && SteamUserStats.RequestCurrentStats())
{
    SteamUserStats.SetStat("MyStat", count);
    SteamUserStats.StoreStats();
}
```

It works fine if i use `SteamUserStats.SetAchievement("MyAchievement");` instead, but SetStat always return false and don't do anything, and I don't really understand why, can someone help please?

**Comment by Ritbulau** [comment]
never mind, I am just stupid

**Comment by W3ktor** [comment]
@Ritbulau Can I ask what was the solution for this?

**Comment by Ritbulau** [comment]
For me the solution was to read the documentation a bit slower, because I tried setting the stat by name of the achievement that had my stat, when what you need is the name of the stat itself... =D
