### ISSUE TITLE
GetFriendPersonaName returns [unknown]

### ISSUE THREAD

**Issue by Daztrax** [rlabrecque/Steamworks.NET#638]
Hi, I'm using SteamFriends.GetFriendPersonaName() to get the Steam usernames by the CSteamID, however, some times it retuns the username as "[unknown]", is there a way to fix this or should I wait for a fix?

**Comment by tsa96** [comment]
https://partner.steamgames.com/doc/api/ISteamFriends `GetFriendsPersonaName`: "This will only be known to the current user if the other user is in their friends list, on the same game server, in a chat room or lobby, or in a small Steam group with the local user."

**Comment by yaakov-h** [comment]
You can also call `RequestUserInformation` to request information for that user, then handle the corresponding `PersonaStateChange_t` callback (which you should be doing anyway).

**Comment by Daztrax** [comment]
Yeah, I made a script to get the username and inside that script it calls `RequestUserInformation` and await to return the username with the PersonaStateChange_t callback, I'll attach the script as a txt file so anyone can see how I have it
[SteamUsernames.cs.txt](https://github.com/user-attachments/files/16679525/SteamUsernames.cs.txt)
