### ISSUE TITLE
Steamworks Join Lobby Via Code

### ISSUE THREAD

**Issue by Yolaras83** [rlabrecque/Steamworks.NET#645]
Hello, so i've been working on multiplayer project in unity and every time i to join with the LobbyID of the InputField.text it says cannot convert System.string to steamworks.CSteamID. I cant find a way for it to work.
![Screenshot_7](https://github.com/user-attachments/assets/b812c5dc-e8fd-4ac8-8c57-aa0ae4d353e2)
![Screenshot_6](https://github.com/user-attachments/assets/61433907-938d-4e22-b068-eef6e2040cfb)

**Comment by rlabrecque** [comment]
What if you try `CSteamID ID = new CSteamID(LobbyCodeInput.text);` CSteamID might not have what ever's required for ConvertTo to work?

**Comment by Yolaras83** [comment]
> CSteamID ID = new CSteamID(LobbyCodeInput.text);

I tried it but im getting an error saying "Cannot convert from string to ulong

**Comment by Yolaras83** [comment]
It's ok, i switched to facepunch.
