### ISSUE TITLE
DllNotFoundException: CSteamworks [Linux Editor]

### ISSUE THREAD

**Issue by ellivr** [rlabrecque/Steamworks.NET#66]
Hey!
I've been trying the Linux version of Unity-Editor, in my Manjaro. I created a blank new project, imported the steamworks.net's unitypackage file, and test run it inside the editor. It gave me this error:

DllNotFoundException: CSteamworks
Steamworks.InteropHelp.TestIfAvailableClient () (at Assets/Plugins/Steamworks.NET/InteropHelp.cs:22)
Steamworks.SteamUser.GetSteamID () (at Assets/Plugins/Steamworks.NET/autogen/isteamuser.cs:37)
NewScript.Start () (at Assets/NewScript.cs:10)

However if I just build the game project somewhere, and run the compiled *.x86 or *.x86_64, everything seems to be working fine, 

I have make sure to put the files in order and steam_appid.txt as well. Anyone know what might have caused this?

**Comment by rlabrecque** [comment]
Yeah, it seems like the Unity editor in Linux doesn't handle plugins yet unfortunately. I still need to create a bug report for the bards.

**Comment by rlabrecque** [comment]
Merging with #93
