### ISSUE TITLE
SteamController.GetControllerState always returns 0

### ISSUE THREAD

**Issue by Symbai** [rlabrecque/Steamworks.NET#67]
The GetControllerState function always returns 0 although my steam controller arrived yesterday is plugged in and works fine within Steam. Setting a BP on the GetControllerState call shows it returns 0 and the messagebox does not appear. This is my code:

  SteamAPI_Initialized = Steamworks.SteamAPI.Init()
        If SteamAPI_Initialized Then
            Controller_Initialized = Steamworks.SteamController.Init("C:\Users\User\AppData\Local\Temporary Projects\WindowsApplication1\bin\Debug\controller.vdf")
        End If

        If Not SteamAPI_Initialized Then
            MsgBox("Failed to initialize SteamAPI!")
        ElseIf Not Controller_Initialized Then
            MsgBox("Failed to initialize SteamController!")
        End If

 If Controller_Initialized Then
            Steamworks.SteamAPI.RunCallbacks()
            Steamworks.SteamController.RunFrame()
            If Steamworks.SteamController.GetControllerState(0, state) Then
			MsgBox("TEST")
			  End If
        End If

**Comment by rlabrecque** [comment]
The controller API doesn't support the new controllers yet. Hopefully Valve releases an update for that soon.
