### ISSUE TITLE
Tried to Initialize the SteamAPI twice in one session! Exception.

### ISSUE THREAD

**Issue by DMinsky** [rlabrecque/Steamworks.NET#68]
There is the reason to fire exception there? 

Our case:
We have 2 scenes, 1 - main menu, 2 - gameplay. SteamManager is on 1 scene. The game loading from 1 scene and SteamManager init. Then load 2 scene, user play some time and go to 1 (main menu) scene. And get "Tried to Initialize the SteamAPI twice in one session!" exception. How should I manage this situation?

**Comment by GeraldT** [comment]
Put the SteamManager on an Object that does not get destroyed should fix that I guess.
If it still happens maybe have your Steam logic in a separate scene that never gets loaded again as the objects stay during loads of other scenes.

http://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

**Comment by DMinsky** [comment]
Thanks. But "Put the SteamManager on an Object that does not get destroyed" SteamManager mark itself as DontDestroyOnLoad on Awake.

**Comment by GeraldT** [comment]
As written - have you tried to put it in a separate scene then that does not need to be loaded again?

**Comment by DMinsky** [comment]
Yeah, this will help. But actually, I just don't want to create new scene, only for this. So, I think I just will replace "throw new System.Exception("Tried to Initialize the SteamAPI twice in one session!");" with return ;)

**Comment by rlabrecque** [comment]
Hey @DMinsky. That exception shouldn't get thrown in this situation because the call on [L43](https://github.com/rlabrecque/SteamManager/blob/master/SteamManager.cs#L43) should get you out of there.

Do you destroy all gameobjects before loading the first scene again?

**Comment by DMinsky** [comment]
Hi @rlabrecque ! [LD43](https://github.com/rlabrecque/SteamManager/blob/master/SteamManager.cs#L43) is ok but... There is two SteamManager game objects at this moment is situation desribed above. One from Main Menu itself, and one, that come from Gameplay (that previously was on Main Menu because of DontDestroyOnLoad).

"Do you destroy all gameobjects before loading the first scene again?" of couse not ;) Default behaviour of LoadScene method doesn't means that user should Destroy all game objects by hands. LoadScene does it automaticly, except... DontDestroyOnLoad objects. So, every time, when user loading back to Main Menu he has two SteamManager on scene. Of course, I can Destroy SteamManager before LoadScene call, but it this case SteamManager will lose all its data.

p.s. sorry for my english, hope you understand me ;)

**Comment by rlabrecque** [comment]
Your English is fine!

The problem is, you should be able to create as many SteamManagers as you want, but all of them after the first one should be deleted automatically because of L42/43.

> Of course, I can Destroy SteamManager before LoadScene call, but it this case SteamManager will lose all its data.

Manually destroying SteamManager is the only way that the "Tried to Initialize the SteamAPI twice in one session! Exception." should ever get called. :fearful:

**Comment by KDSBest** [comment]
The Steam Manager Object need to be a root object and can't be a child of another one. Then it works for me.
