### ISSUE TITLE
Peer-to-Peer Networking Issues

### ISSUE THREAD

**Issue by wolfsmash** [rlabrecque/Steamworks.NET#70]
I have come across an issue with the wrapper for unity. I am trying to use SteamNetworking.SendP2PPacket(), but I am having some issues with the parameters. It says I need a byte array allocated for the buffer. How do I do this on unity? I looked at the steamworks documentation and this came up but I can't seem to convert it to unity c#:

uint32 msgSize = 0;
while ( SteamNetworking()->IsP2PPacketAvailable( &msgSize ) )
{
  void *packet = malloc( msgSize );
  CSteamID steamIDRemote;
  uint32 bytesRead = 0;
  if ( SteamNetworking()->ReadP2PPacket( packet, msgSize, &bytesRead, &steamIDRemote ) )
  {
    // message dispatch code goes here
  }
  free( packet );
}

If you could, please help me convert this and solve my problem.

Thank you,
- Bryce

**Comment by Alloc86** [comment]
Example just for the call:
    byte[] recvBuf = new byte[1024];
    uint size;
    CSteamID sourceId;
    bool result = SteamNetworking.ReadP2PPacket (recvBuf, (uint)recvBuf.Length, out size, out sourceId);
    // Do something if result==true
Note that this is **highly** inefficient if you create a new receive buffer byte array each time. This is just a very simplistic example on how to use the call.

**Comment by wolfsmash** [comment]
If the message was encoded as a string, how would I get the string back?

**Comment by Alloc86** [comment]
With the inverse function of how you got the byte-array of the string. Encoding.GetBytes vs Encoding.GetString (from the top of my head, could be named slightly different).

**Comment by wolfsmash** [comment]
But what variable is assigned the bytes?

**Comment by wolfsmash** [comment]
I still do not understand how to get the bytes received. Where are they stored?

I need the bytes received so I can convert them to a string again.

Any help?

**Comment by Alloc86** [comment]
In the array you pass in to the method.

**Comment by wolfsmash** [comment]
I got it working. Thank you so much!
:)
