### ISSUE TITLE
Achievements only awarded upon exiting game.

### ISSUE THREAD

**Issue by edencorbin** [rlabrecque/Steamworks.NET#71]
I hope this wasn't clearly written in the documentation and I just missed it, lol. Achievements in the game I am working on: http://store.steampowered.com/app/365320/, are only being awarded after exiting the game. Is this normal behavior? What call am I missing to award them in game. I am mainly using modified code from examples, etc, and the achievements are simple one time achievements. myAchievements is a separate local object I maintain with playerPrefs in Unity, and then on a co-routine I call once a second I check if an achievement is unlocked. Again, it works, but upon exiting the game. This is example code that seemed relevant in reviewing:
			
if (myAchievements.Collect_10_Fuses != 0) {
					UnlockAchievement(achievement);
}

private void UnlockAchievement(Achievement_t achievement) {
	achievement.m_bAchieved = true;
	SteamUserStats.SetAchievement(achievement.m_eAchievementID.ToString());
	// Store stats end of frame
	m_bStoreStats = true;
}
Is there a call I can make to force an in game update of achievements and show the unlock in game?

Thanks for any help on this.

**Comment by wolfsmash** [comment]
How did you call the coroutine? 

Make sure that the function starts with IEnumerator instead of void.
Also, make sure you are calling the function with StartCoroutine(FUNCTION HERE); because then it won't get called usually.

Try that and let me know

**Comment by edencorbin** [comment]
Hey Wolfsmash, thanks for these tips, I think both those things are correct, I just omitted them, here is a bit more of the code:

	void OnEnable() {
		if (!SteamManager.Initialized)
			return;
		
		// Cache the GameID for use in the Callbacks
		m_GameID = new CGameID(SteamUtils.GetAppID());
		
		m_UserStatsReceived = Callback<UserStatsReceived_t>.Create(OnUserStatsReceived);
		m_UserStatsStored = Callback<UserStatsStored_t>.Create(OnUserStatsStored);
		m_UserAchievementStored = Callback<UserAchievementStored_t>.Create(OnAchievementStored);
		
		// These need to be reset to get the stats upon an Assembly reload in the Editor.
		m_bRequestedStats = false;
		m_bStatsValid = false;

		myAchievements = GameObject.Find ("GameLogic").GetComponent<LocalAchievements> ();
//I always stop then start coroutines to ensure they are not double triggering/piling up.
		StopCoroutine("EvaluateAchievements");
		StartCoroutine ("EvaluateAchievements");
	}

	IEnumerator EvaluateAchievements(){
		while (true) {
			RunUpdate();
			yield return new WaitForSeconds(1f);
		}
	}

	private void RunUpdate() {
		//Debug.Log ("attempting check");
		if (!SteamManager.Initialized)
			return;
		
		if (!m_bRequestedStats) {
			// Is Steam Loaded? if no, can't get stats, done
			if (!SteamManager.Initialized) {
				//Debug.Log ("Not initialized");
				m_bRequestedStats = true;
				return;
			}
			
			// If yes, request our stats
			bool bSuccess = SteamUserStats.RequestCurrentStats();
			
			// This function should only return false if we weren't logged in, and we already checked that.
			// But handle it being false again anyway, just ask again later.
			m_bRequestedStats = bSuccess;
		}
		
		if (!m_bStatsValid) {
			//Debug.Log ("Not valid");
			return;
		}
		// Get info from sources

		// Evaluate achievements
		foreach (Achievement_t achievement in m_Achievements) {
			if (achievement.m_bAchieved)
				continue;
			
			switch (achievement.m_eAchievementID) {
			case Achievement.COLLECT_10_FUSES:
				if (myAchievements.Collect_10_Fuses != 0) {
					UnlockAchievement(achievement);
				}
				break;
			case Achievement.COMPLETE_CHAPTER_1:
				if (myAchievements.Complete_Chapter_1 != 0){
					//Debug.Log ("attempting to send achievement for chap 1");
					UnlockAchievement(achievement);
				}
				break;
			case Achievement.COMPLETE_CHAPTER_2:
				if (myAchievements.Complete_Chapter_2 != 0){
					UnlockAchievement(achievement);
				}
				break;
			}
		}
}

	private void UnlockAchievement(Achievement_t achievement) {
		achievement.m_bAchieved = true;
		
		// the icon may change once it's unlocked
		//achievement.m_iIconImage = 0;
		//Debug.Log ("ID");
		//Debug.Log (achievement.m_eAchievementID.ToString ());
		// mark it down
		SteamUserStats.SetAchievement(achievement.m_eAchievementID.ToString());
		
		// Store stats end of frame
		m_bStoreStats = true;
	}

**Comment by rlabrecque** [comment]
You're not calling SteamUserStats.StroreStats() anywhere which is required to push the achievement data to Steam.

**Comment by edencorbin** [comment]
rlabrecque, your right, that's nowhere in the script, so three quick questions.
A. Why does it register/work upon quitting the game.
B. How should I use SteamUserStats.StoreStats(), is it an efficient function to call once a second, or should I make sure there is a new achievement/stat to be set before calling it. 
C. Is this not the same/alternative to SteamUserStats.SetStat("MyStat", somevariable);?

**Comment by rlabrecque** [comment]
Hey Eden,

A: Steam essentially calls StoreStats after a program ends to clean up any loose ends.
B: I'd call it after a call to UnlockAchievement. It's actually pretty easy to do, you already have some stuff set up to do it (m_bStoreStats) You basically just need this if statement in your RunUpdate loop: https://github.com/rlabrecque/Steamworks.NET-Example/blob/master/Assets/Scripts/SteamStatsAndAchievements.cs#L120 (Just remove everything above StoreStats)
C: No, it's used in conjunction with SetStat as well, but it really just tells Steam that you have modified the stats or achievements and for it to do it's logic of actually updating the view (producing popups, modifying the UI etc) and storing it on the server.

**Comment by edencorbin** [comment]
rlabrecque, thanks a ton, this is clearly not an issue with the git repo, I appreciate the support here, for some reason I have been unable to join to the steam community where this might better be located. Working great!

**Comment by rlabrecque** [comment]
Do you have the Steamworks Developer badge on your profile?

**Comment by edencorbin** [comment]
I do now, and now I have forum access. Thanks for the help!
