### ISSUE TITLE
Have to manually call SteamController.RunFrame() every frame otherwise SteamController.GetConnectedControllers() always returns zero

### ISSUE THREAD

**Issue by JJC1138** [rlabrecque/Steamworks.NET#73]
Hello. I'm testing out the native Steam Controller API support in https://github.com/rlabrecque/Steamworks.NET/commit/0701a9840a38517c7830fce3e98a900ccfa0cd8e and I found that SteamController.GetConnectedControllers() is always returning zero unless I also call SteamController.RunFrame() every frame. The API comment docs say that shouldn't be necessary because it should be called automatically by SteamAPI.RunCallbacks(). I can't see anything obviously wrong with the code.

**Comment by JJC1138** [comment]
This Steamworks thread might be relevant, especially the top comment:
http://steamcommunity.com/groups/steamworks/discussions/22/490123938429525513/

**Comment by rlabrecque** [comment]
Yeah, I'm currently evaluating how we should best hack around this.

It's unclear why Valve only runs it automatically with SteamAPI_Init, but not SteamAPI_InitSafe (which is what Steamworks.NET uses by default)

I almost pushed a workaround into SteamAPI.RunCallbacks() on the Steamworks.NET side, but I think the 2 additional marshaled calls every single frame will be too expensive, so I'm going to reimplement the workaround in CSteamworks.

**Comment by JJC1138** [comment]
Okay great, thank you for letting me know.
