### ISSUE TITLE
Steamworks testing on one computer not possible? Please help

### ISSUE THREAD

**Issue by wolfsmash** [rlabrecque/Steamworks.NET#74]
I have recently come to a problem with using steamworks. I have my multiplayer setup and ready to go, but I can only run one instance of Steam. Is there a way to run more than one account to test things like multiplayer?

Thanks,
Bryce

**Comment by rlabrecque** [comment]
This isn't really the place for questions like this, the Steamworks Developer discussions forum would be much better suited.

This is really just for Steamworks.NET specific issues.
