### ISSUE TITLE
Methods that return strings can no longer return null, which is sometimes required

### ISSUE THREAD

**Issue by JJC1138** [rlabrecque/Steamworks.NET#75]
InteropHelp.PtrToStringUTF8(IntPtr) returns an empty string for null inputs, which breaks the API of some methods. For example, the comment spec of SteamFriends.GetPlayerNickname(CSteamID) says that it "Returns NULL if the no nickname has been set for that player." whereas it now actually returns an empty string in that case.

**Comment by rlabrecque** [comment]
I'm holding my breath but finally making this change, It really should have been done a year ago.

But.. It's going to be quite the breaking change.

https://github.com/rlabrecque/Steamworks.NET/commit/8180d987d66915c38c680d4b32615ce8d8489f43
