### ISSUE TITLE
Steam Achievements are not Showed

### ISSUE THREAD

**Issue by ngoctrungbmt** [rlabrecque/Steamworks.NET#79]
I can see the achievement working correctly on my dev (using unity )account but not on an normal steam account (after i release on steam.)

Any Idea? any possible misstep?

**Comment by ngoctrungbmt** [comment]
i run in unity4 is was okay. i can got the achievement and leaderboard. But when i run on unity 5 that only run on devUnity but Steam account.

**Comment by rlabrecque** [comment]
Hey @ngoctrungbmt, sorry for the long delay! Did you ever get this solved?

Im guessing that you are/were using an old version of Steamworks.NET that didn't have Unity5 support yet.
