### ISSUE TITLE
Stream Controller support?

### ISSUE THREAD

**Issue by Symbai** [rlabrecque/Steamworks.NET#85]
So when will we be able to use the stream controller? I don't have access to the steam developer forum because I have no developer account. But I cannot believe the controller is released for months and still we cannot check if a button is pressed.

Is it lacking of Valve to deliver support? If yes, why have all these games steam controller support, how do they managed that?

Is it lacking of steamworks.net feature? If yes, when will you add support for the steam controller?

So far we can only check if a controller is plugged in but even that doesn't work. It always returns 0.

**Comment by rlabrecque** [comment]
Sorry I haven't got the Steamworks.NET-Test updated yet, I'll work on that this week for sure!

The missing piece for you right now is probably SteamController.RunFrame(). There's a documentation mismatch with it right now though, and that should be cleared up this week as well.

You then need to cache all the ActionSets and the Actions that they contain.
