### ISSUE TITLE
SpaceWar No Matter What

### ISSUE THREAD

**Issue by Mhinbron** [rlabrecque/Steamworks.NET#86]
It seems no matter how many times I try to remove the Steamworks.net files re add them then add my Steam App ID it always says I am in game playing Spacewar.  Not sure what I might be doing wrong.  Would love the help of someone that may have set this up before and can possibly nail down where I am messing up.

**Comment by rlabrecque** [comment]
The way that you control the AppId is via the steam_appid.txt file. If you're using  Unity the steam_appid.txt file exists in your project folder (next to Assets/, ProjectSettings/ etc)

**Comment by Mhinbron** [comment]
I only just realized I was altering the wrong appid.txt within the assets and not the one next to it and feel like a complete moron.  However now that I have it in the right place with the appid Steam no longer shows me in a game at all.
