### ISSUE TITLE
Linux 64 bit Builds attempt to load steam 32bit overlay

### ISSUE THREAD

**Issue by clivecrous** [rlabrecque/Steamworks.NET#88]
Unity Crash Log:

Native stacktrace:

        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash_Data/Mono/x86_64/libmono.so(+0x91772) [0x7fe5cea75772]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash_Data/Mono/x86_64/libmono.so(+0x347be) [0x7fe5cea187be]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7fe5d554b340]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0xb9c44e]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x85b609]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x8146b6]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x8180a9]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x81084c]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x81109a]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x5dc6c4]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x78a7c5]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x468782]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fe5d3cf8ec5]
        /home/clive/.local/share/Steam/steamapps/common/Bunny Bash/BunnyBash.x86_64() [0x472949]

Debug info from gdb:

ERROR: ld.so: object '/home/clive/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No threads.

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by Alloc86** [comment]
That overlay thing is no real "error", Steam just tries to inject both versions as it doesn't know which one will be appropriate for your program.

SIGSEGV: Might be this issue: http://forum.unity3d.com/threads/5-2-sporadic-sigsegv-crash-in-linux-headless-builds.354031/
