### ISSUE TITLE
Kick a player from the lobby

### ISSUE THREAD

**Issue by MarkMeier** [rlabrecque/Steamworks.NET#89]
There is a function missing where you can kick player from an existing lobby. You can only setup a callback for that.

**Comment by daver84ever** [comment]
I've had a similar question. I seems to have a kicked listener but I couldn't find away for a 'host' peer to kick the player directly.

**Comment by rlabrecque** [comment]
I'm honestly not completely sure, but this question is a little to general for Steamworks.NET specifically and would be better asked on the general Steamworks forum.
