### ISSUE TITLE
Can't enable GameSocketShare

### ISSUE THREAD

**Issue by fr34kyn01535** [rlabrecque/Steamworks.NET#91]
Since none of the overloads of GameServer.Init offer a usQueryPort with the type short, its not possible to pass the constant MASTERSERVERUPDATERPORT_USEGAMESOCKETSHARE (short = -1) to enable GameSocketShare as described in the comment. https://github.com/rlabrecque/Steamworks.NET/blob/d2bca485c98ba95d15d1f4e158d649f606870e85/Plugins/Steamworks.NET/Steam.cs#L137

**Comment by rlabrecque** [comment]
This should be fixed in 2021fa1d313b2816a9fcd5e4a8adec3851e435c7, thanks for the report!
