### ISSUE TITLE
Steam Workshop Uploader Publishing Tool

### ISSUE THREAD

**Issue by Lone-Coder** [rlabrecque/Steamworks.NET#92]
I've used Steamworks.NET in my VR game [A Legend of Luca](http://store.steampowered.com/app/433600/). Thanks for the great library!

I just added mod support and am starting to look at Workshop integration. Since it's a VR game I think it'd be nice to have a command line or gui tool that uploads the mods. Has anyone built one using Steamworks.NET that I could use or could we build one out of the example code easily that could be used for all games to add workshop uploading?

Something like GMPublish from Garry's mod:
http://steamcommunity.com/sharedfiles/filedetails/?id=147513134
http://steamcommunity.com/sharedfiles/filedetails/?id=160789919

Or the Don't Starve Upload tool:
http://forums.kleientertainment.com/topic/26494-dont-starve-steam-workshop-uploader/

**Comment by rlabrecque** [comment]
Hey! Glad to hear it, I've been looking forward to trying out A Legend of Luca when I finally have time!

I've seen this one before:
https://github.com/nihilocrat/SteamWorkshopUploader

I believe once the Modbox SDK gets released if it's not already that uploader will sort of be open source too (though I don't know what license the code will be under)

**Comment by mamoniem** [comment]
For anyone still looking, this one helped a lot:
https://answers.unity.com/questions/1282772/steamworksnet-and-steam-workshop.html
