### ISSUE TITLE
Issues in Linux Editor

### ISSUE THREAD

**Issue by malegretti** [rlabrecque/Steamworks.NET#93]
Hi everyone!

I am having some problems with the Steamworks.Net plugin in the Linux editor, and would like to know if someone could help shred some light on what's happening. As soon as our code try to initialize the plugin, I receive this error on the console:

```
[Steamworks.NET] Could not load [lib]steam_api.dll/so/dylib. It's likely not in the correct location. Refer to the README for more details.
System.DllNotFoundException: CSteamworks

```

It doesn't matter if I try to run the game inside the editor or if I build a binary, the error is the same. The strange thing is, the aforementioned libraries are present in the directory. If I build a x86_64 binary on a Windows machine, it works perfectly on this same Linux machine. I have even tried to copy and replace the files in the project, to no extent. 

Do you guys know if there is any known workaround?

Unity version is 5.3.4f1 on a Ubuntu 16.04 64 bits machine.

Thanks in advance!!! :D

**Comment by rlabrecque** [comment]
Hey @malegretti, There's a workaround provided by one of the Unity Linux developers here:

http://forum.unity3d.com/threads/native-plugin-in-editor-steam-specifically.384970/

I'm not sure that there's much else that I can do about it. We already do quite a bit to make it work enough as is with ["-Wl,-z,origin '-Wl,-rpath,$$ORIGIN'"](https://github.com/rlabrecque/CSteamworks/blob/master/build/linux/Makefile#L24)

I'll ping Tak and see if they've got any closer or if they have anything that I could do to make it better.

**Comment by malegretti** [comment]
Hi @rlabrecque , thanks for the advice! I've copied the library to /opt/Unity/Editor, and yes it worked perfectly.
