### ISSUE TITLE
How would you get the Steam username from the GetDownloadedLeaderboardEntry result?

### ISSUE THREAD

**Issue by thestonefox** [rlabrecque/Steamworks.NET#95]
All I can see is that returns the Steam User ID of the user in the leaderboard.

But if I want to display their name on a leaderboard in the game how would I get their name from this ID?

The steam users on the leaderboard may not be a friend of the playing user, is this possible?

**Comment by thestonefox** [comment]
Nevermind I figured it out using the SteamFriends api :)

**Comment by hamburml** [comment]
Can you give an example?

**Comment by Rastenbe** [comment]
I'm not sure if @thestonefox did it the same way as I did, but the GetFriendPersonaName function gets the job done.

EX: SteamFriends.GetFriendPersonaName(leaderboardEntry.m_steamIDUser)

**Comment by JulianRice** [comment]
I've tried using that @Rastenbe, but it outputs [unknown]. 
Upon further inspection on the Steamworks site, it says `Returns an empty string (""), or "[unknown]" if the Steam ID is invalid or not known to the caller.` 

It also says 
> This will only be known to the current user if the other user is in their friends list, on the same game server, in a chat room or lobby, or in a small Steam group with the local user.
So is there a way to just get the name of the user (not in a group, not friends, not in the same server or lobby, etc.) from the SteamID? I can't seem to find out how to solve this. Will keep working on it.

**Comment by yaakov-h** [comment]
`SteamFriends.RequestUserInformation`?

**Comment by JulianRice** [comment]
After looking into it more, I found a solution. It was tricky at first but it makes sense now-- for those looking at this in the future, check out [this](https://github.com/ErrorNullReference/OLD-INVASION/blob/032d5a66efff1910561743ec16049d62a6fcd673/Assets/Scripts/LobbyScripts/User.cs) script for reference:

**Comment by timartinelli** [comment]
Someone the solution to get the Avatar of the users uploaded by the classification?

score_get = steam_download_scores ("lvl_001", 1, 10);

**Comment by EricNeumann2706** [comment]
Why was this issue closed?
There is still no viable solution for this problem. The Steam-Leaderboard integration makes no sense when we can't access the player's names without being friends with them.
