### ISSUE TITLE
DllNotFoundException _Data/Plugins/CSteamworks.dll

### ISSUE THREAD

**Issue by sloankelly** [rlabrecque/Steamworks.NET#98]
No errors in the editor, but when I make a build and run the game I get that error in the console window (the ingame one) for a PC build. I've tried building as x86 or x86_64, either way gives me the same error. I have the latest stable release of steamworks.net and I'm running Unity 5.3.5f1.

The correct steam_api.dll or steam_api64.dll files are located in the same folder as my executable and CSteamworks.dll exists in the Plugins folder inside the _Data folder.

I even tried using Fusion Log Viewer to see if it would shed any light on the problem (it didn't).

Does anyone have a next step? Or maybe I've missed something. :)

**Comment by sloankelly** [comment]
Found the problem. The steam_api64.dll file in the 'redist' folder in the plugins folder wasn't compatible with CSteamworks.dll. I copied the steam_api64.dll file from the SDK redist folder to the root of my game and it now works.

**Comment by SirMetamorph** [comment]
download the crack ''steamworks'' in this video and put in root paste of Planetbase 1.3.1... Just it... https://www.youtube.com/watch?v=5swyystFuzc&feature=youtu.be
