### ISSUE TITLE
AccessViolation when JoinClanChat after RunCallbacks

### ISSUE THREAD

**Issue by elamaunt** [rlabrecque/Steamworks.NET#99]
The problem is on WIn32 Forms project with Cocossharp framework.

```
var joinCallback = CallResult<JoinClanChatRoomCompletionResult_t>.Create(OnCallResulted);
joinCallback.Set(SteamFriends.JoinClanChatRoom(_globalChatId));

 private void OnCallResulted(JoinClanChatRoomCompletionResult_t param, bool bIOFailure)
{
// wrong result marshaling and AccessViolation after this
}
```

If i comment  !STDCALL conditions in CallbackDispatcher.cs it makes the result of JoinClanChat in success but AccessViolation still remains.

**Comment by rlabrecque** [comment]
Hey @elamaunt is there any chance that joinCallback could be going out of scope and getting garbage collected before OnCallResult() gets called by C++?

**Comment by elamaunt** [comment]
I resolved the problem by compiling the project in Windows mode. When i compiled the project in my solution it was compiled with Debug directive. So thats why the pack size value was wrong and STDCALL condition didnt work properly.
